### ISSUE TITLE
 this error occured while implementing full_sort_topk function

### ISSUE THREAD

**Issue by iamharikrishnank** [RUCAIBox/RecBole#1005]
this error occured while implementing full_sort_topk function 

~\Downloads\RecBole\RecBole-master\recbole\utils\case_study.py in full_sort_scores(uid_series, title, description, model, train_data, test_data, device)
     38     device = device or torch.device('cpu')
     39     uid_series = torch.tensor(uid_series)
---> 40     uid_field = test_data.dataset.uid_field
     41     dataset = test_data.dataset
     42     model.eval()

AttributeError: 'torch.device' object has no attribute 'dataset'

_Originally posted by @iamharikrishnank in https://github.com/RUCAIBox/RecBole/issues/988#issuecomment-945409296_

**Comment by Sherry-XLL** [comment]
@iamharikrishnank `history_item` represents user's history interacted item_id, `history_row` and `history_col` are only processed to some extent, which is used for indexing. The reason for your `TypeError` is the improper user series. That is, your user series may be set randomly, making empty `history_item` when executing `history_item = test_data.uid2history_item[list(uid_series)]`. Please choose reasonable user data for case study analysis, and read the error outputs of Python carefully.

**Comment by sxhysj** [comment]
> @Sherry-XLL I am getting this error while executing topk can u breifly explain use of history_row and history column ---> 52 history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)]) 53 history_col = torch.cat(list(history_item)) 54 history_index = history_row, history_col
> 
> TypeError: full_like(): argument 'input' (position 1) must be Tensor, not NoneType

Same error here when I used 'RecVAE' for predicting. Code below:
import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
import numpy as np
import pandas as pd

if __name__ == '__main__':
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file='./saved/RecVAE-Feb-23-2022_20-33-49.pth',
    )  # Here you can replace it by your model path.

    # read all of the user ids in string
    userid_array = np.loadtxt(fname='sample_submission.csv', delimiter=',', usecols=0) #read the first row
    userid_list = pd.read_csv('sample_submission.csv', names='customer_id')

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    #uid_series = dataset.token2id(dataset.uid_field, ['00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657', '0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa'])
    uid_series = dataset.token2id(dataset.uid_field, userid_list['customer_id'])

    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=12, device=config['device'])
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()

    #save the item list to a file
    #numpy.ndarray to a CSV file
    external_item_list.tofile('submission_20220306.csv', sep=',')

    #score = full_sort_scores(uid_series, model, test_data, device=config['device'])
    #print(score)  # score of all items
    #print(score[0, dataset.token2id(dataset.iid_field, ['0108775015', '0108775044'])])  # score of item ['0108775015', '0108775044'] for user '00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657'.
