### ISSUE TITLE
Using implicit dataset with lightgcn

### ISSUE THREAD

**Issue by satsaras** [RUCAIBox/RecBole#1007]
Hi Team,
I am trying to use an implicit dataset with lightgcn with click interactions between user and item. In ml-100k and other datasets we do see a 'rating' column to define interaction but its explicit. Want to know how you are converting this explicit rating to implicit interaction for algo which runs on implicit feedback like lightgcn

**Comment by chenyuwuxin** [comment]
@satsaras Hello, thanks for your attention to RecBole!
There are two ways to do converting this explicit rating to implicit interaction.

- If your data doesn’t have labels but has users’ feedback information (like rating for items) to show their preferences,first way to label them is to set threshold.
For example, if you `.inter` file is like:
  |  user_id:token | item_id:token | rating:float | timestamp:float |
  |  ----  | ----  | ----  | ---- |
  | 1 | 1193 | 5 | 978300760 |
  | 1 | 661 | 1 | 978302119 |
  | 2 | 11 | 4 | 978302129 |
  | 2 | 112 | 4 | 978302139 |
  | 3 | 555 | 1 | 978302149 |
  | 3 | 234 | 3 | 978302159 |

  To set label for these interactions, you can set 3 as the threshold of rating, and the interactions will be labeled as positive if their rating no less than 3.You can set the config like:

  ```
    threshold:
        rating: 3
    neg_sampling: None
  ```
  And then RecBole will automatically set label for interactions based on their rating column.

- Another way to label these kinds of data is negative sampling. We will assume that for each user, all the observed interactions are positive, and the unobserved ones are negative. And then, we will set positive label for all the observed interactions, and select some negative samples from the unobserved interactions according to a certain strategy.
 For example,you can set the config like:
  ```
  neg_sampling:
     uniform: 1
  ```
   in your configuration file.
   And then, RecBole will automatically select one negative sample for each positive sample uniformly from the unobserved 
   interactions.

To learn more about the labels,you can refer to [LABEL OF DATA](https://recbole.io/docs/user_guide/data/label_of_data.html).
I hope my answer can help you.
