### ISSUE TITLE
读取不到配置文件里的参数

### ISSUE THREAD

**Issue by panxianhaoo** [RUCAIBox/RecBole#1010]
今天刚刚使用，可能遗漏了一些信息，请帮忙解答一下，十分感谢

conda 安装的

run.py里的内容
![image](https://user-images.githubusercontent.com/30815101/137934706-1c4016b4-6fd6-4447-93d3-043b9247d3a5.png)

test.yaml里的内容
![image](https://user-images.githubusercontent.com/30815101/137934813-51cce6d5-19d9-4a7e-8ca6-8024cd09d30c.png)

执行命令
`python run.py --config_files=test.yaml`

结果可以看到epoch还是300
![image](https://user-images.githubusercontent.com/30815101/137935013-aeffe9c5-118f-4930-be43-0ec64f91c719.png)

**Comment by chenyuwuxin** [comment]
@panxianhaoo 你好，这个原因可能是你没有正确读取命令行参数和设置config。
你可以尝试`python run_recbole.py --config_files=test.yaml`命令直接运行。
或者将`run.py`的内容改为：
```
from recbole.quick_start import run_recbole

run_recbole(model='BPR', dataset='ml-100k', config_file_list=['test.yaml'])
```
