### ISSUE TITLE
Quenstion about gather_indexes function

### ISSUE THREAD

**Issue by xiaxin1998** [RUCAIBox/RecBole#1026]
Hi ,
in class SequentialRecommender, there is one function named 'gather_indexes'. What is the meaning? Why we should gathers the vectors at the specific positions over a minibatch? 
Thanks.

**Comment by hyp1231** [comment]
Hi Xin,
in RecBole's sequential models, item sequences in a batch are padded to the same length. After padding, the earliest interacted items are located in index 0, while the most recently interacted items are located in index [len - 1] (where 'len' denotes the length of item sequence).

For example, after padding to 6,
```
i1, i2, i3, 0, 0, 0
i1, i2, 0,  0, 0, 0
i1, 0,  0,  0, 0, 0
```

Then, we use `gather_indexes` to fetch the hidden state of the most recently interacted items.

**Comment by xiaxin1998** [comment]
Thanks for your quick response.
Another question,  line 121 in sasrec.py,  which is 'output = self.gather_indexes(output, item_seq_len - 1)';
'item_seq_len' stores the all the length of sequences in this batch, right? so its shape should be (n, 1) where n is the number of sequences? And in your example, item_seq_len should be [3,2,1]?

**Comment by hyp1231** [comment]
> Thanks for your quick response. Another question, line 121 in sasrec.py, which is 'output = self.gather_indexes(output, item_seq_len - 1)'; 'item_seq_len' stores the all the length of sequences in this batch, right? so its shape should be (n, 1) where n is the number of sequences? And in your example, item_seq_len should be [3,2,1]?

Yes, that's it.

**Comment by xiaxin1998** [comment]
Thanks a lot.
