### ISSUE TITLE
关于RecBole文档错误

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1027]
[**Evaluation introduction**](https://recbole.io/docs/user_guide/train_eval_intro.html)里面split和order反了吧，没有人发现吗😢

**Comment by WhutTjk** [comment]
还有**SASRec** paper中Page 5有**”we randomly generate one negative item j for each time step in each sequence.“**，请问这个在RecBole中的实现中如何体现呢？

**Comment by chenyuwuxin** [comment]
@WhutTjk  你好，

1. “split和order反了”具体是指哪些内容？
2. 通过负采样，具体实现为根据环境配置定义`NegSampleDataLoader` 为每个user进行一比一负采样：https://github.com/RUCAIBox/RecBole/blob/deb1f308b340918aaf27e3aa3392954865e62a39/recbole/data/dataloader/abstract_dataloader.py#L147
`NegSampleDataLoader`使用`RepeatableSampler`采样负例：
https://github.com/RUCAIBox/RecBole/blob/deb1f308b340918aaf27e3aa3392954865e62a39/recbole/sampler/sampler.py#L355

**Comment by WhutTjk** [comment]
@chenyuwuxin 
1. 这里
![image](https://user-images.githubusercontent.com/58941474/139570076-a5c373c0-558c-4da3-a67d-951cef87b667.png)
2. paper是说使用CE损失函数的，然后训练的负采样为1，但是如果我配置了训练时的neg_sampling就会报错
raise ValueError(f"neg_sampling [{self.final_config_dict['neg_sampling']}] should be None "
ValueError: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.
（当然验证的时候取负采样100没问题，只是说训练时按照论文说的负采样1就会出问题，所以我不知道RecBole复现SASRec时是如何体现原论文说的训练负采样为1的，这块我也不太懂...）

**Comment by chenyuwuxin** [comment]
@WhutTjk 

1. 非常感谢你的反馈，我们后续会对文档的错误进行更正。
2. 目前我们实现的SASRec为CELoss，与论文中采用的BCELoss不同，CE把当前的正例以外的所有item都当做负例进行计算，不需要进行负采样。

**Comment by WhutTjk** [comment]
好的明白，谢谢师兄的回复！！
