### ISSUE TITLE
[Question] Please set `user_inter_num_interval` to filter those users who have interacted with all items

### ISSUE THREAD

**Issue by anishparajuli555** [RUCAIBox/RecBole#1028]
**Describe the bug**

When I try to use any GNN models with the .inter file containing user interactions as 0/1 to all items. I get below error : 

`ValueError: Some users have interacted with all items, which we can not sample negative items for them. Please set `user_inter_num_interval` to filter those users.
`
Looks like in my .inter file there is one user who has interacted with all items and the value might have become 1. The code is working fine when we keep only positive interactions  in the .inter file.

**To Reproduce**
YAML FILE
```
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id
load_col:
    inter: [user_id, item_id, comment_interaction]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]

# model config
embedding_size: 64

# Training and evaluation config
epochs: 100
train_batch_size: 32
eval_batch_size: 32
field_separator: ' '
LABEL_FIELD: rating

eval_args:
    group_by: user
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'Precision']
topk: [1,3,5]
valid_metric: MRR@5
metric_decimal_place: 3
```

3. script for running

`python run_recbole.py --model=KGAT --dataset=Angular --config_file=test.yaml
`

How can i fix this issue?

**Comment by chenyuwuxin** [comment]
@anishparajuli555 Hello, thanks for your attention to RecBole!
This problem may be due to you not setting the label field correctly.I don't know the details of `Angular` dataset.
If  `comment_interaction` labels whether the interaction is positive or negative,you should set
`LABEL_FIELD: comment_interaction` in `test.yaml` file.
You can refer to [LABEL OF DATA](https://recbole.io/docs/user_guide/data/label_of_data.html) for information on how to label data.

**Comment by anishparajuli555** [comment]
@chenyuwuxin :  For me  `neg_sampling: None` doesnot works and gives me below error:

`raise ValueError(f"neg_sampling:[{neg_sampling}] should be a dict.")
`
 I tried setting below and it still says the same error

```
LABEL_FIELD: comment_interaction
neg_sampling:
    uniform: 1
```

**Comment by chenyuwuxin** [comment]
@anishparajuli555 You can try:
```
LABEL_FIELD: comment_interaction
neg_sampling: ~
```

**Comment by anishparajuli555** [comment]
For some reasons, it's still giving me the same error. I have attached the KG Files here for your reference.[https://drive.google.com/drive/folders/1vj_wHQeKWv8IYac-qUBVDc8Q7o_SOb5R?usp=sharing](url)

**Comment by chenyuwuxin** [comment]
@anishparajuli555 Hello.If `rating` is 0, which means it has never interacted, and `rating` is 1, which means it has interacted.You can label data in the following ways:

- In the first way, you can remove all items whose `rating` is 0, as you just did.Because we usually think that all the items that appear in the inter file are positive items, while all the items that do not appear are negative items.

- Alternatively, you can filter out items with a rating of 0 in the configuration file like this:
```
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id
load_col:
    inter: [user_id, item_id, rating]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]

# Training and evaluation config
epochs: 100
train_batch_size: 32
eval_batch_size: 32
field_separator: ' '
LABEL_FIELD: rating
val_interval:
  rating: "[1, inf)"


eval_args:
    group_by: user
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'Precision']
topk: [1,3,5]
valid_metric: MRR@5
metric_decimal_place: 3

# model config
embedding_size: 64
```
I hope my answer can help you.

**Comment by anishparajuli555** [comment]
@chenyuwuxin  Thankyou so much! That helped.

**Comment by Captain-Paul** [comment]
@Ethan-TZ 你好，我也遇到了和这个issue标题一样的报错，我的inter文件中是有rating列的，范围是1-5。我的配置如下：
```
parameter_dict = {
    'data_path': '/kaggle/working/',
    'USER_ID_FIELD': 'user_id',
    'ITEM_ID_FIELD': 'video_id',
    'RATING_FIELD': 'rating',
    'user_inter_num_interval': "[0,Inf)",
    'item_inter_num_interval': "[0,Inf)",
    'load_col': {'inter': ['user_id', 'video_id', 'rating']},
    'val_interval': {'rating': "[1,5]"},
    'field_separator': ",",
    'gpu_id': "0",
    'seed': 2024,
    'epochs': 1,
    'threshold': {'rating': 3},
    'train_neg_sample_args': None,
    'neg_sampling': None,
#     'repeatable': True,
    
    'n_neighbors': 50,
    'metric': 'pearson',
    'center': True,
    'aggregate': "weighted_mean",
    'min_neighbors': 10,
    'min_similaity': 0.03,
    
    'eval_args': {
        'group_by': 'user',
        'mode': 'full',
        'split': {'RS': [1, 0, 0]}
    },
}
```
添加了threshold，但好像不起作用，求解答，谢谢
