### ISSUE TITLE
[ Question ] Use of .user and .item for Knowledge Based Recommendation

### ISSUE THREAD

**Issue by anishparajuli555** [RUCAIBox/RecBole#1029]
I was wondering if the .user and .item atomic files are used on KG Based models?

**Comment by chenyuwuxin** [comment]
@anishparajuli555 `.user` and `.item` are not used on KG Based models.
For Knowledge-aware task,we will only use `.inter`,`.kg` and `.link` files.
The content of `.inter` is user feature.
The content of `.kg` is triplets in a knowledge graph.
The content of `.link` is Item-entity linkage data.
You can refer to [Atomic Files](https://recbole.io/docs/user_guide/data/atomic_files.html) for more information.

**Comment by anishparajuli555** [comment]
Thank you for your swift reply. 
Few Questions:
1)
If so, how can we model user attributes like age, total_followers  in the .inter file?  I am looking forward to add user attributes in the KG based models if there is a way. I guess triplets like (user_id, age, 29), (user_id, total_followers, 1000) does not make any sense in the .inter file. 

2) 
Is there any way we can give score/weights to  the relationship created in the .kg file? For e.g: if we want to add user-user similarity score in the KG based models, how can we do that?

**Comment by chenyuwuxin** [comment]
@anishparajuli555 
1. You can create a `.user` file to describe the user feature.
2. You can add a new `.weight` file like (head_id:token tail_id:token weight:float),just set this arg as 
   `additional_feat_suffix: [weight]`.Features of additional features will be stored in `Dataset.feat_list`.You can construct a weight matrix from these three fields,then use this matrix to multiply the elements with the matrix of the model.
