### ISSUE TITLE
近期是否有添加新模型的计划？

### ISSUE THREAD

**Issue by XUPT-guoruihan** [RUCAIBox/RecBole#1031]
非常感谢你们的付出！RecBole是一款非常易用且高效的模型  请问您们最近有添加新模型的计划吗？下个版本大概会在什么时间更新呢？

**Comment by Sherry-XLL** [comment]
@Sherry-XLL 您好，我们开发人员一直在陆陆续续增加一些新模型，但模型上线需要经过开发、调试、测试、审核等步骤，添加到 `master` 分支需要一定的时间。目前 RecBole 的整体框架已经基本定型，暂时不会有大的调整改动，下个版本主要是添加 LightSANs，SGL 等新模型，修复 bug 并添加一些小功能，具体的时间尚未确定，大概会在明年初的时候汇总为一个小版本更新。如果您有添加新模型的需求，可以向我们提供相关论文和作者的源码，有条件的话也欢迎您提出 Pull Request，感谢您对 RecBole 项目的关注！

**Comment by XUPT-guoruihan** [comment]
感谢你们的付出！
