### ISSUE TITLE
关于metrics.py中MRR的计算

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1034]
https://github.com/RUCAIBox/RecBole/blob/99bc8e60b61f7e0e51df3fea599c7a72fe7d4750/recbole/evaluator/metrics.py#L93
这里我觉得MRR的计算方法不应该是改成
`result[row, idx:] += 1 / (idx + 1)`更合适吗？如果只有一个target item还好说，但是如果多个的话，这样的计算是不是就错了？求学长学姐指教

**Comment by chenyuwuxin** [comment]
@WhutTjk 你好，MRR的计算方式如下：
![image](https://user-images.githubusercontent.com/69251138/140498877-90860643-1b1a-44f5-bd07-35a1638d14d2.png)
ranku为进行topk预测给出的第一个正确物品的排名。
`pos_index`为按topk预测对应物品是否正确(bool)。
假设我们有2个用户，进行top5预测，模型给出的结果`pos_index`的形式为 [[0 0 1 1 1] , [0 0 0 1 1]]。
那么idxs为[2,3]，最终的result为[[0 0 1/3 1/3 1/3] , [0 0 0 1/4 1/4]] , 对dim=0求平均值后对应top1~5下的MRR值。
最终结果与多少个target item无关，而只与第一个预测正确的物品对应排名有关。

**Comment by WhutTjk** [comment]
@chenyuwuxin 好的，谢谢！我是在另外一个地方看到有关MRR公式的介绍（[具体网址](https://towardsdatascience.com/ranking-evaluation-metrics-for-recommender-systems-263d0a66ef54)）
![image](https://user-images.githubusercontent.com/58941474/140504000-09718953-cae4-4d7c-807c-2ef6d8690df0.png)
这里可能就没有说是对于每一个用户是只看第一个预测正确的物品，而是预测正确的物品（可能多个），然后取他们的倒数之和的平均，每一个用户都是这么计算，最后取平均值就是MRR了。但这个和学长说的定义不太一样，不过学长所说的这个定义我在一些地方也看到过，所以对此我有些迷糊。

**Comment by chenyuwuxin** [comment]
@WhutTjk 确实，关于MRR有很多种计算方式，你可以参考[metrics](https://recbole.io/docs/recbole/recbole.evaluator.metrics.html)来了解我们的实现方式。

**Comment by WhutTjk** [comment]
@chenyuwuxin 嗯嗯好的，老师让我熟悉咱的RecBole，我最近也在看着doc和源码自己复现一些算法呢~
