### ISSUE TITLE
How to evaluate for a user with *multiple* ground truth items?

### ISSUE THREAD

**Issue by abstrcode** [RUCAIBox/RecBole#1035]
Hello,

For the evaluation, how to evaluate (calculate the metrics) for a user with *multiple* ground truth items? Is there a difference with test user with single test item？ Thanks.

**Comment by chenyuwuxin** [comment]
@abstrcode Hello, thanks for your attention to RecBole!
Generally speaking,for **general** models,we have two ways to build a collection of evaluated items.
1. **Full ranking**:In this way, we include all items in the dataset into the collection of items we evaluate.
2. **Sample-based ranking**:In this way, we sample a certain number of negative items for each ground truth item to construct the collection of items we evaluate.

The recommendation model then scores each item in the evaluation item set,and we find the K items with the highest scores as the final recommendation.We calculate the metrics according to how many ground truth items there are in these K recommended items.Therefore, how many ground truth items a user has are the same.

**Comment by night18** [comment]
@chenyuwuxin Hello,

Could you provide how the data look like for the inter file if I would like to use the Full ranking evaluation?
