### ISSUE TITLE
yelp用enmf模型，内存报错

### ISSUE THREAD

**Issue by hpli** [RUCAIBox/RecBole#1037]
你好：
我使用yelp数据集运行ENMF模型，显示内存不够？我的配置是否错误？谢谢！
![image](https://user-images.githubusercontent.com/9545680/140917936-c2a0b763-82e3-4b9c-b437-765314d2a7fe.png)
![image](https://user-images.githubusercontent.com/9545680/140918153-6eae1af9-87ad-4de7-bdfb-1018a40f56e5.png)

**描述这个 bug**
对 bug 作一个清晰简明的描述。

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
2. 您的代码
3. 您的运行脚本

**预期**
对您的预期作清晰简明的描述。

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [如 0.1.0]
 - Python 版本 [如 3.79]
- PyTorch 版本 [如 1.60]
- cudatoolkit 版本 [如 9.2, none]

**Comment by chenyuwuxin** [comment]
@hpli 你好，感谢你对RecBole的关注！
yelp数据集规模比较大，对计算机内存配置要求较高。
如果你的内存不支持加载整个数据集的话，可以选择过滤掉一些数据。
例如，可以参考以下代码进行配置：
```
config_dict = {
    'checkpoint_dir' : './saved',
    'save_dataset': True,
    'save_dataloaders': True,
    'USER_ID_FIELD': 'user_id',
    'ITEM_ID_FIELD': 'business_id',
    'RATING_FIELD': 'stars',
    'TIME_FIELD': 'date',
    'load_col': "{'inter':['user_id','business_id']}",
    "user_inter_num_interval" : "[15,inf)",
    "item_inter_num_interval": "[15,inf)",
}
run_recbole(model='ENMF',dataset='yelp',config_dict=config_dict)
```

**Comment by hpli** [comment]
@chenyuwuxin 谢谢，按照您给的配置模型可以运行。模型发生错误的阶段不是训练阶段，在数据预处理阶段生成使用np.zero函数生成history_matrix发生内存不够错误，是否能够改成稀疏矩阵？

**Comment by chenyuwuxin** [comment]
@hpli 你好，在数据预处理的过程中，`history_matrix`矩阵的第**i**行，第**j**列表示第**i**个用户历史交互的第**j**个item，用0进行padding。如user1交互的item为1,3,999,4，user2交互的item为4,5,9999。那么history_matrix为[ [ 1 , 3, 999 , 4 ] , [ 4，5，9999，0] ] 。因此在数据集用户数量非常多的时候，所有用户历史交互物品个数的分布应是均匀的，矩阵中0 padding的数量比例非常少，因此改成稀疏矩阵对空间几乎是没有优化的。

**Comment by hpli** [comment]
@chenyuwuxin 非常感谢！
