### ISSUE TITLE
保存dataset和dataloader时候出现这样错误  “can't pickle _thread.RLock objects”

### ISSUE THREAD

**Issue by MRZHAOWC** [RUCAIBox/RecBole#1042]
**Describe the bug**

**To Reproduce**
1. extra yaml file
2. your code
3. script for running

**Expected behavior**

**Screenshots**

**Colab Links**
If applicable, add links to Colab or other Jupyter laboratory platforms that can reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS or Windows]
- RecBole Version [e.g. 0.1.0]
 - Python Version [e.g. 3.79]
- PyTorch Version [e.g. 1.60]
- cudatoolkit Version [e.g. 9.2, none]

**Comment by Sherry-XLL** [comment]
@MRZHAOWC 您好，感谢您对 RecBole 项目的关注！请问您是在运行哪个模型，保存哪个数据集的时候出现了这个错误？`can't pickle _thread.RLock objects` 主要是多进程中线程锁无法被进程打包的问题，可能与您的运行环境有关，您可以试着在报错 `dataset` 和 `dataloader` 的地方输出相关结果，或者存简单的内容调试一下 `dump` 的存储。
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/data/dataset/dataset.py#L1507-L1513

https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/data/utils.py#L53-L66

**Comment by MRZHAOWC** [comment]
非常感谢您的回答，我这几天一直在看你们的这个项目，感觉非常棒，想着用来做点科研。然后我使用的是ml-100看数据集，用的NextItNet模型，还有我想知道你们这个模型前期的数据是怎样处理的就是原子数据到将数据送入模型之前，哪里有详细的说明吗？感谢回答。

**Comment by Sherry-XLL** [comment]
@MRZHAOWC 您好，可以参考我们的[网站](https://recbole.io/cn/index.html)和[官方文档](https://recbole.io/docs/)，文档里有对数据处理的详细说明，有什么问题也可以提出 issue 或者 discussion，感谢您对 RecBole 的关注！
