### ISSUE TITLE
请问输出时为什么没有model's performance

### ISSUE THREAD

**Issue by miiizul** [RUCAIBox/RecBole#1043]
![result](https://user-images.githubusercontent.com/56295135/142206288-65af0b57-bfbb-488f-b6d3-a07da7c26f6c.png)

**Comment by chenyuwuxin** [comment]
@miiizul 感谢你的关注！这个问题是因为`trainer`的 `fit`方法的`verbose`参数为False导致，
可以debug查看`fit`函数传入的参数情况。
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/trainer/trainer.py#L292
如果为False，在调用trainer的fit方法时可以显式地设置`verbose`为`True`，例如：
```
    best_valid_score, best_valid_result = trainer.fit(
        train_data, valid_data, verbose=True,saved=saved, show_progress=config['show_progress']
    )
```

**Comment by miiizul** [comment]
您好！我将对应的verbose参数都修改了，但还是没有输出model's performance。我的python环境是3.7，recbole版本是v1.0.
![fig1](https://user-images.githubusercontent.com/56295135/142342722-4aa10de8-53cf-4b2f-9c41-ffa2b1c2bd01.png)
0
![fig2](https://user-images.githubusercontent.com/56295135/142342735-ef2f47b3-4dfa-4aaf-b3ce-edc329a2335e.png)
。

**Comment by miiizul** [comment]
您好！我将对应的verbose参数都修改了，但还是没有输出model's performance。我的python环境是3.7，recbole版本是v1.0.0。
![fig1](https://user-images.githubusercontent.com/56295135/142342806-17dbfa2f-5b67-49b6-942e-b83477d84514.png)
![fig2](https://user-images.githubusercontent.com/56295135/142342826-b4a117f9-b8fa-4d6b-ad42-088e78b5a828.png)

**Comment by chenyuwuxin** [comment]
@miiizul 有可能是因为logger的日志级别高于INFO，导致没有输出。
你可以尝试在
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/trainer/trainer.py#L79
后加入一条语句：
`self.logger.setLevel(logging.DEBUG)`

**Comment by miiizul** [comment]
还是不行，其他部分的输出都是正常的，只有训练结果部分一直不行
![fig1](https://user-images.githubusercontent.com/56295135/142346592-76d9beb4-0e95-4e12-b800-5a1635f6e188.png
![fig2](https://user-images.githubusercontent.com/56295135/142346608-d7c97b28-0682-4504-aafa-9acd8667f937.png)
)

**Comment by miiizul** [comment]
还是不行，其他部分输出是正常的，只有训练结果部分一直不行
![fig1](https://user-images.githubusercontent.com/56295135/142346708-f0794ea3-fa0c-40c4-988e-2dbdbe3901e0.png
![fig2](https://user-images.githubusercontent.com/56295135/142346719-92b74cbb-42e1-4901-9f8e-8f6b701196e4.png)
)

**Comment by miiizul** [comment]
还是不行，其他部分的输出是正常的，只有训练结果的部分一直不行
![fig1](https://user-images.githubusercontent.com/56295135/142346801-7cd36599-ceb2-4af9-a214-33e84d0d0e45.png)
![fig2](https://user-images.githubusercontent.com/56295135/142346806-daf49115-5288-4a2d-991d-4f7216894c56.png)

**Comment by chenyuwuxin** [comment]
@miiizul 
你好，请尝试将以下代码
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/trainer/trainer.py#L348-L350
改为：
```
if verbose:
    print(self.logger.level)
    print(valid_score_output)
    print(valid_result_output)
    self.logger.info(valid_score_output)
    self.logger.info(valid_result_output)
```
看一下模型是否能够正常得到结果。

**Comment by miiizul** [comment]
这样修改后就正常输出了，非常感谢您的耐心解答！
