### ISSUE TITLE
请问我使用官方例子测试Pop模型和ItemKNN模型，但都只跑了一轮就停止了是为什么呀

### ISSUE THREAD

**Issue by miiizul** [RUCAIBox/RecBole#1045]
这是跑Pop模型run_recbole(model='Pop', dataset='ml-100k')时的结果图
![Pop](https://user-images.githubusercontent.com/56295135/142616573-1e5401cb-92b2-4e57-9619-0036b1d6146b.PNG)
这是跑ItemKNN模型run_recbole(model='ItemKNN', dataset='ml-100k')时的结果图
![ItemKNN](https://user-images.githubusercontent.com/56295135/142616673-d6c09ec6-7273-4c3b-9eca-926d1e1c1b5d.PNG)

**Comment by chenyuwuxin** [comment]
@miiizul 你好，Pop模型根据物品在数据集出现的次数计算流行度作为最终的打分进行topk推荐。而ItemKNN使用K近邻计算训练集物品与物品间的相似度，得到权重矩阵W，然后根据用户在训练集的历史交互计算对物品的打分情况。这两个模型都没有可学习参数去迭代优化，因此一轮就可以得到结果。

**Comment by miiizul** [comment]
感谢解答！
