### ISSUE TITLE
使用pre-trained embedding时报错

### ISSUE THREAD

**Issue by miiizul** [RUCAIBox/RecBole#1046]
您好，我想使用自己预训练的embedding，按照文档将.yaml文件改为如下形式
![fig1](https://user-images.githubusercontent.com/56295135/142726834-6cdb22d7-7423-410e-819b-15757bed3d5c.png)
但是报了这样的错，请问该怎么解决呀
![fig2](https://user-images.githubusercontent.com/56295135/142726849-44cede2b-943a-4c98-984b-9834cc09d8c2.png)

**Comment by Sherry-XLL** [comment]
@miiizul Hello, there is no `item` column when you load data, so pre-training item embeddings can be loaded directly like this:
```python
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, item_emb]
```
And your file with item embeddings should be `[dataset].item` as follows:
item_id:token | item_emb:float_seq
-- | --
1 | -115.08 13.60 113.69
2 | -130.97 263.05 -129.88

In your model, item embedding matrix can be initialized by your pre-trained embedding vectors as following:
```python
class YourModel(GeneralRecommender):
    def __init__(self, config, dataset):
            pretrained_item_emb = dataset.item_feat['item_emb']
            self.item_embedding = nn.Embedding.from_pretrained(torch.from_numpy(pretrained_item_emb))
```
Please notice that when you use pre-trained embeddings, you should put `self.apply(xavier_uniform_initialization)` in the right place in case the pre-training vectors are overwritten.

**Comment by miiizul** [comment]
感谢解答！但是修改后报了如下错误
![fig1](https://user-images.githubusercontent.com/56295135/142754939-e15011ba-cf60-4ba8-ba5d-94fcd3231e06.png)
这是我[dataset].item文件格式
![fig2](https://user-images.githubusercontent.com/56295135/142754971-770f914f-125b-4495-9d9d-940031f70bc5.png)

**Comment by Sherry-XLL** [comment]
@miiizul 您好，加载的 `pretrained_item_emb`  已经是 tensor 格式了，可以用 `self.item_embedding = nn.Embedding.from_pretrained(pretrained_item_emb)` 直接加载，您可以把 `from_numpy` 删了再试试。

**Comment by miiizul** [comment]
已解决，感谢解答！
