### ISSUE TITLE
How to read and write atomic data files to an AWS S3 bucket location?

### ISSUE THREAD

**Issue by akokossi** [RUCAIBox/RecBole#1047]
How to read and write atomic data files to an AWS S3 bucket location?
**Additional context**
I am able to run code in my local computer but my files are in S3
I mean does recbole process accept a dataset path that is located on AWS S3? and can it recognize a file on S3 using s3fs?

**Comment by akokossi** [comment]
I mean does recbole process accept a dataset path that is located on AWS S3? and can it recognize a file on S3 using s3fs?

**Comment by chenyuwuxin** [comment]
@akokossi Hello, thanks for your attention to RecBole!
Unfortunately, we do not support reading and writing dataset from the cloud storage platform at present.And it is very difficult to do so. Firstly,different cloud storage platforms have different access mechanisms. Secondly, reading data from cloud storage platforms may involve user privacy issues.Therefore,the path of the dataset can only be the path of the local computer.

**Comment by akokossi** [comment]
Oh ok, thanks

**Comment by akokossi** [comment]
About the same,  there is a Python package that can be used to access S3 as a file system called s3fs to save and read (Pickle ) files in S3 from RecBole code. I am able to read the atomic files from S3 but the model pickle file seems to be the one that cannot be saved/red from Recbole. Can s3fs be used to read/write the pickle model generated files? if so where can this be applied?
