### ISSUE TITLE
[💡SUG] Python Typing Hints

### ISSUE THREAD

**Issue by FineArtz** [RUCAIBox/RecBole#1051]
Hi, I would like to know whether there will be typing hints in the code. Though I benefit a lot from your complete function description, my editor can neither understand them nor support quick jump to references🙁. Do you have any plans about adding typing hints?

**Comment by chenyuwuxin** [comment]
@FineArtz Hello, thanks for your attention to RecBole!
As you know,our project has large quantities and many details,but there are few maintenance personnel at present.Doing such a thing will cost more,we will think about it carefully.Fortunately, you can refer to the API [documentation(API Doc)](https://recbole.io/docs/) provided by us to better understand our project.We also welcome the community to supplement and improve our code.
