### ISSUE TITLE
How to use GPU? GPU does not work

### ISSUE THREAD

**Issue by gongtigigi** [RUCAIBox/RecBole#1057]
![image](https://user-images.githubusercontent.com/84376695/143366139-b8c19a06-0033-48ab-8872-907c984e0705.png)
When I run quick_start, it seems like recbole use gpu.

![image](https://user-images.githubusercontent.com/84376695/143366277-f0beef77-214c-44f8-baf0-4a3c22e47da6.png)
![image](https://user-images.githubusercontent.com/84376695/143366299-36c7905a-f6c4-4d2c-bcca-ae6b80728fdc.png)
But above screenshots show that my PC does not use gpu.
(There is no GPU RAM like quick start example ![image](https://user-images.githubusercontent.com/84376695/143366548-d9622211-4190-457b-a387-433551df55df.png))
Also, when I run other big dataset and model, it is too slow.

I check the version that recbole required
Linux, recbole 1.0.0, python 3.7.9, pytorch 1.10.0, cuda 10.1

How to use GPU??

**Comment by chenyuwuxin** [comment]
@gongtigigi Hello, thanks for your attention to RecBole!
There may be many reasons for this problem.First you have to make sure your environment is right.That is, you run the following statements in Python:`torch.cuda.is_available()`,the result should be `True`.If not, you should check that the GPU version of `pytorch` is installed correctly.

**Comment by gongtigigi** [comment]
Thanks!
