### ISSUE TITLE
[🐛BUG] Describe your problem in one sentence.

### ISSUE THREAD

**Issue by akokossi** [RUCAIBox/RecBole#1058]
**Describe the bug**
I get this error
"Exception has occurred: ValueError
Some feat is empty, please check the filtering settings."  Not very explicit for me to diagnose issue" what are some of the what can cause this?

**To Reproduce**
parameter_dict = {
            'data_path': DATA_PATH +"/prod-recommend/output/",
            'checkpoint_dir':MODEL_PATH+"/prod-recommend/output/recsys", 
            'max_user_inter_num':8,
            'min_item_inter_num': 1,
            'max_item_inter_num':7,
            'load_col': {
                'inter': ['user_id',"item_id",  'rating','timestamp','discount_rate' ],
                'user':['user_id','avg_usr_rating', 'avg_usr_discount'],
                'item':['item_id','avg_itm_rating', 'avg_itm_discount']
                },
            'USER_ID_FIELD': 'user_id',
            'ITEM_ID_FIELD': 'item_id',
            'TIME_FIELD':"timestamp"
            }
            dddf = pd.read_csv(DATA_PATH +"/prod-recommend/output/mydata/mydata.inter" )
 
            if len(dddf)>10:
                run_recbole(dataset='mydata',model='BPR', config_dict=parameter_dict)

**Expected behavior**
Trying to get my model to run.

**Screenshots**
N/A

**Colab Links**
N/A
**Desktop (please complete the following information):**
 - OS:  Windows]
- RecBole Version -  I used "conda install aibox recbole" on a new environment
 - Python Version - I used "conda install aibox recbole"
- PyTorch Version [1.3.1]
- cudatoolkit Version [none]

**Comment by chenyuwuxin** [comment]
@akokossi Hello, thanks for your attention to RecBole!
This problem may be caused by many reasons. First, you need to update the version of RecBole.Our latest version is v1.0.0 and the required pytorch version is no less than 1.7.0. In the new version, we no longer use variables such as `max_user_inter_num` to filter.You can refer to [GUIDE](https://recbole.io/docs/get_started/install.html) to install and refer to [Settings](https://recbole.io/docs/user_guide/config/data_settings.html) to config.

**Comment by akokossi** [comment]
Thank you. I did what you asked.

I am now getting the following error 


Exception has occurred: ImportError


IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\...\.conda\envs\recbole\python.exe"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

**Comment by akokossi** [comment]
I got it running, it was the python version in my conda environment.  Thank you!
