### ISSUE TITLE
[💡SUG] NISER implementation

### ISSUE THREAD

**Issue by pintonos** [RUCAIBox/RecBole#1061]
Hi!
Are there any plans to implement [NISER](https://arxiv.org/abs/1909.04276) for sequential recommendation? It is based on SR-GNN, which is already implemented in RecBole. Perhaps this implementation is a good reference: [https://github.com/johnny12150/NISER](https://github.com/johnny12150/NISER).

If there are no ressources for this, I could come forward with a PR.

**Comment by Sherry-XLL** [comment]
@pintonos Hello, thank you for your attention to RecBole! We have no plan to implement NISER for the time being. If it's convenient for you, we welcome your pull request very much.

**Comment by Sherry-XLL** [comment]
@pintonos Hello, our team have constructed an extended recommendation library [RecBole2.0](https://github.com/RUCAIBox/RecBole2.0) consisting of 8 packages for up-to-date topics and architectures (e.g., debiased, fairness and GNNs).

In [RecBole-GNN](https://github.com/RUCAIBox/RecBole-GNN), we have implemented the [NISER](https://github.com/RUCAIBox/RecBole-GNN/blob/main/recbole_gnn/model/sequential_recommender/niser.py) model from Gupta et al.: [NISER: Normalized Item and Session Representations to Handle Popularity Bias](https://arxiv.org/abs/1909.04276) (GRLA, CIKM 2019 workshop). 

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
