### ISSUE TITLE
[🐛BUG] LABEL_FIELD与threshold的key重复时，LABEL_FIELD会被删除

### ISSUE THREAD

**Issue by FineArtz** [RUCAIBox/RecBole#1065]
我不确定这是不是bug，但我运行程序时确实遇到了这样的问题。例如，数据集中的标签名称为`label`，我希望把大于等于1的值都设置为1，所以在config中设置
```
LABEL_FIELD: label
threshold:
  label: 1
```
那么在处理`threshold`时，按照[以下代码](https://github.com/RUCAIBox/RecBole/blob/e6c05d4dfb3f1e53816fedc37b6f94829e3ef195/recbole/data/dataset/dataset.py#L878) 的逻辑
```
# Line 878 ~ 883, in _set_label_by_threshold(), recbole/data/dataset/dataset.py
for field, value in threshold.items():
    if field in self.inter_feat:
        self.inter_feat[self.label_field] = (self.inter_feat[field] >= value).astype(int)
    else:
        raise ValueError(f'Field [{field}] not in inter_feat.')
    self._del_col(self.inter_feat, field)
```
首先，`self.inter_feat[self.label_field]`按照`threshold`中的设置变成了期望的值。但是，如果像上面那样，`self.label_field`和`threshold`中的`field`是一样的，在最后一行，`self.label_field`会被删除。所以要让程序正常运行，必须把这两者设置成不一样的值。

**Comment by Sherry-XLL** [comment]
@FineArtz 您好，我们已经在 #1066 中修改了 `dataset.py` 的相关代码，感谢您的反馈与关注！
