### ISSUE TITLE
[🐛BUG] Benchmark preset error with sequential dataset

### ISSUE THREAD

**Issue by pintonos** [RUCAIBox/RecBole#1069]
Hi,
I am trying to use a sequential benchmark dataset, but I get following error:
```
Traceback (most recent call last):
  File "C:/Users/apein/Documents/projects/humrecsys/seq_rec/run.py", line 68, in <module>
    main(args=args)
  File "C:/Users/apein/Documents/projects/humrecsys/seq_rec/run.py", line 42, in main
    dataset = create_dataset(config)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\utils.py", line 41, in create_dataset
    return SequentialDataset(config)
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 38, in __init__
    self._benchmark_presets()
  File "C:\Users\apein\.virtualenvs\humrecsys-Aky0O99T\lib\site-packages\recbole\data\dataset\sequential_dataset.py", line 146, in _benchmark_presets
    self.inter_feat[self.item_list_length_field] = self.inter_feat[self.item_id_list_field].agg(len)
AttributeError: 'SequentialDataset' object has no attribute 'item_id_list_field'
```

This error only appears while using a sequential model. General models work fine with the benchmark dataset.

**Comment by chenyuwuxin** [comment]
@pintonos Hello, thanks for your attention to RecBole!
Please provide the necessary running code and `.yaml` configuration file so that we can reproduce the problem.

**Comment by chenyuwuxin** [comment]
@pintonos Hello, we won't do `data_augmentation` when you use benchmark file to construct sequential dataset. That is, you must manually provide sequential interaction information. More specifically, `item_id_list_field` must be provided in your `.inter` file.

**Comment by pintonos** [comment]
Thanks for the information! Is it somehow possible to call `data_augmentation`, despite the usage of a benchmark dataset?

**Comment by chenyuwuxin** [comment]
@pintonos Sorry , we don't have such an interface at present.

**Comment by pintonos** [comment]
Sorry I have to reopen this.
I was wondering about the data splitting: According to the documentation the `group_by` evaluation parameter, if set to `user`, groups the dataset by the user (or session when used sequentially) before splitting into train, valid and test set. This would imply for me, that e.g. a session id from the valid set is not part of the train set. However, this is not the case! In the `split_by_ratio` function of `Dataset` each session gets equally split into the 3 sets. Is this intended? Whats the point of grouping then? How can I ensure to split the data session-wise only?

**Comment by hyp1231** [comment]
Hi,
I understand that you want to ensure that session id doesn't overlap between train set, validation set and test set. Currently, we suggest to pre-split the dataset into `xxx.train.inter`, `xxx.valid.inter` and `xxx.test.inter` and load it via `benchmark_filename` (one example, [session_based_rec_example](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py), you can also download the processed `diginetica-session` dataset to check it detailly.)

The 1. _group by user_ and 2. _split_ pipeline is mainly designed for general collaborative filtering methods or sequential recommendation methods (especially _leave one out_ evaluation). For session-based recommendation, we recommend following the way in the above example.
