### ISSUE TITLE
[🐛BUG]照着官网教程自定义模型时报错

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1071]
**描述这个 bug**
参照官网自定义模型部分，自定义模型继承GeneralRecommender。
在自定义模型中__init__方法中先调用父类的__init__，在父类即GeneralRecommender的__init__中有self.n_users = dataset.num(self.USER_ID)
而在run.py文件中传入自定义模型的是TrainDataLoader：train_data

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
2. 您的代码
3. 您的运行脚本

**预期**
对您的预期作清晰简明的描述。

**屏幕截图**
报错信息
![image](https://user-images.githubusercontent.com/31268918/144584372-7a739d5b-7b52-4742-a307-d8a14e5beb86.png)
run.py
![image](https://user-images.githubusercontent.com/31268918/144584942-4c1d41e8-74ef-4b5d-848b-c050bb6938f7.png)

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: [Windows]
- RecBole 版本 [1.0.0]
 - Python 版本 [3.68]
- PyTorch 版本 [1.10]
- cudatoolkit 版本 [none]

**Comment by chenyuwuxin** [comment]
@tctctctctc 感谢您对RecBole的关注与反馈！
模型构建部分文档确实存在错误，应修正为：
`model = NewModel(config, train_data.dataset).to(config['device'])`
我们后续会对文档进行修正，再次感谢您的反馈！

**Comment by 2017pxy** [comment]
@tctctctctc 你好，感谢反馈，我们已经在 # 1072 修复了这个问题。
