### ISSUE TITLE
[🐛BUG] Rating predictions evaluated by MAE/RMSE

### ISSUE THREAD

**Issue by irecsys** [RUCAIBox/RecBole#1073]
Hi, I just want to try rating prediction evalutions on the MovieLens data by using ItemKNN 

Below is my yaml file

There are a couple of issues

1). I found the answers about rating predictions in the forum, and set
threshold:
    rating: 3
neg_sampling: None

But there are always errors which told me "neg_sampling: None" is wrong

2). Some of your answers instructed me to set "mode: labeled", but it seems that "labeled" is no longer mentioned in your latest API

3). we must set a value for topK? even if we evaluate it by MAE/RMSE? it always reports errors if I did not set a value for that

4). Can you provide an example of yaml file for running ItemKNN and evaluating MAE/RMSE. All of the examples provided by the official websites are related to top-N recommendations

gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False
threshold:
    rating: 3

epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
neg_sampling: None
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
weight_decay: 0.0

eval_args: 
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: labeled
repeatable: False
metrics: ["MAE","RMSE"]
valid_metric: RMSE

valid_metric_bigger: False
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4

**Comment by Sherry-XLL** [comment]
@irecsys Hello, thanks for your attention to RecBole! 

- 1). If we don't need negative sampling, we should set `neg_sampling: ~` instead of `neg_sampling: None`.
- 2). `labeled` is one of the data range settings which we evaluate the model on, and its documentation can be found [here](https://recbole.io/docs/user_guide/config/evaluation_settings.html#evaluation-settings) as follows:

> mode (str): decides the data range which we evaluate the model on. Now we support four kinds of evaluation mode: ['full','unixxx','popxxx','labeled']. For explicit feedback (data with label), you should set the mode as labeled and we will evaluate the model based on your label. The default value is full.

- 3). RecBole supports both value-based and ranking-based evaluation metrics, and the error is due to incorrect configuration.
- 4). The following file is my configuration file to run ItemKNN with value-based evaluation metrics. You can name this file `ml-1m_general.yaml` and put it in the same folder with `run_recbole.py`. Then, you can run the command line `python run_recbole.py --model=ItemKNN --config_files=ml-1m_general.yaml` and get the results.

```python
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
threshold:
    rating: 3
load_col:
    inter: [user_id, item_id, rating]

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 409600000

neg_sampling: ~

eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}
  group_by: ~
  mode: labeled
  order: RO
valid_metric: AUC
metrics: ['AUC', 'LogLoss', 'MAE', 'RMSE']

# model
embedding_size: 64
```

My results are as follows:
```
04 Dec 09:21    INFO  [Training]: train_batch_size = [4096] negative sampling: [None]
04 Dec 09:21    INFO  [Evaluation]: eval_batch_size = [409600000] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'group_by': None, 'mode': 'labeled', 'order': 'RO'}]
04 Dec 09:21    INFO  ItemKNN()
Trainable parameters: 1
Train     0: 100%|████████████████████████| 20/20 [00:00<00:00, 378.56it/s, GPU RAM: 0.00 G/11.91 G]
04 Dec 09:21    INFO  epoch 0 training [time: 0.08s, train loss: 0.0000]
Evaluate   : 100%|███████████████████████████| 1/1 [00:00<00:00, 13.73it/s, GPU RAM: 0.00 G/11.91 G]
04 Dec 09:21    INFO  epoch 0 evaluating [time: 0.08s, valid_score: 0.589900]
04 Dec 09:21    INFO  valid result: 
auc : 0.5899    logloss : 6.1341    mae : 11.8833    rmse : 14.3886    
04 Dec 09:21    INFO  Saving current best: saved/ItemKNN-Dec-04-2021_09-21-55.pth
04 Dec 09:21    INFO  Loading model structure and parameters from saved/ItemKNN-Dec-04-2021_09-21-55.pth
Evaluate   : 100%|███████████████████████████| 1/1 [00:00<00:00, 15.16it/s, GPU RAM: 0.00 G/11.91 G]
04 Dec 09:21    INFO  best valid : {'auc': 0.5899, 'logloss': 6.1341, 'mae': 11.8833, 'rmse': 14.3886}
04 Dec 09:21    INFO  test result: {'auc': 0.5998, 'logloss': 6.1243, 'mae': 11.8447, 'rmse': 14.3113}
```

**Comment by irecsys** [comment]
> ```python
> LABEL_FIELD: label
> ```

thanks.

Again, it still asks me to setup a value for topK

Is this correct? LABEL_FIELD: label, since we do not have a column "label" in the data, there is a column "rating"

**Comment by Sherry-XLL** [comment]
@irecsys In recommendation filed, there are two kinds of data scenes: explicit feedback scene and implicit feedback scene.

Explicit feedback, like rating for items, has explicit label for model training. While for implicit feedback, like clicks and purchases, the label of data is vague, and generally we will regard all the observed interaction as the positive samples and select negative samples from unobserved interactions (known as negative sampling).

To supports both explicit feedback scene and implicit feedback scene, RecBole design three ways to set label of data. You can refer to [documentation](https://recbole.io/docs/user_guide/data/label_of_data.html?) for more details about label of data.

What's more, what do you mean by `Again, it still asks me to setup a value for topK`? You use the same configuration file with me but there's still an error when you run the code?

**Comment by irecsys** [comment]
> @irecsys In recommendation filed, there are two kinds of data scenes: explicit feedback scene and implicit feedback scene.
> 
> Explicit feedback, like rating for items, has explicit label for model training. While for implicit feedback, like clicks and purchases, the label of data is vague, and generally we will regard all the observed interaction as the positive samples and select negative samples from unobserved interactions (known as negative sampling).
> 
> To supports both explicit feedback scene and implicit feedback scene, RecBole design three ways to set label of data. You can refer to [documentation](https://recbole.io/docs/user_guide/data/label_of_data.html?) for more details about label of data.
> 
> What's more, what do you mean by `Again, it still asks me to setup a value for topK`? You use the same configuration file with me but there's still an error when you run the code?

Yes, I run it in Pycharm.

My run.py looks like this

 parser = argparse.ArgumentParser()
    parser.add_argument('--model', '-m', type=str, default='ItemKNN', help='name of models')
    parser.add_argument('--dataset', '-d', type=str, default='ml-100k', help='name of datasets')
    parser.add_argument('--config_files', type=str, default='test.yaml', help='config files')

and my test.yaml is the same as yours

**Comment by Sherry-XLL** [comment]
@irecsys It may be the problem with the default running path of your code. The default working path of PyCharm is not necessarily the current directory of your code. Your model does not use the configuration information in `test.yaml`, so an error is reported. Please change `test.yaml` in `parser.add_argument('--config_files', type=str, default='test.yaml', help='config files')` to the absolute path of the file on your computer and try again. Alternatively, you can try outputting `args.config_files` to see if it is correct.

**Comment by irecsys** [comment]
> @irecsys It may be the problem with the default running path of your code. The default working path of PyCharm is not necessarily the current directory of your code. Your model does not use the configuration information in `test.yaml`, so an error is reported. Please change `test.yaml` in `parser.add_argument('--config_files', type=str, default='test.yaml', help='config files')` to the absolute path of the file on your computer and try again. Alternatively, you can try outputting `args.config_files` to see if it is correct.

the same error, see below

topk = self.final_config_dict['topk']
KeyError: 'topk'

**Comment by Sherry-XLL** [comment]
@irecsys I don't know why the configuration is exactly the same, but your code will report errors. Please copy the complete error information.

**Comment by irecsys** [comment]
Traceback (most recent call last):
  File "C:\Users\xx\PycharmProjects\RecBole\run_recbole.py", line 27, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\Users\xx\PycharmProjects\RecBole\recbole\quick_start\quick_start.py", line 32, in run_recbole
    config = Config(model=model, dataset=dataset, config_file_list=config_file_list, config_dict=config_dict)
  File "C:\Users\xx\PycharmProjects\RecBole\recbole\config\configurator.py", line 78, in __init__
    self._set_default_parameters()
  File "C:\Users\xx\PycharmProjects\RecBole\recbole\config\configurator.py", line 309, in _set_default_parameters
    topk = self.final_config_dict['topk']
KeyError: 'topk'

**Comment by Sherry-XLL** [comment]
@irecsys `topk` is set in our default configuration file `recbole/properties/overall.yaml` that `topk: [10]`, so there should be no case where `topk` is `None`. I think it is the problem of PyCharm's working path. You can try adding two lines of code to Line 213 in `recbole\config\configuratior.py` and see if the output is `recbole\config`.

```python
def _load_internal_config_dict(self, model, model_class, dataset):
    current_path = os.path.dirname(os.path.realpath(__file__))
    print(current_path)
    exit()
    overall_init_file = os.path.join(current_path, '../properties/overall.yaml')
    model_init_file = os.path.join(current_path, '../properties/model/' + model + '.yaml')
    sample_init_file = os.path.join(current_path, '../properties/dataset/sample.yaml')
    dataset_init_file = os.path.join(current_path, '../properties/dataset/' + dataset + '.yaml')
```

**Comment by Sherry-XLL** [comment]
@irecsys In addition, you can try adding a line `topk: [10]` to `test.yaml`.

**Comment by irecsys** [comment]
> ```python
> 
>     print(current_path)
>     exit()
> ```

Thanks. It works now. I mistakenly changed the overall.yaml. That's the reason why it reports errors when it loads default yaml files
