### ISSUE TITLE
Trying to predict the list of top items per user using your code and got this error

### ISSUE THREAD

**Issue by akokossi** [RUCAIBox/RecBole#1074]
**Describe the bug**

**To Reproduce**
def test_it(model_name,model_file):
    
     config, model, dataset, train_data, valid_data, test_data = load_data_and_model( model_file=model_file)
       
     # or you can use dataset.token2id to transfer external user token to internal user id 
     uid_series = dataset.token2id(dataset.uid_field, ['1004', '1019']) 
  
     topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device']) 
     print(topk_score)  # scores of top 10 items 
     print(topk_iid_list)  # internal id of top 10 items 
     external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu()) 
     print(external_item_list)  # external tokens of top 10 items 
     print() 
  
     score = full_sort_scores(uid_series, model, test_data, device=config['device']) 
     print(score)  # score of all items 
     print(score[0, dataset.token2id(dataset.iid_field, ['242', '302'])])  # score of item ['242', '302'] for user '196'.     

**Expected behavior**
Wanted to get top items per user

but got the error:

05 Dec 23:47    INFO  [Training]: train_batch_size = [2048] negative sampling: [{'uniform': 1}]
05 Dec 23:47    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full', 'group_by': 'user'}]
Traceback (most recent call last):
  File "serve.py", line 153, in <module>
   ...
  File "serve.py", line 142, in test_it
    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
  File "..\.conda\envs\recbole\lib\site-packages\recbole\utils\case_study.py", line 90, in full_sort_topk   
    scores = full_sort_scores(uid_series, model, test_data, device)
  File "..\.conda\envs\recbole\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context 
    return func(*args, **kwargs)
  File "..\.conda\envs\recbole\lib\site-packages\recbole\utils\case_study.py", line 50, in full_sort_scores 
    index = np.isin(dataset[uid_field].numpy(), uid_series)
  File "..\.conda\envs\recbole\lib\site-packages\recbole\data\dataset\dataset.py", line 1264, in __getitem__    return self.join(df) if join else df
  File "..\.conda\envs\recbole\lib\site-packages\recbole\data\dataset\dataset.py", line 1256, in join       
    if self.user_feat is not None and self.uid_field in df:
  File "..\.conda\envs\recbole\lib\site-packages\torch\_tensor.py", line 707, in __contains__
    type(element)
RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.

**Desktop (please complete the following information):**
 - OS:  Windows
- RecBole Version 1.0.0
 - Python Version 3,7
- PyTorch Version 1.7.0
- cudatoolkit Version none]

**Comment by Sherry-XLL** [comment]
@akokossi Hello, do you have this problem when you run BPR model on ml-100k with the initial configuration?

**Comment by akokossi** [comment]
i am able to run the training fine, it is the creation of top n item for users that gives this issue

**Comment by Sherry-XLL** [comment]
@akokossi I don't quite understand your problem. Can you give the code that can reproduce the problem with the data set in RecBole?

**Comment by akokossi** [comment]
Here is the code to train:


#========================================TRAINING CODE=====================================================
# PLEASE CHANGE PATH
from recbole.quick_start import run_recbole, load_data_and_model

path = "C://Users/.../output"

def save_example():
    # configurations initialization
    config_dict = {
        'data_path':"C://Users/.../output",
        'checkpoint_dir': 'C://Users/.../output/saved',
        'save_dataset': True,
        'save_dataloaders': True,
        'USER_ID_FIELD': 'user_id',
        'ITEM_ID_FIELD': 'item_id',
        'TIME_FIELD':"timestamp",
        "RATING_FIELD": 'rating',
        'load_col': {
            'inter': ['user_id',"item_id",  'rating','timestamp','discount_rate' ],
            'user':['user_id','avg_usr_rating', 'avg_usr_discount'],
            'item':['item_id','avg_itm_rating', 'avg_itm_discount']
            },
            "training_neg_sample_num":1,
            "embedding_size":64
        
    }
    run_recbole(model='FPMC', dataset='testdata', config_dict=config_dict)


def load_example():
    # Filtered dataset and split dataloaders are created according to 'config'.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
    )

    # Filtered dataset is loaded from file, and split dataloaders are created according to 'config'.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataset_file=path+'/saved/testdata-dataset.pth',
    )

    # Dataset is neither created nor loaded, and split dataloaders are loaded from file.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataloader_file=path+'/saved/testdata-for-FPMC-dataloader.pth',
    )
    assert dataset is None

    # Filtered dataset and split dataloaders are loaded from file.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
         model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataset_file=path+'/saved/testdata-dataset.pth',
        dataloader_file=path+'/saved/testdata-for-FPMC-dataloader.pth',
    )


if __name__ == '__main__':
    save_example()
    #load_example()



#=============================================Scoring  code=================================================



import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
path = "C://Users/penof/Documents/projects/data/3BFEA81EF251/3BFEA81EF251-1/version-2021_10_14/prod-recommend/output"


if __name__ == '__main__':
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
    )  # Here you can replace it by your model path.

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    uid_series = dataset.token2id(dataset.uid_field, ['1003', '1005'])

    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()

    score = full_sort_scores(uid_series, model, test_data, device=config['device'])
    print(score)  # score of all items
    print(score[0, dataset.token2id(dataset.iid_field, ['ABC_Cereal_Bars prod group 13 ITEM -1', 'ABC_Cereal_Bars prod group 13 ITEM -10'])])  # score of item ['242', '302'] for user '196'.

[data.zip](https://github.com/RUCAIBox/RecBole/files/7673258/data.zip)

**Comment by akokossi** [comment]
`
#========================================TRAINING CODE=====================================================
# PLEASE CHANGE PATH
from recbole.quick_start import run_recbole, load_data_and_model

path = "C://Users/.../output"

def save_example():
    # configurations initialization
    config_dict = {
        'data_path':"C://Users/.../output",
        'checkpoint_dir': 'C://Users/.../output/saved',
        'save_dataset': True,
        'save_dataloaders': True,
        'USER_ID_FIELD': 'user_id',
        'ITEM_ID_FIELD': 'item_id',
        'TIME_FIELD':"timestamp",
        "RATING_FIELD": 'rating',
        'load_col': {
            'inter': ['user_id',"item_id",  'rating','timestamp','discount_rate' ],
            'user':['user_id','avg_usr_rating', 'avg_usr_discount'],
            'item':['item_id','avg_itm_rating', 'avg_itm_discount']
            },
            "training_neg_sample_num":1,
            "embedding_size":64
        
    }
    run_recbole(model='FPMC', dataset='testdata', config_dict=config_dict)


def load_example():
    # Filtered dataset and split dataloaders are created according to 'config'.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
    )

    # Filtered dataset is loaded from file, and split dataloaders are created according to 'config'.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataset_file=path+'/saved/testdata-dataset.pth',
    )

    # Dataset is neither created nor loaded, and split dataloaders are loaded from file.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataloader_file=path+'/saved/testdata-for-FPMC-dataloader.pth',
    )
    assert dataset is None

    # Filtered dataset and split dataloaders are loaded from file.
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
         model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
        dataset_file=path+'/saved/testdata-dataset.pth',
        dataloader_file=path+'/saved/testdata-for-FPMC-dataloader.pth',
    )


if __name__ == '__main__':
    save_example()
    #load_example()



#=============================================Scoring  code=================================================



import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
path = "C://Users/penof/Documents/projects/data/3BFEA81EF251/3BFEA81EF251-1/version-2021_10_14/prod-recommend/output"


if __name__ == '__main__':
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file=path+'/saved/FPMC-Dec-07-2021_22-23-31.pth',
    )  # Here you can replace it by your model path.

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    uid_series = dataset.token2id(dataset.uid_field, ['1003', '1005'])

    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()

    score = full_sort_scores(uid_series, model, test_data, device=config['device'])
    print(score)  # score of all items
    print(score[0, dataset.token2id(dataset.iid_field, ['ABC_Cereal_Bars prod group 13 ITEM -1', 'ABC_Cereal_Bars prod group 13 ITEM -10'])])  # score of item ['242', '302'] for user '196'.

`

**Comment by Sherry-XLL** [comment]
@akokossi Hello, thanks for your attention and advice, we have fixed the bug in #1083.

**Comment by akokossi** [comment]
Thank you for pushing. I reinstalled the recbole environment and run "pip install recbole" , however when rerun this code I now get:

Exception has occurred: RuntimeError
Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.
  File "C:\Users\penof\Downloads\d\test.py", line 18, in <module>
    topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])

Is it because pip install recbole is not using the most recent version?

**Comment by Sherry-XLL** [comment]
@akokossi Yes, pip install is not using the most recent version in GitHub, you can modify code directly in `recbole/utils/case_study.py` as follows.

 https://github.com/RUCAIBox/RecBole/blob/5179244330bbf889398fb95f3d3f84fd6eb61b21/recbole/utils/case_study.py#L50-L53

**Comment by akokossi** [comment]
Thank you it worked. Is there a way to covert the case study output into pandas dataframe?

**Comment by Sherry-XLL** [comment]
@akokossi The type of the case study output is `tensor`. If you want to convert `tensor` into `pandas dataframe`, you can use `.numpy()` to convert `tensor` into `numpy` first, then use `pandas.DataFrame` to convert `numpy` into `dataframe`.

**Comment by akokossi** [comment]
got it, thank you
