### ISSUE TITLE
[🐛BUG] 使用Criteo数据集时报错

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1077]
**描述这个 bug**
使用**_Criteo_**数据集做CTR预估时报错

**如何复现**
config.yaml
load_col:
  inter: [ I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13,
           C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, C21, C22, C23, C24, C25, C26 ]
LABEL_FIELD: label
USER_ID_FIELD: None
ITEM_ID_FIELD: None
RATING_FIELD: None
TIME_FIELD: None

报错
ValueError: `alias_of_user_id` and `alias_of_item_id` should not have the same field ['None'].

**预期**
可以发一个配置文件吗

**Comment by Sherry-XLL** [comment]
@DX12321 你好，**Criteo** 数据集运行 Context 模型的示例配置文件如下：

```python
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: ~
ITEM_ID_FIELD: ~
LABEL_FIELD: label

load_col: 
    inter: '*'

fill_nan: True
normalize_all: True


# training and evaluation
epochs: 500
train_batch_size: 4096
eval_args:
  mode: labeled
  group_by: ~
valid_metric: AUC
metrics: ['AUC', 'LogLoss']

# model
embedding_size: 10
```

**Comment by DX12321** [comment]
好的，谢谢啦
