### ISSUE TITLE
[🐛BUG] 运行官网教程自定义模型时出错

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1078]
**描述这个 bug**
在官网的教程：自定义模型 【https://recbole.io/docs/developer_guide/customize_models.html#complete-code】
运行时报错：
============
File "D:\Anaconda3\lib\site-packages\recbole\data\interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'label'
==========
报错代码：
# model training
best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
2. 您的代码
3. 您的运行脚本

**预期**

**Comment by Sherry-XLL** [comment]
@DX12321 你好，感谢对 RecBole 项目的关注，可能是你的配置文件不太合适，对于 label 的设置可以参考 [Label of data](https://recbole.io/docs/user_guide/data/label_of_data.html)。
