### ISSUE TITLE
[🐛BUG] 运行官网教程上的自动调参程序时报错

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1081]
**描述这个 bug**
  File "D:\Anaconda3\lib\site-packages\hyperopt\pyll\stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
================================================================================
ERROR in rec_eval
EXCEPTION
<class 'AttributeError'>
'numpy.random.mtrand.RandomState' object has no attribute 'integers'
NODE
0 randint
1   Literal{2}
2  size =
3   len
4     array_union
5       array_union
6         array_union
7           Literal{new_ids}
8  rng =
9   Literal{rng-placeholder}
================================================================================
  0%|          | 0/6 [00:00<?, ?trial/s, best loss=?]

Process finished with exit code 1

**如何复现**
复现这个 bug 的步骤：

1. 您引入的额外 yaml 文件
===== config.yaml =====
# model config
embedding_size: 10
mlp_hidden_size: [512,256,128]
===== model.hyper =====
embedding_size choice [4,8,10]
mlp_hidden_size choice ['[64,64,64]','[128,128]']

2. 您的代码
    run_recbole(model='BPR', dataset='ml-100k', config_file_list=['config.yaml'])
    hp = HyperTuning(objective_function=objective_function, algo='exhaustive',
                     params_file='model.hyper', fixed_config_file_list=['config.yaml'])

    # run
    hp.run()
    # export result to the file
    hp.export_result(output_file='hyper_example.result')
    # print best parameters
    print('best params: ', hp.best_params)
    # print best result
    print('best result: ')
    print(hp.params2result[hp.params2str(hp.best_params)])

**预期**
对您的预期作清晰简明的描述。

**链接**
官方参考文档教程 https://recbole.io/docs/user_guide/usage/parameter_tuning.html

**Comment by chenyuwuxin** [comment]
@DX12321 您好，感谢您的关注！
我运行文档的教程代码：
```
from recbole.trainer import HyperTuning
from recbole.quick_start import objective_function

hp = HyperTuning(objective_function=objective_function, algo='exhaustive',
                params_file='test.hyper', fixed_config_file_list=['test.yaml'])

# run
hp.run()
# export result to the file
hp.export_result(output_file='hyper_example.result')
# print best parameters
print('best params: ', hp.best_params)
# print best result
print('best result: ')
print(hp.params2result[hp.params2str(hp.best_params)])
```
command: `python run.py --dataset=ml-100k --model=BPR`
并没有出现错误，出现这个问题可能是python环境版本太低，请您提供运行环境的python版本，RecBole版本。

**Comment by DX12321** [comment]
Python 3.8.3 
RecBole 1.0.0
numpy 1.19.5

**Comment by DX12321** [comment]
我这边又试了一下从命令行运行，也是这个错误
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    hp.run()
  File "D:\Anaconda3\lib\site-packages\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "D:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()
  File "D:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 278, in run
    new_trials = algo(
  File "D:\Anaconda3\lib\site-packages\recbole\trainer\hyper_tuning.py", line 105, in exhaustive_search
    idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
  File "D:\Anaconda3\lib\site-packages\hyperopt\pyll\base.py", line 902, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\hyperopt\pyll\stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
====
是不是numpy版本的问题呀？我的环境配置是：
Python 3.8.3  RecBole 1.0.0  numpy 1.19.5  pytorch 1.7.1

**Comment by chenyuwuxin** [comment]
@DX12321 你好，有可能是你安装的hyperopt库存在一些问题，我安装的hyperopt版本为0.2.5，`hyperopt\pyll\stochastic.py` line100的代码为：`return rng.randint(low, high, size)`，你可以尝试更换一下hyperopt的版本。

**Comment by DX12321** [comment]
嗯嗯，降了一下 hyperopt 的版本，这个错误没有了
但是出现一个新问题，我从命令行运行是没有问题，但是从 Pycharm 中引入yaml的Config文件会报错。缺少配置项参数。
run.py 中的代码
run_recbole(model='BPR', dataset='ml-100k', config_file_list=['config.yaml'])
hp = HyperTuning(objective_function=objective_function, algo='exhaustive',
                 params_file='model.hyper', fixed_config_file_list=['config.yaml'])
报错：
ERROR  job exception: 'model need to be specified in at least one of the these ways: [model variable, config file, config dict, command line] '
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\recbole\config\configurator.py", line 178, in _get_model_and_dataset
    model = self.external_config_dict['model']
KeyError: 'model'

**Comment by chenyuwuxin** [comment]
@DX12321 你可以尝试在PyCharm的运行配置中添加命令行参数 `--model='some_model'`。
