### ISSUE TITLE
[💡SUG] Is there any way to customize training/testing data for Sequential models?

### ISSUE THREAD

**Issue by yuh-yang** [RUCAIBox/RecBole#1082]
Dear authors of RecBole,

Thanks for your great work! Recently when experimenting on sequential recommendation baselines, I was wondering if there's any way to generally customize the training/testing data so as to suit my own evaluation purpose. For example, I have a sampled testing set that contains pairs of history sequence and the last item to predict. Instead of using the default Leave-One-Out strategy handled by RecBole, how can I test the model on my own testing data?

Thanks!

**Comment by hyp1231** [comment]
Hi,

Sure! One example for loading customized dataset via `benchmark_filename` can be found in [session_based_rec_example](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py), you can also download the processed `diginetica-session` dataset [[download]](https://recbole.s3-accelerate.amazonaws.com/ProcessedDatasets/DIGINETICA/session/diginetica_session.zip) to check it detailly.

**Comment by yuh-yang** [comment]
Hi @hyp1231 ,

Thanks for your generous reply, and that really helps. BTW, have you guys develop interfaces for loading customized negative samples for evaluation? I see no explicitly defined negative sample strategy in the case you give. Say, I have 99 negative samples for each ground-truth, and I want them keep consistent across all experiments and models. Therefore, I wish that I can explicitly load these negatives to RecBole. How can I implement this?

Thanks!

**Comment by hyp1231** [comment]
Hi @yuh-yang ,

Maybe it's a bit difficult to load pre-sampled negatives and calculate ranking metrics.

As for me, it will be more convenient to follow the [case_study_example](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py) to obtain model's prediction score on each pre-sampled cases. Then the metrics can be calculated according to your needs.

**Comment by yuh-yang** [comment]
That's a great idea @hyp1231 :)
