### ISSUE TITLE
[Question] 数据集的处理

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1084]
你好，我想问一下咱们这个框架对数据集的预处理是怎么样的。
比如说对Criteo数据集中的缺失值处理，对Movie-lens的评分划分标准
谢谢啦

**Comment by Sherry-XLL** [comment]
@DX12321 你好，数据集预处理的相关配置都可以由用户自己设置，RecBole 提供了多种预处理数据集的设置参数，详情可以参考我们[官方文档](https://recbole.io/docs/user_guide/config/data_settings.html)中的相关内容。我们一般会过滤掉缺失值，对于 MovieLens 的评分，可以通过 `threshold` 设置 `label`，也可以用 `val_interval: rating: "[3,inf)"` 过滤掉评分低的交互。

**Comment by DX12321** [comment]
哦哦，如果我不删除缺失值，只是对缺失的特征填充为0或者1，这个应该怎么设置呀？

**Comment by Sherry-XLL** [comment]
@DX12321 我们会默认用零值进行填充，如果你需要对缺失的特征进行特定的补充的话，可以先用 pandas 修改源数据。

**Comment by DX12321** [comment]
好的，谢谢啦
