### ISSUE TITLE
[🐛BUG]  use movielens [m1-1m] data that find an error -KeyError: 'label'

### ISSUE THREAD

**Issue by snailfrying** [RUCAIBox/RecBole#1085]
[🐛BUG] use movielens m1-1m data that find an error --keyerror-label   no label

**Comment by Sherry-XLL** [comment]
@snailfrying 你是在使用说明模型的时候报了这个错？关于 RecBole 的 label 设置，可以参考[官方文档](https://recbole.io/docs/user_guide/data/label_of_data.html?#label-of-data)。
