### ISSUE TITLE
序列推荐的一些问题

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1089]
**问题**
训练时，对于一个用户的序列，recbole是否只会用序列的最后一个记录来进行训练，比如在fpmc模型的forwrad方法中，会获得序列的最后一个记录作为item_last_click，请问序列中其它记录不会用来训练吗

**截图**
![image](https://user-images.githubusercontent.com/31268918/146863917-528276d8-414e-455b-b3d3-8111b6483439.png)

**Comment by chenyuwuxin** [comment]
@tctctctctc 感谢您的关注！
我们会对用户的历史交互记录使用数据增强方法，例如数据集中用户u1的交互物品为i1,i2,i3,i4,i5，并且MAX_ITEM_LIST_LENGTH为3。经过数据序列增强后，训练数据变为{(u1,<i1,0,0>,i2),(u1,<i1,i2,0>,i3),(u1,<i1,i2,i3>,i4),(u1,<i2,i3,i4>,i5)}。因此，序列中的每个物品都可能用来训练。

**Comment by tctctctctc** [comment]
明白了，感谢！！！

**Comment by tctctctctc** [comment]
请问一下，数据增强是对所有序列模型默认开启的吗？以及为什么有的如TransRec的embedding层会设置padding_idx参数，FPMC则没设置？

**Comment by chenyuwuxin** [comment]
@tctctctctc 您好，我们会对原子文件格式载入的数据集做序列化数据增强，而通过`benchmark_filename`形式载入的数据集不会做数据增强，关于这个问题，你可以参考 [Doc](https://recbole.io/docs/user_guide/config/data_settings.html) 或者 [#issue1096](https://github.com/RUCAIBox/RecBole/issues/1069)。第二个问题，我们一般会对序列用0作为[PAD]来对齐序列长度，因此对于序列化的变量进行embedding lookup时需要指定padding_idx为0，而那些没有设置padding_idx的embedding一般用于非序列变量的lookup，如`user`, `next_item`，在非序列变量中，0不会出现，因此不需要指定padding_idx。

**Comment by Guadzilla** [comment]
“我们会对原子文件格式载入的数据集做序列化数据增强”，请问有参数可以控制**是否对原子文件格式载入的数据进行数据增强**吗？遇到了一个不应该使用数据增强的场景。

**Comment by hyp1231** [comment]
> “我们会对原子文件格式载入的数据集做序列化数据增强”，请问有参数可以控制**是否对原子文件格式载入的数据进行数据增强**吗？如果不想进行数据增强，必须**自定义划分**数据集吗？

您可以提前划分好数据集，然后使用 `benchmark_filename` 这个参数直接加载处理好的（自定义划分后的）数据，详情请参考 [session_based_rec_example.py](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py)。

**Comment by Guadzilla** [comment]
> > “我们会对原子文件格式载入的数据集做序列化数据增强”，请问有参数可以控制**是否对原子文件格式载入的数据进行数据增强**吗？如果不想进行数据增强，必须**自定义划分**数据集吗？
> 
> 您可以提前划分好数据集，然后使用 `benchmark_filename` 这个参数直接加载处理好的（自定义划分后的）数据，详情请参考 [session_based_rec_example.py](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py)。

感谢回复！已解决！
