### ISSUE TITLE
[Question] CUDA out of memory

### ISSUE THREAD

**Issue by irecsys** [RUCAIBox/RecBole#1090]
I am running the library on a small data by using GPU. There are only around 7000 ratings/interactions. Not user or item attributes loaded. The GPU has 11 GB memory. And I got the following out of memory error.

Any suggestions to fix these errors?

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/sparse.py in forward(self, input)
    158         return F.embedding(
    159             input, self.weight, self.padding_idx, self.max_norm,
--> 160             self.norm_type, self.scale_grad_by_freq, self.sparse)
    161 
    162     def extra_repr(self) -> str:

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2042         # remove once script supports set_grad_enabled
   2043         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2044     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   2045 
   2046 

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.17 GiB total capacity; 10.54 GiB already allocated; 15.81 MiB free; 10.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by irecsys** [comment]
model = get_model(config['model'])(config, train_data.dataset).to(config['device'])

It works, if I removed to(config['device'])

**Comment by chenyuwuxin** [comment]
@irecsys The reason for this problem is that your GPU is out of memory. When you removed `to(config['device'])`, your training device has changed from GPU to CPU, thus it works. You can try to make the model smaller or change batchsize of the dataset .
