### ISSUE TITLE
如何使用已经划分好的数据

### ISSUE THREAD

**Issue by saladcat** [RUCAIBox/RecBole#1092]
比如我已经有了train set和val set，该如何构建原子数据集

**Comment by Sherry-XLL** [comment]
@saladcat 你好，如果你已经预先划分好了数据集，可以使用 `benchmark_file `来加载数据，详情可以参考[文档的说明](https://recbole.io/docs/user_guide/config/data_settings.html#benchmark-file)。

原子文件本质上是 `.tsv` 文件，可以用 python 的 `dataframe` 进行预处理，导出时选择 `sep='\t'` 即可，注意表头的名称需要符合[原子文件](https://recbole.io/docs/user_guide/data/atomic_files.html)的要求。

**Comment by saladcat** [comment]
了解了，感谢
