### ISSUE TITLE
关于序列推荐中序列的长度问题

### ISSUE THREAD

**Issue by Galaxy-bur** [RUCAIBox/RecBole#1094]
您好，对于序列推荐，我发现在指定了序列的最大长度，即MAX_ITEM_LIST_LENGTH后，对于长度不及该最大值的，似乎会在后面补0作为填充，我想请问一下有没有可以在前面填充的方法，即我想保留交互历史作为最新的，而在历史阶段补0作为填充。
另外，我还想请问一下，当实际序列长度大于最大长度时，在截取时是会保留最新的最大长度个交互历史，还是会从最初的历史开始保留对应个？
期待您团队的回复，谢谢！

**Comment by chenyuwuxin** [comment]
@Galaxy-bur 您好，非常感谢您的关注！
我们会对用户的历史交互记录使用数据增强方法，例如数据集中用户u1的交互物品为i1,i2,i3,i4,i5，并且MAX_ITEM_LIST_LENGTH为3。经过数据序列增强后，训练数据变为{(u1,<i1,0,0>,i2),(u1,<i1,i2,0>,i3),(u1,<i1,i2,i3>,i4),(u1,<i2,i3,i4>,i5)}。

1. 第一个问题，如果你想在前面用0作为[PAD]，可以通过修改以下代码：
https://github.com/RUCAIBox/RecBole/blob/46fd6f216a1ab423c2c196ec7b3780b4d2f0255d/recbole/data/dataset/sequential_dataset.py#L134
改为：`new_dict[list_field][i][-length:] = value[index]`

2. 第二个问题，如示例，会保留最新的最大长度个交互历史。

**Comment by Galaxy-bur** [comment]
好的，非常感谢您的解答！

**Comment by youngzw** [comment]
@chenyuwuxin 您好，我理解你们使用的这种数据增强方法，但是这种做法貌似跟源论文不太一致，比如说上面提到的SASRec模型，[源代码](https://github.com/kang205/SASRec)中并没有使用这种方式，这样使用该库的代码跑出来的结果作为baseline的结果是否会不太准确呢。相比原代码貌似最终性能提升了1-2%，但是也导致训练速度下降了很多。

**Comment by Galaxy-bur** [comment]
@chenyuwuxin 您好，我想请问一下，这种数据增强方法是仅使用在训练集吗，在验证和测试的时候，是否会将对增强样本的预测结果也包含在最终的计算结果中？

**Comment by chenyuwuxin** [comment]
@youngzw 您好，不同的论文有不同的数据集格式和处理方式，数据集序列化增强方法是为了将原子文件格式的数据集序列化使数据集格式统一。RecBole是一个统一，全面的代码库，最终是为了让不同的模型在一个统一的评测体系中体现出一个相对的结果，而不是为了复现某一个模型的处理方式。

**Comment by chenyuwuxin** [comment]
@Galaxy-bur 我们会对数据集总体做序列化增强，然后通过留一法和模式设置划分训练集，验证集以及测试集。具体方法可以参考[#issue1060](https://github.com/RUCAIBox/RecBole/issues/1060)。

**Comment by da-pang-za** [comment]
@youngzw 您好，我是正在学习RecBole的小白，可以分享一下您利用RecBole运行SASRec模型的代码和配置文件吗？感谢
email:2500018898@qq.com

**Comment by youngzw** [comment]
@da-pang-za 我也没有实际运行过RecBole的代码，只是之前我在使用另外一个开源库[ReChorus](https://github.com/THUwangcy/ReChorus)的时候发现他们的代码training速度比较慢，我就给作者提了issue，作者在回复时说他们在组织训练数据时参考了RecBole的方式，然后我就在这里提了issue。不过我看这个仓库的作者们提供了很多使用教程，遇到问题可以@他们，响应速度还是很快的。
