### ISSUE TITLE
[🐛BUG] 关于设置正负样本采样的问题

### ISSUE THREAD

**Issue by IU-hadlin** [RUCAIBox/RecBole#1095]
我使用的数据集的格式类似 https://recbole.io/docs/user_guide/data/label_of_data.html 中第一类1. Set label field 的数据格式，这是我数据集的一部分格式

`user_id:token	item_id:token	label:float 
18883162123	6955	1 
18883162123	6985	1 
18883162123	15700	0 
18883162123	12872	0`

因此我在.\recbole\properties\dataset\sample.yaml中参照api文档设置成
`# Label for Point-wise DataLoader
LABEL_FIELD: label
threshold: ~
neg_sampling: None`
但运行代码时报错
`ValueError: neg_sampling:[None] should be a dict.`

请问如何设置样本的正负标签读取呢？          
                 
我有注意到初始的设置是采取自动负采样，似乎每个原数据集的样本都会当作正样本
`neg_sampling:
    uniform: 1`

另外，recbole真是伟大的开源项目！

**Comment by Sherry-XLL** [comment]
@IU-hadlin 感谢你对 RecBole 项目的关注和支持！

初始的设置是 Implicit Collaborate Filtering 的典型场景，我们会默认输入的用户-商品交互为正样本，并从用户未交互的商品集中随机采样作为负样本进行损失函数计算。这时输入到模型的数据形式是 pairwise 的，一个 mini-batch 中的每个 `USER_ID` 既有 `ITEM_ID` 又有 `NEG_ITEM_ID`。

如果你的数据已经带有 label 标签，只需设置 `LABEL_FIELD: label`，这时的输入是 pointwise 的形式，即每个 `USER_ID` 对应 `ITEM_ID` 和 `label`，优化时可以与 `label` 计算 cross entropy loss。

如果你不需要进行负采样，可以设置 `neg_sampling: ~`。RecBole 的参数配置是 `yaml` 文件，由于 RecBole 既支持随机负采样，又支持基于流行度的负采样，还可以设置采样的个数，所以 `neg_sampling` 这个参数我们设置为了字典格式。当设置 `neg_sampling: None` 时，`yaml` 读入的 `neg_sampling` 实际上是一个 list，即 `[None]`。不需要某个字典形式的参数时，我们可以用 `neg_sampling: ~` 来表示。

**Comment by IU-hadlin** [comment]
感谢您这么及时的解答！ 目前已经了解了yaml中设置~及是list为`[None]`

我的数据带有label标签，这是我的部分数据
`user_id:token item_id:token label:float
18883162123	6955	1
18883162123	6985	1
18883162123	15700	0
18883162123	12872	0`

当我在.\recbole\properties\dataset\sample.yaml设置为`neg_sampling: ~ `
`# Label for Point-wise DataLoader
LABEL_FIELD: label
threshold: ~
neg_sampling: ~
`
会产生KeyError: 'neg_item_id'的错误，这是由于我其余设置的问题吗，还是当我的数据带有label标签时，只需要设置`LABEL_FIELD: `label`，不需要更改
`neg_sampling: 
    uniform: 1`

**Comment by Sherry-XLL** [comment]
@IU-hadlin 你好，如果你没有指定模型 model 的话，RecBole 默认运行的模型是 `BPR`。BPR 是一个基础的矩阵分解模型，训练时是 pairwise 的输入形式。也就是说，BPR 模型需要每个正例配对一个负例才能进行损失函数计算，因此需要 `NEG_ITEM_ID`。当你的数据带有 label 标签时，如果你只想充分利用标签数据，那么应该使用无需 `NEG_ITEM_ID` 的模型，具体取决于你想使用的模型和你的推荐任务。

**Comment by sxhysj** [comment]
> 的

你好，请问neg_sampling: uniform: 1这种设置是用在什么场景？是没有implicit里面的没有负样本的情况吗？跟neg_sampling: ~设置有什么不同？

**Comment by sxhysj** [comment]
> 感谢您这么及时的解答！ 目前已经了解了yaml中设置~及是list为`[None]`
> 
> 我的数据带有label标签，这是我的部分数据 `user_id:token item_id:token label:float 18883162123 6955 1 18883162123 6985 1 18883162123 15700 0 18883162123 12872 0`
> 
> 当我在.\recbole\properties\dataset\sample.yaml设置为`neg_sampling: ~ ` `# Label for Point-wise DataLoader LABEL_FIELD: label threshold: ~ neg_sampling: ~ ` 会产生`KeyError: 'neg_item_id'`的错误，这是由于我其余设置的问题吗，还是当我的数据带有label标签时，只需要设置`LABEL_FIELD: label`，不需要更改 `neg_sampling: uniform: 1`

你好，请问neg_sampling: uniform: 1这种设置是用在什么场景？是没有implicit里面的没有负样本的情况吗？跟neg_sampling: ~设置有什么不同？

**Comment by Sherry-XLL** [comment]
@sxhysj `neg_sampling: uniform: 1` 用在隐反馈场景下采集负例用于训练，正负例比例为 1:1。`neg_sampling: ~` 适用于不需要通过负采样构造负例的情形，有两种情况，一是在 context-aware 推荐模型中，如果 `label` 是指定的列，那么此时的负反馈信息是显式的 （label 为 0），就无需负采样去构造负例；二是在 sequential 推荐模型中，如果 `loss` 选取的是交叉熵损失函数 `CE` 而不是贝叶斯个性化排序 `BPR`，那么训练可以被看作一个多分类的任务，正例就是 ground truth，其余所有都被看作负例，此时也无需负采样。
