### ISSUE TITLE
[💡SUG] 可以求一下dignetica数据集吗？官方链接目前已经失效了

### ISSUE THREAD

**Issue by JiayinZheng** [RUCAIBox/RecBole#1098]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sherry-XLL** [comment]
@JiayinZheng 你好，我刚才看了一下 [RecSysDatasets repo](https://github.com/RUCAIBox/RecSysDatasets) 里给的[百度网盘](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g)(Password: e272) 和 [Google Drive](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing) 链接都是可以正常访问的，也都能下载 dignetica 数据集，你可以试一下[百度网盘](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g#list/path=%2FRecBole%2FProcessedDatasets%2FDIGINETICA)或者[谷歌云盘](https://drive.google.com/drive/folders/1P37hx5_0JKqk1QBf3rQwG7XS644yzBTY)。

**Comment by JiayinZheng** [comment]
非常感谢，我看一下
