### ISSUE TITLE
[🐛BUG] An error while BPR model loading and initialization

### ISSUE THREAD

**Issue by sergey-semenov-ai** [RUCAIBox/RecBole#1100]
**Describe the bug**
An error while BPR model loading and initialization

**To Reproduce**
from logging import getLogger
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.model.general_recommender import BPR
from recbole.trainer import Trainer
from recbole.utils import init_seed, init_logger

config = Config(model='BPR', dataset='ml-100k')
init_seed(config['seed'], config['reproducibility'])
init_logger(config)
logger = getLogger()
dataset = create_dataset(config)
logger.info(dataset)
model = BPR(config, train_data)
logger.info(model)

code taken from 
https://recbole.io/docs/user_guide/usage/use_modules.html

**Screenshots**
![Снимок экрана от 2022-01-04 13-30-54](https://user-images.githubusercontent.com/70337257/148031729-04130281-35aa-4aec-9437-da9d08f2d532.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
- RecBole Version: 1.0.0
 - Python Version: 3.8.8
- PyTorch Version: 1.10.1+cu102
- cudatoolkit Version:  none

**Comment by chenyuwuxin** [comment]
@sergey-semenov-ai Thank you very much for your attention to RecBole!
There is an error in the details of the document build model code, which should be changed to the following code:
`model = BPR(config, train_data.dataset).to(config['device'])
`
We will fix this problem in subsequent versions. Thanks for your support.

**Comment by sergey-semenov-ai** [comment]
@chenyuwuxin Thanks!!!
