### ISSUE TITLE
关于评估设置中负采样模式的疑问

### ISSUE THREAD

**Issue by Galaxy-bur** [RUCAIBox/RecBole#1103]
您好，在评估设置中可以通过mode来设置是在全样本上评估，或者是抽样指定数量的负样本和正样本一起评估。我的理解是抽取部分负样本的意义是为了加速整个评估过程，降低在全样本上评估的成本。但是我在实验过程中发现：当指定了抽取负样本评估时，时间消耗会远大于在全样本上评估。例如：我在full模式下，一个epoch的evaluate只需要88 step，但是使用uni100，即抽样100个负样本时，一个epoch的evaluate却需要11182 step。
我想请问一下是我的理解有偏差，还是我需要更进一步设置些别的参数？

**Comment by chenyuwuxin** [comment]
@Galaxy-bur 感谢您的关注！
一般而言，当数据集物品数量非常多的时候，如果我们为每个用户评估所有物品显然会浪费大量时间，这时我们为每个正例抽取100个负例(uni100)来加速评估过程。然而，正是因为全评估往往需要大量时间，在全评估时，我们只关注用户数量来追求速率优化，例如：整个数据集有1000个商品，测试集为4个用户构成的100条交互记录，那么全评估共需要评估4*1000=4000个user-item对，而uni100需要评估100*100=10000个user-item对，特别是当数据集按用户id聚集分布时会出现这种现象。

**Comment by Galaxy-bur** [comment]
@chenyuwuxin 感谢您的回答！
我应该是大概理解到您团队的思路了，我先简单复述一下我的理解，再提出一下我的新问题：
假如整个数据集有1000个商品，测试集是4个用户构成的总计100条记录，在全评估模式下，只针对每个用户去计算所有的商品，也就是4000个user-item对，而在uni100的情况下，是对每条记录抽样100个，以此来构成100*100=10000个user-item对。

我现在遇到的问题是：我是在sequential recommend的场景下，使用LS模式，也就是在我的测试集中，对于每个用户我只用他最后一次交互的item作为正样本，以此抽样100个负样本进行计算，他之前交互的item并不在我测试集的考虑范围内，也就是我依旧希望类似全评估的方式，对于这个用户只构成101个user-item对，即对于4个用户构成4*101=404个user-item对来进行运算。我想知道该怎么样可以实现我的想法，是不是只能我自行去改动底层的代码，如果需要，我应该在哪几个地方进行修改呢？

**Comment by chenyuwuxin** [comment]
@Galaxy-bur 对于序列推荐模型，我们采用LS留一法划分数据集去训练模型而不能负采样，具体方式你可以参考[#1060](https://github.com/RUCAIBox/RecBole/issues/1060)。

**Comment by Galaxy-bur** [comment]
@chenyuwuxin 感谢回答，我可以理解数据集的划分思路和数据增强方式，我目前的疑惑在于在最后的评估过程中，我希望可以抽样一部分负样本和正样本进行评估，而非全评估，例如：数据集有1000个item，有4个用户的总计100条交互记录，即我希望对于单个用户预测评估时，仅使用1个正样本和100个负样本参与运算，而不是对于1000个item进行运算。
是否目前的uni100并不支持我这种想法，如果是的话，是否我需要去自行实现这种方式？

**Comment by chenyuwuxin** [comment]
@Galaxy-bur 您好，由于留一法的设置，测试集中每个用户只包含了1条记录，这条记录为包含最后一次交互item的正样本，因此测试集中用户数是和user-item对的数量是一致的，在这种情况下，只需要继续使用uni100进行采样即可，如果想之前交互的item并不在测试集的考虑范围内，需要设置：
`repeatable: False`。

**Comment by Galaxy-bur** [comment]
@chenyuwuxin 好的，非常感谢回答！
