### ISSUE TITLE
lightGCN配置文件出错

### ISSUE THREAD

**Issue by yztian1997** [RUCAIBox/RecBole#1106]
Traceback (most recent call last):
  File "D:/大数据与人工智能/lightgcn/main.py", line 18, in <module>
    dataset = create_dataset(config)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\utils.py", line 50, in create_dataset
    return Dataset(config)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\dataset\dataset.py", line 96, in __init__
    self._from_scratch()
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\dataset\dataset.py", line 106, in _from_scratch
    self._load_data(self.dataset_name, self.dataset_path)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\dataset\dataset.py", line 247, in _load_data
    self._load_inter_feat(token, dataset_path)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\dataset\dataset.py", line 270, in _load_inter_feat
    inter_feat = self._load_feat(inter_feat_path, FeatureSource.INTERACTION)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\recbole\data\dataset\dataset.py", line 413, in _load_feat
    field, ftype = field_type.split(':')
ValueError: too many values to unpack (expected 2)

**Comment by yztian1997** [comment]
# run it in order to validate LightGCN results
seed: 2020
# model config
embedding_size: 64
n_layers: 2
reg_weight: 1e-05

# dataset config
field_separator: "," #指定数据集field的分隔符
seq_separator: " " #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: userId #指定用户id域
ITEM_ID_FIELD: itemId #指定物品id域
RATING_FIELD: rating #指定打分rating域
TIME_FIELD: timestamp #指定时间域
NEG_PREFIX: neg_ #指定负采样前缀
LABEL_FIELD: label #指定标签域
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列
load_col:
  inter: [userId, itemId]

# training settings
epochs: 1000 #训练的最大轮数
train_batch_size: 2048 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 1 #负采样数目
eval_step: 2 #每次训练后做evalaution的次数
neg_sampling:
  uniform: 1
stopping_step: 5 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

# evalution settings
metrics: ["Precision","Recall","NDCG"] #评测标准
topk: [10, 15, 20] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: Recall@20 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size
loss_decimal_place: 4
metric_decimal_place: 4


# gpu settings
gpu_id: 1


# others for my task


show_progress: True

eval_args:
  split:

**Comment by chenyuwuxin** [comment]
@yztian1997 您好，感谢您的关注！
这个问题可能是数据集格式错误所致，请按照[原子文件](https://recbole.io/docs/user_guide/data/atomic_files.html?highlight=atomic)格式正确配置数据集。

**Comment by yztian1997** [comment]
能不能给一个lightGCN针对ml-100k数据集的配置文件

**Comment by chenyuwuxin** [comment]
@yztian1997 
您好，示例文件如下：
```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
val_interval:
    rating: "[3,inf)"    
unused_col: 
    inter: [rating]

# training and evaluation
epochs: 500
train_batch_size: 4096
valid_metric: MRR@10

# model
embedding_size: 64
```
