### ISSUE TITLE
[🐛BUG] Over-estimated TopK metrics

### ISSUE THREAD

**Issue by irecsys** [RUCAIBox/RecBole#1107]
In my evaluations, I found that sometimes, precision or recall is larger than 1.

I went through the coding, and I beleive this is a bug in the library. Correct me, if I am wrong

Let's take a look at recbole/evaluator/base_metric.py

```python
def used_info(self, dataobject):
        """Get the bool matrix indicating whether the corresponding item is positive
        and number of positive items for each user.
        """
        rec_mat = dataobject.get('rec.topk')
        topk_idx, pos_len_list = torch.split(rec_mat, [max(self.topk), 1], dim=1)
        return rec_mat.to(torch.bool).numpy(), pos_len_list.squeeze(-1).numpy()
```

In the coding above, I blieve that we should:

```python
return topk_idx.to(torch.bool).numpy(), pos_len_list.squeeze(-1).numpy()
````

Not 

```python
return rec_mat.to(torch.bool).numpy(), pos_len_list.squeeze(-1).numpy()
```

If I am going to recommender topK items, the first parameter returned is always with size num_users x K+1

**Comment by 2017pxy** [comment]
Hi @irecsys, thanks for your correct. Here is indeed a typo and we have already fix it and we plan to update the fix in next version( [fix commit](https://github.com/RUCAIBox/RecBole/commit/58490871755f7779200937504241e03686c33d89) ). 

However,  **this typo will not influence the calculation of Recall**.  Though the first parameter returned (`rec_mat.to(torch.bool).numpy()`) has one more dimension than correct one (`topk_idx.to(torch.bool).numpy()`), we will not use this extra dimension in the following metrics calculation. Your can read the code in `topk_result()`https://github.com/RUCAIBox/RecBole/blob/1bd8a587867959e8c37b881b2321eb6be7579912/recbole/evaluator/base_metric.py#L65-L80

So, could you please offer your config yaml file and  data file to us so that we can reproduce your problem? Many thanks!

**Comment by irecsys** [comment]
In my data, the extra lens column was added.

In calculating metrics, cumsum will also count the last column => it presents TRUE on the last column, which results over-estimated precision and recall in this case

**Comment by 2017pxy** [comment]
Did you modify the code? I don't understand why the extra column will be calculated following our code.

**Comment by irecsys** [comment]
class Recall(TopkMetric):
    r"""Recall_ is a measure for computing the fraction of relevant items out of all relevant items.

    .. _recall: https://en.wikipedia.org/wiki/Precision_and_recall#Recall

    .. math::
       \mathrm {Recall@K} = \frac{1}{|U|}\sum_{u \in U} \frac{|\hat{R}(u) \cap R(u)|}{|R(u)|}

    :math:`|R(u)|` represents the item count of :math:`R(u)`.
    """

    def __init__(self, config):
        super().__init__(config)

    def calculate_metric(self, dataobject):
        pos_index, pos_len = self.used_info(dataobject) => extra column in the pos_index, if the bug in used_info() function was not fixed
        result = self.metric_info(pos_index, pos_len)
        metric_dict = self.topk_result('recall', result)
        return metric_dict

    def metric_info(self, pos_index, pos_len):
        hits = np.cumsum(pos_index, axis=1) => hits calculated from a true/false matrix
        rel = pos_len.reshape(-1, 1)
        recall = hits / rel
        return recall

**Comment by irecsys** [comment]
> But the last column will not be used in `topk_result`. In this function, we will only use columns in `self.topk`. The last column is `max(self.topk) + 1` and will not be used.
> 
> ```python
> def topk_result(self, metric, value):
>     """Match the metric value to the `k` and put them in `dictionary` form.
> 
>     Args:
>         metric(str): the name of calculated metric.
>         value(numpy.ndarray): metrics for each user, including values from `metric@1` to `metric@max(self.topk)`.
> 
>     Returns:
>         dict: metric values required in the configuration.
>     """
>     metric_dict = {}
>     avg_result = value.mean(axis=0)
>     for k in self.topk:
>         key = '{}@{}'.format(metric, k)
>         metric_dict[key] = round(avg_result[k - 1], self.decimal_place)  # Here we only use the columns in `self.topk`.
>     return metric_dict
> ```

I believe that the function you gave just calculated mean and save it to the dict.

Look at the precision class I gave to u.

Any metric calculations which used np.cumsum(pos_index, axis=1) will be affected, my two cents

**Comment by guijiql** [comment]
`np.cumsum` function indeed count the last column. The shape of `rec_mat` is (user_num, max(self.topk) + 1). And the return value of `metric_info` is also shaped like (user_num, max(self.topk)+1).
However, in the above mentioned code:
https://github.com/RUCAIBox/RecBole/blob/1bd8a587867959e8c37b881b2321eb6be7579912/recbole/evaluator/base_metric.py#L65-L80
The shape of `avg_result` is max((self.topk)+1). But we only save the first `max(self.topk)` values in the loop where we save it to the dict
```
for k in self.topk:
        key = '{}@{}'.format(metric, k)
        metric_dict[key] = round(avg_result[k - 1], self.decimal_place)
```

**Comment by irecsys** [comment]
Yes. You are right. My codes in took results were changed Too, Which counts the last column

**Comment by 2017pxy** [comment]
@irecsys So do you have any other question? If your problem is solved, you can close this issue. Thanks!
