### ISSUE TITLE
[🐛BUG] 新数据集训练过程，loss一直没有变换，auc也为0.5

### ISSUE THREAD

**Issue by vincentForWss** [RUCAIBox/RecBole#1109]
很奇怪，我按照上面的方法改写了我的数据集格式，但最后用DeepFm跑CTR任务，出的结果是auc为0.5，一直没有改进。想问下是什么情况。其中，关于我的数据集，具体如下：
1. 样本极不平衡（负例:正例=100:1）
2. 使用label:token
3. data.inter
user_id:token	item_id:token	rating:float	timestamp:float
6e2105d9fe	90318011	0	1627776000000000000
6e2105d9fe	GRHLA20211530	0	1630454400000000000
4. item.inter
item_id:token	理财产品计价类型:token	理财产品周期类型:token	理财产品产品模式:token	理财产品风险等级:token	理财产品是否滚存型产品:token	理财产品是否允许变更分红方式:token	理财产品持有天数:float	理财产品募集方式:token	理财产品管理方式:token	理财产品业务模式:token	理财产品收益特点:token	理财产品期限:float	理财产品投资模式:token	理财产品预期收益率:float	理财产品最高收益率:float	理财产品最低收益率:float	理财产品展示等级:token	理财产品类型:token	理财产品产品模式2:token	理财产品收益记息基数:token	理财产品预期最低收益率:float	理财产品预期最高收益率:float	理财产品产品面值:float	理财产品发行价格:float	理财产品收益率:float	理财产品距今总天数:float
ZXGRHLA2021059	0	1	1.0	1.0	0.0	0	364.0	未知	未知	未知	2.0	5.0	1.0	0.04268	0.04373	0.0158	未知	A	未知	未知	0.0011	0.0011	1.0	1.0	3.9485	35.0
5. data.user
user_id:token	客户性别:token	客户等级:token	客户年龄:float	客户最新风险等级:token	客户风险向好性努力程度:float	客户风险等级评估距今总天数:float
d4931873cb	1.0	4.0	40.0	3.0	0.0	576.0

**Comment by vincentForWss** [comment]
参考的方案URL：https://github.com/RUCAIBox/RecBole/issues/983

**Comment by chenyuwuxin** [comment]
@vincentForWss 感谢您的关注！
注意到您的数据集文件有较多的float类型字段，可能是这些字段数据分布有较大差异，建议对数值类型的数据进行归一化。即在yaml文件中设置`normalize_all: True`。

**Comment by vincentForWss** [comment]
确实是分布的问题，正规化后就没问题啦！！！十分感谢！！！
