### ISSUE TITLE
[❓Question] 样本不平衡下，关于推荐系统的是否点击任务的配置问题

### ISSUE THREAD

**Issue by vincentForWss** [RUCAIBox/RecBole#1111]
您好！

首先，根据文档的参数说法，我理解的是，在训练过程中，该参数通过控制样本池中负项的分布，这样削减训练中的样本的不平衡性。但我不太理解的是，是'未点击'为负例，还是'点击'为负例，应该是有参数能够显示声明？
- neg_sampling(dict): This parameter controls the negative sampling for model training. The key range is ['uniform', 'popularity'], which decides the distribution of negative items in sampling pools. uniform means uniformly select negative items while popularity means select negative items based on their popularity (Counter(item) in .inter file). Note that if your data is labeled, you need to set this parameter as None. The default value of this parameter is {'uniform': 1}.

然后，我想问下咱们项目在配置文件中有哪些解决样本不平衡性？例如通过控制loss的正负例权重，等等。注：该疑惑建立在目前未能理解neg_sampling参数的使用上

**Comment by 2017pxy** [comment]
@vincentForWss 一般来说，推荐系统负采样的假设都是用户未交互的为负例，交互的为正例。基于这一被广泛接受的假设，我们设计了负采样模块，并且没有对其进行说明。 

此外，我个人理解，负采样的作用就是在数据缺乏标签的条件下，为模型给出训练负例。我不清楚你这里提到的样本不平衡性指的是什么？如果你想要通过负采样来调整训练数据中的正负例占比，你可以通过调整采样比来实现。

**Comment by vincentForWss** [comment]
抱歉哈，我是刚入门推荐系统。

我这边的任务是，给定label的条件下（1为点击，0为未点击），然后预测给定user-item的点击情况，所以会存在label=1极度稀少，label=0很多的情况。

根据您的答案，”可以通过调整采样比来实现“是有专门的配置`采样比`参数么，还是需要我从原文件使用`采样策略`入手?

**Comment by 2017pxy** [comment]
@vincentForWss `neg_sampling`这个参数就可以控制采样策略和采样比，我建议你仔细阅读我们的文档。
