### ISSUE TITLE
ItemKNN相关问题

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1112]
**描述这个 bug**

您好，在ItemKnn中通过并行操作预测评分，好像只是根据相似度简单的加权和，并没有再除以权重和
self.pred_mat = self.interaction_matrix.dot(self.w).tolil()
想请问一下是不是这样

**屏幕截图**
![image](https://user-images.githubusercontent.com/31268918/148635343-601a7f8b-a948-4f55-b653-89dc7d659cb5.png)
![image](https://user-images.githubusercontent.com/31268918/148635354-716b4def-2b75-47c8-8e5e-988aa2f456f8.png)

**Comment by chenyuwuxin** [comment]
@tctctctctc 感谢您的关注！
确实，ItemKNN中`self.w`包含了每个商品的topk相似物品的余弦相似度，`self.interaction_matrix`为用户打分矩阵，这里并没有除以权重和。

**Comment by Captain-Paul** [comment]
@tctctctctc 你好，想问一下ItemKNN这里，手动除以权重和的操作是否是
```python
for i in range(self.n_items):
            self.pred_mat[:, i] /= np.sum(self.w[:, i])
```
目的是得到和训练数据中rating范围相同的预测rating
