### ISSUE TITLE
[🐛BUG] Gathering Wrong Indices in BERT4Rec

### ISSUE THREAD

**Issue by yuh-yang** [RUCAIBox/RecBole#1113]
def full_sort_predict(self, interaction):
        item_seq = interaction[self.ITEM_SEQ]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        item_seq = self.reconstruct_test_data(item_seq, item_seq_len)
        seq_output = self.forward(item_seq)
        seq_output = self.gather_indexes(seq_output, item_seq_len-1)  # [B H]
        test_items_emb = self.item_embedding.weight[:self.n_items]  # delete masked token
        scores = torch.matmul(seq_output, test_items_emb.transpose(0, 1))  # [B, item_num]
        return scores

In this code, the masked position is item_seq[item_seq_len], cause the code`item_seq = self.reconstruct_test_data(item_seq, item_seq_len)` adds the mask token at the last position of the raw sequence. However, the gathered indices are set as item_seq[item_seq_len-1], which seems not so right. Did I get something wrong? :)

**Comment by Sherry-XLL** [comment]
@yuh-yang Thanks very much for your attention and feedback, this is indeed a bug and has been fixed in #1115.

**Comment by yuh-yang** [comment]
@Sherry-XLL Thanks for fixing. It's interesting that although it's a bug, it leads to approximately right evaluation results LOL
