### ISSUE TITLE
❓ 关于knowledge_aware_recommender部分模型无法运行

### ISSUE THREAD

**Issue by IU-hadlin** [RUCAIBox/RecBole#1116]
我采用我自己的数据集运行**mkr和ripplenet模型**时会报错

>   File "F:\LCW\PycharmProject\RecBole-master\recbole\data\interaction.py", line 127, in __getattr__
>     raise AttributeError(f"'Interaction' object has no attribute '{item}'")
> AttributeError: 'Interaction' object has no attribute 'size'

但是可以运行**cke模型**，我的部分数据集部分格式如下，
.inter
> user_id:token	item_id:token	rating:float
> 18602312525	1009	1
> 18602312525	783	1
> 18602312525	1049	1

.link
> item_id:token	entity_id:token
> 1180	1124
> 1415	1246
> 5656	2160
> 338	338

.kg
> head_id:token	relation_id:token	tail_id:token
> 1	0	2252
> 1	0	2253
> 2	0	2252
> 3	0	2252

我不知道是否是数据集格式或者其他问题，望您解答

**Comment by Sherry-XLL** [comment]
@IU-hadlin 你好，我在 MovieLens 数据集上运行 MKR 模型并未报错，你有在 RecBole 提供的数据集上尝试运行 KG 模型吗？可以参考 [MovieLens-KG](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md) 获取相关数据，如果仍然报错，麻烦提供完整的报错信息和配置文件。
