### ISSUE TITLE
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:75] data. DefaultCPUAllocator: not enough memory: you tried to allocate 17376997200 bytes. Buy new RAM!

### ISSUE THREAD

**Issue by Figfavture** [RUCAIBox/RecBole#1118]
只要切换新的数据集运行模型，就报这个错误，所有的方法都试过了，一直报错。
换到服务器上运行，依然报这个错误。

**Comment by chenyuwuxin** [comment]
@Figfavture 您好，感谢您的关注！这个问题是由于服务器的内存不足导致，你可以尝试在内存空间较大的计算机运行或者减少数据集的容量。

**Comment by Figfavture** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        非常感谢您，刚刚查看了一下，确实是有其他同学在占用服务器，导致内存不足。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 1/17/2022 20:23，Tian ***@***.***> wrote： 




@Figfavture 您好，感谢您的关注！这个问题是由于服务器的内存不足导致，你可以尝试在内存空间较大的计算机运行或者减少数据集的容量。
