### ISSUE TITLE
How to access the timestamp of interaction in Sequential recommendation?

### ISSUE THREAD

**Issue by Li-Muyang** [RUCAIBox/RecBole#1123]
Hi, I want to convert the timestamp of interactions into embedding but I don't know how to access them in SeqRec, is there a function to call that allows me to achieve that?

**Comment by Wicknight** [comment]
@Li-Muyang Hello,thanks for your attention to RecBole!
Is your question how to **access the timestamp** of data? If so, let me give you an example here.
```
    def calculate_loss(self, interaction):
        label = interaction[self.LABEL_FIELD]
        item_seq = interaction[self.ITEM_SEQ]
        user = interaction[self.USER_ID]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        next_items = interaction[self.POS_ITEM_ID]
        output = self.forward(user, item_seq, item_seq_len, next_items)
        loss = self.loss(output, label)
        return loss
```
The above is the function **‘calculate_loss’** of model **DIN** used in the training process. We can access the timestamp through parameter 'interaction'. Suppose the corresponding column in the dataset is listed as 'timestamp',then we can **access the timestamp using 'interaction['timestamp']'**, just like the following example:
```
    def calculate_loss(self, interaction):
        label = interaction[self.LABEL_FIELD]
        item_seq = interaction[self.ITEM_SEQ]
        user = interaction[self.USER_ID]
        item_seq_len = interaction[self.ITEM_SEQ_LEN]
        next_items = interaction[self.POS_ITEM_ID]

        time = interaction['timestamp']
        '''
        Perform other processing to convert it into embedding
        '''

        output = self.forward(user, item_seq, item_seq_len, next_items)
        loss = self.loss(output, label)
        return loss
```
Also, the same method can be used in the function 'predict'.

**Comment by Li-Muyang** [comment]
> time = interaction['timestamp']

Hi, thank you for your quick response, however I would correct that just calling interaction[TIMESTAMP] does not give what I want, what I mean was the timestamp corresponding to each interaction, i.e. (batch_size, max_seq_len), however interaction[TIMESTAMP] will just return (batch_size), what I did was to add `self.TIMESTAMP_SEQ = self.TIMESTAMP + config['LIST_SUFFIX']` in the abstract sequential recommender, and then call interaction[TIMESTAMP_SEQ] to get what I want
Please do correct me if that's not the way to do it

**Comment by Wicknight** [comment]
I'm sorry that I didn't understand the problem correctly before. I think your method is correct.

**Comment by Wicknight** [comment]
Because there is no new reply for a long time, the issue has been closed. If you have any questions, please feel free to comment
