### ISSUE TITLE
About the difference in accuracy of BERT4Rec

### ISSUE THREAD

**Issue by yamato0811** [RUCAIBox/RecBole#1132]
I ran the code of BRET4Rec on both the latest master branch and the released v1.0.0.
The accuracy of  v1.0.0 was much higher than that of latest code.
Why is this?

Here is the code I ran and the results.

run_recbole.py
```import argparse
from recbole.quick_start import run_recbole

config_dict = {
    'gpu_id' : '0',
    'epochs' : 50,
    'loss_type' : 'CE',
    'neg_sampling' : 'None',
    'load_col' : {'inter': ['user_id', 'item_id', 'rating', 'timestamp']},
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', '-m', type=str, default='BPR', help='name of models')
    parser.add_argument('--dataset', '-d', type=str, default='ml-100k', help='name of datasets')
    parser.add_argument('--config_files', type=str, default=None, help='config files')

    args, _ = parser.parse_known_args()

    config_file_list = args.config_files.strip().split(' ') if args.config_files else None
    run_recbole(model=args.model, dataset=args.dataset, config_dict=config_dict)
```

I ran it this way.
```
python run_recbole.py -m BERT4Rec -d ml-1m
```

Here are the results of the verification.
latest code : {'recall@10': 0.0619, 'mrr@10': 0.0191, 'ndcg@10': 0.0289, 'hit@10': 0.0619, 'precision@10': 0.0062}
v1.0.0 : {'recall@10' : 0.1457,  'mrr@10' : 0.0439,  'ndcg@10' : 0.0672, 'hit@10' : 0.1457, 'precision@10' : 0.0146}

![スクリーンショット 2022-01-27 22 28 31](https://user-images.githubusercontent.com/64122953/151368323-0a71bf3d-eac9-4b54-9f65-4267be3b5f10.png)

By the way, the loss curves were almost the same.

![スクリーンショット 2022-01-27 22 30 51](https://user-images.githubusercontent.com/64122953/151368744-23d0df91-e5f3-4d36-a370-4d81f8cbc489.png)

**Comment by chenyuwuxin** [comment]
@yamato0811 Hello,thanks for your attention to RecBole!
After the release of RecBolev1.0.0, we repaired several bugs which involve BERT4Rec model. You can refer to [#issue1113](https://github.com/RUCAIBox/RecBole/issues/1113) for specific details. I hope my answer can help you.

**Comment by yamato0811** [comment]
Thank you for your answer and help.
According to #issue1113, some bugs seem to be fixed. But I can't get right evaluation results in my environment.
So, I'm going to use v1.0.0 for now.

I always use RecBole. Thank you‼️
