### ISSUE TITLE
Sequential recommendation运行mind数据集报错

### ISSUE THREAD

**Issue by trhflybingo** [RUCAIBox/RecBole#1137]
执行python run_recbole.py --dataset=mind-small-dev --model=SRGNN命令时

出现：
ValueError: [timestamp] is not exist in interaction [The batch_size of interaction: 2740998
    user_id, torch.Size([2740998]), cpu, torch.int64
    item_id, torch.Size([2740998]), cpu, torch.int64

以下是我的参数：
# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
#neg_sampling:
#  uniform: 1

neg_sampling: ~

eval_step: 1
stopping_step: 10
clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0

# evaluation settings
eval_args: 
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
repeatable: False
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
topk: [10]
valid_metric: MRR@10
valid_metric_bigger: True
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4

**Comment by Sherry-XLL** [comment]
@trhflybingo 你好，在运行 Sequential 模型时需要加载 `timestamp` 列，并设置数据排序顺序为 `TO`，详情可以参考 API 文档中的 [Evaluation Settings](https://recbole.io/docs/user_guide/config/evaluation_settings.html)。

> ``order (str)``: decides how we sort the data in `.inter`. Now we support two kinds of ordering strategies: ``['RO', 'TO']``, which denotes the random ordering and temporal ordering. For ``RO``, we will shuffle the data and then split them in this order. For ``TO``, we will sort the data by the column of `TIME_FIELD` in ascending order and the split them in this order. The default value is ``RO``.

因此，sequential 模型的标准配置如下：

```python
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
  inter: [user_id, item_id, timestamp]

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
valid_metric: recall@10
eval_args:
  split: {'LS': 'valid_and_test'}
  mode: full
  order: TO
neg_sampling: ~

# model
embedding_size: 64 
```

你可以根据需求设置 `MAX_ITEM_LIST_LENGTH`(Maximum length of each generated sequence) 来调整生成序列的最大长度。而对于 `SRGNN` 模型，模型的默认超参数在 `recbole/properties/mode/SRGNN.yaml` 文件中，具体的参数含义可以参考[文档中 SRGNN 模型的相关介绍](https://recbole.io/docs/user_guide/model/sequential/srgnn.html)。

https://github.com/RUCAIBox/RecBole/blob/56cc32fb6db93bdb97a3a6db06cb6a562c6dbf0f/recbole/properties/model/SRGNN.yaml#L1-L3

此外，MIND 数据集是用于新闻推荐的有标签数据，`label` 为 `1/0` 表示用户是否有点击行为，可以用于点击率预测的 CTR (click-through rate prediction) 模型。如果你将 MIND 数据集用于 General Recommendation 中的隐反馈推荐或者序列推荐，最好在预处理时通过 `val_interval` 参数和数据中的 `label` 过滤掉标签为 `0` 的交互，使结果更合理并具有可解释性。
