### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by fxvvv** [RUCAIBox/RecBole#1141]
想请问一下用源码和自己的数据训练出的模型，怎么用训练好的序列推荐模型做新的预测任务（输出预测的结果）

**Comment by Sherry-XLL** [comment]
@fxvvv RecBole 目前只支持 [case study](https://recbole.io/docs/user_guide/usage/case_study.html) 式的预测分析，也就是说，我们将数据划分为训练集、验证集和测试集，模型会在训练集上进行充分训练，通过验证集设置超参数，并在测试集上检验模型的训练效果。而 case study 中的案例分析就是利用在训练集上训练并在验证集上调整的模型，根据测试集中的数据输出预测结果。

如果你只是想给定用户的商品序列然后输出下一个交互的商品，那么可以直接利用训练好的模型的 predict 函数输出 scores，选择得分最高所对应的商品即为预测的结果，这种情况没有现成的模板，但可以根据需求自行实现。但值得注意的是，数据已经训练的模型基于的是原数据集的商品，所以训练好的序列推荐模型只能在原来的商品集上做预测任务，也就是说给定的商品序列不能包含模型未见过的商品。
