### ISSUE TITLE
Any comprehensive evaluation of models?

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#1145]
Do you provide any comprehensive evaluation of models on some given benchmark sets?

For instance, general models on 100k sets, etc...

Any suggestions would be appreciated.

**Comment by Sherry-XLL** [comment]
@sxhysj Hello, this is a meaningful but expensive work for us to provide a comprehensive evaluation. On the one hand, we currently have more than seventy models and twenty benchmark datasets, and tuning the hyperparameters suitable for each model has a huge time overhead. On the other hand, it is difficult for us to guarantee the absoluteness and authority of the comparison, and it is easy to cause controversy. If you are interested, you can try it yourself, but RecBole will not publish test results in the near future. Thanks again for your attention to RecBole!
