### ISSUE TITLE
关于SASRec的问题

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1146]
请问一下，为什么使用交叉熵优化时考虑了所有的item而不是像原论文那样抽负样本

**Comment by 2017pxy** [comment]
@tctctctctc ，你好，SASRec原文就是考虑所有item的，原文loss_func如下：
![图片](https://user-images.githubusercontent.com/38801065/154926040-226e9397-894b-4393-b4e6-addd6f263b8b.png)

**Comment by 2017pxy** [comment]
@tctctctctc 你好，这里是我们做的接口统一，我们为所有seq类模型实现了两种loss：CE和BPR。我们这里没有采样的原因是因为我们使用的是CE loss，而不是BCE loss；我们目前对于SASRec没有实现BCE loss的版本。这种loss的设置主要是适配我们的数据部分。

**Comment by tctctctctc** [comment]
请问一下，inter_matrix 方法在 dataset 和 sequential_dataset 中有什么区别？

**Comment by tctctctctc** [comment]
感谢
