### ISSUE TITLE
[🐛BUG (?)] Running the quick start example ignores the .yaml configuration

### ISSUE THREAD

**Issue by karapostK** [RUCAIBox/RecBole#1147]
**Describe the bug**
I'm following the [quick start (from API) guide](https://www.recbole.io/docs/get_started/quick_start.html) for RecBole. I create both the .yaml file and the run.py files as specified in the guide.

```
from recbole.quick_start import run_recbole
run_recbole(model='BPR', dataset='ml-100k')
```
I then run the model with
`python run.py --config_files=test.yaml`

The code ignores the configuration from the .yaml file (e.g. the train_batch_size, eval_batch_size or anything that I decide to change) and runs a default configuration (e.g. train_batch_size set to 2048 even though it should be 4096)

However, it works if I pass a hyperparameter from the command line e.g.

`python run.py --embedding_size=32` 
will run BPR with embedding_size = 32

**To Reproduce**
1. Follow the steps of [Quick Start From API](https://www.recbole.io/docs/get_started/quick_start.html#quick-start-from-api).
2. Try to change anything in the .yaml file

**Expected behavior**
Changing the configuration file should have an effect on the experiment

**Desktop (please complete the following information):**
 - OS: Linux
- RecBole Version 1.0.0
 - Python Version 3.9.7
- PyTorch Version 1.8.1
- cudatoolkit Version none

**Comment by leoleojie** [comment]
@karapostK Hello, thanks for your feedback. We have revised the document in PR #1151. 
You can create a new python file (e.g., run.py), and write the following code:
```
run_recbole(model='BPR', dataset='ml-100k', config_file_list=['test.yaml'])
```
Then run the following command:
```
python run.py 
```
As for why it works if you pass parameters from the command line, RecBole supports the combination of three types of parameter configurations: Command Line，Parameter Dicts and Config Files. The priority of the configuration methods is: Command Line > Parameter Dicts > Config Files > Default Settings.  Please refer to  [API doc](https://www.recbole.io/docs/user_guide/config/parameters_configuration.html) for details.
