### ISSUE TITLE
[💡SUG] Use embedding feateures without custom model

### ISSUE THREAD

**Issue by astrung** [RUCAIBox/RecBole#1150]
**Is your feature request related to a problem? Please describe.**
As what i read in [document,](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html) , after loading embedding user features, i still need to custom a new model(`YourModel`) to use external embedding features. But it is costly for re-create all new layers and model, so i hope i can find an end-to-end approach.

**Describe the solution you'd like**
Is there any models i can use directly with only appended config and don't need to modify code?

**Additional context**

    class YourModel(GeneralRecommender):
        def __init__(self, config, dataset):
            pretrained_user_emb = dataset.get_preload_weight('uid')
            self.user_embedding = nn.Embedding.from_pretrained(torch.from_numpy(pretrained_user_emb))

**Comment by Wicknight** [comment]
@astrung Hello, thanks for your attention to RecBole!
At present, we only support the method described in the document to use auxiliary embedding in the model. You need to slightly modify the code based on the corresponding model to use external embedding. If you have a better solution, you are welcome to discuss with us.

**Comment by astrung** [comment]
@Wicknight 
thank you for you answer. 
I think we can have another options here. Lead embedding features as user features (create embed1, ..., embedN in data.user atomic file), then use Context-aware model for predicting. As i read in [this document](https://recbole.io/docs/user_guide/usage/running_different_models.html#context-aware-recommendation), Context-aware model use user features for predicting.
    
    1. Is this possible ?
    2. And can we use Context-aware model without explicit feedback(rating) ?  i only have clicked data without rating, so i have data with only implicit feedback. All of iteration in my data is labeled with only 1, so can i use this model ?

**Comment by Wicknight** [comment]
@astrung 
1. You can do this if the context-aware model is applicable to your task.
2.When you use the context-aware model, either your data has been clearly divided into positive and negative cases, or your data contains rating information, which can be divided into positive and negative cases by setting a threshold. The situation you described cannot use the context-aware model.
Therefore, in general, we need to use the way in [document](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html) to use pre-trained embedding

**Comment by astrung** [comment]
@Wicknight 
thank i close topic. However. i got a new problem. 
Please check it if you can help
https://github.com/RUCAIBox/RecBole/issues/1157
