### ISSUE TITLE
Problem：自定义数据集和划分

### ISSUE THREAD

**Issue by fxvvv** [RUCAIBox/RecBole#1152]
请问一下，想要以dataframe的格式从数据库中导入自己的数据集且自己划分train和test，quick_start中的train_data、valid_data和test_data直接作为算法的输入，使用seq类的算法（SASRec），有什么数据结构的要求吗（必要的col）

**Comment by chenyuwuxin** [comment]
@fxvvv 感谢您的关注！
使用自定义划分的序列数据集可以通过设置`benchmark_filename`来实现，但是我们不会对数据集进行序列增强，因此数据集必须提供处理好的序列数据，即在`.inter`文件中提供`item_id_list_field`属性列，更多的细节可以参考[#issue 1069](https://github.com/RUCAIBox/RecBole/issues/1069)。

**Comment by fxvvv** [comment]
你好，想再问一下，不以.inter文件的形式输入可以吗？直接输入train_data、valid_data和test_data可以吗？
源码里dataset、train_data和test_data都是定义的类的类型
截图
![image](https://user-images.githubusercontent.com/74700748/155498872-969cacc4-c4d2-4bf0-b33c-2a0897425ae3.png)

**Comment by chenyuwuxin** [comment]
@fxvvv 不太清楚**直接输入train_data、valid_data和test_data**的意思。如果你想要加载已经保存好的数据集，可以使用**load_data_and_model**接口，具体实现方式可以参考[Save and Load](https://recbole.io/docs/user_guide/usage/save_and_load_data_and_model.html?highlight=save_dataset)。一般是将数据集划分成 `[dataset].train.inter , [dataset].val.inter , [dataset].test.inter` 这种形式，然后设置`benchmark_filename`。具体设置请参考[Data Settings](https://recbole.io/docs/user_guide/config/data_settings.html?highlight=benchmark_filename)。

**Comment by fxvvv** [comment]
有没有接口可以将csv文件转化成.inter文件呢



---原始邮件---
发件人: "Tian ***@***.***&gt;
发送时间: 2022年2月25日(周五) 上午8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RUCAIBox/RecBole] Problem：自定义数据集和划分 (Issue #1152)




 
@fxvvv 不太清楚直接输入train_data、valid_data和test_data的意思。如果你想要加载已经保存好的数据集，可以使用load_data_and_model接口，具体实现方式可以参考Save and Load。一般是将数据集划分成 [dataset].train.inter , [dataset].val.inter , [dataset].test.inter 这种形式，然后设置benchmark_filename。具体设置请参考Data Settings。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyuwuxin** [comment]
@fxvvv `.inter`文件记录用户和物品的交互信息，它的格式不固定，可以是csv文件。你只需要在文件头写明字段信息就可以作为.inter文件，具体的处理方式参考[atomic files](https://recbole.io/docs/user_guide/data/atomic_files.html?highlight=atomic)，并且在配置文件中指明文件字段分隔符`field_separator: ","`，更多设置细节参考[Data Settings](https://recbole.io/docs/user_guide/config/data_settings.html?highlight=field_separator)。
