### ISSUE TITLE
[🐛BUG] RaCT算法没有计算结果

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#1153]
**描述这个 bug**
RaCT算法没有计算结果，我用不同的测试数据集试过，都是没有Evaluation过程。

**如何复现**
复现这个 bug 的步骤：
python run_recbole.py --model=RaCT

**屏幕截图**
<img width="374" alt="截屏2022-02-23 下午8 09 16" src="https://user-images.githubusercontent.com/28251436/155317311-5410fc79-bcd9-4cb1-ba86-146148434eed.png">

**实验环境（请补全下列信息）：**
 - 操作系统: macOS 12.3.1
- RecBole 版本 1.0.0
 - Python 版本 3.9.10
- PyTorch 版本 1.10.2
- cudatoolkit 版本 11.3.1

**Comment by Sherry-XLL** [comment]
@sxhysj 你好，RaCT 是基于演员-评价者强化学习方法（actor-critic reinforcement learning）的推荐模型，包括三个训练阶段：`actor pre-training`, `critic pre-training` 以及 `actor-critic training`。

在默认配置下，`train_stage: actor_pretrain`，此时模型为预训练阶段，不会有验证的 evaluation 过程，预训练的目的是得到 `./saved` 文件夹下的预训练模型。将预训练的模型路径作为 `pre_model_path`，更改 RaCT.yaml 文件的训练阶段 `train_stage` 即可进入 `critic_pretrain` 的预训练阶段。第二次预训练完之后再次更改 `pre_model_path` 为新的预训练模型路径，设置 `train_stage: finetune`，在第三次微调阶段才会有验证结果的输出。

https://github.com/RUCAIBox/RecBole/blob/e37661a5810bdf2543dba99dc888e597d5277232/recbole/properties/model/RaCT.yaml#L1-L11

RaCT 的模型默认配置信息可以在 `recbole/properties/model/RaCT.yaml` 中查看和更改，具体的模型使用可以参考[模型文档](https://recbole.io/docs/user_guide/model/general/ract.html)。
