### ISSUE TITLE
代码疑问，请求解答

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1155]
https://github.com/RUCAIBox/RecBole/blob/a26f73a24c0208a75f9a8d7c439f60b61c8868d1/recbole/sampler/sampler.py#L70-L95
这段代码里的最后一个while的解释是啥呢？我看不懂，求解 please！！！

**Comment by leoleojie** [comment]
@WhutTjk  你好！在基于流行度的负采样时，我们以商品流行度作为采样权重对采样池内的商品进行带权采样。这个问题也可以视为如何从一个离散的分布中采样。在伯乐系统中，为了降低复杂度，我们使用的是alias method. 而这段代码构建的alias table也是在为采样做准备。

简单来说，我们可以将采样视为一个打靶问题。比如给一个离散分布
![image](https://user-images.githubusercontent.com/88081427/155466668-2e1539fc-8d50-4976-a095-ea21bb084a32.png)
我们可以归一化后构建这样的矩形进行采样。![image-20220224130639316](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241306345.png)
此时采样过程可以分为两步，首先采样选择哪一列，再进行第二次采样，落在红色区域则采样失败，否则采样成功。但是这样的做法可能导致无穷次采样，即每次都落在红色区域。

于是便提出了**alias method**：

用上面的例子来说，以概率的均值(1/N)归一化获得矩形图:![image-20220224131546867](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241315902.png)
此时通过将多出来的部分补到小矩形的位置上，得到![image-20220224131729319](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241317355.png)

此时获得的矩形没有多余部分，矩形的每一列仍只由两个部分组成，并且每一列中都一定保留了一部分原先就存放在这的矩形。此时我们就可以按照上面的方法进行采样，并且每次采样一定会有结果。

![image-20220224133623140](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241336173.png)

为了实现这个算法，我们需要维护两个不同的table： **a probability table** *Prob*，**an alias table** *Alias*。其中*Prob*存放的是每一列中，原先就存放在这的矩形被选中的概率，而*Alias*存放的是哪一块矩形填补到了该列当中。在采样时，我们首先随机选择出一列 i , 随后第二次采样，根据Prob[i]来决定采样 i还是Alias[i]. 
以上面的例子来说明两个table构建的过程：

![image-20220224134452105](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241344136.png)

![image-20220224134832652](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241348681.png)
注意到此时我们有两个矩形小于１，这说明他们不能填满一列，而是需要其他列来补充。同时我们有两列矩形大于1，可以用来补充其他列。这里选择4\3作为补充，得到：

以此类推：

![image-20220224134956993](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241349023.png)

![image-20220224135019462](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241350495.png)

![image-20220224135035691](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241350721.png)

![image-20220224135051149](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241350173.png)

最终得到：![image-20220224135108925](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241351950.png)即可进行采样。

具体的算法说明如下：

![image-20220224134201140](https://raw.githubusercontent.com/leoleojie/cloudimg/master/data/202202241342183.png)

更细节的描述请阅读有关alias method的文章。

**Comment by WhutTjk** [comment]
非常感谢！图文结合很清楚！！
