### ISSUE TITLE
[🐛BUG] neg_sampling paramters isn't working with GRU4Rec

### ISSUE THREAD

**Issue by astrung** [RUCAIBox/RecBole#1157]
**Describe the bug**
I have a custom dataset, but when setting parameters for running new data with GRU4Rec, i always get bus with neg_sampling parameter.

- If i use setting: `'neg_sampling': {'uniform': 1}`, i got this error: `ValueError: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.`
- But if i use setting `'neg_sampling': None`, i got this error: 

      Traceback (most recent call last):
          File "C:/Users/AnhNT5/PycharmProjects/test_recbox/test.py", line 55, in <module>
              best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
          File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 315, in fit
              train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
          File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 168, in _train_epoch
              losses = loss_func(interaction)
          File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\model\general_recommender\bpr.py", line 77, in calculate_loss
              neg_item = interaction[self.NEG_ITEM_ID]
          File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\data\interaction.py", line 131, in __getitem__
              return self.interaction[index]
      KeyError: 'neg_item_id' 

**To Reproduce**
I only have clicked data without rating, so i have data with only implicit feedback. So i want to use sequential model (`GRU4Rec`). This is my code:

    from logging import getLogger
    from recbole.config import Config
    from recbole.data import create_dataset, data_preparation
    from recbole.model.general_recommender import BPR
    from recbole.trainer import Trainer
    from recbole.utils import init_seed, init_logger
    
    parameter_dict = {
        'data_path': 'C:\\Users\\AnhNT5\\kaggle\\HM_recommendation',
        'USER_ID_FIELD': 'user_id',
        'ITEM_ID_FIELD': 'item_id',
        'TIME_FIELD': 'timestamp',
        'user_inter_num_interval': "[50,inf)",
        'item_inter_num_interval': "[50,inf)",
        'val_interval': {'timestamp': "[1577751000, inf)"},
        'load_col': {'inter': ['user_id', 'item_id', 'timestamp']},
        'neg_sampling': None,
        # 'NEG_PREFIX': 'neg_',
        # 'neg_sampling': {'uniform': 1},
        # 'train_neg_sample_args': {'strategy': 'by', 'by': 1, 'distribution': 'uniform'},
        # 'eval_neg_sample_args': {'strategy': 'full', 'distribution': 'uniform'}
    }
    
    if __name__ == '__main__':
        # configurations initialization
        # config = Config(model='BPR', dataset='ml-100k')
        # config = Config(model='BPR', dataset='recbox_data', config_dict=parameter_dict)
        config = Config(model='GRU4Rec', dataset='recbox_data', config_dict=parameter_dict)
    
        # init random seed
        init_seed(config['seed'], config['reproducibility'])
    
        # logger initialization
        init_logger(config)
        logger = getLogger()
    
        # write config info into log
        logger.info(config)
    
        # dataset creating and filtering
        dataset = create_dataset(config)
        logger.info(dataset)
    
        # dataset splitting
        train_data, valid_data, test_data = data_preparation(config, dataset)
    
        # model loading and initialization
        model = BPR(config, train_data.dataset).to(config['device'])
        logger.info(model)
    
        # trainer loading and initialization
        trainer = Trainer(config, model)
    
        # model training
        best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
    
        # model evaluation
        test_result = trainer.evaluate(test_data)
        print(test_result)
  

**Expected behavior**
I hope to run `GRU4Rec` model without any error. Running with `BPR` model is fine, but i got above error with `GRU4Rec` model.

**Desktop (please complete the following information):**
 - OS: Windows10
-  recbole version: 1.0.0
 - Python Version: 3.7.11
- PyTorch Version: 1.8.2+cu10
- cudatoolkit Version: 10.2

**Comment by astrung** [comment]
I add output log here. Please check and help

    C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\python.exe C:/Users/AnhNT5/PycharmProjects/test_recbox/test.py
    24 Feb 16:07    INFO  
    General Hyper Parameters:
    gpu_id = 0
    use_gpu = True
    seed = 2020
    state = INFO
    reproducibility = True
    data_path = C:\Users\AnhNT5\kaggle\HM_recommendation\recbox_data
    show_progress = True
    save_dataset = False
    save_dataloaders = False
    benchmark_filename = None
    
    Training Hyper Parameters:
    checkpoint_dir = saved
    epochs = 300
    train_batch_size = 2048
    learner = adam
    learning_rate = 0.001
    eval_step = 1
    stopping_step = 10
    clip_grad_norm = None
    weight_decay = 0.0
    loss_decimal_place = 4
    
    Evaluation Hyper Parameters:
    eval_args = {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full', 'group_by': 'user'}
    metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
    topk = [10]
    valid_metric = MRR@10
    valid_metric_bigger = True
    eval_batch_size = 4096
    metric_decimal_place = 4
    
    Dataset Hyper Parameters:
    field_separator = 	
    seq_separator =  
    USER_ID_FIELD = user_id
    ITEM_ID_FIELD = item_id
    RATING_FIELD = rating
    TIME_FIELD = timestamp
    seq_len = None
    LABEL_FIELD = label
    threshold = None
    NEG_PREFIX = neg_
    load_col = {'inter': ['user_id', 'item_id', 'timestamp']}
    unload_col = None
    unused_col = None
    additional_feat_suffix = None
    rm_dup_inter = None
    val_interval = {'timestamp': '[1577751000, inf)'}
    filter_inter_by_user_or_item = True
    user_inter_num_interval = [50,inf)
    item_inter_num_interval = [50,inf)
    alias_of_user_id = None
    alias_of_item_id = None
    alias_of_entity_id = None
    alias_of_relation_id = None
    preload_weight = None
    normalize_field = None
    normalize_all = None
    ITEM_LIST_LENGTH_FIELD = item_length
    LIST_SUFFIX = _list
    MAX_ITEM_LIST_LENGTH = 50
    POSITION_FIELD = position_id
    HEAD_ENTITY_ID_FIELD = head_id
    TAIL_ENTITY_ID_FIELD = tail_id
    RELATION_ID_FIELD = relation_id
    ENTITY_ID_FIELD = entity_id
    
    Other Hyper Parameters: 
    neg_sampling = None
    repeatable = True
    embedding_size = 64
    hidden_size = 128
    num_layers = 1
    dropout_prob = 0.3
    loss_type = CE
    MODEL_TYPE = ModelType.SEQUENTIAL
    MODEL_INPUT_TYPE = InputType.POINTWISE
    eval_type = EvaluatorType.RANKING
    device = cuda
    train_neg_sample_args = {'strategy': 'none'}
    eval_neg_sample_args = {'strategy': 'full', 'distribution': 'uniform'}
    
    
    24 Feb 16:07    INFO  recbox_data
    The number of users: 17258
    Average actions of users: 74.41820710436345
    The number of items: 8648
    Average actions of items: 148.5179831155314
    The number of inters: 1284235
    The sparsity of the dataset: 99.13952480336246%
    Remain Fields: ['user_id', 'item_id', 'timestamp']
    24 Feb 16:08    INFO  [Training]: train_batch_size = [2048] negative sampling: [None]
    24 Feb 16:08    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full', 'group_by': 'user'}]
    24 Feb 16:08    INFO  BPR(
      (user_embedding): Embedding(17258, 64)
      (item_embedding): Embedding(8648, 64)
      (loss): BPRLoss()
    )
    Trainable parameters: 1657984
    Traceback (most recent call last):
      File "C:/Users/AnhNT5/PycharmProjects/test_recbox/test.py", line 55, in <module>
        best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 315, in fit
        train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 168, in _train_epoch
        losses = loss_func(interaction)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\model\general_recommender\bpr.py", line 77, in calculate_loss
        neg_item = interaction[self.NEG_ITEM_ID]
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\data\interaction.py", line 131, in __getitem__
        return self.interaction[index]
    KeyError: 'neg_item_id'
    
    Process finished with exit code 1

**Comment by Sherry-XLL** [comment]
@astrung Hello, the model is BPR according to you logging output. When the type of loss function is `'BPRLoss'`, the training task will be optimized in the pair-wise way, which maximizes the difference between positive item and negative item, so negative sampling is needed. GRU4Rec works well when `neg_sampling` is `None` and `loss_type` is `'CE'`.

```
24 Feb 16:08    INFO  BPR(
  (user_embedding): Embedding(17258, 64)
  (item_embedding): Embedding(8648, 64)
  (loss): BPRLoss()
)
Trainable parameters: 1657984
Traceback (most recent call last):
  File "C:/Users/AnhNT5/PycharmProjects/test_recbox/test.py", line 55, in <module>
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
  File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 315, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 168, in _train_epoch
    losses = loss_func(interaction)
  File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\model\general_recommender\bpr.py", line 77, in calculate_loss
    neg_item = interaction[self.NEG_ITEM_ID]
  File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\data\interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'neg_item_id'
```

**Comment by astrung** [comment]
@Sherry-XLL 
I have added `loss_type: CE` to my yaml config as this below code.

    parameter_dict = {
    'data_path': 'C:\\Users\\AnhNT5\\kaggle\\HM_recommendation',
    'USER_ID_FIELD': 'user_id',
    'ITEM_ID_FIELD': 'item_id',
    'TIME_FIELD': 'timestamp',
    'user_inter_num_interval': "[50,inf)",
    'item_inter_num_interval': "[50,inf)",
    'val_interval': {'timestamp': "[1577751000, inf)"},
    'load_col': {'inter': ['user_id', 'item_id', 'timestamp']},
    'neg_sampling': None,
    'loss_type': 'CE'}

but i still got same error. **It is still using BPRLoss. How can i fix it ?**

    25 Feb 16:47    INFO  BPR(
      (user_embedding): Embedding(17258, 64)
      (item_embedding): Embedding(8648, 64)
      (loss): BPRLoss()
    )
    Trainable parameters: 1657984
    Traceback (most recent call last):
      File "C:/Users/AnhNT5/PycharmProjects/test_recbox/test.py", line 56, in <module>
        best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 315, in fit
        train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\trainer\trainer.py", line 168, in _train_epoch
        losses = loss_func(interaction)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\model\general_recommender\bpr.py", line 77, in calculate_loss
        neg_item = interaction[self.NEG_ITEM_ID]
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\data\interaction.py", line 131, in __getitem__
        return self.interaction[index]
    KeyError: 'neg_item_id'

**Comment by Sherry-XLL** [comment]
@astrung The loss is `BPRLoss` because your model is BPR, please make sure that `model='GRU4Rec'`.

**Comment by astrung** [comment]
@Sherry-XLL 
thank you. I find out that i need to change below code: `model = BPR(config, train_data.dataset).to(config['device'])` to `model = GRU4Rec(config, train_data.dataset).to(config['device'])`

**Comment by Sherry-XLL** [comment]
@astrung You are welcome, and thanks for your attention to RecBole!
