### ISSUE TITLE
[💡SUG] Create .kg and .link from raw csv file

### ISSUE THREAD

**Issue by astrung** [RUCAIBox/RecBole#1166]
**Is your feature request related to a problem? Please describe.**
 I want to compare Knowledge graph model and other models for my raw data, but i don't know how to create `.kg` and `.link` atomic files to use with RecBole. I have checked this convert [tools](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md) , but this tool need an specific format as input (input data need to be `.kg` files), but i don't have `.kg` files, i have only raw csv file. How can i create .kg and .link files from only raw csv file ?
 
**Describe the solution you'd like**

**I hope some clear and simple solution for converting from csv file to `.kg` and `.link` files. I want to create a graph with item, categories of items, shops which sell items.** 

**Describe alternatives you've considered**
In my ideal, i think i can encode item_id, category_id, shop_id  as entity_id, then:

- create `.link` file with 2 relation_id: belong_to_category and sell_at_shop. Item_id will be head_id, and shop_id and category_id will be tail_id
- create `.kg` file with item_id and encoded entity_id.
All steps will be need to code manually. **I am doing correctly ? Can i do faster by other ways ? Please help**

**Comment by Wicknight** [comment]
@astrung Hello , thanks for your attention to RecBole!
According to your description, I think you are doing correctly. You can encoder item, shop and category, and then you can use a loop to automatically convert .csv file into a .link file or .kg file line by line. I think this is a good method, and I don't think there is a simpler way than this. I think you can try this first, and if you have difficulty with other problems in the process, you can continue to discuss with us.

**Comment by astrung** [comment]
@Wicknight 
thank you for fast response.
I have another question: `.kg` file and `.link` file is for only a graph of items. How can i create a graph of user and use it for Knowledge graph model ?

**Comment by Wicknight** [comment]
@astrung 
In this regard, we do not support user based knowledge graph at present. If you need to use it in this way, you need to design it according to our **KnowledgeBasedDataset** and transform it on this basis.

**Comment by astrung** [comment]
@Wicknight 
thank you for fast response.
So now i will test with graph of items first.
If i can make a new model with graph of users, i will contribute it later
