### ISSUE TITLE
[🐛BUG] 关于SRGNN和GCSAN无法调用GPU的问题

### ISSUE THREAD

**Issue by Sword-CS** [RUCAIBox/RecBole#1167]
**描述这个 bug**
当我用SRGNN和GCSAN模型在ml-1m和yelp数据集上（数据集文件均来自于平台所提供的已处理好的原子文件）运行时，发现无法调用GPU来运行模型，即使GPU处于空闲状态，参数文件均采用平台设置的默认参数。请问是什么问题导致出现这种情况的？期待回复，特此感谢。

**实验环境（请补全下列信息）：**
 - 操作系统: Linux
- RecBole 版本 0.1.1
 - Python 版本 3.7
- PyTorch 版本 1.60
- cudatoolkit 版本 10.2

ko

**Comment by hyp1231** [comment]
请问其他模型可以调用 GPU 吗，比如默认的 BPR 模型运行 ml-100k 数据集？

**Comment by Sword-CS** [comment]
运行其它非GNN类的序列模型，例如GRU4Rec或NARM等都没有问题，能调用GPU进行训练，就GNN类的模型无法调用GPU。同样的配置文件，只调换了模型就会出现这个问题。



---原始邮件---
发件人: "Yupeng ***@***.***&gt;
发送时间: 2022年2月27日(周日) 晚上11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RUCAIBox/RecBole] [🐛BUG] 关于SRGNN和GCSAN无法调用GPU的问题 (Issue #1167)




 
请问其他模型可以调用 GPU 吗，比如默认的 BPR 模型运行 ml-100k 数据集？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyp1231** [comment]
好的。请问您指的“无法调用 GPU”是指下面的哪种情况：
1）GPU 利用率低，但是 nvidia-smi 可以查询到进程；
2）nvidia-smi 查询不到这个进程；

**Comment by Sword-CS** [comment]
您好，属于第二种情况，无法查询到进程，GPU利用率为0，并且没有任何的显存占用。其它模型倒能正常调用，能显示进程及显存占用等信息。

---原始邮件---
发件人: "Yupeng ***@***.***&gt;
发送时间: 2022年2月28日(周一) 上午8:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RUCAIBox/RecBole] [🐛BUG] 关于SRGNN和GCSAN无法调用GPU的问题 (Issue #1167)




 
好的。请问您指的“无法调用 GPU”是指下面的哪种情况：
 1）GPU 利用率低，但是 nvidia-smi 可以查询到进程；
 2）nvidia-smi 查询不到这个进程；
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyp1231** [comment]
好的，这边建议做如下实验来检测具体问题：

1）在 `__init__` 函数中打印 `self.device`，检查输出；
https://github.com/RUCAIBox/RecBole/blob/eaed67f8cd494b2edbb7f87e31ef4dec3632837c/recbole/model/sequential_recommender/srgnn.py#L121

2）在 `forward` 函数中打印 `hidden.device`，检查输出：
https://github.com/RUCAIBox/RecBole/blob/eaed67f8cd494b2edbb7f87e31ef4dec3632837c/recbole/model/sequential_recommender/srgnn.py#L189

3）可以考虑使用最近的 release 版本（v1.0.1）进行实验，检查是否还会出现当前问题。

**Comment by Sword-CS** [comment]
现在在ml-1m数据集上运行SRGNN时：
（1）__init__函数中打印self.device&nbsp; --&gt;&nbsp; 显示: cuda
（2）forward函数中打印hidden.device&nbsp; --&gt; 显示: cuda:0
（3）nvidia-smi命令能够显示显存占用2582MiB/11019MiB, 但GPU利用率为0


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/RecBole"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/RecBole] [🐛BUG] 关于SRGNN和GCSAN无法调用GPU的问题 (Issue #1167)





 
好的，这边建议做如下实验来检测具体问题：
 
1）在 __init__ 函数中打印 self.device，检查输出；
 https://github.com/RUCAIBox/RecBole/blob/eaed67f8cd494b2edbb7f87e31ef4dec3632837c/recbole/model/sequential_recommender/srgnn.py#L121
 
2）在 forward 函数中打印 hidden.device，检查输出：
 https://github.com/RUCAIBox/RecBole/blob/eaed67f8cd494b2edbb7f87e31ef4dec3632837c/recbole/model/sequential_recommender/srgnn.py#L189
 
3）可以考虑使用最近的 release 版本（v1.0.1）进行实验，检查是否还会出现当前问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyp1231** [comment]
好的，根据这些结果，推测出程序还是在调用 GPU，并未出现 bug。

当前 RecBole 的 SR-GNN 和 GCSAN 遵循了原作者的开源代码，会在输入模型前，对每个序列建图（邻接矩阵形式），并用于之后的 GNN 计算。而建图操作是在 CPU 上完成，此时 GPU 上很有可能阻塞，并等待 CPU 上的建图和 CPU-GPU 通讯，因此 GPU 利用率低。

我个人曾经开发过一个使用 PyTorch Geometric 库优化的 SR-GNN 模型，GPU 利用率较高，放在 [srgnnpyg.py](https://github.com/hyp1231/RecBole/blob/pyg/recbole/model/sequential_recommender/srgnnpyg.py) 了。但是这个版本不是 RecBole 的官方代码，因此请谨慎参考。

**Comment by Sword-CS** [comment]
好的，感谢解答。
