### ISSUE TITLE
关于learner和pre_weight的疑问

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1168]
1. 想问一下如果模型中有对抗训练部分，也就是需要多个leaner分别涵盖模型的不同部分，比如GAN里面的生成和判别器，RecBole是如何处理的呢？
2. pre_weight也就是提前训练好的embedding会不会因为数据预处理部分（比如删除了某些user、item或者顺序打乱等）导致出问题呢？
请求解答！

**Comment by chenyuwuxin** [comment]
@WhutTjk 感谢您的关注！
1. 对于这种训练方式比较特殊的模型，我们会专门设计一个`trainer`来实现模型的训练过程，例如`RecVAETrainer`，它是一个encoder，decoder类型的模型。我们为模型的encoder，decoder部分分别设置了一个`optimizer`：
```
class RecVAETrainer(Trainer):
    r"""RecVAETrainer is designed for RecVAE, which is a general recommender.

    """

    def __init__(self, config, model):
        super(RecVAETrainer, self).__init__(config, model)
        self.n_enc_epochs = config['n_enc_epochs']
        self.n_dec_epochs = config['n_dec_epochs']

        self.optimizer_encoder = self._build_optimizer(self.model.encoder.parameters())
        self.optimizer_decoder = self._build_optimizer(self.model.decoder.parameters())

```
2.  不会。因为我们会以key-value的形式处理user_embedding或者item_embedding，具体的使用方式请参考：[pre_weight](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html?highlight=pre)。

**Comment by WhutTjk** [comment]
好的，明白了！谢谢！
