### ISSUE TITLE
[🐛BUG] CUDA error when try to get predict result without valid/test data

### ISSUE THREAD

**Issue by astrung** [RUCAIBox/RecBole#1169]
**Describe the bug**
In my scenario, i need to use all of my data for training model, then get recommendation for all of users. So i don't need to create a valid data or test data, or test data/valid data is empty. But when i use empty test data with this function: [full_sort_topk](https://recbole.io/docs/recbole/recbole.utils.case_study.html#recbole.utils.case_study.full_sort_topk), i got this error: `RuntimeError: CUDA error: invalid configuration argument`

**Note**: If i split data into test and valid data, i got no error. But if i use all data for training(don't split into test and valid data), i always get above error. So i have 2 questions here:

1. Why i need to have a non-empty test data for using function `full_sort_topk` ?
2. How can get predicted result when use all of data for training without test data ?
Please help. 

**To Reproduce**
This is my code for getting bugs:

    from logging import getLogger
    from recbole.config import Config
    from recbole.data import create_dataset, data_preparation
    from recbole.utils.case_study import full_sort_topk
    import pandas as pd
    from recbole.model.sequential_recommender import GRU4Rec
    from recbole.trainer import Trainer
    from recbole.utils import init_seed, init_logger
    
    if __name__ == '__main__':
        parameter_dict = {'epochs': 5, 'neg_sampling': None,
                          'eval_args': {
                              'split': {'RS': [10, 0, 0]}, # i use all of data for traning, no data for test and eval
                              'group_by': 'user',
                              'order': 'TO',
                              'mode': 'full'}
                          }
        # configurations initialization
        config = Config(model='GRU4Rec', dataset='ml-100k', config_dict=parameter_dict)
    
        # init random seed
        init_seed(config['seed'], config['reproducibility'])
    
        # logger initialization
        init_logger(config)
        logger = getLogger()
    
        # write config info into log
        logger.info(config)
    
        # dataset creating and filtering
        dataset = create_dataset(config)
        logger.info(dataset)
    
        # dataset splitting
        train_data, valid_data, test_data = data_preparation(config, dataset)
    
        # model loading and initialization
        model = GRU4Rec(config, train_data.dataset).to(config['device'])
        logger.info(model)
    
        # trainer loading and initialization
        trainer = Trainer(config, model)
    
        # model training
        best_valid_score, best_valid_result = trainer.fit(train_data)
    
    
        external_user_ids = dataset.id2token(dataset.uid_field, list(range(dataset.user_num)))[1:]
        topk_score, topk_iid_list = full_sort_topk(list(range(dataset.user_num))[1:], model, test_data, k=12,
                                                   device=config['device'])
        external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
        external_item_str = [' '.join(x) for x in external_item_list.tolist()]
        result = pd.DataFrame(external_user_ids, columns=['customer_id'])
        result['prediction'] = external_item_str

**Expected behavior**
I hope i can get predicted result when my test data is empty.

**Screenshots**
This is my stacktrace

    Traceback (most recent call last):
      File "C:/Users/AnhNT5/PycharmProjects/test_recbox/main.py", line 58, in <module>
        device=config['device'])
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\utils\case_study.py", line 90, in full_sort_topk
        scores = full_sort_scores(uid_series, model, test_data, device)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\AnhNT5\anaconda3\envs\recbox_gpu\lib\site-packages\recbole\utils\case_study.py", line 64, in full_sort_scores
        scores[:, 0] = -np.inf  # set scores of [pad] to -inf
    RuntimeError: CUDA error: invalid configuration argument

**Desktop (please complete the following information):**
 - OS: Windows10
-  recbole version: 1.0.0
 - Python Version: 3.7.11
- PyTorch Version: 1.8.2+cu10
- cudatoolkit Version: 10.2

**Comment by astrung** [comment]
@Sherry-XLL 
so if I have a new user with iterations, I still need to create an eval dataloader for predicting ?
can we have another ways ?
it take many steps, so it is hard and slow in practice use case

**Comment by Sherry-XLL** [comment]
@astrung RecBole is aiming at the baseline comparison in the research of academic papers, which is applicable to the classic recommendation scenarios and cannot directly deal with the cold-start users. In other words, in case study, the input is the users who have appeared in the training data, and then evaluate the recommendation performance by using interactions in the test data.

**Comment by astrung** [comment]
@Sherry-XLL 
thank you for fast respond.
I have checked with a sample data from kaggle, it looks great for research purpose, but it seem to be deeply customize if I want to use it in practice. I will try customize and test it in practice, so I hope I can ask you if any problem occurs.

Anyway, i create a notebook for introduction using Recbole with csv data step by step, can i make a pull request to contribute to Recbole document ? 

.

**Comment by Sherry-XLL** [comment]
@astrung If you have specific questions about RecBole, it is suggested that you put forward different issues to facilitate targeted replies. All the time, we welcome any open source contribution to RecBole. After you make the PR, we will review it in detail.

**Comment by astrung** [comment]
@Sherry-XLL @Wicknight 
I have created some notebook for understanding recbole test dataset and making recommendation by using all items without test data:
* understanding test dataset: https://www.kaggle.com/code/astrung/recbole-using-all-items-for-prediction/notebook
* making prediction without test data: 
    * https://www.kaggle.com/code/astrung/sequential-model-fixed-missing-last-item
    * https://www.kaggle.com/code/astrung/lstm-model-with-item-infor-fix-missing-last-item

Can we use this notebook as a tutorial ? Should we push a pull request for adding new notebooks in guide document ?
I am sure that it is useful for using in practical case

**Comment by Sherry-XLL** [comment]
@astrung 

Hello, I'm so sorry for my late reply! 

Your notebooks look great to new users.  At your convenience, you can push a pull request and we will review it in detail. 

In addition, we welcome you to open a new issue instead of reopening the previous issue, in case we miss your reply. 

Thanks very much for your attention and enhancement to RecBole!

**Comment by elloza** [comment]
I am following the notebooks you have made in Kaggle to start with Rebole. Fantastic work!

However, I have some doubts for the case of session based recommendation (each session is a user).

Let's imagine that we have 5 new interactions with items that are available in the dataset, how can we make a recommendation of the sixth item without having a user in the dataset with those interactions? I mean, how could RecBole be used to make a prediction about a new session (or part of it)?

Thank you very much!

Translated with www.DeepL.com/Translator (free version)

**Comment by astrung** [comment]
@elloza sorry for my late response.
Sorry I can't get your ideal, but I think your question is :"If a new session starts, it doesn't have any interactions, so how we can get recommend ?"
In this case, we can use other recommendation engines like as "most-view items", "trending-items". And after getting some interactions, we can use recommendation engine.
In practice, we usually mix between other engines.

**Comment by astrung** [comment]
@elloza Or if you want predict with a new user with some interactions - a user doesn't appear in your dataset, you should make a new interaction for this user, then call API directly with new [Interaction](https://github.com/RUCAIBox/RecBole/blob/52f5707b4879b991014d2c4d09c4b416aadc4fd9/recbole/data/interaction.py#L43) object. You can check my notebook about how to create a new interaction: https://www.kaggle.com/code/astrung/recbole-using-all-items-for-prediction
