### ISSUE TITLE
[💡SUG] 如何使用自己的数据集？

### ISSUE THREAD

**Issue by zgabhuajun** [RUCAIBox/RecBole#1170]
请问如何使用自己的数据集来进行实验？我看到RecBole提供了很多数据集，但是我想使用与之不同的自己的数据集应该怎么做？

**Comment by hyp1231** [comment]
您好，请参考我们我们的 [API 文档 - Prepare atomic files](https://recbole.io/docs/user_guide/usage/running_new_dataset.html#prepare-atomic-files)，只要讲您自己的数据集处理成“原子文件”的形式即可。

**Comment by zgabhuajun** [comment]
好的，非常感谢！
