### ISSUE TITLE
MLPLayers可以添加一下额外参数吗？

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1173]
https://github.com/RUCAIBox/RecBole/blob/04f7a501fdab5d4eddf7ad3158d2ab28f6302ad4/recbole/model/layers.py#L54
比如对于LeakyReLU没有办法设置斜率的情况，感觉可以添加一个字典参数更好一些？

**Comment by Sherry-XLL** [comment]
@WhutTjk 感谢你对 RecBole 的关注和建议，我们会在下一版本集中开发的时候考虑是否对默认参数进行参数设置。如果目前你比较需要字典参数的功能，可能需要自行实现一下，也欢迎你整理相关的代码向我们提出 Pull Request，再次感谢你的提议。
