### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../saved/BPR-Aug-20-2021_03-32-13.pth'

### ISSUE THREAD

**Issue by linjianwei888** [RUCAIBox/RecBole#1174]
跑run_example 案例时，这个模型找不啊。 模型训练完，怎么指定模型的保存路径呢？

**Comment by Wicknight** [comment]
@linjianwei888 
您好！模型的保存路径由参数checkpoint_dir指定，关于该参数的介绍您可以查看[官方文档](https://recbole.io/docs/user_guide/config/environment_settings.html)。
另外，您描述的run_example案例，我推测是其中的save_and_load_example.py,其中的代码读取的模型路径（model_file）只是一个例子，是需要实时变动更新的，因为在您训练完成后模型的最新路径是与这个例子不一致的，所以才导致FileNotFoundError.
因此总结如下：您需要先运行该py文件中的save_example函数，然后到您通过checkpoint_dir指定的模型路径下查看模型的最新路径，更新load_example函数中对应的路径，然后运行load_example函数，该案例便可以正常运行。

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
