### ISSUE TITLE
关于inter_matrix的问题

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1176]
请问一下，inter_matrix在dataset和sequential_dataset中有什么区别

**Comment by chenyuwuxin** [comment]
@tctctctctc 感谢您的关注！
**inter_matrix**在**dataset**和**sequential_dataset**没有区别，均表示用户和物品交互信息的稀疏矩阵，但它们的处理方式有一些区别。
对于sequential_dataset，我们会做序列化的数据增广：例如u1依次交互i1，i2，i3，增广后的数据集为：{u1,<i1,0,0>,i2}，{u1,<i1,i2,0>,i3}，这种处理方式会导致数据增广后的数据集丢失每个用户首次交互的物品信息(u1-i1)，所以在**sequential_dataset**中，首先根据序列长度为1的交互还原数据增广前完整交互信息，即得到**local_inter_feat**，然后构造交互的稀疏矩阵表示。

**Comment by tctctctctc** [comment]
感谢！那么 inter_matrix 获得的交互矩阵应该是关于时间无序的，请问有没有方法可以获得用户按照时间戳排序后的历史交互序列？

**Comment by chenyuwuxin** [comment]
@tctctctctc 你好，在进行数据增广后，数据集的记录形式为<用户，物品，用户的历史交互序列， ...... >。
例如用户 u1 的历史交互序列为 i1,i2,i3,i4,i5 并且设置序列的最大长度MAX_ITEM_LIST_LENGTH为3。
经过数据增广后，序列数据集变为：
**interaction:**
  |  USER_ID | ITEM_SEQ | ITEM_ID |
  |  ----  | ----  | ----  | 
  | u1 | i1,0,0 | i2 | 
  | u1 | i1,i2,0 | i3 |
  | u1 | i1,i2,i3 | i4 |
  | u1 | i2,i3,i4 | i5 |
 
因此，可以使用`interaction[self.ITEM_SEQ]`获得对应用户按照时间戳排序后的历史交互序列。

**Comment by tctctctctc** [comment]
`interaction[self.ITEM_SEQ]`这种方式只能获得某个时间步的用户交互序列，我想知道有没有定义方法能得到用户所有历史交互，且是按时间戳排序的，然后可以通过索引查询到具体用户的历史交互序列

**Comment by chenyuwuxin** [comment]
@tctctctctc 你好，目前还没有实现好的接口，不过dataset已经实现好了排序接口，非常容易实现你要的功能，你可以参考以下代码：
```
        dataset.sort(by=[self.uid_field, self.time_field], ascending=True)
        last_uid = None
        uid_list , his_list , res = [] , [] , []
        for i, uid in enumerate(dataset.inter_feat[dataset.uid_field].numpy()):
            if uid != last_uid and len(res) != 0:
                uid_list.append(last_uid)
                his_list.append(res)
                last_uid = uid
                res = []
            res.append(dataset.inter_feat[dataset.iid_field][i])
        uid_list.append(last_uid)
        his_list.append(res)
```
uid_list 为用户序列，his_list为对应用户的历史交互物品序列。

**Comment by tctctctctc** [comment]
感谢！！！
