### ISSUE TITLE
Is there a quick way to make a sampler of all users in the test_data?

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#1178]
In the actual prediction process, we want to predict all users that were appeared in the given dataset. However, in the default 8:1:1 splitting mode, the test data dataloader may not contain all user ids in which way it will fail in the prediction mode as in the function:topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=12, device=config['device']) the input parameter of 'test_data' requires all user ids to be predicted.

My question is: is there a quick way in RecBole configuration that allows to sample all user ids in test_data dataloader of a given dataset?

**Comment by Wicknight** [comment]
@sxhysj Hello , thanks for your attention to RecBole!
You can use the following configuration to predict, and use parameter ‘**group_by**’ and parameter '**mode**' to make the evaluation work.
```
eval_args: 
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
```

**Comment by sxhysj** [comment]
> @sxhysj Hello , thanks for your attention to RecBole! You can use the following configuration to predict, and use parameter ‘**group_by**’ and parameter '**mode**' to make the evaluation work.
> 
> ```
> eval_args: 
>   split: {'RS':[0.8,0.1,0.1]}
>   group_by: user
>   order: RO
>   mode: full
> ```

I did use the same configuration but the some IDs seem not to be sampled. Here is the prediction code:
```
import torch
from recbole.utils.case_study import full_sort_topk, full_sort_scores
from recbole.quick_start import load_data_and_model
import pandas as pd

if __name__ == '__main__':
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file='./saved/RecVAE-Feb-23-2022_20-33-49.pth',
    )  # Here you can replace it by your model path.

    # read all of the user ids in string
    df_user = pd.read_csv('sample_submission.csv')
    userid_list = df_user['customer_id'].tolist()

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    #uid_series = dataset.token2id(dataset.uid_field, ['00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657', '0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa'])

    #userid_list = ['00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657', '0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa']
    #print(userid_list)
    uid_series = dataset.token2id(dataset.uid_field, userid_list)
    #print(uid_series)

    #start predicting
    try:
        topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=12, device=config['device'])
    except Exception as inst:
        print("Predicting error")
        print("Exception is {}".format(inst))

    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())
    print(external_item_list)  # external tokens of top 10 items
    print()
```

And the number of user IDs in test_data is smaller than the the actual number of users. Then an error is reported:
```
09 Mar 13:29    INFO  hnm
The number of users: 1371981
Average actions of users: 23.334630667241193
The number of items: 105543
Average actions of items: 304.057734798703
The number of inters: 31788324
The sparsity of the dataset: 99.97804719097992%
Remain Fields: ['t_dat', 'customer_id', 'article_id', 'price', 'sales_channel_id', 'FN', 'Active', 'club_member_status', 'fashion_news_frequency', 'age', 'postal_code', 'product_code', 'prod_name', 'product_type_no', 'product_type_name', 'product_group_name', 'graphical_appearance_no', 'graphical_appearance_name', 'colour_group_code', 'colour_group_name', 'perceived_colour_value_id', 'perceived_colour_value_name', 'perceived_colour_master_id', 'perceived_colour_master_name', 'department_no', 'department_name', 'index_code', 'index_name', 'index_group_no', 'index_group_name', 'section_no', 'section_name', 'garment_group_no', 'garment_group_name', 'detail_desc']
09 Mar 13:44    INFO  [Training]: train_batch_size = [2048] negative sampling: [{'uniform': 1}]
09 Mar 13:44    INFO  [Evaluation]: eval_batch_size = [2048] eval_args: [{'group_by': 'user', 'order': 'RO', 'split': {'RS': [0.8, 0.1, 0.1]}, 'mode': 'full'}]
Predicting error
Exception is full_like(): argument 'input' (position 1) must be Tensor, not NoneType
Traceback (most recent call last):
  File "/Users/huanchen/git/hnm/predict.py", line 43, in <module>
    print(topk_score)  # scores of top 10 items
NameError: name 'topk_score' is not defined
```

Some user IDs seem not to be sampled so the 'full_like()' function reports error.

**Comment by Wicknight** [comment]
@sxhysj 
This problem has nothing to do with whether the test_data contains all user_ids.
Test_data saves the interaction records of each user in the training set and validation set, and only plays a role of padding these records in the function 'full_sort_topk'.
At present, a possible reason is that there are some users who have limit interactions and hard to divide the test set according to your split ratio 8:1:1. For example, if a user have only one interaction, in our framework, he will not have the test set and his id will not occur in `test data`. 
You can try to filter the users who has too few interactions and try again. Hope my suggestion is helpful. Thanks!
