### ISSUE TITLE
[🐛BUG] 自动调超参，报numpy包错误，版本兼容有问题，建议检查并更新requirements。

### ISSUE THREAD

**Issue by GitHub-ZHY** [RUCAIBox/RecBole#1182]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
2. 您的代码
3. 您的运行脚本

**预期**
对您的预期作清晰简明的描述。

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [如 0.1.0]
 - Python 版本 [如 3.79]
- PyTorch 版本 [如 1.60]
- cudatoolkit 版本 [如 9.2, none]

**Comment by hyp1231** [comment]
请问可以提供更多细节吗？比如您的运行命令、自定义的 yaml 配置、具体的报错信息、操作系统、以及各个 package 的版本？

**Comment by GitHub-ZHY** [comment]
absl-py                  0.12.0
aiohttp                  3.7.4
argon2-cffi              20.1.0
astroid                  2.4.2
astunparse               1.6.3
async-generator          1.10
async-timeout            3.0.1
atomicwrites             1.4.0
attrs                    20.3.0
autopep8                 1.5.5
backcall                 0.2.0
bleach                   3.3.0
blessings                1.7
blinker                  1.4
blis                     0.7.4
boto                     2.49.0
boto3                    1.17.46
botocore                 1.20.46
brotlipy                 0.7.0
bz2file                  0.98
cachetools               4.2.1
catalogue                1.0.0
certifi                  2021.10.8
cffi                     1.14.5
chardet                  3.0.4
click                    8.0.3
cloudpickle              2.0.0
cmake                    3.22.3
colorama                 0.4.4
colorlog                 4.7.2
coverage                 5.5
cryptography             3.4.7
cycler                   0.10.0
cymem                    2.0.5
Cython                   0.29.27
dataclasses              0.6
decorator                4.4.2
defusedxml               0.7.1
docopt                   0.6.2
en-core-web-sm           2.3.0
entrypoints              0.3
filelock                 3.0.12
Flask                    2.0.3
future                   0.18.2
gast                     0.4.0
gensim                   4.1.2
google-api-core          1.25.1
google-auth              1.28.0
google-auth-oauthlib     0.4.3
google-cloud-core        1.6.0
google-cloud-storage     1.19.0
google-pasta             0.2.0
google-resumable-media   1.2.0
googleapis-common-protos 1.53.0
googledrivedownloader    0.4
grpcio                   1.36.1
h5py                     2.10.0
httpstat                 1.3.1
huggingface-hub          0.0.17
hyperopt                 0.2.5
idna                     2.10
imageio                  2.13.3
importlib-metadata       3.7.3
iniconfig                1.1.1
ipykernel                5.5.0
ipython                  7.22.0
ipython-genutils         0.2.0
ipywidgets               7.6.3
isodate                  0.6.1
isort                    5.6.4
itsdangerous             2.1.0
jedi                     0.18.0
jieba                    0.42.1
Jinja2                   3.0.3
jmespath                 0.10.0
joblib                   1.0.1
jsonpath                 0.82
jsonschema               3.2.0
jupyter                  1.0.0
jupyter-client           6.1.12
jupyter-console          6.4.0
jupyter-core             4.7.1
jupyterlab-pygments      0.1.2
jupyterlab-widgets       1.0.0
Keras                    2.4.3
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.2
kiwisolver               1.3.1
lazy-object-proxy        1.4.3
lightgbm                 3.3.0
llvmlite                 0.37.0
lxml                     4.7.1
Markdown                 3.3.4
MarkupSafe               2.1.0
matplotlib               3.3.3
mccabe                   0.6.1
mistune                  0.8.4
mkl-fft                  1.3.0
mkl-random               1.1.1
mkl-service              2.3.0
mongo-tools              0.0.2
more-itertools           8.7.0
multidict                5.1.0
murmurhash               1.0.5
nbclient                 0.5.3
nbconvert                6.0.7
nbformat                 5.1.2
nest-asyncio             1.5.1
netron                   5.6.2
networkx                 2.6.3
nltk                     3.5
notebook                 6.3.0
numba                    0.54.1
numpy                    1.22.3
oauthlib                 3.1.0
olefile                  0.46
onnx                     1.10.2
opencv-python            4.5.5.64
opt-einsum               3.1.0
packaging                20.9
pandas                   1.1.3
pandocfilters            1.4.3
parso                    0.8.1
pathy                    0.4.0
pickleshare              0.7.5
Pillow                   8.4.0
pip                      22.0.3
plac                     1.1.3
pluggy                   0.13.1
polars                   0.13.9
preshed                  3.0.2
prettytable              2.0.0
prometheus-client        0.9.0
prompt-toolkit           3.0.18
protobuf                 3.19.1
py                       1.10.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.6.0
pycparser                2.20
pydantic                 1.7.3
pyecharts                1.9.0
Pygments                 2.8.1
PyJWT                    1.7.1
pylint                   2.6.0
pymongo                  3.11.3
pyOpenSSL                20.0.1
pyparsing                2.4.7
pyreadline               2.1
pyrsistent               0.17.3
PySocks                  1.7.1
pytest                   0.0.0
python-dateutil          2.8.1
python-louvain           0.15
pytorch-transformers     1.2.0
pytz                     2021.1
pywin32                  228
pywinpty                 0.5.7
PyYAML                   5.4.1
pyzmq                    22.0.3
qtconsole                5.0.3
QtPy                     1.9.0
rdflib                   6.1.1
recbole                  1.0.1
regex                    2021.3.17
requests                 2.25.1
requests-oauthlib        1.3.0
rsa                      4.7.2
s3transfer               0.3.6
sacremoses               0.0.43
scikit-learn             0.24.1
scipy                    1.8.0
seaborn                  0.11.2
Send2Trash               1.5.0
sentence-transformers    2.2.0
sentencepiece            0.1.95
setuptools               52.0.0.post20210125
shellingham              1.3.1
simplejson               3.17.2
sip                      4.19.13
six                      1.15.0
sklearn                  0.0
smart-open               2.2.1
spacy                    2.3.5
spacy-legacy             3.0.2
srsly                    1.0.5
style                    1.1.0
tensorboard              2.8.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.6.0
tensorflow               2.3.0
tensorflow-estimator     2.3.0
termcolor                1.1.0
terminado                0.9.3
testpath                 0.4.4
texttable                1.6.4
thinc                    7.4.5
threadpoolctl            2.1.0
tokenizers               0.10.3
toml                     0.10.1
torch                    1.8.1+cu102
torch-cluster            1.5.9
torch-geometric          2.0.1
torch-scatter            2.0.8
torch-sparse             0.6.12
torch-spline-conv        1.2.1
torchaudio               0.8.1
torchtext                0.9.1
torchvision              0.9.1+cu102
tornado                  6.1
tqdm                     4.59.0
traitlets                5.0.5
transformers             4.10.3
typer                    0.3.2
typing_extensions        4.1.1
update                   0.0.1
urllib3                  1.26.4
wasabi                   0.8.2
wcwidth                  0.2.5
webencodings             0.5.1
Werkzeug                 2.0.3
wheel                    0.36.2
widgetsnbextension       3.5.1
win-inet-pton            1.1.0
wincertstore             0.2
wordcloud                1.8.1
wrapt                    1.12.1
xmltodict                0.12.0
yacs                     0.1.6
yarl                     1.6.3
zipp                     3.4.1

**Comment by GitHub-ZHY** [comment]
parser.add_argument('--model', '-m', type=str, default='SGL', help='name of models')
    parser.add_argument('--dataset', '-d', type=str, default='ml-1m', help='name of datasets')
    parser.add_argument('--config_files', type=str, default=None, help='fixed config files')
    parser.add_argument('--params_file', type=str, default="hyper.sgl", help='parameters file')
    parser.add_argument('--output_file', type=str, default='hyper_sgl.result', help='output file')

**Comment by GitHub-ZHY** [comment]
Traceback (most recent call last):
  File "D:/RecBole/run_hyper.py", line 38, in <module>
    main()
  File "D:/RecBole/run_hyper.py", line 30, in main
    hp.run()
  File "D:\RecBole\recbole\trainer\hyper_tuning.py", line 309, in run
    fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
  File "C:\Users\.conda\envs\deeplearning\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
    rval.exhaust()
  File "C:\Users\.conda\envs\deeplearning\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\Users\.conda\envs\deeplearning\lib\site-packages\hyperopt\fmin.py", line 270, in run
    new_trials = algo(
  File "D:\RecBole\recbole\trainer\hyper_tuning.py", line 105, in exhaustive_search
    idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
  File "C:\Users\.conda\envs\deeplearning\lib\site-packages\hyperopt\pyll\base.py", line 911, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "C:\Users\.conda\envs\deeplearning\lib\site-packages\hyperopt\pyll\stochastic.py", line 103, in randint
    return rng.randint(low, high, size)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

**Comment by GitHub-ZHY** [comment]
use_gpu: True
seed: 2022
epochs: 2
type: "ED"
n_layers: 3
ssl_tau: 0.5
reg_weight: 1e-05
ssl_weight: 0.05
drop_ratio: 0.1
embedding_size: 64

**Comment by Sherry-XLL** [comment]
@GitHub-ZHY 你好，我们已经在 #1192 中修复了这一 bug，你可以按照最新代码更新 `hyper_tuning.py` 再尝试一下，感谢你对 RecBole 的关注。

**Comment by GitHub-ZHY** [comment]
好的，感谢。

**Comment by GitHub-ZHY** [comment]
ps:&nbsp;如果是本人设置错误或有简单修正方式，烦请及时告知。
os：win10
numpy_version: 1.22.3
hyperopt: 0.2.5

bug_info:
C:\Users\xxx\.conda\envs\deeplearning\python.exe D:/RecBole/run_hyper.py
Traceback (most recent call last):
&nbsp; File "D:/RecBole/run_hyper.py", line 38, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "D:/RecBole/run_hyper.py", line 30, in main
&nbsp; &nbsp; hp.run()
&nbsp; File "D:\RecBole\recbole\trainer\hyper_tuning.py", line 309, in run
&nbsp; &nbsp; fmin(self.trial, self.space, algo=self.algo, max_evals=self.max_evals)
&nbsp; File "C:\Users\xxx\.conda\envs\xxxx\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
&nbsp; &nbsp; rval.exhaust()
&nbsp; File "C:\Users\xxx\.conda\envs\xxxx\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
&nbsp; &nbsp; self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
&nbsp; File "C:\Users\xxx\.conda\envs\xxxx\lib\site-packages\hyperopt\fmin.py", line 270, in run
&nbsp; &nbsp; new_trials = algo(
&nbsp; File "D:\RecBole\recbole\trainer\hyper_tuning.py", line 105, in exhaustive_search
&nbsp; &nbsp; idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
&nbsp; File "C:\Users\xxx\.conda\envs\xxxx\lib\site-packages\hyperopt\pyll\base.py", line 911, in rec_eval
&nbsp; &nbsp; rval = scope._impls[node.name](*args, **kwargs)
&nbsp; File "C:\Users\xxx\.conda\envs\xxxx\lib\site-packages\hyperopt\pyll\stochastic.py", line 103, in randint
&nbsp; &nbsp; return rng.randint(low, high, size)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
================================================================================
ERROR in rec_eval
EXCEPTION
<class 'AttributeError'&gt;
'numpy.random._generator.Generator' object has no attribute 'randint'
NODE
0 randint
1&nbsp; &nbsp;Literal{4}
2&nbsp; size =
3&nbsp; &nbsp;len
4&nbsp; &nbsp; &nbsp;array_union
5&nbsp; &nbsp; &nbsp; &nbsp;array_union
6&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;array_union
7&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Literal{new_ids}
8&nbsp; rng =
9&nbsp; &nbsp;Literal{rng-placeholder}
================================================================================
&nbsp; 0%|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | 0/12 [00:00<?, ?trial/s, best loss=?]


Process finished with exit code 1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/RecBole"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/RecBole] [🐛BUG] 自动调超参，报numpy包错误，版本兼容有问题，建议检查并更新requirements。 (Issue #1182)





 
请问可以提供更多细节吗？比如您的运行命令、自定义的 yaml 配置、具体的报错信息、操作系统、以及各个 package 的版本？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
