### ISSUE TITLE
[🐛BUG?] Inconsistency between `item_embedding_size` and actual output dimension in DMF

### ISSUE THREAD

**Issue by mmosc** [RUCAIBox/RecBole#1185]
Hi!
Thank you for this library!

I'm using DMF to train deep matrix factorization models on ml-100k. 

In the `.yaml` config file, I define:
```
user_embedding_size: 12
item_embedding_size: 12
item_hidden_size_list: [64, 64]
user_hidden_size_list: [64, 64]
```
from which I would expect a final embedding size of 12. However, the final embedding corresponds to the last entry of the `item_hidden_size_list`, and `user_embedding_size` actually corresponds to the output of the first layer, as we can see from here:
https://github.com/RUCAIBox/RecBole/blob/7236c07b1b0e039814e168ef8926dcba85a9b26c/recbole/model/general_recommender/dmf.py#L78
and here:
https://github.com/RUCAIBox/RecBole/blob/7236c07b1b0e039814e168ef8926dcba85a9b26c/recbole/model/general_recommender/dmf.py#L110

Am I right?

If so, I find it a bit misleading, since the actual embedding size does not correspond to the  'item_embedding_size' variable. 

Cheers!
Marta

**Comment by Sherry-XLL** [comment]
@mmosc Hello, your understanding is correct and the actual embedding size of `item` should correspond to the `item_embedding_size`. However, the default embedding size of users and items is `64` in `DMF.yaml`, maybe your `.yaml` file is not loaded correctly, so the model still uses the default parameters. You can print the `user_embedding_size` and `item_embedding_size` to verify that the parameters are read correctly. What's more, the final values of all parameters can also be seen in the default output of the configuration. 

https://github.com/RUCAIBox/RecBole/blob/7236c07b1b0e039814e168ef8926dcba85a9b26c/recbole/properties/model/DMF.yaml#L5-L9

**Comment by mmosc** [comment]
Hi @Sherry-XLL ,

Thanks for your quick reply!

comparing `item_embedding_size` and the actual size of the tensor outputted from `get_item_embedding` is exactly what I had tried out, but the two dimensions don't match, as you can see from the bottom of [this notebook](https://github.com/mmosc/recbole/blob/master/DMF.ipynb).

You can see two things:
 - The `test.yaml` gets loaded correctly: the final embedding dimension corresponds to the last entry of the `item_hidden_size_list` stored in it, i.e. 16 and not 64 as default
 - Although `item_embedding_size` is set to 12, The shape of the item embeddings tensor is `number_of_items` x 16, and not `number_of_items` x 12.

So I am still facing the same inconsistency...

**Comment by Sherry-XLL** [comment]
@mmosc Hello, the actual embedding size of DMF is the last entry of the `hidden_size_list`, not the `user_embedding_size` or `item_embedding_size`. That is to say, you can regard `user_embedding_size` and `item_embedding_size` as the intermediate linear layer size between rating matrix and multi-layer non-linear projection. If you expect a final embedding size of 12, just set `user_hidden_size_list[-1] = item_hidden_size_list[-1] = 12`.

**Comment by mmosc** [comment]
Ok, thanks for looking into that!

So what's the need of specifying explicitly the dimension of the intermediate linear layer (with `user_embedding_size` and `item_embedding_size`)? I suggest removing them and have the user deciding directly with the elements of the  `hidden_size_list`.

And also to specify explicitly in the documentation that the actual embedding size of DMF is the last entry of the `hidden_size_list`.

**Comment by Sherry-XLL** [comment]
@mmosc In the documentation of [DMF](https://recbole.io/docs/user_guide/model/general/dmf.html?highlight=dmf), `user_embedding_size (int)` and `item_embedding_size (int)` are the initial embedding sizes of users and items. The last value in `user_hidden_size_list` and `item_hidden_size_list` must be the same, which ensures that the final embedding size is the same for similarity calculation. 

In #1194, we have added the description in the documentation to specify the actual embedding size of DMF. Thanks for your attention to RecBole!
