### ISSUE TITLE
Interaction创建错误

### ISSUE THREAD

**Issue by WhutTjk** [RUCAIBox/RecBole#1187]
**描述这个 bug**
[Interaction.py文件](https://github.com/RUCAIBox/RecBole/blob/ed883cd43f0a1bf675053c0d7558217d3b6f5f5e/recbole/data/interaction.py#L117)
这里会报错，因为self.interaction[k]可能shape={Size: 0} 导致出现
IndexError: tuple index out of range

**如何复现**
从user_feature中通过整形index获取一项数据就会报此错误！

**屏幕截图**
![image](https://user-images.githubusercontent.com/58941474/158060970-bd1fc2e2-4518-46fc-82aa-81fd279a6351.png)）

**实验环境（请补全下列信息）：**
 - 操作系统:  Windows
- RecBole 版本 1.0.0
 - Python 版本 3.7
- PyTorch 版本 1.9.0
- cudatoolkit 版本 10.1

**Comment by WhutTjk** [comment]
顺便再问一下，有没有啥办法可以一次读取全部批次数据，不需要分一个一个mini-batch

**Comment by leoleojie** [comment]
@WhutTjk 您好！感谢你对伯乐的关注。请问能否提供更详细的信息，比如使用的模型，数据集？

**Comment by WhutTjk** [comment]
模型我自己写的，数据集就是movielens100k，这个bug我用其他方式替代了，但只是说这种情况确实会出现



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: leoleojie ***@***.***&gt;
发送时间: 2022年3月13日 21:59
收件人: RUCAIBox/RecBole ***@***.***&gt;
抄送: WhutTjk ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [RUCAIBox/RecBole] Interaction创建错误 (Issue #1187)





 
@WhutTjk 您好！感谢你对伯乐的关注。请问能否提供更详细的信息，比如使用的模型，数据集？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyushuo** [comment]
@WhutTjk 感谢你的反馈，我们在#1188 修复了这个bug。
对于你想一次读取全部批次数据的问题，我们的`Dataset`类的`inter_feat`成员是包含了所有交互数据，你可以这个成员来获取交互数据。

**Comment by WhutTjk** [comment]
@chenyushuo 好滴！和我处理方法一样😂
