### ISSUE TITLE
[💡SUG] 序列推荐数据预处理时，过滤掉交互次数少的序列

### ISSUE THREAD

**Issue by kuzma-long** [RUCAIBox/RecBole#1193]
在dataset设置参数里，是否可以添加一个阈值，序列长度低于某个值的删除

**Comment by Sherry-XLL** [comment]
@kuzma-long 序列推荐中，用户的交互商品序列长度就是该用户交互的商品数，可以通过参数 `user_inter_num_interval (str)` 过滤掉交互过少的用户，详细信息可以参考[文档](https://recbole.io/docs/user_guide/config/data_settings.html)的数据设置部分。
