### ISSUE TITLE
Plotting training metrics on Weights and Biases platform

### ISSUE THREAD

**Issue by Vaibhav-2022** [RUCAIBox/RecBole#1198]
Hello,
I am trying to plot my training metrics on Weights and Biases platform. I have referred to the [documentation](https://recbole.io/docs/user_guide/usage/use_weights_and_biases.html) but unable to plot the metrics. Can someone point me in right direction?. Thanks.

**Comment by Wicknight** [comment]
@Vaibhav-2022 Hello, thanks for your attention to RecBole!
I tested with BPR model and it worked normally. From your description I can't tell what happened during your experiment.  Could you please provide more detailed information?

**Comment by Vaibhav-2022** [comment]
Hi @Wicknight and @ayulockin. I have figured out the issue. Thanks for your prompt response.
