### ISSUE TITLE
Dissecting sequential_dataset.py and got an error Attribute Error: 'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by Jeriousman** [RUCAIBox/RecBole#1201]
I tried to understand how you are processing sequential data. So I was dissecting it. Then I faced the above error ```Error: 'DataFrame' object has no attribute 'sort'```

What I did is as following:

import argparse

from recbole.quick_start import run_recbole
import logging
from logging import getLogger
1. Getting config
```
import torch
import pickle
import recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation, save_split_dataloaders, load_split_dataloaders
from recbole.utils import init_logger, get_model, get_trainer, init_seed, set_color

parser = argparse.ArgumentParser()
parser.add_argument('--model', '-m', type=str, default='BERT4Rec', help='name of models')
parser.add_argument('--dataset', '-d', type=str, default='ml-100k', help='name of datasets')
parser.add_argument('--config_files', type=str, default=None, help='config files')


##for BERT4Rec
args, _ = parser.parse_known_args()
config_dict = {'neg_sampling' : None}
config_file_list = args.config_files.strip().split(' ') if args.config_files else None
config = Config(model='BERT4Rec', dataset='ml-100k', config_dict = config_dict)
```

2. Then instantiated SequentialDataset class by
```
seqdata = SequentialDataset(config)
seqdata._aug_presets()
seqdata.sort(by=[seqdata.uid_field, seqdata.time_field], ascending=True)
```

Then I got the error Error: 'DataFrame' object has no attribute 'sort'
is not SequentialDataset a DataFrame? If it is, sort is deprecated. How is it being used?

My ultimate goal is, how to proceed with this part without error here? Can you kindly provide me code for it?

**Comment by Sherry-XLL** [comment]
@Jeriousman Hello, thanks for your attention to RecBole. `SequentialDataset` is based on RecBole's `Dataset` class, and features are stored as `pandas.DataFrame` inside `recbole.data.dataset.Dataset`. In the standard process of sequential recommendation, function `_change_feat_format` will change feat format from `pandas.DataFrame` to `Interaction`, then perform data augmentation. In your code you didn't change the format type to `Interaction` in RecBole, so it reported an error. 

Actually, `sort` is a function in `Dataset`, which is used to sort the interaction records inplace as follows:
https://github.com/RUCAIBox/RecBole/blob/0679bb658788a7b738f7f675c352a83f715619b0/recbole/data/dataset/dataset.py#L1457-L1465

After `_change_feat_format`, the feat format of `self.inter_feat` is changed from `pandas.DataFrame` to `Interaction`. Therefore, the final `sort` function is actually in the `Interaction`, and it makes use of numpy's `argsort` function essentially:
https://github.com/RUCAIBox/RecBole/blob/0679bb658788a7b738f7f675c352a83f715619b0/recbole/data/interaction.py#L299-L337

If you want to understand how the sequential data is processed, it is important to understand the logical order of the running of program. For example, by calling method `Dataset.build()`, it will processing dataset into DataLoaders, and the first thing is to change the feat format. Don't skip some necessary processing operations, and you can get the correct results.

**Comment by Jeriousman** [comment]
Thank you for your very dedicated feedback. I appreciate it a lot! Happy dissecting
