### ISSUE TITLE
[🐛BUG]I followed your blog to run the sequence recommendation, but there was an error

### ISSUE THREAD

**Issue by a514131** [RUCAIBox/RecBole#1208]
I followed your blog to run the sequence recommendation, but there was an error

ValueError: neg_sampling [{'uniform': 1}] should be None when the loss_type is CE.

**Comment by chenyuwuxin** [comment]
@a514131 Hello, thanks for your attention to RecBole!
The type of loss function. If it set to 'CE', the training task is regarded as a multi-classification task and the target item is the ground truth. In this way, negative sampling is not needed. If it set to 'BPR', the training task will be optimized in the pair-wise way, which maximize the difference between positive item and negative item. In this way, negative sampling is necessary, such as setting --neg_sampling="{'uniform': 1}". Defaults to 'CE'. Range in ['BPR', 'CE']. 
i.e. if you use 'CE' loss, please set `neg_sampling: ~` in your config file.
You can see this in the documentation of the sequence model you are running such as [GRU4RecKG](https://recbole.io/docs/user_guide/model/sequential/gru4reckg.html).

**Comment by a514131** [comment]
Thank you for your answer, but I have encountered new problems again. Keyerror: 'precision' appears when running gru4rec, and keyerror: 'class' appears when running gru4recf

> @a514131您好，感谢您对 RecBole 的关注！ 损失函数的类型。如果设置为'CE'，则训练任务被视为多分类任务，目标项目是ground truth。这样就不需要负采样了。如果设置为“BPR”，训练任务将以成对的方式进行优化，最大化正项和负项之间的差异。这种方式需要负采样，比如设置--neg_sampling="{'uniform': 1}"。默认为“CE”。['BPR', 'CE'] 中的范围。 即如果你使用'CE'损失，请`neg_sampling: ~`在你的配置文件中设置。 您可以在您正在运行的序列模型的文档中看到这一点，例如[GRU4RecKG](https://recbole.io/docs/user_guide/model/sequential/gru4reckg.html)。

**Comment by chenyuwuxin** [comment]
@a514131 Hello, this is an error from the configuration file. Please set the `selected_features` field in your yaml file to indicate the characteristics of the selected item.

**Comment by a514131** [comment]
> @a514131 Hello, this is an error from the configuration file. Please set the `selected_features` field in your yaml file to indicate the characteristics of the selected item.

感谢您的解答，但是我还是没有成功找到 selected_features 配置字段在哪里，阅读过了API文档没有找到，可以解答一下吗

**Comment by chenyuwuxin** [comment]
@a514131 你好，`selected_features`是FDSA，GRU4RecF以及SASRecF模型需要设置的字段。你可以在`recbole/properties/model/`目录下的模型默认配置文件中找到。此外，如果你需要改变这个字段，只需要在你提供的配置文件中设置即可，因为用户提供的配置文件可以覆盖掉默认配置。
