### ISSUE TITLE
BPR get header of datasets as input

### ISSUE THREAD

**Issue by rezash121** [RUCAIBox/RecBole#1210]
As I checked in the Movielens-100k dataset, the number of items is 1682. However, your built-in dataset shows there are 1683 items.
I checked the ml-100k.item, and I think your code gets the first line (header) as input.
Would you please check it?

**Comment by 2017pxy** [comment]
Hi @rezash121, it's not a bug. RecBole will correctly deal with the header (You can check our code in  [dataset.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataset/dataset.py)). As for the number of items, in RecBole, we will add an extra item as the padding item and set the `0` as padding item ID, so the item number shows in logs  is one more than the real number.  

BTW, padding item has no impact on the model training and evaluation, and you can read more detail in our [Docs](https://recbole.io/docs/recbole/recbole.data.dataset.dataset.html?highlight=padding).

**Comment by rezash121** [comment]
Thank you so much.
