### ISSUE TITLE
[🐛BUG] 使用超参失败

### ISSUE THREAD

**Issue by shishanya** [RUCAIBox/RecBole#1222]
**描述这个 bug**
lightgcn使用超参报错

**如何复现**
复现这个 bug 的步骤：
1. 
![4e23f8ccdd0dc29c1b291cae99ba5f0](https://user-images.githubusercontent.com/95926906/161064884-1a7194d7-129c-4d93-adba-5b0196ecd5ee.png)

2. 
![1865a01e0b53f650340109c4fbd970b](https://user-images.githubusercontent.com/95926906/161064963-a8cbf4b0-7c3e-449f-8d06-589e2228bca5.png)

3. 
![17232044ffeeda61fa04aad74663080](https://user-images.githubusercontent.com/95926906/161065061-2b9ae22e-c09c-4d90-b645-c851e3f765ef.png)
![7c5faf502543267f539e39403a25246](https://user-images.githubusercontent.com/95926906/161065160-f933006e-8af2-49c6-b0f0-1b83077f6dbf.png)

**预期**
希望能帮忙解决bug

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [如 0.1.0]
 - Python 版本 [如 3.79]
- PyTorch 版本 [如 1.60]
- cudatoolkit 版本 [如 9.2, none]

**Comment by Wicknight** [comment]
@shishanya 
您好！请问您提到的超参报错是指截图中的“UserWarning”吗？如果是指这个warning的话，可以按照命令行中提示的一样，将i=torch.LongTensor([row, col])修改为i=torch.LongTensor(np.array([row, col]))

**Comment by shishanya** [comment]
@Wicknight 
您好，我这边按您的方法改了之后不再报bug了，但运行程序会出现进度条卡住不动了

`PS C:\Users\gongshishan\Desktop\capsuleGNN\RecBole> python .\run_hyper.py --dataset=ml-1m --model=LightGCN
running parameters:
{'alpha': 0.75, 'lambda1': 0.1, 'lambda2': 50}
  0%|                                                                                                                                                            | 0/64 [00:00<?, ?trial/s, best loss=?]
`

**Comment by Wicknight** [comment]
@shishanya 
推荐您先使用较小的数据集，如--dataset=ml-100k，来测试一下这是否是程序的问题。另外您可以先使用 python run_recbole.py --dataset=ml-1m --model=LightGCN --config_files=LightGCN.yaml 观察模型在一组参数下的运行时间来预估超参数微调的时间。

**Comment by shishanya** [comment]
@Wicknight 好的谢谢你的建议大佬！

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
