### ISSUE TITLE
KGAT数据处理问题

### ISSUE THREAD

**Issue by flyking1994** [RUCAIBox/RecBole#1230]
与KGAT原代码两处不同：
（1）只将U-Igraph转成无向图，保持KG为有向图（kg_dataset.py 363-364,393-394 ）。源代码都处理成无向图(下18,21,27,30)

（2）无向图的关系没有进行处理，保持r(u,i)=r(i,u)（kg_dataset.py 369-371,400-402）。源代码中并非如此(下19,22,28,31)。

1.         def _np_mat2sp_adj(np_mat, row_pre, col_pre):
2.             n_all = self.n_users + self.n_entities
3.             # single-direction
4.             a_rows = np_mat[:, 0] + row_pre
5.             a_cols = np_mat[:, 1] + col_pre
6.             a_vals = [1.] * len(a_rows)
7. 
8.             b_rows = a_cols
9.             b_cols = a_rows
10.             b_vals = [1.] * len(b_rows)
11. 
12.             a_adj = sp.coo_matrix((a_vals, (a_rows, a_cols)), shape=(n_all, n_all))
13.             b_adj = sp.coo_matrix((b_vals, (b_rows, b_cols)), shape=(n_all, n_all))
14. 
15.             return a_adj, b_adj
16. 
17.         R, R_inv = _np_mat2sp_adj(self.train_data, row_pre=0, col_pre=self.n_users)
18.         adj_mat_list.append(R)
19.         adj_r_list.append(0)
20. 
21.         adj_mat_list.append(R_inv)
22.         adj_r_list.append(self.n_relations + 1)
23.         print('\tconvert ratings into adj mat done.')
24. 
25.         for r_id in self.relation_dict.keys():
26.             K, K_inv = _np_mat2sp_adj(np.array(self.relation_dict[r_id]), row_pre=self.n_users, col_pre=self.n_users)
27.             adj_mat_list.append(K)
28.             adj_r_list.append(r_id + 1)
29. 
30.             adj_mat_list.append(K_inv)
31.             adj_r_list.append(r_id + 2 + self.n_relations)
32.         print('\tconvert %d relational triples into adj mat done. @%.4fs' %(len(adj_mat_list), time()-t1))
33. 
34.         self.n_relations = len(adj_r_list)
35.         # print('\tadj relation list is', adj_r_list)
36. 
37.         return adj_mat_list, , adj_r_list

**Comment by flyking1994** [comment]
是这个问题有啥问题吗～～～

**Comment by Wicknight** [comment]
@flyking1994 
我们已经注意到这个问题了，正在检查，感谢反馈

**Comment by ShanleiMu** [comment]
@flyking1994 
（1）对于KG图的构建与KGAT原文不同，是因为现有的知识图谱结合推荐的数据集合自身存在大量的对称关系（例如通过KB4Rec构建得到的推荐数据集），KGAT原文构建的方式会导致信息重复和冗余。例如数据集中的三元组为<h1,r1,t1>, <t1,r2,h1>，其中r1, r2是对称关系，KGAT原文构建的初衷是把这种对称关系也建模进去，但数据集本身已经显示的表示出这种对称关系，因此我们这里没有再进行处理。
（2）感谢指出，这里确实和原文不同，实现时为了复用这个方法，所以没有对U-I图的构建进行额外处理。我们会对这里进行改正。但根据我们的经验，这里不会对性能产生太多的影响。修复后我们在此进行反馈。

**Comment by flyking1994** [comment]
@ShanleiMu 谢谢你的回复。确实影响没有很大。我关注到这里是因为KGAT的实验结果不好，这让我比较困扰～～～

在ml-100k上，我似乎使用KGCN（0.3181）和KGAT（0.3204）都难以得到出较好的结果（要明显差于NGCF（0.3342），LightGCN（0.3381）, SGL（0.3438）等，甚至低于BRPMF（0.3253））（我暂时只使用了这个数据集）。我设置的train， val, test比例为7:1:2，earlystop为10（针对recall@20），seed设置为2022，括号中为recall@20的值。此外使用LightGCN在KG+UI的协同图上实验结果也不好。希望有人能在这里交流这个问题（看看是本来如此还是我哪里搞错了）～～～

**Comment by flyking1994** [comment]
@ShanleiMu 非常感谢你的回复！
