### ISSUE TITLE
Providing legit full tutorials for models.

### ISSUE THREAD

**Issue by Jeriousman** [RUCAIBox/RecBole#1232]
**I think providing full legit tutorials for general/sequential/KG/context-aware models could be crucial to users and recbole's popularity.**

It is nice to start with quick_start you provide. But as it is just how to run the code working, there is no science behind it for actual performence. If you make one of common models (say, one model per each category general/sequential/KG/context-aware) with whole legit process with explanation, a lot of people would use Recbole much easier. Just running examples are nothing but hollow shells. If your legit end-to-end (from processing data to training and evaluating) legit tutorials actually really reproduce papers' performance, it would be the best as we can see it is actually working as told and it is legit to use recbole for sure.

**Comment by 2017pxy** [comment]
@Jeriousman Thanks for your advice, and we will consider it carefully.
