### ISSUE TITLE
[🐛BUG]处理Electronics_5数据，将其转化为原子文件是报错

### ISSUE THREAD

**Issue by yztian1997** [RUCAIBox/RecBole#1233]
**描述这个 bug**
处理Electronics_5数据，将其转化为原子文件是报错

复现这个 bug 的步骤：
![image](https://user-images.githubusercontent.com/97169405/161882319-499445d8-d59a-490b-8a54-2c258feb2718.png)
python run.py --dataset Amazon_Electronics \
--input_path Amazon_Electronics --output_path output_data/Amazon_Electronics \
--convert_inter --convert_item

报错：
Traceback (most recent call last):
File "run.py", line 42, in
datasets.convert_item()
File "D:\大数据与人工智能\lightgcn\RecSysDatasets-master\conversion_tools\src\extended_dataset.py", line 3948, in convert_item
input_item_data = self.load_item_data()
File "D:\大数据与人工智能\lightgcn\RecSysDatasets-master\conversion_tools\src\extended_dataset.py", line 3919, in load_item_data
finished_data = origin_data.drop(columns=['salesRank', 'categories'])
File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\frame.py", line 4308, in drop
return super().drop(
File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\generic.py", line 4153, in drop
obj = obj._drop_axis(labels, axis, level=level, errors=errors)
File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\generic.py", line 4188, in _drop_axis
new_axis = axis.drop(labels, errors=errors)
File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\pandas\core\indexes\base.py", line 5592, in drop
raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['salesRank' 'categories'] not found in axis"

**预期**
将Electronics_5.json和ratings_Electronics.csv转化为原子文件

**Comment by hyp1231** [comment]
如我们在 [RecSysDatasets - usage - Amazon](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/Amazon.md) 中所说：

> However, we're sorry for the metadata before 2014 we used can't be downloaded from the website now. We will continue with the assumption that the operator already has the original metadata. If you don't have the original metadata, you can download processed data from  [Baidu Yun](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g) or [Google Drive](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing).

推测您使用的 metadata 并不是 2014 版本的，因此会出现上述问题。

**Comment by yztian1997** [comment]
> 如我们在 [RecSysDatasets - usage - Amazon](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/Amazon.md) 中所说：
> 
> > However, we're sorry for the metadata before 2014 we used can't be downloaded from the website now. We will continue with the assumption that the operator already has the original metadata. If you don't have the original metadata, you can download processed data from  [Baidu Yun](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g) or [Google Drive](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing).
> 
> 推测您使用的 metadata 并不是 2014 版本的，因此会出现上述问题。

百度云上没有带评论的Amazon_Electronics数据集

**Comment by hyp1231** [comment]
我们未处理过带评论的该数据集

**Comment by hyp1231** [comment]
由于超过 5 天没有新回复，先关闭 issue 了。如果还有疑问，欢迎随时评论。
