### ISSUE TITLE
How to change loss_type for predicting embedding?

### ISSUE THREAD

**Issue by gongtigigi** [RUCAIBox/RecBole#1235]
Hello
I want to predict embedding and find similar item with that embedding.
But RecBole seems to support CE and BPR loss only.
Do I have to make new loss type with prediction part and valid metric???

**Comment by leoleojie** [comment]
@gongtigigi Thanks for your attention for RecBole! 
Could you please provide more detailed information, such as what model to use, what is the meaning of predicting embedding, what task would you like to do?  And I think valid metric depends on the task you want to do, not the loss to use.

**Comment by gongtigigi** [comment]
Hmm.. I have to study paper more.
After study, I will ask question 
Would you please erase this issue??
