### ISSUE TITLE
dynamic negative sampling问题

### ISSUE THREAD

**Issue by Jiangrijin** [RUCAIBox/RecBole#1237]
你好，我在 recbole/data/dataloader/abstract_dataloader.py 文件里找到了动态负采样相关的代码，请问策略是选出负样本中分数最高的吗？

**Comment by Sherry-XLL** [comment]
@Jiangrijin 

对于隐式反馈来说数据没有明确的标签，为了进行模型训练，一般从用户未交互商品集中进行负例的选择，即负采样。

在模型训练过程中，负例能够带给模型的信息量会随着模型的训练情况不断变化。动态负采样的思路是使用当前模型对用户未交互过的商品进行打分，然后选择分数更高的样例作为负例对当前模型进行训练。

然而，动态负采样的策略并不是从所有未交互商品中选择模型给分最高的样例，而是先随机从未交互商品集中采样若干个候选负例并进行打分，从这几个候选负例中选择分数最高的样例作为训练时的负例。先随机采样的目的一是考虑效率，二是为了缓解伪负例的问题。换句话说，如果每次采样都选择分数最高的负样本，那么此时的负例更有可能是未来的正例，反而会降低训练的质量。

在 RecBole 的实现中，参数 `neg_sampling (dict)` 控制模型训练时的负采样策略及方式。此参数的默认值为 `{'uniform'：1}`，意味着为每个正例随机采样一个负例。在动态负采样时，`dynamic` 决定了候选负例的数量。例如，`{'uniform'：1，'dynamic'：2}` 意味着为每个正例随机采 2 个负例，并动态地选择得分较高的样例作为负例。这里的 `'uniform'：1` 表示一个正例匹配一个负例，`'dynamic'：2` 表示从两个候选负例中进行负例选择。

每个正例匹配的负例数量越多，候选负例集的数量越大，相应的动态负采样的强度也越大，需要针对不同的模型和数据集进行调整才能得到最优的参数配置。

**Comment by Jiangrijin** [comment]
好的，非常感谢！
