### ISSUE TITLE
word2vec vector as a column feature in atomic file.

### ISSUE THREAD

**Issue by Yoloniverse** [RUCAIBox/RecBole#1238]
I am trying to make my own data which has a column with 300 dimension of word2vec vector included. Should I make this column in atomic file with float_seq type? Will it be processed as is? Because it is not meant to do any sequence calculation but just 300 dim vector. But I see that it might be not suitable the other data types you provide. So I am asking here.

Should I make it as float_seq in atomic file and it wont be processed as sequence? Below is an item's word feature (vector) for example.
![스크린샷, 2022-04-07 09-29-34](https://user-images.githubusercontent.com/89169051/162096750-54bdbcf7-2e76-4ea1-bdc3-1ebb6baf24f9.png)

Extra question. Can I make atomic file with pandas dataframe csv file? If I do so and it is okay, I guess I should set config to separator as , not \t?

Sorry I added it to bug label by mistake

**Comment by Wicknight** [comment]
@Yoloniverse 
Hello, thanks for your attention to RecBole!
It should be loaded with float_seq type. Actually, I'm a little confused about what you're worried about. We will not do any sequence calculation in the process. If you want to load pre-trained embedding here, you can refer to our document [here](https://recbole.io/docs/user_guide/usage/load_pretrained_embedding.html). And it will be transfered into class: 'numpy.ndarray' finally.

**Comment by Yoloniverse** [comment]
Thank you for the answer!
