### ISSUE TITLE
[🐛BUG] GCMC Hyper_tuning 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

### ISSUE THREAD

**Issue by GitHub-ZHY** [RUCAIBox/RecBole#1240]
**描述这个 bug**
GCMC Hyper_tuning 代码不通，总是有不同的模型会在Hp时报这个Bug，rng.integers(low, high, size) no intergers。

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
- gcmc.yaml
embedding_size: 64
sparse_feature: True
class_num: 2
learner: adam
weight_decay: 0.995
train_batch_size: 4096
eval_batch_size: 40960000
metrics: ["Recall","NDCG","Hit","Precision","MRR"]
topk: [ 1,2,5,10,20,40,50,60,80,100 ]
valid_metric: Recall@20

- hyper.gcmc
learning_rate choice [0.01]
dropout_prob choice [0.3,0.4,0.5,0.6,0.7,0.8]
accum choice ['stack','sum']
gcn_output_dim choice [256,500,1024]
num_basis_functions choice ['2']

3. 您的代码

4. 您的运行脚本
--model=GCMC --config_files=GCMC.yaml --dataset='ml-1m' --config_files=GCMC.yaml --params_file=hyper.gcmc --output_file=hyper_gcmc_ml1m.result

**预期**
通。

**屏幕截图**
Connected to pydev debugger (build 211.6693.115)
================================================================================
ERROR in rec_eval
EXCEPTION
<class 'AttributeError'>
'numpy.random.mtrand.RandomState' object has no attribute 'integers'
NODE
0 randint
1   Literal{1}
2  size =
3   len
4     array_union
5       array_union
6         array_union
7           Literal{new_ids}
8  rng =
9   Literal{rng-placeholder}
================================================================================
  0%|                                    | 0/36 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "/home//anaconda3/envs//lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home//anaconda3/envs//lib/python3.8/site-packages/hyperopt/progress.py", line 25, in tqdm_progress_callback
    yield pbar
  File "/home//anaconda3/envs//lib/python3.8/site-packages/hyperopt/fmin.py", line 278, in run
    new_trials = algo(
  File "/home///RecBole/recbole/trainer/hyper_tuning.py", line 110, in exhaustive_search
    idxs, vals = pyll.rec_eval(domain.s_idxs_vals, memo={
  File "/home//anaconda3/envs//lib/python3.8/site-packages/hyperopt/pyll/base.py", line 902, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/home//anaconda3/envs//lib/python3.8/site-packages/hyperopt/pyll/stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

Process finished with exit code 1

**链接**
None

**实验环境（请补全下列信息）：**
- 操作系统: [Windows]
- RecBole 版本 [0.1.0]
- Python 版本 [3.8]
- PyTorch 版本 [如 1.8.1]
- cudatoolkit 版本 [11.4]

**Comment by chenyuwuxin** [comment]
@GitHub-ZHY 您好，感谢您的关注！
我们在[#1192](https://github.com/RUCAIBox/RecBole/pull/1192)中修复了这个bug，请使用最新源码重新安装RecBole。

**Comment by GitHub-ZHY** [comment]
@chenyuwuxin 您好，我已经使用了最新的RecBole，#1192也是我提的Issue，好像问题并不出现在此，目前我仍在debug，烦请您再看下。

**Comment by chenyuwuxin** [comment]
你可以参考 #1181的解决方案




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/RecBole"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/RecBole] [🐛BUG] GCMC Hyper_tuning 'numpy.random.mtrand.RandomState' object has no attribute 'integers' (Issue #1240)





 
@chenyuwuxin 您好，我已经使用了最新的RecBole，#1192也是我提的Issue，好像问题并不出现在此，目前我仍在debug，烦请您再看下。

**Comment by GitHub-ZHY** [comment]
@chenyuwuxin 配置文件如下：# general
gpu_id: 0
use_gpu: True
seed: 2022
state: INFO
reproducibility: True
#data_path: 'dataset/ml-1m'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
dataset_save_path: None
save_dataloaders: False
dataloaders_save_path: None
log_wandb: False
wandb_project: 'recbole'

# training settings
epochs: 300
train_batch_size: 4096
learner: adam
learning_rate: 0.01
neg_sampling:
  uniform: 1
eval_step: 1
stopping_step: 10
#clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.995
loss_decimal_place: 4
require_pow: False

# evaluation settings
eval_args:
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
repeatable: False
metrics: ["Recall","NDCG","Hit","Precision","MRR"]
topk: [ 1,2,5,10,20,40,50,60,80,100 ]
valid_metric: Recall@20
valid_metric_bigger: True
eval_batch_size: 40960000
metric_decimal_place: 4

# Other Hyper Parameters:
#accum: stack
embedding_size: 64
sparse_feature: True
class_num: 2
dropout_prob: 0.3
gcn_output_dim: 256
num_basis_functions: 2

**Comment by chenyuwuxin** [comment]
@GitHub-ZHY 可能是配置出现了问题，general 类模型在ml-1m数据集运行的示例配置文件为：
```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
val_interval:
    rating: "[3,inf)"    
unused_col: 
    inter: [rating]

# training and evaluation
epochs: 500
train_batch_size: 4096
valid_metric: MRR@10

# model
embedding_size: 64
```

**Comment by wuxinran-Angel** [comment]
> @GitHub-ZHY 您好，感谢您的关注！ 我们在[#1192](https://github.com/RUCAIBox/RecBole/pull/1192)中修复了这个bug，请使用最新源码重新安装RecBole。

您好 我在使用最新源码后 出现了和上述同样的问题；但使用之前的版本不会出现bug；

## config
# environment setting
show_progress: False

# dataset settings
dataset: 'yoochoose-sample'
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: 'session_id'
load_col: 
unused_col:
  inter: [timestamp]

# training settings
epochs: 300
train_batch_size: 4096
neg_sampling: 

# evaluation settings
eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  # split: {'LS': 'valid_and_test'}
  order: 'TO'
  mode: 'full'
  group_by: 'none'
metrics: ['MRR', 'Recall']
topk: [20]
valid_metric: 'MRR@20'
stopping_step: 10

# model config
model: 'GRU4Rec'
embedding_size: 64

**Comment by chenyuwuxin** [comment]
@wuxinran-Angel 您好，这个问题是由于hyperopt包的版本与numpy不匹配，而与RecBole的版本无关，如果出现冲突，请尝试降低hyperopt的版本(例如降低到0.2.5)。

**Comment by wuxinran-Angel** [comment]
谢谢您的回复
我昨天尝试了这个问题 还没有来得及在github上回复。
我之前采用了hyperopt 0.2.7版本（用pip安装recbole 1.1可以正常运行）；现在下降到0.2.5版本（用git clone最新的包可以运行）。
谢谢您的解答

吴忻冉


------------------ Original ------------------
From: Tian Zhen ***@***.***&gt;
Date: Tue,Apr 12,2022 8:55 AM
To: RUCAIBox/RecBole ***@***.***&gt;
Cc: Xinran Wu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [RUCAIBox/RecBole] [��BUG] GCMC Hyper_tuning 'numpy.random.mtrand.RandomState' object has no attribute 'integers' (Issue #1240)
