### ISSUE TITLE
FM模型跑不通

### ISSUE THREAD

**Issue by shishanya** [RUCAIBox/RecBole#1242]
**描述这个 bug**
您好，我的代码在评估时出错，不知道是什么原因？

![8c741142dab703a771af9227fbb58d2](https://user-images.githubusercontent.com/95926906/162563203-627c1529-1585-460f-b41f-e1c97f3bf56d.png)
![516174af378e53122d8295155c6be13](https://user-images.githubusercontent.com/95926906/162563210-7307e16c-af67-4a01-a71a-e934ebe681b3.png)
![4651d2c3632cf37eea2c112ae67c89d](https://user-images.githubusercontent.com/95926906/162563216-86caf5d0-28f0-4c14-b651-2630117a9adb.png)

**实验环境（请补全下列信息）：**
 - 操作系统: Windows10
- RecBole 版本 [如 0.1.0]
 - Python 版本 [如 3.79]
- PyTorch 版本 [如 1.60]
- cudatoolkit 版本 [如 9.2, none]

**Comment by Wicknight** [comment]
@shishanya 您好！感谢您的关注！
一般来说我们应用context-aware recommendation模型来做CTR预测，因此您的评测方式选用了'labeled',  但同时评价指标也应改为'AUC','LogLoss'等value-based的指标，而不是使用Ranking-based的评价指标。这里提供如下参考：
```
metrics: ['AUC', 'LogLoss']
valid_metric: AUC

eval_args:
group_by: ~
order: TO
split: {'RS': [0.8,0.1,0.1]}
mode: labeled
```

**Comment by shishanya** [comment]
@Wicknight 您好，我想请问FM里评测能使用Ranking-based的指标评测吗？具体配置文件该怎么写呢？

**Comment by Wicknight** [comment]
@shishanya RecBole 支持通过与一般推荐模型一样的完整排名 (full sort) 来评估 context-aware 推荐模型，但此时需要确保 .inter 文件不能加载任何其他上下文信息列，这种情况下模型可以用 Recall 等 ranking-based evaluation metrics 作为评测指标。您可以参考我们的文档中有关Context-aware Recommendation模型[参数设置部分](https://recbole.io/docs/user_guide/usage/running_different_models.html?highlight=note%20recbole%20also%20support#context-aware-recommendation)的说明。

**Comment by shishanya** [comment]
@Wicknight 好的，谢谢您的解答，辛苦！

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
