### ISSUE TITLE
请问这几种数据集以及模型划分的区别是什么？

### ISSUE THREAD

**Issue by superjdz** [RUCAIBox/RecBole#1244]
模型被分为general,contex-aware,sequential以及knowledge-based.
请问这样划分的情况下模型和数据集划分的区别是什么？有没有相关资料可以提供一下？
期待您的回答

**Comment by 2017pxy** [comment]
@superjdz 你好，我们的模型主要按照输入数据来进行划分，详情请参考[模型文档](https://recbole.io/docs/user_guide/model_intro.html).

关于数据集划分，是指我们如何将数据集划分成：训练集，验证集和测试集，详情请参考[eval_args的介绍](https://recbole.io/docs/user_guide/config/evaluation_settings.html).
