### ISSUE TITLE
有没有NFM的配置文件

### ISSUE THREAD

**Issue by yztian1997** [RUCAIBox/RecBole#1245]
哪位有NFM的配置文件，可以麻烦发一下吗，谢谢

**Comment by 2017pxy** [comment]
@yztian1997 你好，伯乐会按照ml-100k为每个模型设置默认参数，用户可以直接执行：
```
python run_recbole.py --model=MODEL_NAME
```
来按照默认参数在ml-100k上训练和评测所选的模型。

但不同数据集的配置文件是不同的，而且对于用户不同的训练，评测需求，也要调整相应参数的设置。因此，我们无法给出一个通用的配置文件。你可以参考我们内置的默认配置文件：[overall.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/overall.yaml), [NFM.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/model/NFM.yaml)等文件来设置你自己的配置。

在设置配置前，强烈建议你先仔细阅读我们的[使用文档](https://recbole.io/docs/)。谢谢！
