### ISSUE TITLE
[🐛BUG] SR-GNN和GC-SAN配置文件问题

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1246]
你好，对于SR-GNN和GC-SAN模型有以下几个问题：
Q1.问一下SR-GNN和GC-SAN模型在yoochoose和diginetica数据集上的配置文件可以发一下吗
Q2.这两个数据集要使用的话是下载百度网盘里的哪一个呢，merged和not-merged区别是什么..
谢谢啦

**Comment by hyp1231** [comment]
你好，

A1. 请参考 [results on diginetica](https://github.com/RUCAIBox/RecBole-GNN/blob/main/results/sequential/diginetica.md)。
A2. merged 指合并同一用户/session 对某 item 的重复点击，not-merged 反之。建议序列化推荐用 not-merged，一般序列化推荐不去重的。

**Comment by DX12321** [comment]
好的，谢谢啦，官方下载的那个数据集是 not-merged 的吧

**Comment by hyp1231** [comment]
> 好的，谢谢啦，官方下载的那个数据集是 not-merged 的吧

如果用 RecBole 的自动下载功能，需要标注清楚是否为 merged，比如可以 `--dataset=diginetica-not-merged`，就是下载我们处理好的 not-merged 数据

**Comment by hyp1231** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
