### ISSUE TITLE
请问如何获得所有用户-项目对的推荐打分和性能评估

### ISSUE THREAD

**Issue by zengxinran** [RUCAIBox/RecBole#1247]
recbole库很好的帮我实现了一些推荐器，但是我无法解决以下问题：
1.full_sort_scores中需要输入uid_series，如何可以获得所有的test数据的用户id呢？
2.我的实验需要使用所有用户-项目对的性能评估，而不是推荐器整个的性能评估，请问怎样可以获得呢？

**Comment by hyp1231** [comment]
你好，
1. 其实 RecBole 在 full_sort_scores 中输入的是全部用户的 id。不过如果您是想问 test 数据中有交互的用户的 id，可以在 run_recbole.py 中，调用 `test_data.dataset.inter_feat[config['USER_ID_FIELD']]` 来查看。
2. 或许您指的是 case study 功能，可以参考 [case_study_example](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py)。

**Comment by zengxinran** [comment]
你好，我的第二个问题是怎么可以求得所有用户-项目对的例如NDCG等指标的值，在文档中我只看到了求整个模型的NDCG等指标

**Comment by hyp1231** [comment]
首先 NDCG 这类指标是对列表的排序指标，没办法对于具体的 user-item pair 计算。

那如果想拿到具体某个 user 的排序列表的 NDCG 这类指标，可以在这个位置

https://github.com/RUCAIBox/RecBole/blob/896155c56fb2f426554d1179dae85dc0a8f4a38e/recbole/evaluator/metrics.py#L182

保存 result（也就是对 user 平均之前的指标数值），进而进一步分析。

**Comment by zengxinran** [comment]
使用trainer.fit训练的模型可以不保存直接使用于full_sort_scores吗？怎么使用？

**Comment by zengxinran** [comment]
那full_sort_scores的到的结果的行列对应的分别是输入的uid和itemid吗？itemid是按照大小顺序来的吗?

**Comment by hyp1231** [comment]
> 那full_sort_scores的到的结果的行列对应的分别是输入的uid和itemid吗？itemid是按照大小顺序来的吗?

行列是按照 remap ID 操作后的 user/item id 排列的，因为原始的 user/item id 输入可能是各种各样的字符串，所以 RecBole 会先进行 remap ID，将原始的字符串映射到从 0 开始的整数 id 上。因此可以通过调用 `dataset.token2id` 这个函数来从原始的字符串 ID，获取 remap 后的整数 ID。

**Comment by zengxinran** [comment]
好的，非常感谢您的帮助

**Comment by hyp1231** [comment]
> [RecBole/recbole/evaluator/metrics.py](https://github.com/RUCAIBox/RecBole/blob/896155c56fb2f426554d1179dae85dc0a8f4a38e/recbole/evaluator/metrics.py#L182) result = self.metric_info(pos_index, pos_len) 为什么result的大小为行数为user数(可以理解)，但是列数为20，这里的20是？（我用的top20）

假设这个指标是 NDCG，`result[i][j]` 代表用户 `i` 的 NDCG@j 指标。

**Comment by hyp1231** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
