### ISSUE TITLE
请问学习的trainer如何直接使用？

### ISSUE THREAD

**Issue by zengxinran** [RUCAIBox/RecBole#1248]
您好，recbole很便捷，但是我有一些困惑：
1.使用fit拟合了trainer，他可以保存过后在访问模型，有直接访问模型的方法将其使用在full_sort_scores中吗？
2.获得的full_sort_scores怎么样可以将它和原始id编号保存为csv格式
望解惑，谢谢！

**Comment by hyp1231** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
