### ISSUE TITLE
请问怎么划分数据集？

### ISSUE THREAD

**Issue by zengxinran** [RUCAIBox/RecBole#1250]
您好，
split_ratio还是'eval_args': {'split': {'RS': [0.8, 0.1, 0.1]}用于划分数据集
split_ratio、eval_args这两个参数分别表示什么意思

**Comment by hyp1231** [comment]
您好，`split_ratio` 是旧版本参数，已经被废弃，现在统一使用 `eval_args` 来指定评测配置（划分、排序、分组、负样本），详见 [API Doc](https://recbole.io/docs/user_guide/config/evaluation_settings.html)。

**Comment by zengxinran** [comment]
你好，感谢您的解答
还有一个问题就是我使用ta-feng数据时有一列amount，我使用了隐式反馈数据，所以amount应该使用吗？
这样定义'RATING_FIELD': 'amount'是不是不太对
我的训练结果非常不好
recall@20 : 0.0548    ndcg@20 : 0.0279

**Comment by zengxinran** [comment]
还有就是如何可以获取构建的负例样本和原始dataset呢？

**Comment by zengxinran** [comment]
Train     5: 100%|██████████████████████████████████████████████████| 98/98
Evaluate   : 100%|███████████████████████████████████████████| 27637/27637
您好，这里的98和27637是什么意思呢？

**Comment by zengxinran** [comment]
为什么我划分数据后比例不对且数量变少了
![image](https://user-images.githubusercontent.com/99645407/163539690-23322275-fcc6-4167-9f94-19a0c18a94ef.png)
![image](https://user-images.githubusercontent.com/99645407/163539766-0380e2b8-363f-446d-aa9c-8f093a5a0e16.png)

**Comment by hyp1231** [comment]
> 你好，感谢您的解答 还有一个问题就是我使用ta-feng数据时有一列amount，我使用了隐式反馈数据，所以amount应该使用吗？ 这样定义'RATING_FIELD': 'amount'是不是不太对 我的训练结果非常不好 recall@20 : 0.0548 ndcg@20 : 0.0279 precision@20 : 0.0035

模型是？

**Comment by zengxinran** [comment]
BPR

**Comment by hyp1231** [comment]
> 还有就是如何可以获取构建的负例样本和原始dataset呢？

模型输入的 `interaction` 里面可以拿到负例；
原始 dataset 可以参考您项目文件夹中的 `dataset/` 文件夹

**Comment by zengxinran** [comment]
而且数据划分后只有122个训练例，而数据有247989行

**Comment by hyp1231** [comment]
> 为什么我划分数据后比例不对且数量变少了 ![image](https://user-images.githubusercontent.com/99645407/163539690-23322275-fcc6-4167-9f94-19a0c18a94ef.png) ![image](https://user-images.githubusercontent.com/99645407/163539766-0380e2b8-363f-446d-aa9c-8f093a5a0e16.png)

`dataset` 对应的 class 是 `recbole.data.dataset.Dataset`，调用 `__len__` 获得的是交互数据的行数；`train_data` 对应的 class 是 `DataLoader`，调用 `__len__` 获得的是 batch 的数量

**Comment by hyp1231** [comment]
> 而且数据划分后只有122个训练例，而数据有247989行

您可以 print 打印出来看一下

**Comment by zengxinran** [comment]
怎么打印呢

**Comment by hyp1231** [comment]
> 怎么打印呢

`print`

**Comment by zengxinran** [comment]
<recbole.data.dataloader.general_dataloader.TrainDataLoader object at 0x000002E0D938A0F0>

**Comment by zengxinran** [comment]
打印出来长这样

**Comment by zengxinran** [comment]
还有就是在使用dataset.token2id时，出现TypeError: The type of tokens [0] is not supported的错误

**Comment by hyp1231** [comment]
是的，您打印获得这样的结果，就知道这个 object 的 class 是 `recbole.data.dataloader.general_dataloader.TrainDataLoader`，因此就可以看到 `__len__` 的定义。

https://github.com/RUCAIBox/RecBole/blob/896155c56fb2f426554d1179dae85dc0a8f4a38e/recbole/data/dataloader/abstract_dataloader.py#L67-L68

然后就可以看到

https://github.com/RUCAIBox/RecBole/blob/896155c56fb2f426554d1179dae85dc0a8f4a38e/recbole/data/dataloader/general_dataloader.py#L55-L57

https://github.com/RUCAIBox/RecBole/blob/896155c56fb2f426554d1179dae85dc0a8f4a38e/recbole/data/dataloader/general_dataloader.py#L45

就可以了解到它输出的 122 不是您之前理解的“训练例”。

-----


> 还有就是在使用dataset.token2id时，出现TypeError: The type of tokens [0] is not supported的错误

找到 `dataset.token2id` 的定义在

https://github.com/RUCAIBox/RecBole/blob/5f2f8bb5eafe7ae67b03d75cdd7b04060c28f6e9/recbole/data/dataset/dataset.py#L1105-L1123

因此就可以知道 `tokens in self.field2token_id[field]` 给出了 `False`，所以可以打印一下 `self.field2token_id[field]`，就会发现为啥 `0` 不在里面了

**Comment by hyp1231** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
