### ISSUE TITLE
valid_metric参数设置

### ISSUE THREAD

**Issue by kuzma-long** [RUCAIBox/RecBole#1254]
valid_metric (str)
这个参数用于early_stop，想问下能否将这个参数类型改为list or str，接收多个评价指标作为valid metric，只要其中有一个指标继续在增长就将early_stop置0，现有的只能设置一个是否会导致模型效果不是最优？

**Comment by Wicknight** [comment]
@kuzma-long 您好！感谢您的建议！您提出的这种方法可以作为一种策略来用于early_stop, 但一般来说学术论文里都是选用某个单一指标作为标准，当指标不再提升时（一定轮次）提前停止。因此为了保证有依据可循，我们选择了学术论文中一般采用的这种策略。如果您觉得在这种策略下模型效果无法达到最优，您可以选择增大 stopping_step 的值，如果连续 30 轮或 50 轮一个具体的指标都没有提升，已经可以提前停止了。当然，您也可以在RecBole基础上进行修改，对您的这种策略进行试验，欢迎您进一步和我们讨论！

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
