### ISSUE TITLE
使用douban数据集跑BPR模型报错

### ISSUE THREAD

**Issue by Liaoyejia** [RUCAIBox/RecBole#1255]
用douban数据集跑BPR模型时，报错如下：
![image](https://user-images.githubusercontent.com/56429041/163748516-7d962d14-c699-4a9f-b6f5-bf5019522c47.png)

错误提示要设置 `user_inter_num_interval` 这个参数，该怎么设置呢？

**Comment by 2017pxy** [comment]
@Liaoyejia 关于`user_inter_num_interval`, 请参考我们的[docs](https://recbole.io/docs/user_guide/config/data_settings.html)
