### ISSUE TITLE
请问怎么获得userid？

### ISSUE THREAD

**Issue by zengxinran** [RUCAIBox/RecBole#1258]
for batch_idx, batched_data in enumerate(iter_data)循环中怎么可以求得userid呢?我的这个循环是每轮循环一个用户。

**Comment by Wicknight** [comment]
@zengxinran 您好！batched_data是Interaction类型，因此要获得userid需要先获得其对应的key, 您可以通过如下操作来获得userid：
```
USER_ID = config['USER_ID_FIELD']
for batch_idx, batched_data in enumerate(iter_data)：
    user = batched_data[USER_ID]
```

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
