### ISSUE TITLE
question: 请问一下您们对于ml1m这个数据集中训练集和测试集的划分

### ISSUE THREAD

**Issue by liguogongdegou** [RUCAIBox/RecBole#1259]
请问一下您们对于ml1m这个数据集中训练集和测试集的划分是怎么样的，我看一些开源代码对diginetica数据集的处理是在时间戳中后几天的数据设置为测试集，请问您们也是这样设置的吗

**Comment by liguogongdegou** [comment]
追问一下，您们对ml-1m这个数据集处理完之后大约有多大啊，谢谢谢谢

**Comment by leoleojie** [comment]
@liguogongdegou 您好，感谢您对伯乐的关注！
1、对于数据集划分问题，目前伯乐支持两种划分策略：按比例划分和留一法，并且支持在用户维度划分数据集。具体请参考[相关文档](https://recbole.io/docs/user_guide/config/evaluation_settings.html)。
2、我们给出了数据集的[相关信息](https://github.com/RUCAIBox/RecSysDatasets/tree/master/dataset_info/MovieLens)，并提供了[处理好的原子文件](https://recbole.io/dataset_list.html)，您可以下载查看。
