### ISSUE TITLE
关于训练集构造的问题

### ISSUE THREAD

**Issue by Light-lyy** [RUCAIBox/RecBole#1262]
假设训练数据内容如下，用户0与项目0、1、2交互，用户1与项目0、1交互，即总共有5条交互数据在训练集中。

对于训练集的构造，我的猜想是（0，0，\_），（0，1，\_），（0，2，\_），（1，0，\_），（1，1，\_）。
三元组的3个元素分别代表用户ID、正样本ID、负样本ID，下划线代表随机抽取的负样本。并且保证了训练集内不重不漏地包含了所有的交互数据。称为方法A

但在Lightgcn的源码（https://github.com/gusye1234/LightGCN-PyTorch/blob/master/code/utils.py#L72）
是这样实现的：
先确定了训练集条目数等于交互总数，即5，再从所有用户中可重复地抽取5个用户，比如[1，1，1，1，0]，再分别为每个被抽到的用户抽取一个正样本和一个负样本，比如正样本[0，0，1，0，2]。这样训练集就是：
（1，0，\_），（1，0，\_），（1，1，\_），（1，0，\_），（0，2，\_）。
显然，这样训练集很可能无法包含所有的交互数据，比如这个例子中用户0与项目0、1的交互就没存在于训练集中。称为方法B

我的问题是：
1.RecBole的实现是方法A还是方法B，还是其他方法？
2.我似乎无法理解方法B的合理性，但在实验中方法B却能得到比方法A更好的结果。你们对此有什么见解吗？

希望能得到你们的帮助

**Comment by Wicknight** [comment]
@Light-lyy 您好，感谢您对RecBole的关注！
1.RecBole的实现是方法A，我们会为每个正例抽取负例来进行训练，采样方法和采样比例都是可以通过参数进行设置的，您可以参考我们的[文档](https://recbole.io/docs/user_guide/config/training_settings.html)中的neg_sampling参数。
2.对于LightGCN源码中的方法B, 我认为他是为了一定程度上解决数据集中的长尾分布问题，即可能在交互数据中大部分正样本都是由极少数的user提供的，而他的这种方法可以通过采样在一定程度上解决这个问题。

**Comment by Light-lyy** [comment]
> @Light-lyy 您好，感谢您对RecBole的关注！ 1.RecBole的实现是方法A，我们会为每个正例抽取负例来进行训练，采样方法和采样比例都是可以通过参数进行设置的，您可以参考我们的[文档](https://recbole.io/docs/user_guide/config/training_settings.html)中的neg_sampling参数。 2.对于LightGCN源码中的方法B, 我认为他是为了一定程度上解决数据集中的长尾分布问题，即可能在交互数据中大部分正样本都是由极少数的user提供的，而他的这种方法可以通过采样在一定程度上解决这个问题。

感谢解答。另外还想问一下，RecBole的负采样是只在构造训练集的时候采样一次，以后每一代的训练都使用这个包含相同负样本的训练集？还是说每一代的训练都要为正例重新进行负采样？

**Comment by Light-lyy** [comment]
> > @Light-lyy 您好，感谢您对RecBole的关注！ 1.RecBole的实现是方法A，我们会为每个正例抽取负例来进行训练，采样方法和采样比例都是可以通过参数进行设置的，您可以参考我们的[文档](https://recbole.io/docs/user_guide/config/training_settings.html)中的neg_sampling参数。 2.对于LightGCN源码中的方法B, 我认为他是为了一定程度上解决数据集中的长尾分布问题，即可能在交互数据中大部分正样本都是由极少数的user提供的，而他的这种方法可以通过采样在一定程度上解决这个问题。
> 
> 感谢解答。另外还想问一下，RecBole的负采样是只在构造训练集的时候采样一次，以后每一代的训练都使用这个包含相同负样本的训练集？还是说每一代的训练都要为正例重新进行负采样？

通过阅读你们TrainDataLoader类的源码（https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataloader/general_dataloader.py#L62）
似乎这个Loader在给出每一个batch的数据时都要重新进行负采样，而不是只采样一次保存起来供以后使用。不知道理解得对不对

**Comment by Wicknight** [comment]
@Light-lyy 是的，我们在给出每一个batch的数据时都要重新进行负采样。
