### ISSUE TITLE
数据集MIND配置

### ISSUE THREAD

**Issue by EmmmmmBoom** [RUCAIBox/RecBole#1278]
​Dear recbole:
在使用recbole中遇到了问题，希望能够得到帮助。
1请问新闻数据集MIND怎么配置呢，样例中ml-100k是一个没有划分训练、测试集的数据集，然而MIND很大已经划分了训练、验证、测试集，我怎么在这个数据集上训练呢？
2我想在adressa数据集上也跑一下， 不会配置，，

**Comment by Wicknight** [comment]
@EmmmmmBoom 您好！感谢您对RecBole的关注！
1.对于划分训练、验证、测试集的数据集，RecBole通过benchmark_filename参数进行设置，此时eval_args中的split参数不起作用，详情您可以通过阅读我们的[官方文档](https://recbole.io/docs/user_guide/config/data_settings.html#benchmark-file)进行了解。
2.数据集的配置可以根据您的使用目的和使用模型而改变，我们在recbole/properties/dataset中提供了sample.yaml作为一个一般的配置范例以供参考，同时建议您对照着阅读RecBole文档中介绍[数据集设置](https://recbole.io/docs/user_guide/config/data_settings.html)的部分。然后根据您的需要，在sample.yaml的基础上进行修改得到符合您要求的配置。

**Comment by EmmmmmBoom** [comment]
> benchmark_filename参数进行设置，此时ev

mind 的文件中是没有test的吗，只有train和dev

**Comment by Wicknight** [comment]
@EmmmmmBoom 是的，由于MIND官网提供的测试集没有提供标签，RecBole这里没有提供官网测试集。

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
