### ISSUE TITLE
当我想设置评价指标为['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']时，出错

### ISSUE THREAD

**Issue by czkyx** [RUCAIBox/RecBole#1284]
`07 May 14:27    INFO  
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = dataset/Amazon_Office_Products
show_progress = True

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 30
train_batch_size = 2048
learner = adam
learning_rate = 0.001
training_neg_sample_num = 0
training_neg_sample_distribution = uniform
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
draw_loss_pic = False
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_setting = RO_RS
group_by_user = True
split_ratio = [0.8, 0.1, 0.1]
leave_one_num = 2
real_time_process = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 	
seq_separator =  
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = {'rating': 4}
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
lowest_val = None
highest_val = None
equal_val = None
not_equal_val = None
max_user_inter_num = None
min_user_inter_num = 0
max_item_inter_num = None
min_item_inter_num = 0
fields_in_same_space = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters: 
valid_metric_bigger = True
embedding_size = 32
rm_dup_inter = None
filter_inter_by_user_or_item = True
SOURCE_ID_FIELD = source_id
TARGET_ID_FIELD = target_id
benchmark_filename = None
MODEL_TYPE = ModelType.CONTEXT
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
device = cuda
train_neg_sample_args = {'strategy': 'none'}

07 May 14:27    INFO  NumExpr defaulting to 4 threads.
07 May 14:27    INFO  Amazon_Office_Products
The number of users: 909315
Average actions of users: 1.367169096703669
The number of items: 130007
Average actions of items: 9.562527883328462
The number of inters: 1243186
The sparsity of the dataset: 99.99894838924583%
Remain Fields: ['user_id', 'item_id', 'timestamp', 'label']
07 May 14:27    INFO  Build [ContextDataLoader] for [train] with format [InputType.POINTWISE]
07 May 14:27    INFO  [train] No Negative Sampling
07 May 14:27    INFO  [train] batch_size = [2048], shuffle = [True]

07 May 14:27    INFO  Build [ContextDataLoader] for [evaluation] with format [InputType.POINTWISE]
07 May 14:27    INFO  Evaluation Setting:
	Group by user_id
	Ordering: {'strategy': 'shuffle'}
	Splitting: {'strategy': 'by_ratio', 'ratios': [0.8, 0.1, 0.1]}
	No Negative Sampling
07 May 14:27    INFO  [evaluation] batch_size = [4096], shuffle = [False]

07 May 14:27    INFO  FM(
  (token_embedding_table): FMEmbedding(
    (embedding): Embedding(1039322, 32)
  )
  (float_embedding_table): Embedding(1, 32)
  (first_order_linear): FMFirstOrderLinear(
    (token_embedding_table): FMEmbedding(
      (embedding): Embedding(1039322, 1)
    )
    (float_embedding_table): Embedding(1, 1)
  )
  (fm): BaseFactorizationMachine()
  (sigmoid): Sigmoid()
  (loss): BCELoss()
)
Trainable parameters: 34297660
Train     0: 100% 495/495 [00:08<00:00, 60.55it/s]
07 May 14:28    INFO  epoch 0 training [time: 8.24s, train loss: 35912.8304]
Evaluate   :   0% 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/quick_start/quick_start.py", line 55, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/trainer/trainer.py", line 288, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/trainer/trainer.py", line 185, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/trainer/trainer.py", line 406, in evaluate
    batch_matrix = self.evaluator.collect(interaction, scores)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/evaluator/proxy_evaluator.py", line 59, in collect
    results.append(evaluator.collect(interaction, scores))
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/evaluator/evaluators.py", line 67, in collect
    scores_matrix = self.get_score_matrix(scores_tensor, user_len_list)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/evaluator/abstract_evaluator.py", line 90, in get_score_matrix
    scores_matrix = self.sample_collect(scores_tensor, user_len_list)
  File "/content/drive/Shareddrives/share/RecBole-master/recbole/evaluator/abstract_evaluator.py", line 69, in sample_collect
    scores_list = torch.split(scores_tensor, user_len_list, dim=0)
  File "/usr/local/lib/python3.7/dist-packages/torch/functional.py", line 159, in split
    return tensor.split(split_size_or_sections, dim)
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 574, in split
    return super(Tensor, self).split_with_sizes(split_size, dim)
TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not NoneType`

**Comment by hyp1231** [comment]
你好！从配置文件中可以看到您还在使用 RecBole 老版本的评测配置的参数。由于老版本可能存在一些问题，建议您将 RecBole 升级至 1.0.1 版本，并重新尝试。

如果还是会报错，希望您可以告诉我们您的运行指令和配置文件，方便我们共同找出问题，谢谢

**Comment by czkyx** [comment]
非常感谢！！！
