### ISSUE TITLE
希望能整合RecBole_GNN

### ISSUE THREAD

**Issue by zgmming** [RUCAIBox/RecBole#1285]
RecBol里面的几个GNN推荐模型太慢了，希望能整合RecBole_GNN。

**Comment by hyp1231** [comment]
你好，感谢专注，但是我们并没有这个打算。

主要原因在于，我们期待 RecBole 是最基础的推荐算法代码库，使用 RecBole 的用户没有必要安装 PyG 这种专门为图网络设计的代码包（而且它并不容易安装）。

因此我们选择开发 RecBole 的拓展代码库，希望满足有额外需求的用户，比如 RecBole-GNN 就服务于专注于图网络+推荐的用户。

所以感谢你的理解，如果 RecBole-GNN 有兼容性问题，欢迎在拓展代码库的项目下提 issue，谢谢。
