### ISSUE TITLE
您好，请问如果想要用训练好的模型进行推荐预测，要如何操作呢？

### ISSUE THREAD

**Issue by Luo-rex** [RUCAIBox/RecBole#1286]

**Comment by Wicknight** [comment]
@Luo-rex 您好！您可以使用RecBole中提供的专门用于用户案例分析的接口：`recbole.utils.case_study` 来为指定用户进行推荐预测。该接口下共有两个函数：
`full_sort_scores`：计算指定用户对所有商品的推荐评分；
`full_sort_topk`：为指定用户进行top-k商品推荐；
关于该接口的详细信息您可以查看RecBole的[文档](https://recbole.io/docs/recbole/recbole.utils.case_study.html)。
同时我们在RecBole/run_example/case_study_example.py中展示了一个完整的使用该接口的示例。
需要注意的是，该接口适用于不进行重复推荐的场景，即在案例分析时将不会为用户推荐在训练集中出现过的商品；如果您只是想要简单地获得用户在所有商品上的评分，您可以通过`model.full_sort_predict`来实现。
