### ISSUE TITLE
time_field能否指定多列

### ISSUE THREAD

**Issue by bbb801** [RUCAIBox/RecBole#1292]
您好，
我的数据在时间上次序上存在两列，一列是以日期为单位，比如2020年3.21日。如果在同一天，则可以另一列以次序编排为单位比如1，2，3（如下）
User ID.    日期             次序
100    2020年3.21日     1
100    2020年3.21日     2
100    2020年3.29日    1
101    2020年4.21日     1
101    2020年3.25日    1
101    2020年3.29日    1

我尝试将日期和次序设置为float，并且添加到time_field, TIME_FIELD: [time,order]，显示错误。我最后只能使用日期这一列。我能否两列都使用呢？

**Comment by chenyuwuxin** [comment]
@bbb801 您好，感谢您的关注！
`TIME_FIELD` 只能指定timestamp的单个字段，而不能组合使用。如果你只是想根据这两列进行排序的话，可以做一个简单的映射：`new timestamp = timestamp(日期) * 10 + 次序`，将**new timestamp**作为最终的timestamp。
