### ISSUE TITLE
[💡SUG] 基于深度强化学习的推荐系统也是推荐系统比较有意义且热门的方向之一，有将其加入recbole的相关计划么😀

### ISSUE THREAD

**Issue by Arielliu3124** [RUCAIBox/RecBole#1296]
**您希望添加的功能是否与某个问题相关？**
目前只在GENERAL类里面看到了RaCF的实现，但是强化学习的实力远非如此

**描述您希望的解决方案**
这方面学术界比较关键的一个成果应该是[Deep Reinforcement Learning based Recommendation with Explicit User-Item Interactions Modeling](https://arxiv.org/abs/1810.12027) 业界的话应该是个很大的系统工程，京东和youtube都有比较好的成果
github有类似实现https://github.com/backgom2357/Recommender_system_via_deep_RL

**描述您考虑的替代方案**
关于您考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**

**Comment by chenyuwuxin** [comment]
@Arielliu3124 非常感谢您的关注和反馈！
您可以将希望添加的模型列在 [New Method to be added](https://github.com/RUCAIBox/RecBole/discussions/611) 中，我们会考虑添加。
另外也欢迎通过 PR 的形式提交您的实现，在经过测试后我们会合并入项目中，并将您列为贡献者。
