### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by ghost** [RUCAIBox/RecBole#1302]

**Comment by Wicknight** [comment]
@hyeri0414 Hello, thanks for your attention to RecBole!
According to our experiments, your configuration is basically OK except for the parameter ‘val_interval’ settings. The following is the configuration file I used in my experiment，and in the first epoch of training, the 'ndcg@10' value reaches **0.2**. I guess the reason for the poor performance is that **your configuration file is not loaded correctly and the mode of the evaluation is set to 'full'**. I suggest that you check the log file or debug to see if the mode of the evaluation is set to '**pop100**' as described in the configuration file.
```
#dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 200
POSITION_FIELD: position_id
load_col:
  inter: '*'
user_inter_num_interval: "[5,inf)"

#training and evaluation
epochs: 500
train_batch_size: 256
neg_sampling: ~
eval_args:
  order: TO
  split:
    LS: valid_and_test
  mode: pop100
topk: [1, 5, 10]
valid_metric: NDCG@10
eval_batch_size: 2048
learning_rate: 0.001
```

**Comment by hyeri0414** [comment]
Thank you for your reply. I've confirmed that it's working well. Have a nice day~!

**Comment by Wicknight** [comment]
Since there is no new reply for a long time, the issue has been closed. If you have any questions, please feel free to comment.
