### ISSUE TITLE
[🐛BUG] 有关item_id_list_field属性和eval_setting的问题

### ISSUE THREAD

**Issue by KingGugu** [RUCAIBox/RecBole#1303]
**描述这个 bug**
您好，我在自己划分的数据集上运行SASRec这个序列模型，我的三个文件分别是ml-1m.part1.inter、ml-1m.part2.inter、ml-1m.part2.inter，三个文件都包含四列数据，user，item，rate和timestamp。

1.报错提示缺少item_id_list_field这一属性，我查看了相关issue，但仍然不清楚这一列应该是怎样的，或者应该有哪些值，请问这一列是从来标注序列数据的吗？该如何标注？
2.我的数据都是通过.csv转换过来的，如果添加了这一列，该如何调用RecSysDatasets-master中的转换工具来将csv转换为inter文件？（因为我需要自己对数据集进行一些增强操作，所以我之前的转换都是把csv文件保存为4列，然后调用转换工具中对ml-20m的转换代码，对我的几个数据集进行转换，生成inter文件）

非常感谢！

**Comment by leoleojie** [comment]
@KingGugu 您好！感谢您对的关注！
1. 在加载序列数据集时，我们会对用户的历史交互记录使用数据增强方法，例如数据集中用户u1的交互物品为i1,i2,i3,i4,i5，并且MAX_ITEM_LIST_LENGTH为3。经过数据序列增强后，训练数据变为{(u1,<i1,0,0>,i2),(u1,<i1,i2,0>,i3),(u1,<i1,i2,i3>,i4),(u1,<i2,i3,i4>,i5)} 
然而在加载自定义划分的序列数据集时，我们并不会额外的处理序列数据，因此训练数据集中需要提前处理出这些增强后的交互序列，测试和训练数据中也要写入用户的历史交互物品序列，并写入至`.inter`文件中的`item_id_list_field`属性列。
2. 您可以修改src/extended_dataset.py中的ML20MDataset类，在`inter_fields`中加入`item_id_list:token_seq`字段信息。

**Comment by KingGugu** [comment]
> @KingGugu 您好！感谢您对的关注！
> 
> 1. 在加载序列数据集时，我们会对用户的历史交互记录使用数据增强方法，例如数据集中用户u1的交互物品为i1,i2,i3,i4,i5，并且MAX_ITEM_LIST_LENGTH为3。经过数据序列增强后，训练数据变为{(u1,<i1,0,0>,i2),(u1,<i1,i2,0>,i3),(u1,<i1,i2,i3>,i4),(u1,<i2,i3,i4>,i5)}
>    然而在加载自定义划分的序列数据集时，我们并不会额外的处理序列数据，因此训练数据集中需要提前处理出这些增强后的交互序列，测试和训练数据中也要写入用户的历史交互物品序列，并写入至`.inter`文件中的`item_id_list_field`属性列。
> 2. 您可以修改src/extended_dataset.py中的ML20MDataset类，在`inter_fields`中加入`item_id_list:token_seq`字段信息。

您好，请问意思就是item_id_list_field那一列的要写入类似<i1,i2,i3>这样的序列数据？比如用户A交互了5个物品，id分别是01,02,03,04,05，我只想有一条长度为5的序列，那item_id_list_field这一列的数据就是<01,02,03,04,05>。请问我这样理解对吗？非常感谢！

**Comment by leoleojie** [comment]
是的，您理解的没错。

**Comment by KingGugu** [comment]
最后请问一下，每一条数据的数据格式是<item_id,itemid,itemid>还是item_id,itemid,itemid就可以？

**Comment by leoleojie** [comment]
格式是i0 i1 i2 i3 i4

**Comment by KingGugu** [comment]
您好，我还有一个关于评估模式的问题，我评估时想采用留一分割，负采样100个。这是我yaml文件的参数设置（如下）：
![image](https://user-images.githubusercontent.com/61101061/172742940-7ab0dd51-929e-4710-a8a0-2a6a95445ce8.png)

之后运行程序，在打印参数设置时，我发现评估模式还是对的，但在开始训练前打印评估方式时，我发现mode又变成了full。
![image](https://user-images.githubusercontent.com/61101061/172743135-37089474-4800-4be4-b01e-fd50182a08db.png)
![image](https://user-images.githubusercontent.com/61101061/172743153-8d774477-f257-48c2-bae3-62824b06be3c.png)
可以看到最后一张图片里，mode又变成了full，请问是哪里出现了问题，是我的设置不对吗？

**Comment by leoleojie** [comment]
1. 请将参数设置中的`eval_settings`修改为`eval_args`，看看是否正确
2. 是的，是这样构造数据

**Comment by KingGugu** [comment]
您好，我在训练模型时遇到了cuda的报错。感觉可能和我的数据有关。GRU4rec不会报错，SASRec和BERT4rec会报错，我还没有尝试其它的序列模型。以SASRec为例，我的yaml文件设置如下（其余几个除了模型参数不同，剩下的设置都相同）：
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'

# dataset config
field_separator: "\t" #指定数据集field的分隔符
seq_separator: " " #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: item_id #指定物品id域
RATING_FIELD: rating #指定打分rating域
TIME_FIELD: timestamp #指定时间域

# training settings
epochs: 500 #训练的最大轮数
train_batch_size: 4096 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
neg_sampling: {uniform: 1}
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

# evalution settings
eval_args:
# eval_setting: 
  split: {'LS': 'valid_and_test'}
  mode: uni100
  order: TO
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准
topk: [10] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: MRR@10 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size

# split files settings
benchmark_filename: ['train', 'valid', 'test']
ITEM_ID_LIST_FILED : item_id_list
LIST_SUFFIX : _list
load_col:
   inter: [user_id, item_id, rating, timestamp, item_id_list]
#  inter: [user_id, item_id, rating, timestamp]


SASRec的报错如下（BERT4Rec的报错与之类似，GRU4Rec不会报错）：
Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/home/dangyizhou/Rec/recbole/quick_start/quick_start.py", line 56, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "/home/dangyizhou/Rec/recbole/trainer/trainer.py", line 335, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/home/dangyizhou/Rec/recbole/trainer/trainer.py", line 181, in _train_epoch
    losses = loss_func(interaction)
  File "/home/dangyizhou/Rec/recbole/model/sequential_recommender/sasrec.py", line 111, in calculate_loss
    seq_output = self.forward(item_seq, item_seq_len)
  File "/home/dangyizhou/Rec/recbole/model/sequential_recommender/sasrec.py", line 103, in forward
    trm_output = self.trm_encoder(input_emb, extended_attention_mask, output_all_encoded_layers=True)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dangyizhou/Rec/recbole/model/layers.py", line 549, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dangyizhou/Rec/recbole/model/layers.py", line 496, in forward
    attention_output = self.multi_head_attention(hidden_states, attention_mask)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dangyizhou/Rec/recbole/model/layers.py", line 409, in forward
    hidden_states = self.out_dropout(hidden_states)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 1279, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.



我的处理后的数据形式是（train、valid、test中的train.inter）：
![image](https://user-images.githubusercontent.com/61101061/172984625-d1b17f4e-ce5d-4e0a-b91a-d3175f002305.png)
我觉得可能是因为某些item_id_list为空（用户的第一个交互）导致的，于是删除了所有的空值。如下图，但报错依然存在。
![image](https://user-images.githubusercontent.com/61101061/172984509-f8d9e4af-224b-4a76-82dc-6fdce671fed1.png)

请问问题是否与序列长度有关？比如需要输入的序列等长？

**Comment by downeykking** [comment]
> 1. 请将参数设置中的`eval_settings`修改为`eval_args`，看看是否正确
> 2. 是的，是这样构造数据

你好！想请问下如何seq_max_len设置为3了，test.csv中的数据还是这样子吗？还是变成了如下呢：
<html>
<body>


user | item | rating | timestamp | item_id_list
-- | -- | -- | -- | --
u1 | i7 | X | XXXXXX | i4 i5 i6


</body>
</html>
