### ISSUE TITLE
[:question: Question] Content-Based Recommenders?

### ISSUE THREAD

**Issue by mmosc** [RUCAIBox/RecBole#1306]
Hi!
Looking at the list, I see that models are categorized either in General, Context-aware, Sequential, or Knowledge-based recommenders. 

Is there a list of models that allow leveraging item features (e.g. categorical such as Genres in Movie recommendation, or vectorial such as the track features provided by the [Music4All dataset](https://sites.google.com/view/contact4music4all) ?

Best, 
Marta

**Comment by Wicknight** [comment]
@mmosc Hello, thanks for your attention to RecBole!
Do you intend to use the features of items to support for recommendation? For example, we can use features in the Music4All dataset such as genres and mode to support for recommendation. If you are looking for such models, the Context-aware models meet your requirements. In RecBole, these item features can be loaded through atomic files. You can read our documentation about [Context-aware models](https://recbole.io/docs/user_guide/model_intro.html#context-aware-recommendation) and [Atomic Files](https://recbole.io/docs/user_guide/data/atomic_files.html) for further information.

**Comment by mmosc** [comment]
Hi @Wicknight and thank you for your quick reply!
Yes, I want to use hybrid models which relies both on item features and user-item interaction history. 

However, the features I am going to use are neither categorical nor binary, but are real-valued N-dimensional vectors, like for instance a vector made of [danceability, energy, valence, tempo], which would be in R^4. 

In my case, the feature vectors are way larger, with N of the order of hundreds or of the order of thousands.

Do context-aware models allow the use of features like that?

**Comment by Wicknight** [comment]
1. The format here is not fixed, and it can be customized by yourself. We use the **'field_separator (str)'** parameter to set the separator of different columns, and use the **'seq_separator (str)'** parameter to set the separator inside the sequence features. You can refer to our official documentation on [dataset parameters](https://recbole.io/docs/user_guide/config/data_settings.html#atomic-file-format) and [atomic files](https://recbole.io/docs/user_guide/data/atomic_files.html#additional-atomic-files).
2. Even if the model itself does not use these vectors, you can add additional code to load these vectors as illustrated in [our documentation](https://recbole.io/docs/user_guide/data/atomic_files.html#additional-atomic-files). For **ContextRecommender**, it is another way to load vectors. This kind of model encodes all float features through **'float_embedding_table'** and **'embed_float_fields'**. So you can load your feature vectors as a **pre-train float_embedding_table**. 
3. Just as [my example](https://recbole.io/docs/user_guide/data/atomic_files.html#additional-atomic-files) above.

**Comment by mmosc** [comment]
Thanks a lot, this answers all my questions :) 
I will try this out
