### ISSUE TITLE
使用token2id将外部id转换为内部id时，显示id不存在

### ISSUE THREAD

**Issue by Luo-rex** [RUCAIBox/RecBole#1313]
打扰了，我又来了

#1286 之前请教如何使用自己训练的模型进行预测，使用`recbole.utils.case_study`中的方法可以实现，十分感谢

但在我尝试对整个数据集中的用户都进行预测时，程序出错并显示
`ValueError: token [001bf9b4bb1cbd8e24659de883b197deebf276ab7a49589f54b86e9ff98f0554] is not existed in user_id`

起初我认为是模型在训练时过滤掉了10次交互以下的用户，所以无法完成用户id转换，但在我将数据集中15次交互以下的用户都过滤掉后，依然出现相似错误，完整报错信息如下
```
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1297/4066924139.py in <module>
      3 )  # Here you can replace it by your model path.
      4 
----> 5 uid_series = dataset.token2id(dataset.uid_field, test)
      6 print(uid_series)

~/anaconda3/envs/seele_py37_tk17/lib/python3.7/site-packages/recbole/data/dataset/dataset.py in token2id(self, field, tokens)
   1119                 raise ValueError(f'token [{tokens}] is not existed in {field}')
   1120         elif isinstance(tokens, (list, np.ndarray)):
-> 1121             return np.array([self.token2id(field, token) for token in tokens])
   1122         else:
   1123             raise TypeError(f'The type of tokens [{tokens}] is not supported')

~/anaconda3/envs/seele_py37_tk17/lib/python3.7/site-packages/recbole/data/dataset/dataset.py in <listcomp>(.0)
   1119                 raise ValueError(f'token [{tokens}] is not existed in {field}')
   1120         elif isinstance(tokens, (list, np.ndarray)):
-> 1121             return np.array([self.token2id(field, token) for token in tokens])
   1122         else:
   1123             raise TypeError(f'The type of tokens [{tokens}] is not supported')

~/anaconda3/envs/seele_py37_tk17/lib/python3.7/site-packages/recbole/data/dataset/dataset.py in token2id(self, field, tokens)
   1117                 return self.field2token_id[field][tokens]
   1118             else:
...
-> 1119                 raise ValueError(f'token [{tokens}] is not existed in {field}')
   1120         elif isinstance(tokens, (list, np.ndarray)):
   1121             return np.array([self.token2id(field, token) for token in tokens])

ValueError: token [2795505681d574c130640daea614f2bbc2f2432c6e66a5917a4cc71045936945] is not existed in user_id
```
- 请问这是什么原因引起的呢？
- 如果我想将无法进行id转换的用户id除去，我应该如何找到内部id和外部id转换表？

**Comment by Sherry-XLL** [comment]
@Sherry-XLL 您好，出现这个错误的原因就是在预处理阶段过滤掉了交互次数较少的用户，所以不是每一个在原数据集中出现过的用户都有映射关系。如果您只想对可以进行 ID 转换的用户进行案例分析，可以直接使用内部 ID 作为 `uid_series`，如注释所示。

https://github.com/RUCAIBox/RecBole/blob/ddff6211d030906f502a073a9f2b9e2250e93664/run_example/case_study_example.py#L23-L25

同时，您还可以使用 `dataset.id2token` 将所选择的内部 ID 转换为外部 token。

**Comment by Luo-rex** [comment]
> @Sherry-XLL 您好，出现这个错误的原因就是在预处理阶段过滤掉了交互次数较少的用户，所以不是每一个在原数据集中出现过的用户都有映射关系。如果您只想对可以进行 ID 转换的用户进行案例分析，可以直接使用内部 ID 作为 `uid_series`，如注释所示。
> 
> https://github.com/RUCAIBox/RecBole/blob/ddff6211d030906f502a073a9f2b9e2250e93664/run_example/case_study_example.py#L23-L25
> 
> 同时，您还可以使用 `dataset.id2token` 将所选择的内部 ID 转换为外部 token。

原来内部id用从1到用户总数的数组来表示就可以，~~是在下疏忽了~~，通过这个方法确实可以快速找到对应的用户，然后用`dataset.id2token`完成转换，十分感谢

对于另一个问题，我在训练模型时是按照下面的参数设置的
```
user_inter_num_interval = [10,inf)
item_inter_num_interval = [10,inf)
```
过滤后，模型显示`The number of users: 224933`，而我自己处理数据，将十次以下的用户过滤后，满足条件的用户数量为227730，我猜测是不是模型在预处理的时候是先过滤掉了一部分item，然后再过滤user，这样使得一些原本交互次数符合条件的用户在之后也被过滤掉了

**Comment by Sherry-XLL** [comment]
@Luo-rex 您好，如果只考虑 `user_inter_num_interval = [10,inf)`，不考虑对物品的约束，那么直接将十次以下的用户过滤即可，也就是您所处理得到的结果。

但是，当用户和物品都有限制条件时，用户和物品的过滤之间会有相互作用。

首先，我们过滤掉了交互不足十次的用户，再过滤掉交互不足十次的物品。由于这些被过滤的物品可能和第一次过滤后交互不低于十次的用户有过交互，当物品数量减少后，部分用户的交互次数可能会低于十次，因此需要再对用户进行过滤。同理，第一次满足条件的物品在第二次对用户过滤后交互次数也可能少于十次，又将进行下一次对物品的过滤。如此循环往复，直至用户数量和物品数量在一轮过滤后不发生变化，此时的用户和物品才同时满足交互次数不少于十次的要求。

RecBole 在这部分的实现中同样使用了循环，退出循环的条件是所有用户和所有物品都满足交互次数的条件，具体代码可以参考 RecBole 的数据处理部分：

https://github.com/RUCAIBox/RecBole/blob/ddff6211d030906f502a073a9f2b9e2250e93664/recbole/data/dataset/dataset.py#L693-L729
