### ISSUE TITLE
读入.kg文件后 三元组和原数据不一致

### ISSUE THREAD

**Issue by Kongxiangzhouye** [RUCAIBox/RecBole#1316]
在[链接](https://recbole.io/docs/recbole/recbole.data.dataset.kg_dataset.html)中，指出了.kg文件在读入时会被重新映射，这个我是明白的，但是我不太理解本来是双向边的三元组，读入后变得不对称了。
(因为在.kg的数据是保证 如果有 (h-r-t) 10000-0-10001，就一定会有三元组(10001-1-10000)，即对于实体10000来说，在head_id和tail_id中的出现次数是一致的)。
但是在处理后，对同一个id在head_id和tail_id里进行次数统计，出现的次数不一致，甚至有在head_id里出现100多次，在tail_id里却一次没出现，导致在后续处理数据时出错。

**如何复现**
数据是MCCLK原论文中的book-crossing数据集，并按照recbole的原子文件格式进行处理。
链接: https://wwi.lanzoup.com/iQJxd06j0f4f
然后直接读入查看dataset中有关kg的数据就可以发现了。
**屏幕截图**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/28479946/174113534-07109ac5-8fee-42df-bca4-33be5be71753.png">

我不太确定是我处理数据处理出了问题，还是使用方式上存在问题，期待您的回复，谢谢~

**Comment by chenyuwuxin** [comment]
@Kongxiangzhouye 你好，感谢你的关注！
你提供的数据集并不满足 “在head_id和tail_id中的出现次数是一致的”。例如id 4250，在head_id出现次数为4，在tail_id出现次数为2。

**Comment by Kongxiangzhouye** [comment]
> @Kongxiangzhouye你好，感谢你的关注！ 你提供的数据集没有满足“在head_id和tail_id中的出现次数是一致的”。例如id 4250，在head_id出现次数为4，在tail_id出现次数为2。

你好，感谢你的回复! 确实是数据集的问题，谢谢!!
