### ISSUE TITLE
[💡SUG]请求指导：测试集细分测试的最佳实践？

### ISSUE THREAD

**Issue by wu1hong** [RUCAIBox/RecBole#1319]
RecBole是一个很棒的开源项目，非常感谢各位开发者。

场景：我把Amazon的三个数据集Books（B），CDs（C），Movies（M）添加来源标签拼接成一个大的数据集（all）放入NeuMF模型进行训练（只用到了user_id和item_id）。用`create_dataset, data_preparation`来得到`train_data, val_data, test_data`三个`dataloader`。`test_data`中包含了三个来源的数据。

请问：我应该怎么做才能把`test_data`中三个来源的数据分开，得到`test_B, test_C, test_M`三个`dataloader`，分别对其`eval`

我目前在做一个对比的工作：比较单独domain模型的性能与混合domain模型的性能差异。

**Comment by leoleojie** [comment]
@wu1hong 您好！感谢你对伯乐的关注！
你可以关注伯乐最新的 [CDR子包](https://github.com/RUCAIBox/RecBole-CDR)，在子包里我们每个dataset以及dataloader都将不同的domain之间的部分进行了区分，你可以仿照我们的处理方式推广到更多的domain（子包的处理方式是以两个domain为例的)

**Comment by wu1hong** [comment]
非常感谢你的建议！我会好好去看看的。
祝愿RecBole越办越好！
