### ISSUE TITLE
自动调参的问题

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1324]
您好，我想问一下，Recbole框架中对自定义的模型怎么实现自动调参呢？官方API文档是在命令行调用的，可以写在Pycharm中运行吗？
(我自己在命令行调用自动调参代码，提示是recbole框架中没有这个模型)

**Comment by chenyuwuxin** [comment]
@DX12321 您好，感谢您的关注！
模型开发一般需要创建2个文件：
1. 在RecBole/recbole/model/ 下对应类别的文件夹下创建[model_name].py 的模型文件。
2. 在RecBole/recbole/properties/model/ 下创建模型的特殊参数配置文件[model_name].yaml，文件命名保证与模型类名一致。
同时需要在RecBole/recbole/model/ 对应文件夹下的_init_.py 文件中进行初始化，格式参考已有的代码。
请确保自定义的模型满足上述要求。
