### ISSUE TITLE
【使用疑问】请问官方给出的超参数搜索的文档中，为什么都不对embedding_size进行搜索呢？

### ISSUE THREAD

**Issue by KingGugu** [RUCAIBox/RecBole#1325]
很多模型都有embedding_size这个参数，例如GRU4Rec，但文档中给出的超参数搜索的范围，却没有对embedding_size这个参数进行搜索
![image](https://user-images.githubusercontent.com/61101061/175024156-dcb00ec7-2595-44bd-a157-e9b115fb07d9.png)

请问是需要我们自行搜索吗（如果需要的话）？还是说默认的64一般就是最优的？

如果我需要搜索的话，是否可以这样添加一行
embedding_size choice [32,64,128,256]

**Comment by KingGugu** [comment]
好的，明白了，非常感谢！
最后想请问一下RecBole2.0大概什么时候上线呢？

**Comment by Sherry-XLL** [comment]
@KingGugu 您好，RecBole 2.0 的各个子包都已开源，详情请点击 [repo](https://github.com/RUCAIBox/RecBole2.0) 和 [paper](https://arxiv.org/pdf/2206.07351)。

RecBole 2.0 includes 8 packages covering the up-to-date research topic in recommender system:

[Data augmentation (RecBole-DA)](https://github.com/RUCAIBox/RecBole-DA)
[Meta recommendation (RecBole-MetaRec)](https://github.com/RUCAIBox/RecBole-MetaRec)
[Debiased recommendation (RecBole-Debias)](https://github.com/RUCAIBox/RecBole-Debias)
[Fairness-aware recommendation (RecBole-FairRec)](https://github.com/RUCAIBox/RecBole-FairRec)
[Cross-domain recommendation (RecBole-CDR)](https://github.com/RUCAIBox/RecBole-CDR)
[Graph-based recommendation (RecBole-GNN)](https://github.com/RUCAIBox/RecBole-GNN)
[Transformer-based recommendation (RecBole-TRM)](https://github.com/RUCAIBox/RecBole-TRM)
[Person-job fit (RecBole-PJF)](https://github.com/RUCAIBox/RecBole-PJF)
