### ISSUE TITLE
 torch.randperm(self.length)不同model会不一致，导致训练过程加载的batch不一致！！！

### ISSUE THREAD

**Issue by TangJiakai** [RUCAIBox/RecBole#1327]
**描述这个 bug**
同样的benchmark、不同的model，其余设置完全一致，但是index = torch.randperm(self.length)不一样，这就造成训练过程加载的batch是不一致的！！！

**预期**
应该固定seed之后，那么每次出来的index都是一样的（因为self.length是一样的)

**Comment by leoleojie** [comment]
@TangJiakai 您好！感谢您对伯乐的关注！
对于这个问题，我们将进行修改，敬请期待我们的新版本发布。也欢迎您提出 Pull Request，感谢您对 RecBole 项目的关注！
