### ISSUE TITLE
引入其他数据集后遇到的问题，无法运行

### ISSUE THREAD

**Issue by Soar1998** [RUCAIBox/RecBole#1330]
我想在general_recommender类下的模型运行一下我自己处理的药物数据集，该数据集经过我的处理后和pinterest数据集一样，只有一个inter类型的文件，里边只有user_id:token和item_id:token两列数据，我尝试在多个general_recommender模型下运行都没有问题，现在我想做的是修改一下评价指标，我看评估器给出的指标中有AUC指标，我想在general_recommender模型下用AUC来评价结果，我的方法是添加一个yaml文件，其中添加这样一行：“metrics: ["AUC"]”，但是总是无法运行模型会在断言处结束（“Full sort evaluation do not match value-based metrics!”），。我想问一下，是我的yaml文件没写对，还是框架设置就是这样的，没有办法对general_recommender模型使用AUC指标。因为我发现该指标在其它类型的模型下可以使用。

**Comment by Wicknight** [comment]
@Soar1998 
您好！这里的运行报错正如报错信息所示，是由于评测模式(**mode** in **eval_args**)与评测指标不兼容造成的，与是否使用general_recommender模型无关。由于您在yaml文件中没有指定[评测模式](https://recbole.io/docs/user_guide/train_eval_intro.html#evaluation-method)，因此该参数选用了默认值：full，在该评测模式下，RecBole会对所有候选项目进行完整排名，与评测指标AUC不兼容。因此可以通过将该参数设置为其它值来解决该问题，详情您可以参考RecBole关于[评测的文档](https://recbole.io/docs/user_guide/train_eval_intro.html#evaluation-method)。

**Comment by Soar1998** [comment]
感谢回复，已经解决啦！谢谢
