### ISSUE TITLE
run_recbole(model='FM', dataset='ml-100k') 跑了半天auc0.5

### ISSUE THREAD

**Issue by yuanjie-ai** [RUCAIBox/RecBole#1331]
{'best_valid_score': 0.5,
 'valid_score_bigger': True,
 'best_valid_result': OrderedDict([('auc', 0.5), ('logloss', 15.5394)]),
 'test_result': OrderedDict([('auc', 0.5), ('logloss', 15.5843)])}

**Comment by leoleojie** [comment]
@yuanjie-ai 您好，感谢您对伯乐的关注！
能否提供您的参数设置？根据以往的经验来看， 如#1109 所说，这可能是由于没有对数据归一化造成的，即没有在yaml文件中设置`normalize_all: True`。
