### ISSUE TITLE
关于CE loss的负采样问题

### ISSUE THREAD

**Issue by ShowTBC** [RUCAIBox/RecBole#1333]
关于loss_type官网文档的描述中，当采用的loss类型设置为CE时，neg_sampling这个参数会要求设置为None。
我想问一下为什么loss类型为CE时，不需要负采样？
        我看到很多关于推荐系统的文章定义CE loss时，都采用了负采样的训练方式，然后正负样本之比大多是1:1。

**Comment by hyp1231** [comment]
使用 RecBole 并选用 CE loss 时，用的是剩余的全部商品作为负样本。为了方便配置，因此设置 `neg_sampling: ~` 即可。

您指的正负样本比 1:1 可能一般指的是 Binary Cross Entropy (BCE) 损失进行优化。RecBole 大部分模型没有提供 BCE 的接口，因为一般来说在相同负例数下，BPR 会比 BCE 效果好些。如果您希望测试 BCE 的效果，也可以稍微修改一下对应模型代码即可。

**Comment by zyx1017** [comment]
@hyp1231 请问能简单提供下修改思路嘛

**Comment by Sherry-XLL** [comment]
@zyx1017 您好，若您想在现有框架中使用 BCE 损失函数，一个简单的改法是参考目前的 GCMC 模型，分别得到 `user` 与 `pos_item` 和 `neg_item` 的得分，然后与 0/1 的 `label` 计算交叉熵损失函数。

https://github.com/RUCAIBox/RecBole/blob/26e8d93d3a896e8f477e60bb7fd79744eca89579/recbole/model/general_recommender/gcmc.py#L196-L210

同时，建议您新开一个 issue 表述您的问题，我们开发人员一般不会关注已经 close 的 issue。感谢您对 RecBole 的关注！
