### ISSUE TITLE
dataloader加载数据时希望有prefetch功能

### ISSUE THREAD

**Issue by taoxuewen** [RUCAIBox/RecBole#1355]
请问下有prefetch吗，有可能是我没有发现，如果有的话，望指导一下在哪里配置，谢谢！因为现在GPU利用率不高

**Comment by leoleojie** [comment]
@taoxuewen 感谢您对伯乐的关注！
目前伯乐并不支持prefetch和多线程加载数据。在下个版本中，我们可能尝试加入这些功能。敬请期待！

**Comment by Sherry-XLL** [comment]
您好 @taoxuewen！

我们团队在 2022 年的 10 月 5 日发布了伯乐的 [1.1.1 版本](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1)，现在伯乐的框架已经支持分布式的训练和验证，您可以参考我们的[文档](https://recbole.io/docs/get_started/distributed_training.html) 来获取更多细节和使用实例。

由于 issue 的低活跃度，我们将关闭该 issue。若您有新的问题，欢迎提出新的 issue。感谢您对伯乐的关注！
