### ISSUE TITLE
ImportError: cannot import name 'set_color' when running quick_start.py

### ISSUE THREAD

**Issue by caijie1998** [RUCAIBox/RecBole#1358]
Traceback (most recent call last):
  File "RecBole/recbole/quick_start/quick_start.py", line 17, in <module>
    from recbole.utils import init_logger, get_model, get_trainer, init_seed, set_color
ImportError: cannot import name 'set_color'

**Comment by Wicknight** [comment]
@caijie1998 
Please check whether your local files are complete, for example, check whether the recbole/utils/__ init__. py and rebole/utils/logger.py are complete. Under normal circumstances, this error will not occur if the local file is complete.

**Comment by Wicknight** [comment]
Since there is no new reply for a long time, the issue has been closed. If you have any questions, please feel free to comment.
