### ISSUE TITLE
有关序列模型STAMP的问题

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1363]
您好，最近在跑序列模型时遇到一个问题，就是基于RNN的模型，GRU4Rec、NARM和STAMP三个模型中，理论上来讲，其性能应该是GRU4Rec<NARM<STAMP。但是我使用Recbole框架跑出的结果却是STAMP的最低。实验设置如下：

embedding_size: 100
loss_type: 'CE'
hidden_size: 128 # GRU4Rec
num_layers: 1# GRU4Rec
dropout_prob: 0.3# GRU4Rec

使用的相同数据集 diginetica ，数据集是CORE论文提供的。实验结果：

GRU4Rec
('recall@10', 0.33964), ('recall@20', 0.46487), ('mrr@10', 0.147), ('mrr@20', 0.15562)

NARM
('recall@10', 0.34703), ('recall@20', 0.47226), ('mrr@10', 0.1477), ('mrr@20', 0.15634)

STAMP
('recall@10', 0.31747), ('recall@20', 0.43664), ('mrr@10', 0.13705), ('mrr@20', 0.14527)

从实验结果可以看到，STAMP模型的性能最差，但是STAMP原论文中不是这样的。想问一下这是什么原因导致的呢？谢谢

**Comment by DX12321** [comment]
这个实验结果是batch_size=100的设置下跑出来的结果

**Comment by DX12321** [comment]
这个实验结果是batch_size=100的设置下跑出来的结果

**Comment by leoleojie** [comment]
@DX12321 
您好！感谢您对伯乐的关注。
很抱歉由于我们检查了代码并且做了部分调参测试，所以回复比较晚。
经检查，代码方面应该没有问题。伯乐基本是按照原论文实现，一部分可能因为兼容性的问题有了修改。
从我们的测试结果来看，GRU4Rec和NARM效果较为接近，而STAMP效果确实较差。通过比较其他的文章给出的结果，如 [SLIST](https://arxiv.org/pdf/2103.16104.pdf),   [TAGNN](https://arxiv.org/pdf/2005.02844.pdf)  ，可以发现，也存在STAMP弱于NARM的情况。除此以外，STAMP文中给出的NARM的结果，似乎是直接使用NARM原文的结果，这也有可能存在一定的问题。所以目前还并不清楚STAMP结果较差的详细原因。
如果您发现了其他的错误欢迎提PR修改，如果对模型方面有相关的疑问也可以联系咨询原作者。

**Comment by DX12321** [comment]
十分感谢！！！
论文中对比的话这个对比模型只能删了
