### ISSUE TITLE
[💡SUG] 数据集处理时添加.user

### ISSUE THREAD

**Issue by KlaineWei** [RUCAIBox/RecBole#1366]
我在使用贵项目时，遇到了序列推荐的相关问题，比如Ber4Rec模型，运行时数据集需要.user文件，但是你们给出的很多原子文件并没有.user，而且用脚本进行转换也会失败，希望可以有更多数据集支持.user文件，否则序列推荐很多数据集都跑不起来。

**Comment by hyp1231** [comment]
您好，RecBole 提供的 BERT4Rec 应该是不强制要求 `.user` 文件的，建议您检查下参数配置。

可以在 ml-1m 数据集上运行的一个参数配置可参考 https://github.com/RUCAIBox/RecBole/issues/1302#issuecomment-1147049367

**Comment by Sherry-XLL** [comment]
您好 @KlaineWei！

我们团队在 2022 年的 10 月 5 日发布了伯乐的 [1.1.1 版本](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1)，并在 [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) 新增了 13 个数据集。

在伯乐现有的 41 个预处理好的数据集中，[MovieLens](https://github.com/RUCAIBox/RecommenderSystems-Datasets/tree/master/dataset_info/MovieLens)、[Yelp](https://github.com/RUCAIBox/RecommenderSystems-Datasets/tree/master/dataset_info/Yelp)、Book-Crossing、[Ta Feng](https://github.com/RUCAIBox/RecommenderSystems-Datasets/tree/master/dataset_info/TaFeng)、[LFM-1b](https://github.com/RUCAIBox/RecommenderSystems-Datasets/tree/master/dataset_info/LFM-1b)、EndoMondo、ModCloth 和 RentTheRunway 都包含 `.user` 数据。您可以从 [百度网盘](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g) (密码: e272) 和 [谷歌云盘](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing) 中下载我们的数据集。

由于 issue 的低活跃度，我们将关闭该 issue。若您有新的问题，欢迎提出新的 issue。感谢您对伯乐的关注！
