### ISSUE TITLE
[💡SUG] distributed training

### ISSUE THREAD

**Issue by PALIN2018** [RUCAIBox/RecBole#1375]
感谢recbole团队的辛苦付出！ 我在doc中发现最近更新了distributed training，但是目前版本的recbole貌似并没有更新这一特性，所以请问多卡训练的recbole会于近期公布吗？ 谢谢！

**Comment by leoleojie** [comment]
@PALIN2018 您好！感谢您对伯乐的关注！
是的，我们将于新版本上线多卡训练的功能。目前新版本仍在测试阶段，预计将于九月份上线，敬请期待！

**Comment by Sherry-XLL** [comment]
@PALIN2018 您好，我们已经在 2022 年的 10 月 5 日发布了伯乐的 [1.1.1 版本](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1)，目前的最新版本已经支持分布式训练和验证，您可以参考我们[文档](https://recbole.io/docs/get_started/distributed_training.html)中的运行实例了解更多使用的细节。

非常感谢您对伯乐的关注和建议！开源用户的建议反馈是我们开发团队持续更新的动力，期待您能再次使用我们的库并给出宝贵的意见。
