### ISSUE TITLE
Evaluate against an external test data set

### ISSUE THREAD

**Issue by ThomasEKolb** [RUCAIBox/RecBole#1376]
Hello,
first, thanks for this great project!

Is there a possibility to evaluate a trained model against an test data set from another model?

Our setup is as following:
We trained two BERT4Rec models by using the proposed description [1]. Both models do have the same atomic file structure (they are subsets from different timespans of the same base data set):
- 1st trained on data set "A" = Model 1
- 2nd trained on data set "B"  = Model 2

This results in a model, dataloader and dataset file for both.

The question is now is it possible to load Model 1 by using "load_data_and_model(...)" and evaluating this model with "trainer.evaluate(test_data)" against the test dataset from Model 2? 

The error which is shown is:

```
File ~/.../recbole/trainer/trainer.py:475, in Trainer.evaluate(self, eval_data, load_best_model, model_file, show_progress)
    466 iter_data = (
    467     tqdm(
    468         eval_data,
   (...)
    472     ) if show_progress else eval_data
    473 )
...
--> 406 scores = scores.view(-1, self.tot_item_num)
    407 scores[:, 0] = -np.inf
    408 if history_index is not None:

RuntimeError: shape '[-1, 41607]' is invalid for input of size 205340672
```

[1] https://recbole.io/docs/user_guide/usage/use_modules.html#use-modules

**Comment by chenyuwuxin** [comment]
@ThomasEKolb Hello, thanks for your attention to RecBole!
It seems impossible to do this, because the item embedding trained from two subsets is different ( i.e. some item of 2nd dataset does not exist in 1st dataset). If you want to do this, please ensure that the items in the two subsets are the same.

**Comment by ThomasEKolb** [comment]
Hello! Thank you for the quick reply.
