### ISSUE TITLE
请问SimpleX在哪里呢

### ISSUE THREAD

**Issue by bruno686** [RUCAIBox/RecBole#1377]
你好，我在recbole官网看到有支持SimpleX，但是在仓库里没有看到这个，请问这是咋回事呢

**Comment by Sherry-XLL** [comment]
@bruno686 您好，新开发的 SimpleX 模型在 [1.1.x](https://github.com/RUCAIBox/RecBole/tree/1.1.x) 分支中，预计新的版本于九月上线，如果您需要的话可以先参考 [1.1.x](https://github.com/RUCAIBox/RecBole/tree/1.1.x) 分支中的代码。

**Comment by bruno686** [comment]
好的，刚才运行了一下[1.1.x]分支的SimpleX有报错，这会在九月修复吗

**Comment by Sherry-XLL** [comment]
@bruno686 您好，分支 [1.1.x](https://github.com/RUCAIBox/RecBole/tree/1.1.x) 目前仍在开发阶段，SimpleX 已经通过了模型的基本测试，只是添加的一个新功能尚未修复 bug。如果您需要现在就使用 SimpleX 模型，请注释掉 `recbole/quick_start/quick_start.py` 中的第 78 和 79 行即可正常运行模型：

https://github.com/RUCAIBox/RecBole/blob/411a45af7287fd6dfcd452a9db88d714ac20fb2f/recbole/quick_start/quick_start.py#L78-L79

请注释这两行代码如下：

```python
# flops = get_flops(model, dataset, config["device"])
# logger.info(set_color("FLOPs", "blue") + f": {flops}")
```

然后在运行 SimpleX 模型，即可得出结果。

**Comment by shahjaidev** [comment]
Hi, I had a question about SimpleX in 1.1.x

I see that the properties/model/Simplex.yaml file has the following set parameters:
![image](https://user-images.githubusercontent.com/22052444/185306200-38f16e5c-9393-4729-b759-9e7c37f5357e.png)

About **history_len**
What does this entail in the context of SimpleX? 

(i) Only a fixed set of 50 interacted items will be considered during item aggregation step? 
OR
(ii) Each time, a randomly sampled set of 50 interacted items for a user will be selected. 

Related to this, is the dataloader for SimpleX iterating over each user, then randomly sampling 1 positive item 
OR is it iterating over **all** user-positive item interactions in an epoch?


Lastly, are the embeddings mixed one more time with all interacted items before evaluation? (as opposed to using the raw original user embeddings). 

If so, I assume this mixing is done with the interacted items for each user, _from the train set_   ...?

**Comment by shahjaidev** [comment]
Also, I see that the two lines
flops = get_flops(model, dataset, config["device"]) 
 ‎logger‎‎. ‎‎info‎‎(‎‎set_color‎‎(‎‎"FLOPs"‎‎, ‎‎"blue"‎‎) ‎‎+‎‎ ‎‎f": ‎‎{‎‎flops‎‎}‎‎"‎) 

are no longer present in quick_start.py of branch 1.1.x. Can I directly run SimpleX from a config file without any hidden issues?

**Comment by Sherry-XLL** [comment]
@shahjaidev Hello, the two lines still exist in branch 1.1.x and we have fixed the bug in #1397 , now you can run it correctly.

**Comment by shahjaidev** [comment]
Ah yes, thanks for the quick reply.

**Comment by shahjaidev** [comment]
cc @Sherry-XLL I'll move my above comment with questions to another issue, I think that's more appropriate to do. thanks!
