### ISSUE TITLE
请问有计划增加UltraGCN吗

### ISSUE THREAD

**Issue by bruno686** [RUCAIBox/RecBole#1378]
你好，请问有计划增加《UltraGCN: Ultra Simplification of Graph Convolutional Networks for Recommendation》吗，看到UltraGCN在论文里报道的性能非常强大，如果能增加到recbole中和其他模型一起对比性能就好了。

**Comment by Wicknight** [comment]
@bruno686 感谢您的建议！

您可以按照 https://github.com/RUCAIBox/RecBole/discussions/611 的统一格式将该模型列出，我们会根据#611 的各种需求规划未来的开发计划。如果后续有相关进展，我们会在本 issue 下回复。

另外我们也欢迎通过 PR 的形式提交您的实现，在经过测试后我们会合并入项目中，并将您列为贡献者。

**Comment by Wicknight** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
