### ISSUE TITLE
尝试添加AUPR评价指标，但是结果很低

### ISSUE THREAD

**Issue by Soar1998** [RUCAIBox/RecBole#1390]
这是我的代码：
class AUPR(LossMetric):
    def __init__(self, config):
        super().__init__(config)

    def calculate_metric(self, dataobject):
        return self.output_metric('aupr', dataobject)

    def metric_info(self, preds, trues):
        result = metrics.average_precision_score(y_true=trues, y_score=preds)
        return result
我是仿照AUC指标的写法写的，可以跑通，但是运行出来的结果只有0.3左右，肯定不正常，但是也不知道哪里出问题了

**Comment by Wicknight** [comment]
@Soar1998 您好！请问您使用的是哪个模型呢？其它指标（例如AUC）的运行结果是否正常呢？

**Comment by Wicknight** [comment]
@Soar1998 您好！我在ml-100k数据集上使用多个模型进行测试，AUC指标的平均值在0.9左右，AUPR的平均值在0.58左右，因此您的计算应该是没有问题的。初步推测是因为您的数据分布极度不均衡导致AUPR结果较差，如果您是通过设定[threshold](https://recbole.io/docs/user_guide/data/label_of_data.html#set-threshold)来为数据集添加label的话，推荐您更换threshold的取值进行尝试。

**Comment by Soar1998** [comment]
谢谢
