### ISSUE TITLE
[💡SUG] Evaluate model trained outside of RecBole

### ISSUE THREAD

**Issue by tsafavi** [RUCAIBox/RecBole#1401]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for the great contribution. I have several pairwise recommendation models I trained using a different library. I want to load my model's predicted user-item scores and evaluate them with RecBole, without conducting any further training or validation. 

**Describe the solution you'd like**
Something as simple as:
```
...
user_item_scores = torch.load(path_to_saved_scores)
metrics = ["hit", "ndcg"]
topk = [1, 5, 10]
recbole.evaluate(user_item_scores, test_data, metrics, topk)
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zhengbw0324** [comment]
@tsafavi 
Sorry, we don't support this function yet. If necessary, you can use our evaluation [metrics ](https://recbole.io/docs/recbole/recbole.evaluator.metrics.html)to implement it yourself.
