### ISSUE TITLE
Can you please provide one data example on the entity features of "'ml-100k'" to run "GRU4RecKG"

### ISSUE THREAD

**Issue by Cheerlen** [RUCAIBox/RecBole#1406]
hi, there,

I am trying to run GRU4RecKG, and found no entity config file, as follows, "recbole/config/../dataset_example/ml-100k/ml-100k.ent] not found"

I only found this format, can you post one data example?  Thanks

load_col:
    inter: [user_id, item_id]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]
    ent_feature: [ent_id, ent_vec]
alias_of_entity_id: [ent_id]
preload_weight:
    ent_id: ent_vec
additional_feat_suffix: [ent_feature]

**Comment by zhengbw0324** [comment]
@Cheerlen 

You can see a data example containing knowledge graph [here](https://github.com/RUCAIBox/RecBole/tree/master/recbole/dataset_example/ml-100k). And you can also refer to our [documents](https://recbole.io/docs/user_guide/data/atomic_files.html) to better understand the meaning of each data file.
