### ISSUE TITLE
Question: Is it possible to read a pre-defined train, validate, and test sets?

### ISSUE THREAD

**Issue by rahmanidashti** [RUCAIBox/RecBole#1408]
Hi,

How can I read and run a model on a dataset that is splitted into `train`, `validate`, and `test`? Suppose, I have a dataset called `MovieLensSmall.txt` which is currently splitted into `MovieLensSmall_train.txt`, `MovieLensSmall_validate.txt`, and `MovieLensSmall_test.txt`, should I first create the atomic files? For each one? and how can I load these pre-defined sets?

**Comment by AoiDragon** [comment]
@rahmanidashti Hello, 

Yes, you should first create the atomic files for each dataset. Then you should form your dataset as `benchmark_filename` and add it to the config file. See [here](https://recbole.io/docs/user_guide/config/data_settings.html?highlight=benchmark) for more details about benchmark file in RecBole.

**Comment by rahmanidashti** [comment]
Thanks. I see and I have created a repository to add some examples: https://github.com/rahmanidashti/RecBoleExperiments
