### ISSUE TITLE
[🐛BUG] Logger issue

### ISSUE THREAD

**Issue by evelyn023** [RUCAIBox/RecBole#1409]
**Describe the bug**
The logger doesn't print model and dataset infomartion, it also doesn't print the evaluation result. But the same code worked well a few days ago.

**Code**
```
!pip install recbole 
from recbole.quick_start import run_recbole
run_recbole(model='BPR', dataset='ml-100k')
```

**Runtime Result**
<img width="695" alt="1661179845(1)" src="https://user-images.githubusercontent.com/61037456/185951291-599a61f4-20c4-45f4-80b7-cf1f220d10b9.png">

**Desktop (please complete the following information):**
 - OS: Windows
- RecBole Version: 1.0.1
- Python Version: >3.7

**Comment by evelyn023** [comment]
Also there is nothing in my '.log' file.

**Comment by zhengbw0324** [comment]
@evelyn023 Hello, thanks for your attention to RecBole!
We're also not sure what caused the problem. I think you can try reinstalling RecBole. Or switch other branches of RecBole.
