### ISSUE TITLE
[💡SUG] 一对多负采样

### ISSUE THREAD

**Issue by junkangwu** [RUCAIBox/RecBole#1410]
**您希望添加的功能是否与某个问题相关？**
现在很多模型都是通过uniform 1-N采样方式进行计算，由于不区分样本是否交互过从而有较为高效的训练速度，反复学习了recbole框架后，似乎没有直接简洁的修改方式？

**描述您希望的解决方案**
希望实现一对多的负采样形式，如经典BPR-MF模型，每个正样本item对应M个负样本。

**描述您考虑的替代方案**
请问pair-wise是否只支持1-1负采样？但point-wise又缺少负采样部分。

**其他**
无

**Comment by AoiDragon** [comment]
@junkangwu 您好，

RecBole已经实现一对多的负采样，您可以修改`train_neg_sample_args`中的`distribution`和`sample_num`实现uniform 1-N的采样方式。具体操作方式可以参考[这里](https://recbole.io/docs/user_guide/config/training_settings.html)。

**Comment by junkangwu** [comment]
我修改这个参数没有效果，请问train_neg_sample_args['sample_num']这个参数有在什么位置被调用吗？我查询代码文件没找到具体位置。

**Comment by AoiDragon** [comment]
您可以通过修改命令行或配置文件修改该参数。另外在master分支下这个参数名是`neg_sampling`，如果您使用的是master分支，可以修改一下参数名再试试。读取该参数设置的代码在[这里](https://github.com/RUCAIBox/RecBole/blob/master/recbole/config/configurator.py#L350)。
