### ISSUE TITLE
AutoInt是不是初始化部分少了？

### ISSUE THREAD

**Issue by TangJiakai** [RUCAIBox/RecBole#1412]
https://github.com/RUCAIBox/RecBole/blob/61848c0cc03d25645ebeffbfe9b58c48aaafaa76/recbole/model/context_aware_recommender/autoint.py#L89

初始化部分应该加这个
self.v_res_embedding = nn.Linear(self.embedding_size, self.attention_size)

**Comment by zhengbw0324** [comment]
@TangJiakai 
感谢您的建议，我们已经修复了这个问题。
