### ISSUE TITLE
FwFM算法似乎实现有问题？

### ISSUE THREAD

**Issue by TangJiakai** [RUCAIBox/RecBole#1413]
伯乐中FwFM实现似乎有错误？
如果按照原论文说法，FwFM实现那么应该是
一阶项：为每个filed学习一个embedding，之后就是filed和feat之间点积之和（然而伯乐实现仍然是传统FM方法，当然这个也算是一种方法，只不过没有按照FwFM提出的最优方法来）
二阶项：
1. 应该是学习n(n-1)/2个标量值，其中n表示filed数量（伯乐采用每个filed交叉项学习一个vector的方式，与原文不符合）
2. 伯乐是每个batch都学习一个新的filed 交叉权重矩阵，这应该是错误吧？按理应该是放到初始化中的
https://github.com/RUCAIBox/RecBole/blob/07d80fe86e0e2d29c2a2369b1d1d15c6b54dfa85/recbole/model/context_aware_recommender/fwfm.py#L91-L120

**Comment by Sherry-XLL** [comment]
Dear @TangJiakai,

Thanks for your contributions to RecBole in #1414! 
We will close the issue since the bug has been fixed. 
Looking forward to your well-meant advice again.

Best Wishes
Sherry
