### ISSUE TITLE
如何添加 user_id 和entity 的link文件？是否可以给个例子

### ISSUE THREAD

**Issue by 2022L** [RUCAIBox/RecBole#1417]
**您希望添加的功能是否与某个问题相关？**
关于这个问题的简洁清晰的描述，例如，当 [...] 时，我总是很沮丧。

**描述您希望的解决方案**
关于解决方案的简洁清晰的描述。

**描述您考虑的替代方案**
关于您考虑的，能实现这个功能的其他替代方案的简洁清晰的描述。

**其他**
您可以添加其他任何的资料、链接或者屏幕截图，以帮助我们理解这个新功能。

**Comment by AoiDragon** [comment]
@2022L 您好，.link文件中的默认属性是`item_id`和`entity_id`，想要添加新的属性可以参考[这里](https://recbole.io/docs/user_guide/data/atomic_files.html)提到的添加atomic files的方法。
