### ISSUE TITLE
[🐛BUG] Illegal algo [bayes]

### ISSUE THREAD

**Issue by Fabrice-Clement** [RUCAIBox/RecBole#1424]
**Describe the bug**
Hello,

I cannot use the 'bayes' algorithm for hyper parameter tuning.

Thanks

**To Reproduce**

I've tried the run_hyper.py example and change the following lines : 

```
    hp = HyperTuning(objective_function, algo='bayes',
                     params_file=args.params_file, fixed_config_file_list=config_file_list)

```

    OS: linux
    RecBole Version : think it is 1.0 ( have done : it clone https://github.com/RUCAIBox/RecBole.git today )
    Python Version : 3.8.5

**Comment by AoiDragon** [comment]
@Fabrice-Clement Hello!

You can switch to branch `1.1.x` to use `bayes` algorithm when hypertuning.

**Comment by Fabrice-Clement** [comment]
Ok, I can't wait to upgrade to version 1.1 !

Again, thanks for this awesome framework, very useful for RecSys practitionners.
