### ISSUE TITLE
如何获取模型推荐的topk物品呢？

### ISSUE THREAD

**Issue by 0375w** [RUCAIBox/RecBole#1432]
我尝试了两种方法，用了case_study的full_sort_scores和full_sort_topk，直接用model.predict，获取每对user_item的pair对的得分，然后再获取topk，然后自行计算mrr得分比模型直接用trainer.evaluate输出的得分低了很多，我不清楚是否是我获取topk物品的操作有问题，如果方便的话，可以给一个案例吗？

**Comment by AoiDragon** [comment]
@0375w 
我认为您的思路是正确的，如果方便的话可以提供一下您的代码吗？

**Comment by 0375w** [comment]
> @0375w 我认为您的思路是正确的，如果方便的话可以提供一下您的代码吗？

哦抱歉，后来我发现是因为我内外部的user_id转换不正确导致的，感谢回复
