### ISSUE TITLE
你好，我想问下，RecBole 可以在离线的情况下安装使用吗？比如在学校 无网络的服务器上！？

### ISSUE THREAD

**Issue by 1358337137** [RUCAIBox/RecBole#1433]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhengbw0324** [comment]
@1358337137 
使用pip或conda的环境配置和安装过程需要网络，环境配置完成后可以离线使用，但如果需要下载我们的数据集仍需要连接网络。
