### ISSUE TITLE
[🐛BUG] 单机多卡训练错误

### ISSUE THREAD

**Issue by KlaineWei** [RUCAIBox/RecBole#1437]
https://recbole.io/docs/get_started/distributed_training.html 我根据这个页面demo进行单机多卡的训练，但是并不能实现多gpu训练

**Comment by zhengbw0324** [comment]
@KlaineWei
您好，目前单机多卡训练只有最新的1.1.x分支支持，可以尝试使用我们的最新github分支再次尝试。
