### ISSUE TITLE
[🐛BUG] 请问history_item_matrix(value_filed=None)方法返回matrix横纵坐标具体含义。

### ISSUE THREAD

**Issue by cizhouyu** [RUCAIBox/RecBole#1441]
在recbole.data.dataset中有一个方法：history_item_matrix(value_filed=None)，返回history_matrix等三个矩阵。我想问的是，
1. history_matrix的横坐标含义是‘user_token’还是'user internal id'；history_matrix[i]的内容的含义是‘item_token’还是'item internal id'？
2. 在返回的三个矩阵中，横坐标和内容含义是否相同？
谢谢！

**Comment by cizhouyu** [comment]
谢谢！
请问，history_matrix[i]返回的每个元素是item internal id吗？

**Comment by AoiDragon** [comment]
是的

**Comment by cizhouyu** [comment]
我知道了，谢谢！
