### ISSUE TITLE
[🐛BUG] BERT4Rec性能较差，无法复现原论文的结果

### ISSUE THREAD

**Issue by PALIN2018** [RUCAIBox/RecBole#1443]
哈喽，我们在使用BERT4Rec做实验的时候，发现跑出来的结果很差， Recsys 2022的文章A Systematic Review and Replicability Study of BERT4Rec for Sequential Recommendation (https://arxiv.org/abs/2207.07483)也提出了这一问题，不知道是不是目前的实现存在bug？ 请问贵团队是否可以再对比一下目前的实现和已有实现的区别？

**Comment by AoiDragon** [comment]
@PALIN2018 你好，
这是由于RecBole默认对所有模型按照`full`模式进行评测，也就是和所有物品一起测试。而BERT4Rec原论文中使用的是`pop100`方法，即针对每个测试物品选择100个负例物品进行测试。我们认为这是造成RecBole和原论文性能差异的主要原因。

**Comment by zyx1017** [comment]
@AoiDragon 你好，同样条件下，使用SASRec的效果远比Bert4Rec的效果要好。这是咋回事
