### ISSUE TITLE
自定义数据集在Sequential Recommendation上的问题

### ISSUE THREAD

**Issue by XiaoLangLangY** [RUCAIBox/RecBole#1445]
我使用了`benchmark_filename`来设置自定义文件，有`train.inter, valid.inter, test.inter`三个文件作为输入，例如`user_id:1`的交互序列为`(2,3,4,5,6,7,8,9)`，设置`MAX_ITEM_LIST_LENGTH: 3`（实际文件中的长度为200，这里方便举例用3），三个文件数据格式为：

`train.inter`中的数据：
| user_id:token | item_id:token |timestamp:float | item_id_list:token_seq |
| :----: | :----: | :----: | :----: |
| 1 | 2 | xxxxx | 0 0 0 |
| 1 | 3 | xxxxx | 2 0 0 |
| 1 | 4 | xxxxx | 2 3 0 |
| 1 | 5 | xxxxx | 2 3 4 |
| 1 | 6 | xxxxx | 3 4 5 |

`valid.inter`中的数据：
| user_id:token | item_id:token |timestamp:float | item_id_list:token_seq |
| :----: | :----: | :----: | :----: |
| 1 | 7 | xxxxx | 4 5 6 |

`test.inter`中的数据：
| user_id:token | item_id:token |timestamp:float | item_id_list:token_seq |
| :----: | :----: | :----: | :----: |
| 1 | 8 | xxxxx | 5 6 7 |
| 1 | 9 | xxxxx | 6 7 8 |

①请问这样构造`item_id_list`的格式对吗？文件中的`user_id`和`item_id`均从`1`开始映射，也就是说文件中不存在user_id为0的user，且`item_id`为`0`的item仅起到补齐`MAX_ITEM_LIST_LENGTH`的作用，没有和user有实际交互的意义，这样的理解对吗？
②我用这三个文件作为输入运行`GRU4Rec、SASRec、BERT4Rec`这三个模型，仅有`BERT4Rec`可以顺利完成`train、valid、test`三个阶段，而`GRU4Rec、SASRec`均在`test`阶段报错，报错信息如下：
```
2022-09-22 14:00:04.982370: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Train     0: 100%|███████████████████████| 679/679 [03:32<00:00,  3.19it/s, GPU RAM: 6.29 G/10.92 G]
22 Sep 14:03    INFO  epoch 0 training [time: 212.53s, train loss: 4896.2551]
Evaluate   : 100%|███████████████████████| 100/100 [00:09<00:00, 10.78it/s, GPU RAM: 6.29 G/10.92 G]
22 Sep 14:03    INFO  epoch 0 evaluating [time: 9.91s, valid_score: 0.051800]
22 Sep 14:03    INFO  valid result: 
mrr@10 : 0.0149    mrr@20 : 0.0176    mrr@50 : 0.0205    recall@10 : 0.0492    recall@20 : 0.0895    recall@50 : 0.1862    ndcg@10 : 0.0227    ndcg@20 : 0.0328    ndcg@50 : 0.0518
22 Sep 14:03    INFO  Saving current: saved/SASRec-Sep-22-2022_14-00-09.pth
22 Sep 14:03    INFO  Loading model structure and parameters from saved/SASRec-Sep-22-2022_14-00-09.pth
Evaluate   :   5%|█▏                      | 10/198 [00:00<00:16, 11.32it/s, GPU RAM: 6.29 G/10.92 G]/opt/conda/conda-bld/pytorch_1614378098133/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [157,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1614378098133/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [157,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
......
...... n条一样的报错信息
......
/opt/conda/conda-bld/pytorch_1614378098133/work/aten/src/ATen/native/cuda/Indexing.cu:662: indexSelectLargeIndex: block: [108,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Evaluate   :   6%|█▎                      | 11/198 [00:01<00:20,  9.08it/s, GPU RAM: 6.29 G/10.92 G]
Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/root/work/GNN_RS/RecBole/RecBole-master/recbole/quick_start/quick_start.py", line 65, in run_recbole
    test_result = trainer.evaluate(test_data, load_best_model=saved, show_progress=config['show_progress'])
  File "/usr/local/miniconda3/envs/python37/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/work/GNN_RS/RecBole/RecBole-master/recbole/trainer/trainer.py", line 478, in evaluate
    self.eval_collector.eval_batch_collect(scores, interaction, positive_u, positive_i)
  File "/root/work/GNN_RS/RecBole/RecBole-master/recbole/evaluator/collector.py", line 151, in eval_batch_collect
    pos_matrix[positive_u, positive_i] = 1
RuntimeError: CUDA error: device-side assert triggered
```
**请问这是什么原因呢？问题有点多，麻烦了，非常感谢！**

**Comment by AoiDragon** [comment]
@XiaoLangLangY 你好，

1. 你的item_id_list格式不正确。你应该重复使用用户交互过的物品进行占位而不是用没有出现过的物品，可以参考我们官方文档中的[例子](https://recbole.io/docs/get_started/started/sequential.html?highlight=item_id_list)。你给出的示例的正确形式应该如下表所示。

<html>
<body>
<!DOCTYPE html>

user_id:token | item_id:token | item_id_list:token_seq
-- | -- | --
1 | 3 | 2 2 2
1 | 4 | 2 2 3
1 | 5 | 2 3 4
1 | 6 | 3 4 5


</body>
</html>

2. `RuntimeError: CUDA error: device-side assert triggered` 经常由索引超出标签数量限制导致，可能与你使用未出现的物品0占位有关。

**Comment by XiaoLangLangY** [comment]
你好，非常感谢你的回答！还有个疑问就是`item_id_list`中的元素顺序是不重要的么，我看官方文档里的顺序是乱的并没有按照用户的交互序列来，也就是说，例如上诉例子中 `user_id=1,item_id=4`那行的`item_id_list`可以是`2 2 3`、`2 3 2`、`3 2 2`中任意一种排列方式吗？

**Comment by AoiDragon** [comment]
是的

**Comment by zyx1017** [comment]
@XiaoLangLangY 你好，能问一下你是如何自制数据集的嘛？我在这方面遇到了困惑。

**Comment by night18** [comment]
Can the "user_id:token" be duplicated, if their item_id_list are different?
