### ISSUE TITLE
[🐛BUG]history_item_matrix(value_filed=None)方法返回history_value值只有0和1

### ISSUE THREAD

**Issue by cizhouyu** [RUCAIBox/RecBole#1446]
history_item_matrix(value_filed=None)方法返回的三个矩阵中，history_value表示用户交互记录的数值。
发现history_value中的数值仅包含0和1（如下图所示）。
![question1](https://user-images.githubusercontent.com/60316519/191934831-94df69d5-9540-4ebd-87d8-e5d6077dac6a.png)
请问：
1.history_value[i][j]中的数值含义为：用户i与物品j交互过，则取1；否则取0？
2.我想要获得用户i与物品j交互的具体评分（例如test_data中用户对物品的评分），应该怎么做呢？
（i指的是用户internal id；j指的是item internal id）

**Comment by zhengbw0324** [comment]
@cizhouyu 
问题1：当没有设置 value_fileds 的情况下，默认 value_fileds=None，此时 history_value 只会存在0和1，history_value[i][j] 为 1 代表用户 i 与物品 j 交互过，否则取0。

问题2：如果想设置具体评分，需要制指定 value_fileds ，如 `history_item_matrix(value_filed=self.rating_field)`。

**Comment by cizhouyu** [comment]
好的！感谢您的回复！
