### ISSUE TITLE
[🐛BUG] history_matrix[u]返回的物品id在原始数据集中找不到

### ISSUE THREAD

**Issue by cizhouyu** [RUCAIBox/RecBole#1447]
数据集：movielens-100k
算法：BPR
我希望获得用户u在数据集中交互过的物品列表，因此调用了recbole.data.dataset中history_item_matrix(value_filed=None)方法，利用返回的矩阵history_matrix[u]获得了用户交互过的物品id列表[i_1,i_2,...,i_n]。但是我发现有一些[u,i_k]在原始数据集ml-100k.inter中并不存在，这与我的想法出现了矛盾。
如下图所示，打印id为119用户的历史交互物品列表：
![question2-1](https://user-images.githubusercontent.com/60316519/191936777-ccc26a0f-ad7e-48cc-a684-22199d04c6f0.png)
可以看到其中有物品146.但是我在ml-100k.inter中查找用户-物品对119-146时，发现并不存在，如下图所示。
![question2-2](https://user-images.githubusercontent.com/60316519/191937163-77e42e9b-a0b1-48b3-9952-5287259fd71e.png)
请问是我哪里写得不对/理解得不对吗？我希望获得用户u在数据集中交互过的物品列表及其评分，应该怎么做呢？谢谢！

**Comment by AoiDragon** [comment]
@cizhouyu 你好

1. RecBole会对数据集中的id进行remap操作，因此内部数据集的索引和原始数据集中的是不一致的。

2. 可以通过指定history_item_matrix的value_field参数为评分对应的field来获得评分。

**Comment by cizhouyu** [comment]
谢谢！
我发现有一些用户-物品对转换为user token：item token后，在原始数据集ml-100k.inter中仍然找不到（有一些可以找到，比如user token="1"交互过的物品集合）。如下图所示，user token="11"，item token="32"时，在原始数据集ml-100k.inter中找不到对应的数据。
![question2-3](https://user-images.githubusercontent.com/60316519/192316543-d4a50355-4421-4d74-86ed-36c7f4d5d580.png)
请问我如何修正它呢？谢谢！

**Comment by cizhouyu** [comment]
噢 是我自己的问题，不好意思。我应该再运行一句看结果。
