### ISSUE TITLE
用户评价指标保存问题

### ISSUE THREAD

**Issue by W-Douglas** [RUCAIBox/RecBole#1452]
你好，请问如何保存每个用户在模型上的评价指标如NDCG等，是通过相应参数的修改还是另外的计算

**Comment by zhengbw0324** [comment]
@W-Douglas 
你好，目前伯乐还不支持保存每个用户的评价指标。如果需要可以尝试修改代码，保存在计算指标时的中间结果。

**Comment by W-Douglas** [comment]
感谢您的回复，我同时注意到在case_study文件有full_sort_scores函数，那么这个函数在计算scores时使用的是什么指标？是在配置文件中人为规定的吗？

**Comment by zhengbw0324** [comment]
@W-Douglas
`full_sort_scores`函数里面是使用模型的`full_sort_predict`函数求用户对每个物品的score，这个score你可以类比点击率，越大代表用户对该物品越感兴趣，没有实际意义，只是用于对物品排名，与各种评价指标不是一个东西。
