### ISSUE TITLE
License问题

### ISSUE THREAD

**Issue by leoleoasd** [RUCAIBox/RecBole#1453]
请问为什么中文版的readme中有『本项目的所有数据和代码只能被用于学术目的』而英文版的没有呢？

如果使用MIT License，许可证并不对用途做出任何要求。如果你们希望『本项目的所有数据和代码只能被用于学术目的』，需要写一份和 MIT 兼容的补充License，作为附加条款，一起放到 LICENSE 文件中

**Comment by AoiDragon** [comment]
@leoleoasd 

感谢你对伯乐的关注和建议，我们会在近期完成修改。
