### ISSUE TITLE
Error installing RecBole

### ISSUE THREAD

**Issue by therealadarsh** [RUCAIBox/RecBole#1456]
I tried to install recbole using Conda, pip and from the local source but I am getting error generating the metadata.
![err_1](https://user-images.githubusercontent.com/54485879/193064641-fff0132b-890a-47fd-aeee-0933158afa5b.jpg)
![err_2](https://user-images.githubusercontent.com/54485879/193064649-5019a71a-d0b5-470f-b69f-08f37f646a81.jpg)
![err_3](https://user-images.githubusercontent.com/54485879/193064662-bc2d15d8-c1dc-43a4-9b6a-44abee5a643a.jpg)

**Comment by zhengbw0324** [comment]
@therealadarsh 
You can try to reduce the Python version to 3.9.
