### ISSUE TITLE
有关会话推荐模型的问题

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#1472]
您好，我今天更新了Recbole框架，在运行基于会话的推荐模型时出现问题：
Q1.配置文件中 `train_neg_sample_args` 这个参数需要指定为None。此问题我已经解决。

Q2.在跑 SR-GNN / GC-SAN 模型时代码报错，使用的数据集是 `CORE` 论文提供的数据集和配置文件。在8月跑的时候是可以跑通的。今天更新后代码报错：
  File "Anaconda3\lib\site-packages\recbole\model\abstract_recommender.py", line 130, in __init__
    self.n_items = dataset.num(self.ITEM_ID)
AttributeError: 'list' object has no attribute 'num'

**Comment by zhengbw0324** [comment]
@DX12321 您好！
Q1：在新版本的RecBole中，我们将原来的参数`neg_sampling ` 替换为了 `train_neg_sample_args `，因此配置文件中需要更改参数名称。
Q2：我目前无法判断准确原因，但应该与数据集配置有关，如果更改了`train_neg_sample_args `仍有问题，请您提供一下您的配置参数。
