### ISSUE TITLE
关于数据集处理问题

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1484]
作者您好！我在使用recbole的general dataset，**以movielens-100k为例**，有以下几个问题需要请教:
1.bole是否支持dataset的深拷贝？我看到dataset实现了copy，但是内部调用的是copy.copy？
2.有关数据集的处理，general mode的 dataset支持在初始化dataset后再对内部的交互进行修改吗？该如何做呢？
**更具体来说，我遇到的问题是我试图深拷贝一份已经完成初始化的dataset1，拷贝的这个新数据集为dataset2。我想对dataset2调用自定义函数删除其中的一些交互。**
对此，我对已经完成了初始化的dataset2调用了自定义函数，这个函数的写法参照了bole自带的_filter_inter_by_user_or_item函数，您可以理解成我写了这样一行代码:
dataset2._filter_inter_by_user_or_item()
最后报错如下。
File "F:\RecBole-master\recbole\data\dataset\dataset.py", line 1095, in _filter_inter_by_user_or_item
    remained_inter = pd.Series(True, index=self.inter_feat.index)
  File "F:\RecBole-master\recbole\data\interaction.py", line 131, in __getattr__
    raise AttributeError(f"'Interaction' object has no attribute '{item}'")
AttributeError: 'Interaction' object has no attribute 'index'
似乎初始化之后无法获取到feat_mat.index这个参数了，这种情况应该如何处理呢？
可能有些乱，不好意思。

**Comment by AoiDragon** [comment]
@ithok 你好，

1. RecBole没有自带的深拷贝方法，你可以使用`copy.deepcopy()`对数据集进行深拷贝。

2. 我按照你的步骤调用了深拷贝后的数据集的`_filter_inter_by_user_or_item()`方法，但并没有出现相同的报错信息，可能是你的自定义函数中存在错误。

**Comment by ithok** [comment]
您好，我是在model里对dataset调用的_filter_inter_by_user_or_item()方法，不论是拷贝后的还是正常调用都是找不到index的。
**具体原因我也排查了一下，似乎是dataset在初始化的时候feat一直维持着dataframe，在初始化结束后会变为interaction，因此index无法再被索引到。您可以查看一下是否有类似的问题。**
因此我的做法是把interaction状态的inter_feat复制出来处理后生成newinter_feat，之后调用dataset自带的copy方法把newinter_feat传进去。
不知道这样会改变数据集的用户数参数之类的吗？

**Comment by ithok** [comment]
还有一个关于dataloader的问题，bole中的data preparation对原始dataset进行划分后得到了三个dataloader。
这里我想对其中的train_dataloader中的train_dataset进行更改，操作内容是把这个dataset中的交互去除一部分。我的做法是把交互矩阵读取出来，然后修改完成以后形成new_dataset。之后，我直接生成原本的train_dataloader的一个副本aux_dataloader，然后把aux_dataloader的dataset参数改成我修改后的new_dataset。
我有点担心这样做以后aux_dataloader的sampler的运作会出现我意想不到的bug，但我不知道具体会有什么影响，不知道您有没有头绪。

**Comment by AoiDragon** [comment]
`dataset`在`build()`后会将`Dataframe`类型的数据转换为`Interaction`类型，因此无法用index索引。`dataset`的`copy`方法只会更改`inter_feat`，不会修改数据集的其他属性。
