### ISSUE TITLE
[🐛BUG] 运行NCL的代码时报错

### ISSUE THREAD

**Issue by guhahaha** [RUCAIBox/RecBole#1487]
**屏幕截图**
![image](https://user-images.githubusercontent.com/97571749/195303897-61d786c8-5d33-43d3-9598-8184bed4e7d9.png)

**链接**
https://github.com/RUCAIBox/NCL

**实验环境（请补全下列信息）：**
 - 操作系统: [Windows]
- RecBole 版本 [1.0.0]
 - Python 版本 [3.7.7]
- PyTorch 版本 [1.7.1]
- cudatoolkit 版本 [11.0]

**Comment by AoiDragon** [comment]
@guhahaha 你好，

报错信息显示您的atomic file的后缀名称不正确，您可以检查一下配置文件中的相关字段。另外您也可以选择从我们提供的百度网盘链接下载数据集（参考[这里](https://recbole.io/docs/user_guide/data/dataset_download.html)）再使用。
