### ISSUE TITLE
请教一个关于dataloader处理的问题

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1489]
问题是这样，bole在对原始数据集作划分后会得到三个划分后的dataloader（train,valid,test)。我目前的需求是要对训练用的train_data做交互删减形成一个**辅助训练数据集**，但是bole提供的dataloar创建的现成接口只能用于数据预处理（或者我还没有发现其他方式），所以目前我不知道如何能达成我的目的。
目前我尝试的方法是，把train_data这个dataloader中的数据集提取出来，做完处理以后形成一个aux_dataset再依此创建一个辅助dataloader便于我在trainer中调用，但是这里存在的问题是。
![image](https://user-images.githubusercontent.com/37830886/195503917-b021809e-e140-4825-ba6f-da62c2b6b6d6.png)
我试图这样去创建我的辅助dataset的dataloader，因为我的辅助dataset和原本训练用的dataset只有交互上的区别，所以我没有变更sampler，直接用已经初始化好的train_data的sampler代替了，其结果就是，虽然这行代码运行没问题，但是当我实际去迭代辅助数据集中的数据时:
![image](https://user-images.githubusercontent.com/37830886/195504413-7110fb4b-20ec-479e-9273-76b923b05b76.png)
会产生这样的错误
![image](https://user-images.githubusercontent.com/37830886/195504481-ca79773f-2033-4230-be1a-ee5952a6a21d.png)

请问这种情况应该如何解决，或者有什么更好的做法吗

**Comment by AoiDragon** [comment]
这是因为您没有正确从`DataLoader`中获取用于负采样的`sampler`。

RecBole的`DataLoader`继承自PyTorch的`DataLoader`，而PyTorch的`DataLoader`中也有`sampler`成员。为了避免冲突，RecBole将用于负采样的`sampler`命名为`_sampler`。因此您需要将`get_dataloader`中的参数修改为`train_data._sampler`。
