### ISSUE TITLE
[💡SUG] 是否有商品的时效性推荐？或按照商品字段值里的标签——有效性1，无效0进行推荐

### ISSUE THREAD

**Issue by taogeanton3** [RUCAIBox/RecBole#1490]
是否有商品的时效性按照日期衰减进行推荐？
或按照商品字段值里的标签——有效性1，无效0进行推荐

**Comment by zhengbw0324** [comment]
@taogeanton3 您好！
目前RecBole并没有您所说的功能，如果需要您可以尝试自己实现。
