### ISSUE TITLE
[💡SUG] 关于推荐任务问题

### ISSUE THREAD

**Issue by luanxian1** [RUCAIBox/RecBole#1492]
首先十分感谢你们能开源这样一个功能强大的库。在你们的代码你们实现的都是topn任务，我想请教一下是否可以将topn任务改成评分预测任务？或者如果有做评分预测版本的代码那就更好了

**Comment by AoiDragon** [comment]
@luanxian1 你好，RecBole目前还不包括评分预测任务。
