### ISSUE TITLE
关于数值特征离散化问题

### ISSUE THREAD

**Issue by Superboshen** [RUCAIBox/RecBole#1493]
您好，请问为何数值型特征离散化后会变成一个list
我对.inter文件的“rating”特征离散化后，为何rating由原来的数值变成了一个结尾是1的list

原来的rating：
<img width="996" alt="截屏2022-10-17 14 43 18" src="https://user-images.githubusercontent.com/39661614/196106881-c6bc4671-f027-4130-ac1e-847f0dc83dd8.png">

离散化后的rating：
<img width="633" alt="截屏2022-10-17 14 38 49" src="https://user-images.githubusercontent.com/39661614/196106573-7294422d-bdfa-476c-8a51-b20d342a319c.png">

**Comment by zhengbw0324** [comment]
@Superboshen 您好！
我们在数据加载时会对 float 类型的数据进行归一化，如您提到的数据中1会归一化为0.0，3会归一化为0.5。最终的 list 类型中的第一个数值即为归一化后的数据。第二个数值则为这个数据所在桶（bucket）的 index，这个 index 会在对 float 特征进行 embedding 时使用。如果您在配置文件中没有针对本列设置`discretization`参数，那么默认仅有一个桶（bucket），所有数据的 index 都会为1.0。
此外，对 float 数据的离散化配置可以参考我们的[文档](https://recbole.io/docs/user_guide/config/data_settings.html)，我们的方法主要参考论文（An Embedding Learning Framework for Numerical Features in CTR Prediction）。关于 float 数据的 embedding 也可以阅读我们的源码：https://github.com/RUCAIBox/RecBole/blob/5c07ac44c56641c5bbe9aea04d7d2a554494c698/recbole/model/layers.py#L153
