### ISSUE TITLE
AttributeError: 'MetaDataLoader' object has no attribute 'sample_size'

### ISSUE THREAD

**Issue by non-knife** [RUCAIBox/RecBole#1494]
我在运行RecBole-MetaRec这个拓展包的时候，运行quickstart.py文件，报出这个错误，请问是哪里出现问题了

> Traceback (most recent call last):
>   File "C:/Users/Administrator/Desktop/RecBole-MetaRec-master/quickstart.py", line 4, in <module>
>     metaQuickStart(modelName, datasetName)
>   File "C:\Users\Administrator\Desktop\RecBole-MetaRec-master\recbole_metarec\MetaUtils.py", line 348, in metaQuickStart
>     train_data, valid_data, test_data = meta_data_preparation(config, dataset)
>   File "C:\Users\Administrator\Desktop\RecBole-MetaRec-master\recbole_metarec\MetaUtils.py", line 84, in meta_data_preparation
>     train_data = MetaDataLoader(config, train_dataset, train_sampler, shuffle=True)
>   File "C:\Users\Administrator\Desktop\RecBole-MetaRec-master\recbole_metarec\MetaDataLoader.py", line 41, in __init__
>     super(MetaDataLoader, self).__init__(config, dataset, sampler, shuffle)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\recbole\data\dataloader\abstract_dataloader.py", line 65, in __init__
>     dataset=list(range(self.sample_size)),
>   File "C:\ProgramData\Anaconda3\lib\site-packages\recbole\data\dataloader\abstract_dataloader.py", line 112, in __getattribute__
>     return super().__getattribute__(__name)
> AttributeError: 'MetaDataLoader' object has no attribute 'sample_size'

**Comment by non-knife** [comment]
已解决，换用recbole1.0.1版本

**Comment by chenyuwuxin** [comment]
@non-knife 您好，感谢您对RecBole的关注！
我们已经对子包的兼容性问题进行了修复，您可以使用recbole 1.1.1版本运行元学习相关模型！非常感谢您的反馈与支持。
