### ISSUE TITLE
.iter文件中的其他特征如何引入模型训练

### ISSUE THREAD

**Issue by Jia-py** [RUCAIBox/RecBole#1495]
请问.iter文件中除user_id与item_id外的特征，如AliEC数据集中的场景id特征，如何引入模型训练呢？读了部分代码，似乎只能引入用户和item各自的特征。

**Comment by zhengbw0324** [comment]
@Jia-py 您好！
我们目前没有模型是需要使用.inter文件的其他特征的。常见的推荐模型也很少使用这些特征，因为在训练过程中我们需要采样负例，针对负例，我们无法生成相应特征。
