### ISSUE TITLE
选择验证排序模式为uni时报错

### ISSUE THREAD

**Issue by garyspnong** [RUCAIBox/RecBole#1496]
我想测试EASE在ml-100k上的结果，我不想要全排序，所以把'eval_args' :改成{'mode': 'uni100'}的时候报错RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Double for the source.请问要怎么解决

**Comment by AoiDragon** [comment]
@garyspnong 你好，从报错信息看是由于您处理的数据类型不一致，您可以回到报错信息指出的代码处将数据类型统一为`Float`或`Double`。

**Comment by AoiDragon** [comment]
@garyspnong 
您好，感谢您对伯乐的关注。我们已在#1497 中修复了这个bug。
