### ISSUE TITLE
有关dataset与sampler的问题，是否支持通过inter_feat新建一个dataset？

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1498]
RT,我不是很清楚除了常规的初始化，bole是否还支持其他的数据集初始化方法。
具体来说，我有一个需求，需要在一个数据集的基础上修改形成一个新的数据集dataset2，dataset2不仅仅是交互矩阵变化了，包括user_num和item_num这种数据也会变化，换而言之，除了需要以原数据集为输入条件以外，dataset2几乎就是一个新数据集了，而bole似乎只提供了copy inter_feat来新建new dataset的方法。
所以我想了解的就是，bole是否实现了RT所述的新建dataset的api（除了inter_feat外，dataframe也可以？），或是有什么比较快捷的方法能解决这个问题吗？

除此之外，关于sampler的问题，bole的示例代码里的sampler都基于train,valid,test划分来进行。**这里的问题是我的dataset2是一个辅助数据集，它的设定是整个数据集都被用于训练。但是如果我不对dataset进行test和valid的划分，我似乎无法得到对应的sampler**。不知道这种情况应该如何解决呢？

感谢bole团队的辛勤付出，如果bole有类似辅助数据集的实现案例希望能够请教，言语组织不是很流畅，烦请见谅。

**Comment by zhengbw0324** [comment]
@ithok 您好！
（1）对于第一个问题，我想您是希望创建一个与 dataset1 参数配置相同但数据不同的数据集，您可以使用相同的配置文件进行数据集创建。而如果需要数据集复制，您可以使用 python 自带的 copy 库进行完整的 dataset 复制。
（2）对于第二个问题，您可以使用从 benchmark_filename 读入数据的方法（详见[文档](https://recbole.io/docs/user_guide/config/data_settings.html)），然后参考 utils.py 文件中的`data_preparation`函数自定义数据处理过程即可。
