### ISSUE TITLE
请问bole是否有支持p值的api？

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1511]
RT。
就是为了排除实验偶然性的p值，我没有在文档中发现类似的设定，也可能只是我没有发现。
非常感谢！

**Comment by zhengbw0324** [comment]
@ithok 您好！
您的意思是控制实验的可复现吗？可以通过设置`seed`和`reproducibility (bool)`参数控制实验的复现性，具体信息可以参考[文档](https://recbole.io/docs/user_guide/config/environment_settings.html)。
