### ISSUE TITLE
[🐛BUG] No module named 'ray' error when importing quick_start module on v1.1.1

### ISSUE THREAD

**Issue by petrov826** [RUCAIBox/RecBole#1518]
Hello RecBole team! Thank you for releasing v.1.1.1😄

**Describe the bug**
I'm trying to use distributed training which was implemented in v1.1.1. I found that when importing `recbole.quick_start.quick_start` module, `ModuleNotFoundError: No module named 'ray'` raises.

**To Reproduce**
On google colab, ran below code.
```python
!pip install recbole -Uqqq

import recbole
recbole.__version__ # returns 1.1.1

from recbole.quick_start.quick_start import (
    run_recbole,
    objective_function,
    load_data_and_model,
    run_recboles,
)
```
**Stacktrace**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-a7dac08d3310>](https://localhost:8080/#) in <module>
----> 1 from recbole.quick_start.quick_start import (
      2     run_recbole,
      3     objective_function,
      4     load_data_and_model,
      5     run_recboles,

1 frames
[/usr/local/lib/python3.7/dist-packages/recbole/quick_start/__init__.py](https://localhost:8080/#) in <module>
----> 1 from recbole.quick_start.quick_start import (
      2     run_recbole,
      3     objective_function,
      4     load_data_and_model,
      5     run_recboles,

[/usr/local/lib/python3.7/dist-packages/recbole/quick_start/quick_start.py](https://localhost:8080/#) in <module>
     19 
     20 import pickle
---> 21 from ray import tune
     22 
     23 from recbole.config import Config

ModuleNotFoundError: No module named 'ray'
```

**Expected behavior**
Successfully import `quick_start` module.

**Desktop**
- platform: [Google Colab]
- OS: [Linux]
- RecBole Version [1.1.1]
- Python Version [3.7.15]

**Comment by AoiDragon** [comment]
Hello @petrov826 ,

It seems that you didn't install ray. You can run `pip install ray` then try again.

**Comment by petrov826** [comment]
Thank you @AoiDragon. I'll install it manually and try again.

I thought RecBole v.1.1.1 comes with all necessary packages, because`conda install -c pytorch pytorch` also installs  `setuptools`, `sqlite`, `typing_extensions` and more.
