### ISSUE TITLE
[🐛BUG] 为什么新建同级目录下不能引用

### ISSUE THREAD

**Issue by SEVEN77777777777** [RUCAIBox/RecBole#1527]
**描述这个 bug**
ModuleNotFoundError: No module named 'recbole.model.fmnet

我把fmnet.py新建在model文件夹中，与layers.py同一级目录，为什么可以引用layers，但是不能引用fmnet？

**Comment by AoiDragon** [comment]
@SEVEN77777777777 你好，我按照你的方法在model文件夹下添加了测试用的.py文件，是可以正常引用的。请检查一下是否是其他方面的问题。
