### ISSUE TITLE
请问是否支持在超参数调节时输出日志？

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1529]
RT,运行均无问题，但发现使用recbole的超参数搜索时，日志不如单次运行时输出的完整。
具体来说,当我调用LightGCN模型进行超参数搜索时，运行过程中log的输出是这样的:
![image](https://user-images.githubusercontent.com/37830886/200606188-1a3b1572-9d1c-4032-bf9e-0646cf114fad.png)
打个比方就是甚至不太知道模型是否在运行。
而固定好参数，或者说在相同设置下执行run.py时日志输出是这样的:
![image](https://user-images.githubusercontent.com/37830886/200606675-80627890-b98a-4569-8bb9-d1f80326cdc1.png)

请问这种情况就是正常bole执行超参搜索的情况还是我设置有什么不到位的地方吗？是否可以设置成每轮日志输出结果呢？

非常感谢bole团队的工作！

**Comment by zhengbw0324** [comment]
@ithok 您好！
您如果希望打印完整的输出可以通过修改 [quick_start.py](https://github.com/RUCAIBox/RecBole/blob/master/recbole/quick_start/quick_start.py) 文件中的 `objective_function` 函数实现，在函数中设置训练和验证过程显示日志，以训练为例：在以下代码处https://github.com/RUCAIBox/RecBole/blob/51392878edff5454d7c7442125015cea23acf955/recbole/quick_start/quick_start.py#L146-L148
修改参数`verbose=True`并添加`show_progress=True`。

这种设置后会使得日志信息非常多，且在超参数搜索的过程中打印大量干扰信息，个人不推荐这样做，如果只是想知道代码是否在运行，可以通过`nvidia-smi`命令查看 gpu 状态实现。

**Comment by ithok** [comment]
好的，非常感谢您的回复！

**Comment by paul0728** [comment]
請問有沒有辦法讓它只紀錄最佳設置參數以及集最佳結果？謝謝
