### ISSUE TITLE
为什么超参数搜索需要设置early stop？

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1532]
RT。
![image](https://user-images.githubusercontent.com/37830886/201084279-9318b4c1-bdaf-4ae4-ae2c-d4aa8313497d.png)
我在对baseline进行grid search的时候出现了earlystoping，我想了解的是bole是根据什么来决定early stop的？
如果我没有理解错误的话，是超参数的组合对性能没提升10次就停止搜索，那么超参数的顺序就会起到很关键的作用，而early stop默认只有10，在超参组合大的情况下基本不可能搜索到最优解。和单次模型运行不一样的是，超参数的组合是没法至少保证是在loss减小的方向上的，这样做不就有点问题吗？
所以主要就是想请教一下，是否bole真的是按我描述的这样对超参数进行搜索，还是我理解存在了错误，因为我是需要对baseline进行搜索，网格搜索early stop的结果似乎不太具有说服力？
非常感谢！

**Comment by zhengbw0324** [comment]
@ithok 您好！
您可以在`run_hyper.py`文件内根据实际情况修改`early_stop`参数。

**Comment by ithok** [comment]
好的
