### ISSUE TITLE
[🐛BUG] 更改quickstart.py文件中模型和数据名，train loss始终为0

### ISSUE THREAD

**Issue by Anna1015** [RUCAIBox/RecBole#1533]
**描述这个 bug**
运行 RecBole-MetaRec的quickstart.py文件，只更改了modelName, datasetName = 'MAMO', 'ml-1m'。运行结果如下，train loss始终为0。

12 Nov 21:12    INFO  epoch 0 training [time: 17.81s, train loss: 0.0000]
12 Nov 21:13    INFO  epoch 0 evaluating [time: 1.53s, valid_score: 0.735000]
12 Nov 21:13    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:13    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

12 Nov 21:13    INFO  epoch 1 training [time: 16.26s, train loss: 0.0000]
12 Nov 21:13    INFO  epoch 1 evaluating [time: 1.50s, valid_score: 0.735000]
12 Nov 21:13    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:13    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

12 Nov 21:13    INFO  epoch 2 training [time: 16.39s, train loss: 0.0000]
12 Nov 21:13    INFO  epoch 2 evaluating [time: 1.50s, valid_score: 0.735000]
12 Nov 21:13    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:13    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

12 Nov 21:13    INFO  epoch 3 training [time: 20.08s, train loss: 0.0000]
12 Nov 21:13    INFO  epoch 3 evaluating [time: 1.67s, valid_score: 0.735000]
12 Nov 21:13    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:13    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

12 Nov 21:14    INFO  epoch 4 training [time: 17.91s, train loss: 0.0000]
12 Nov 21:14    INFO  epoch 4 evaluating [time: 1.50s, valid_score: 0.735000]
12 Nov 21:14    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:14    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

12 Nov 21:14    INFO  epoch 5 training [time: 19.33s, train loss: 0.0000]
12 Nov 21:14    INFO  epoch 5 evaluating [time: 1.68s, valid_score: 0.735000]
12 Nov 21:14    INFO  valid result: 
precision@5 : 0.5674    recall@5 : 0.5674    hit@5 : 0.9968    ndcg@5 : 0.5593    mrr@5 : 0.735
12 Nov 21:14    INFO  Saving current: saved/MAMO-Nov-12-2022_21-12-41.pth

**实验环境：**
 - 操作系统: [macOS]
- RecBole 版本 [如 1.1.1]
 - Python 版本 [如 3.7]

**Comment by AoiDragon** [comment]
@Anna1015 您好，关于RecBole子库的问题可以在[对应仓库](https://github.com/nuster1128/RecBole-MetaRec)内提问。
