### ISSUE TITLE
[🐛BUG] No module named 'recbole.data.transform'

### ISSUE THREAD

**Issue by tctctctctc** [RUCAIBox/RecBole#1534]
**描述这个 bug**
在较新的版本中，abstract_dataloader引入报错

**屏幕截图**
![image](https://user-images.githubusercontent.com/31268918/201522646-1e9fcd45-1745-491e-88da-9619688cd2ab.png)

**实验环境（请补全下列信息）：**
 - 操作系统:  Windows
- RecBole 版本 [master]
 - Python 版本 [如 3.6.8]
- PyTorch 版本 [如 1.10.0]

**Comment by zhengbw0324** [comment]
@tctctctctc 您好！
仅通过您提供的信息，我还不能确定具体原因，但建议您将 python 版本更新为 3.7-3.9 重新尝试。如果还是存在问题，可以尝试从 GitHub 重新 clone 代码，目前 GitHub 应该没有问题。

**Comment by tctctctctc** [comment]
感谢，问题已解决！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月14日(星期一) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RUCAIBox/RecBole] [🐛BUG] No module named &#39;recbole.data.transform&#39; (Issue #1534)





 
@tctctctctc 您好！
 仅通过您提供的信息，我还不能确定具体原因，但建议您将 python 版本更新为 3.7-3.9 重新尝试。如果还是存在问题，可以尝试从 GitHub 重新 clone 代码，目前 GitHub 应该没有问题。
