### ISSUE TITLE
如何使用amazon的beauty和sports数据集

### ISSUE THREAD

**Issue by lalunex** [RUCAIBox/RecBole#1536]
你好，我想问一下如何在线使用amazon的beauty和sports数据集（我本地没有数据集文件）

我设置的dataset=‘Amazon_Beauty’，但是爆出了下面的错误，这是什么原因呢？
那我应该用什么办法才可以正确的在网上下载对应的数据集，并在本地的模型中使用该数据集？

!!!Note: hyper-parameter analysis, embedding size:[100]
15 Nov 21:53    INFO  
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 42
state = INFO
reproducibility = True
data_path = dataset/Amazon_Beauty
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 256
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = {'max_norm': 5.0, 'norm_type': 2}
weight_decay = 0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'group_by': 'user', 'order': 'TO', 'split': {'LS': 'valid_and_test'}, 'mode': 'full'}
repeatable = True
metrics = ['Hit', 'NDCG', 'MRR']
topk = [1, 5, 10, 20]
valid_metric = Hit@20
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 	
seq_separator =  
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = (4, inf)
item_inter_num_interval = (4, inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters: 
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.SEQUENTIAL
scheduler = False
step_size = 4
gamma = 0.1
num_layers = 1
dropout_prob = 0.3
loss_type = BPR
initializer_range = 0.02
step = 1
sub_model = BERT4Rec
data_augmentation = True
our_att_drop_out = 0.2
our_ae_drop_out = 0.3
gumbel_temperature = 0.5
is_gumbel_tau_anneal = True
long_tail_rate = 0.95
pre_train_model_dict = {'amazon-sports-outdoors': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-14-44.pth', 'NARM': 'saved/NARM-May-17-2022_13-16-07.pth', 'Caser': 'saved/Caser-May-17-2022_13-17-42.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-20-26.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-27-07.pth', 'STAMP': 'saved/STAMP-May-17-2022_14-20-57.pth', 'DSAN': 'saved/DSAN-May-19-2022_23-25-56.pth'}, 'ml-100k': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-13-42.pth', 'NARM': 'saved/NARM-May-19-2022_19-31-33.pth', 'Caser': 'saved/Caser-May-17-2022_13-13-56.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-14-04.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-14-14.pth', 'STAMP': 'saved/STAMP-May-17-2022_13-14-49.pth'}, 'yelp': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-15-01.pth', 'NARM': 'saved/NARM-May-17-2022_13-17-59.pth', 'Caser': 'saved/Caser-May-17-2022_13-26-00.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-30-05.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-45-49.pth', 'STAMP': 'saved/STAMP-May-17-2022_14-27-11.pth'}, 'amazon-beauty': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-13-26.pth', 'NARM': 'saved/NARM-May-17-2022_13-14-20.pth', 'Caser': 'saved/Caser-May-17-2022_13-16-13.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-17-49.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-21-48.pth', 'STAMP': 'saved/STAMP-May-17-2022_14-05-50.pth'}, 'amazon-clothing-shoes-jewelry': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-32-16.pth', 'NARM': 'saved/NARM-May-17-2022_13-34-29.pth', 'Caser': 'saved/Caser-May-17-2022_13-37-12.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-40-44.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-46-02.pth', 'STAMP': 'saved/STAMP-May-17-2022_15-03-23.pth'}, 'ml-1m': {'GRU4Rec': 'saved/GRU4Rec-May-17-2022_13-13-41.pth', 'NARM': 'saved/NARM-May-17-2022_13-14-36.pth', 'Caser': 'saved/Caser-May-17-2022_13-15-33.pth', 'BERT4Rec': 'saved/BERT4Rec-May-17-2022_13-16-38.pth', 'SASRec': 'saved/SASRec-May-17-2022_13-27-12.pth', 'STAMP': 'saved/STAMP-May-17-2022_13-39-43.pth'}}
load_pre_train_emb = False
embedding_size = 100
n_layers = 2
n_heads = 2
hidden_size = 100
inner_size = 100
hidden_dropout_prob = 0.5
attn_dropout_prob = 0.5
hidden_act = gelu
layer_norm_eps = 1e-12
mask_ratio = 0.6
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
eval_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}

Traceback (most recent call last):
  File "/home/bigdata6/ll/HSD-main/run_hsd.py", line 337, in <module>
    main(model, dataset, sub_model)
  File "/home/bigdata6/ll/HSD-main/run_hsd.py", line 57, in main
    dataset = create_dataset(config)
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/utils.py", line 70, in create_dataset
    dataset = dataset_class(config)
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/sequential_dataset.py", line 36, in __init__
    super().__init__(config)
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/dataset.py", line 108, in __init__
    self._from_scratch()
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/dataset.py", line 118, in _from_scratch
    self._load_data(self.dataset_name, self.dataset_path)
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/dataset.py", line 267, in _load_data
    self._download()
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/dataset.py", line 234, in _download
    url = self._get_download_url("url")
  File "/home/bigdata6/anaconda3/envs/ll_torch10/lib/python3.9/site-packages/recbole/data/dataset/dataset.py", line 227, in _get_download_url
    raise ValueError(
ValueError: Neither [dataset/Amazon_Beauty] exists in the device nor [Amazon_Beauty] a known dataset name.

**Comment by zhengbw0324** [comment]
@lalunex 您好！
我们将 RecBole 中的数据集整理在 [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) 仓库中，您可以在该仓库中下载相应数据集数据（注意不要下载以 example 结尾的示例数据）。此外，如果希望在代码运行时下载默认数据集，您可以查看 RecBole 包下 recbole/properties/dataset/url.yaml 文件，其中包含了所有支持自动下载的数据集名称与URL。

**Comment by lalunex** [comment]
感谢的你的回复，我的问题解决了
