### ISSUE TITLE
运行SASRec时，评估模式设置为“full”时运行一次评估所需时间比“uni100”短

### ISSUE THREAD

**Issue by ShowTBC** [RUCAIBox/RecBole#1537]
1、对于基于内积计算交互得分的模型，能否在“抽样排序”上也使用和“全排序”类似的加速策略，对于一条数据，直接与候选item集的的所有item进行内积运算。
2、对于序列推荐模型，注意到在创建dataloader时，本框架是将.inter文件中的除'user_id'外所有的特征都构建了序列，这样会占用极大内存，如果.inter文件比较大就会导致内存不足，能否在这方面考虑优化一下，比如构建序列时仅保存索引，然后dataloader取数时再通过索引取出对应特征。

**Comment by AoiDragon** [comment]
@ShowTBC 感谢您对伯乐的关注，我们会考虑在下一次开发中进行这方面的改进。
