### ISSUE TITLE
Is the model after Trainer.fit the best model or the last model?

### ISSUE THREAD

**Issue by PosoSAgapo** [RUCAIBox/RecBole#1538]
Hi, thank you for making this wonderful repository and I learned a lot from it. 
There is a question  I would like to ask:
Is the model after Trainer.fit the best model or the last model?
As the progress bar will show which epoch gives the best model, I wonder after the training, is the model after trainer.fit the best model or just the last model? Since I would like to inference after trainer.fit, do I have to load model from the disk to get the best model or the model is already the best model on the validation set?

**Comment by zhengbw0324** [comment]
@PosoSAgapo 
Hello, after completing the training, we will save the model with the best performance on the verification set.

**Comment by PosoSAgapo** [comment]
> save the model with the b

Yes. I know that the RecBole will save the best model on the validation set. 
However, I did not intend to load the model from the disk, so I would like to know, after the trainer.fit, the model I have after training, is it the best model or the last model? I know that best model on the validation set is saved.

**Comment by zhengbw0324** [comment]
@PosoSAgapo 
Each epoch model will be updated, and the model is the final epoch model in the training process

**Comment by PosoSAgapo** [comment]
Thanks! Your resposne helps a lot!
