### ISSUE TITLE
How to set negative sampling num in hyper parameter tuning?

### ISSUE THREAD

**Issue by PosoSAgapo** [RUCAIBox/RecBole#1540]
Previously, the negative sampling hyperparameter is set as `training_neg_sample_num`, but not it is deprecated. I would like to set it as a hyperparameter, but config it as a dict like` [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]` raises an error in the run_hyper.py.

**Comment by zhengbw0324** [comment]
@PosoSAgapo 
The negative sampling parameters are the configuration associated with the dataset. Our hyperparameter search only supports the hyperparameters associated with the model.

**Comment by PosoSAgapo** [comment]
@zhengbw0324 
Thank you for your detailed explanation. However,  negative sampling is a very important hyperparameter, especially for datasets of implicit feedback which is usually only trainable using negative sampling. It would be wonderful to also include the negative sampling as part of the hyperparameter tune.
