### ISSUE TITLE
[🐛BUG] 你好，我用movielens_1m数据集  运行模型，出现下面的错误，请问该怎么解决呢？

### ISSUE THREAD

**Issue by MambaDong** [RUCAIBox/RecBole#1541]
你好，我用movielens_1m数据集  运行模型，出现下面的错误，请问该怎么解决呢？

![image](https://user-images.githubusercontent.com/44498860/202358772-fc7370b1-b692-4a84-90a9-0be3bc2f9886.png)

谢谢！

**Comment by AoiDragon** [comment]
@MambaDong 您好，可以提供一下使用的模型以及配置文件吗？

**Comment by MambaDong** [comment]
![be9a36d6dfbde4dc54d72d0cb3bee15](https://user-images.githubusercontent.com/44498860/202724907-56de3523-cb49-4013-82ca-417b699eb6ef.png)
您好，这个是GC-SAN模型 其他类似的Bert模型也不能运行，
![image](https://user-images.githubusercontent.com/44498860/202725964-39709e35-614a-495d-9141-7e6a9ddcf571.png)

**Comment by MambaDong** [comment]
你好打扰，麻烦问下这个问题解决了吗

**Comment by AoiDragon** [comment]
在RecBole1.1中我们将`neg_sampling`替换为`train_neg_sample_args`，您可以尝试更新框架后使用新的参数。在其他设置相同的情况下，我这边并没有发现错误。

**Comment by Sherry-XLL** [comment]
您好 @MambaDong，

可能是您的配置文件导致了 `timestamp` 属性没有被正确加载。MovieLens-1M 在 GCSAN 等序列模型的参考配置如下：

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, rating, timestamp]

# data filtering for interactions
val_interval:
    rating: "[3,inf)"    
unused_col: 
    inter: [rating]

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 40960000
valid_metric: NDCG@10
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO

# disable negative sampling
train_neg_sample_args: ~
```

欢迎您更新伯乐到最新版本，按照如上 `.yml` 新建配置文件并重新运行代码。

感谢您对伯乐的关注，若有新的问题欢迎新开一个 issue 提问。

**Comment by bodymostafa123** [comment]
can anyone here help me with my problem in #1670
any help will be appreciated from you
