### ISSUE TITLE
在case_study_example的問題

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1543]
您好，請問在case_study_example中是否可以印出train_data和 valid_data的用戶item歷史紀錄?

以下是我的code，我將所有的test_data改為train_data:

if __name__ == "__main__":
        config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file="saved/BPR-Oct-31-2022_08-14-21.pth",
train_user_ids = ["196"]
k = 10
print('User_id', train_user_ids)

uid_series = dataset.token2id(dataset.uid_field, train_user_ids)
topk_score, topk_iid_list = full_sort_topk(uid_series, model, train_data, k, device=config['device'])

#所有用戶的歷史item
history_item = train_data.uid2history_item[list(uid_series)]
print(history_item)

print("topk_score",topk_score)
print("topk_iid_list",topk_iid_list)

報錯:AttributeError: 'TrainDataLoader' object has no attribute 'is_sequential'

我想知道驗證集中已及測試集中用戶購買的商品，請問該如何更改?

**Comment by Paitesanshi** [comment]
@emilyjeng 
您好，感谢您对伯乐的关注！
目前伯乐的case study只支持在test data上进行。如果您想查看训练集或验证集上的具体信息，建议在相关位置(如模型的predict函数)打印对应信息或利用调试功能在相应地方设置断点，观察具体结果。

**Comment by emilyjeng** [comment]
@Paitesanshi 感謝回答，可以舉例要怎麼在檔案中更改嗎？

**Comment by Paitesanshi** [comment]
您好，您可以修改两部分的代码来实现这个需求。
1. 在case_study_example.py 中注释`history_item= train_data.uid2history_item[list(uid_series)]`及下面的`print(history_item)`，因为train_data并不支持这个功能。
2. 在recbole/utils/case_study.py文件的full_sort_scores函数中，注释部分内容，如下所示：
```
 #if not test_data.is_sequential:
    input_interaction = dataset.join(Interaction({uid_field: uid_series}))
    # history_item = test_data.uid2history_item[list(uid_series)]
    # history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
    # history_col = torch.cat(list(history_item))
    # history_index = history_row, history_col
    # else:
    #     _, index = (dataset.inter_feat[uid_field] == uid_series[:, None]).nonzero(as_tuple=True)
    #     input_interaction = dataset[index]
    #     history_index = None
    # Get scores of all items
    input_interaction = input_interaction.to(device)
    try:
        scores = model.full_sort_predict(input_interaction)
    except NotImplementedError:
        input_interaction = input_interaction.repeat_interleave(dataset.item_num)
        input_interaction.update(test_data.dataset.get_item_feature().to(device).repeat(len(uid_series)))
        scores = model.predict(input_interaction)

    scores = scores.view(-1, dataset.item_num)
    scores[:, 0] = -np.inf  # set scores of [pad] to -inf
    # if history_index is not None:
    #     scores[history_index] = -np.inf  # set scores of history items to -inf
```
3. 再运行case_study_example.py即可运行，结果如下图：
![Snipaste_2022-11-19_14-23-15](https://user-images.githubusercontent.com/45314239/202837971-f6af3393-d85d-4150-81c5-238b1efb6917.jpg)

**Comment by emilyjeng** [comment]
@Paitesanshi 您好，我按照您說的設置去更改，但發現會報錯，我無法解決這錯誤：

File "case_study_example.py", line 37, in <module>
    topk_score, topk_iid_list = full_sort_topk(uid_series, model, train_data, k, device=config['device'])
  File "/Emily/RecBole/recbole/utils/case_study.py", line 95, in full_sort_topk
    scores = full_sort_scores(uid_series, model, test_data, device)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Emily/RecBole/recbole/utils/case_study.py", line 60, in full_sort_scores
    input_interaction = input_interaction.to(device)
UnboundLocalError: local variable 'input_interaction' referenced before assignment

**Comment by Paitesanshi** [comment]
@emilyjeng 
您好，您是否多注释了一行，45行的`input_interaction = dataset.join(Interaction({uid_field: uid_series}))`这句不需要注释。

**Comment by emilyjeng** [comment]
@Paitesanshi 十分感謝！！！目前成功執行。想請問這是根據test_data做topk的排序嗎？而我發現改為valid_data也是可執行的

**Comment by Paitesanshi** [comment]
@emilyjeng 排序的依据是传入`full_sort_topk`函数的是train_data或test_data。上面的注释其实是去除了一些只在test_data中有的内容，所以train_data和valid_data都可以运行。但是在对test_data进行case study时还是建议按源代码和伯乐相关文档进行。如果问题已经解决请关闭issue。
如果认可我们的工作，请为伯乐仓库点亮star,再次感谢您的关注和支持!

**Comment by emilyjeng** [comment]
非常感謝解答！！
