### ISSUE TITLE
请问如何读取自定义模型？

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1544]
RT，我自定义了一个模型并且完成了训练，但是bole提供的load_data_and_model接口似乎只针对预设模型，这种情况下应该如何完成类似load_data_and_model接口的工作读取自定义模型的训练结果呢？

**Comment by leoleojie** [comment]
@ithok 您好，感谢您对伯乐的关注！
伯乐提供的load_data_and_model接口可以读取自定义的模型，前提在于自定义模型的py文件保存在`recbole/model`目录下的general_recommender, context_aware_recommender, sequential_recommender或 [knowledge_aware_recommender等文件夹内，您可以查看伯乐[读取自定义模型的接口](https://recbole.io/docs/_modules/recbole/utils/utils.html#get_model)做进一步了解。
