### ISSUE TITLE
[🐛BUG] When using RecBole via Notebook, tqdm continue printing new line

### ISSUE THREAD

**Issue by adebiasio-estilos** [RUCAIBox/RecBole#1545]
When using RecBole via Jupyter Lab Notebooks, tqdm continue printing new line when show_progress=True

**Comment by zhengbw0324** [comment]
This is because the default tqdm will output multiple lines in Jupyter Lab Notebooks. You can try to replace `from tqdm import tqdm` with `from tqdm.notebook import tqdm`.

**Comment by adebiasio-estilos** [comment]
> This is because the default tqdm will output multiple lines in Jupyter Lab Notebooks. You can try to replace `from tqdm import tqdm` with `from tqdm.notebook import tqdm`.

Thanks for answering!
Already tried this but unfortunately nothing change
