### ISSUE TITLE
想问下数据集avazu的YAML有没有参考的地方

### ISSUE THREAD

**Issue by SEVEN77777777777** [RUCAIBox/RecBole#1549]
我把avazu数据集的yaml设置成：
# dataset config
field_separator: "\t"
seq_separator: " "
LABEL_FIELD: label

load_col:
    inter: '*'

fill_nan: True
USER_ID_FIELD: ~
ITEM_ID_FIELD: ~
normalize_all: True
val_interval:
  timestamp: "[14102931, inf)"
然后再调用deepfm训练 最后结果
 raise ValueError('Some feat is empty, please check the filtering settings.')
ValueError: Some feat is empty, please check the filtering settings.
想问下这个数据集配置是哪里出问题了麻  谢谢

**Comment by Wicknight** [comment]
@SEVEN77777777777 您好！感谢您对伯乐的关注与支持！
就像报错信息中提示的一样，出现这种错误一般是因为在过滤数据时过滤条件设置的不合理导致数据全部被剔除。而您这里只设置了'timestamp'这一项过滤条件，经过测试在avazu数据集上应该不会出现这种情况。请检查您的数据集是否是按照[文档说明的流程](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/Avazu.md)获得的。

**Comment by SEVEN77777777777** [comment]
感谢您的回复  能否看看您的AVAZU数据集的config配置

**Comment by SEVEN77777777777** [comment]
> @SEVEN77777777777 您好！感谢您对伯乐的关注与支持！ 就像报错信息中提示的一样，出现这种错误一般是因为在过滤数据时过滤条件设置的不合理导致数据全部被剔除。而您这里只设置了'timestamp'这一项过滤条件，经过测试在avazu数据集上应该不会出现这种情况。请检查您的数据集是否是按照[文档说明的流程](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/Avazu.md)获得的。
感谢您的回复 能否看看您的AVAZU数据集的config配置

**Comment by Wicknight** [comment]
@SEVEN77777777777 您好，我在测试时使用的就是您上面的配置，并没有报错。我们搜集整理了很多数据集，但并没有针对每个数据集做一个标准的配置文件，因为不同场景和用户需求下往往需要不同的配置，我们在’dataset.yaml‘文件以及我们的[官方文档](https://recbole.io/docs/user_guide/config/data_settings.html)中对每个参数进行了详细的介绍，推荐您详细阅读之后根据您自己的任务需求设置参数的取值即可。如果仍然发生了上述报错，欢迎您将详细的信息反映给我们！

**Comment by SEVEN77777777777** [comment]
> @SEVEN77777777777 您好，我在测试时使用的就是您上面的配置，并没有报错。我们搜集整理了很多数据集，但并没有针对每个数据集做一个标准的配置文件，因为不同场景和用户需求下往往需要不同的配置，我们在’dataset.yaml‘文件以及我们的[官方文档](https://recbole.io/docs/user_guide/config/data_settings.html)中对每个参数进行了详细的介绍，推荐您详细阅读之后根据您自己的任务需求设置参数的取值即可。如果仍然发生了上述报错，欢迎您将详细的信息反映给我们！



您好 我现在重新生成.inter Avazu数据集原子文件
<img width="229" alt="9313abfacd95b6a5927bd87d1cfaf14" src="https://user-images.githubusercontent.com/111297136/203277754-ff2100e8-4c07-419d-8730-5d1472f824b5.png">
然后用命令行运行run_recbole.py文件  用deepfm 发现还是不行 不知道是不是数据集太大的原因  其结果报memoryerror 超时错误  我电脑是16+512的配置  运行的时候内存已经占了百分之99
想问下 您 这是什么原因呢

**Comment by Wicknight** [comment]
@SEVEN77777777777 应该就是数据集太大的原因。如果不能处理完整的数据集，建议提前在conversion_tools中对数据进行处理时就添加限制条件，剔除不需要的数据项。例如在[待加载特征](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/src/extended_dataset.py#L254)列中剔除您不需要的特征列，以及[转化原子文件](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/src/extended_dataset.py#L279)时根据特征项的值进行剔除。

**Comment by SEVEN77777777777** [comment]
> @SEVEN77777777777 应该就是数据集太大的原因。如果不能处理完整的数据集，建议提前在conversion_tools中对数据进行处理时就添加限制条件，剔除不需要的数据项。例如在[待加载特征](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/src/extended_dataset.py#L254)列中剔除您不需要的特征列，以及[转化原子文件](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/src/extended_dataset.py#L279)时根据特征项的值进行剔除。



不好意思打扰您   能否解决我这个疑问  非常感谢

**Comment by Wicknight** [comment]
@SEVEN77777777777 您好，您在val_interval中取值区间的设置错误，区间应将最小值限制放在前面，即[14102302, inf)

**Comment by SEVEN77777777777** [comment]
> @SEVEN77777777777 您好，您在val_interval中取值区间的设置错误，区间应将最小值限制放在前面，即[14102302, inf)

您好 其实这样我也尝试过  但是还是没有结果  猜测还是数据量太大的原因  所以我想知道缩小数据量有什么办法吗  前面我尝试了转换原子文件时将10多个特征注释掉了  发现数据量并没有减少

**Comment by Wicknight** [comment]
@SEVEN77777777777 您好，根据您的反馈，我们发现avazu数据集中特征列的选择加载没有正常运作，您可以将extended_dataset.py中AVAZUDataset下的convert_inter更改为如下代码，经测试这样可以顺利实现特征列的选择加载：
``` 
    def convert_inter(self):
        try:
            idx_list = list(self.inter_fields.keys())
            with open(self.output_inter_file, 'w') as fp, open(self.inter_file, encoding='utf-8') as rp:
                fp.write('\t'.join(self.inter_fields.values()) + '\n')
                lines = rp.readlines()[1:]
                for line in tqdm(lines):
                    token_line = line.strip().split(self.sep)
                    token_list = []
                    for idx in idx_list:
                        token_list.append(token_line[idx])
                    fp.write('\t'.join(token_list) + '\n')
        except NotImplementedError:
            print('This dataset can\'t be converted to inter file\n')
```

**Comment by SEVEN77777777777** [comment]
> @SEVEN77777777777 您好，根据您的反馈，我们发现avazu数据集中特征列的选择加载没有正常运作，您可以将extended_dataset.py中AVAZUDataset下的convert_inter更改为如下代码，经测试这样可以顺利实现特征列的选择加载：
> 
> ```
>     def convert_inter(self):
>         try:
>             idx_list = list(self.inter_fields.keys())
>             with open(self.output_inter_file, 'w') as fp, open(self.inter_file, encoding='utf-8') as rp:
>                 fp.write('\t'.join(self.inter_fields.values()) + '\n')
>                 lines = rp.readlines()[1:]
>                 for line in tqdm(lines):
>                     token_line = line.strip().split(self.sep)
>                     token_list = []
>                     for idx in idx_list:
>                         token_list.append(token_line[idx])
>                     fp.write('\t'.join(token_list) + '\n')
>         except NotImplementedError:
>             print('This dataset can\'t be converted to inter file\n')
> ```


非常感谢您的回复  缩小数据量其实在[1:1000000]其实就可以了  我把数据量缩小之后成功跑通了

**Comment by DipperZ** [comment]
您好，请问怎么缩写数据集的数据量来进行训练呢，原始数据太大了本地电脑无法支持训练
