### ISSUE TITLE
TopK是否從history_item中推薦?

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1550]
您好，請問history_item輸出的item為內部ID，但為甚麼與external_item_list的print，沒有一樣的itemID?

以下是我的code:
user_ids = ["196"]
k = 36
print('test_data_User_id', user_ids)

uid_series = dataset.token2id(dataset.uid_field, user_ids)
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k, device=config['device'])
external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list.cpu())

#用戶的歷史item
history_item = test_data.uid2history_item[list(uid_series)]
print('history_item', history_item)

#print("topk_score",topk_score)
#print("topk_iid_list",topk_iid_list)
print("external_item_list",external_item_list)

輸出:
![image](https://user-images.githubusercontent.com/74802442/202989507-55d2e51a-d11a-4bfc-b70f-ab0c4ad7ea61.png)

topk_iid_list是將topk_iid_list的TopK轉為內部ID，但topk_iid_list是從history_item去做topK的嗎?或許是我的理解錯誤，希望可以說明這部分，感謝!!

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，full_sort是在test_data上进行的，其中history_item表示的是除了test_data中出现过的物品之外的用户交互的所有物品，也就是训练集和测试集中交互的物品，所以topk_iid_list不应该包括history_item中的物品。我们把history_item中的item评分都设为了-inf来保证这些物品在topk排序中会排在最后面。

**Comment by emilyjeng** [comment]
@Paitesanshi 感謝解答，這使我更了解了RecBole!!

我將valid_test印出topk_iid_list，對照著test_data的topk_iid_list，發現有些item一樣，是否評估指標的數值(比如hit@10=0.7)，就是依據valid_data去驗證test_data在預測出推薦的前10有多少一樣的item?

valid_data
![image](https://user-images.githubusercontent.com/74802442/203190858-2201c611-4123-44bf-be0e-7abb566a69ba.png)
test_data
![image](https://user-images.githubusercontent.com/74802442/203190875-82fe1976-6efd-43bd-9054-2344da451f05.png)

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，所有指标的计算都是基于单独的数据集，valid_data和test_data的指标计算没有关系。hit@10=0.7的含义应该是，假设用户在test_data中交互了10件物品，模型输出的topk推荐结果中有7件物品属于test_data中的这10件物品。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好!感謝你的耐心解答!，所以valid_data是對train_data驗證嗎?，這樣才會幫助train_data的訓練，但valid_data並不驗證test_data? 所訓練模型的輸出評估結果都是對test_data這個單一測是集的評估結果?

**Comment by Paitesanshi** [comment]
> @Paitesanshi 您好!感謝你的耐心解答!，所以valid_data是對train_data驗證嗎?，這樣才會幫助train_data的訓練，但valid_data並不驗證test_data? 所訓練模型的輸出評估結果都是對test_data這個單一測試集的評估結果?
@emilyjeng 您好，是的。valid_data是对利用train_data训练得到模型进行验证。最后的指标评估结果只是基于test_data计算得到。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好，根據您說的假设用户在test_data中交互了10件物品，模型输出的topk推荐结果中有7件物品属于test_data中的这10件物品，可是預測的推薦結果應該是test_data中用戶未交互過的。

因此我覺得結果是否是test_data將history_item排置最後，而剩下的數據中假設用戶有10件物品，而最後hit@10=0.7，输出的topk推荐结果中有7件物品属于test_data中的这10件物品，但這樣的7件商品是否是test_data中就交互過的歷史?

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，您关于流程的理解是正确的。我们保存valid_data上结果最好的模型(假设为hit@10=0.7)，并在test_data上预测。
topk推荐结果命中的7件物品是test_data中用户实际交互的物品，test_data中的10件物品也是用户实际交互过仅属于test_data的记录。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好，以下為我的設置
checkpoint_dir = saved
show_progress = True
save_dataset = Ture
dataset_save_path = Ture
save_dataloaders = Ture
dataloaders_save_path = Ture
log_wandb = False

並確認dataset_save_path
<img width="344" alt="image" src="https://user-images.githubusercontent.com/74802442/203463087-7923d73a-2e41-4860-98fe-55c1d3bbe14e.png">

但還是出現一樣的問題

**Comment by emilyjeng** [comment]
@Paitesanshi ，您好，因為模型的訓練完的分數為

best valid : OrderedDict([('recall@10', 0.2462), ('mrr@10', 0.1837), ('ndcg@10', 0.1765), ('hit@10', 0.3174), ('precision@10', 0.0366)])
test result: OrderedDict([('recall@10', 0.2367), ('mrr@10', 0.1821), ('ndcg@10', 0.1733), ('hit@10', 0.3033), ('precision@10', 0.0358)])

但我查看TOP20時，以留下history_data對照，發現訓練集的推薦跟history的重疊度很高(代表商品的推薦都有對)，那為甚麼會訓練分數低呢?還是history有照分數高低排序，TOP20也按照排序但推薦順序與history不一樣，所以分數很低??

**Comment by Paitesanshi** [comment]
> @Paitesanshi 您好，我重新更換了user_ids後成功預測出TopK
> 
> ![image](https://user-images.githubusercontent.com/74802442/203465698-c48549ab-fd5b-41ce-8096-9e41ef0629a0.png)
> 
> 我認為這問題是因為設置了'order': 'RO' (亂數方式)將數據分成0.8訓練，0.1驗證，0.1測試時，TopK使用測試集但裡面並沒有User_id為 ['mh_-eMZ6K5RLWhZyISBhwA']，於是我將User_id改為'RreNy--tOmXMl1en0wiBOg'，執行成功，代表測試集有這個User_id。
> 
> 請問'order': 'RO'時或是'order': 'TO'時該如何知道test_data有哪些User_id呢? history_item要如何轉回外部的編號? 以及要如何知道test_data的User_id全部交互了哪些items呢?

@emilyjeng 您好，您可以通过test_data.uid_list得到所有的用户id。dataset.field2id_token['item_id']中包含所有物品的token,下标对应item_id, 您可以利用这个将history_item转回外部编号。test_data.uid2history_item加上test_data.uid2positive_item即为用户交互的所有物品。

**Comment by Paitesanshi** [comment]
> @Paitesanshi ，您好，不好意思又有個疑惑，使用模型為RecVAE，資料集為yelp2022，模型的訓練完的分數為下:
> 
> best valid : OrderedDict([('recall@10', 0.2462), ('mrr@10', 0.1837), ('ndcg@10', 0.1765), ('hit@10', 0.3174), ('precision@10', 0.0366)]) test result: OrderedDict([('recall@10', 0.2367), ('mrr@10', 0.1821), ('ndcg@10', 0.1733), ('hit@10', 0.3033), ('precision@10', 0.0358)])
> 
> 我的設置: #dataset config field_separator: "\t" seq_separator: " " USER_ID_FIELD: user_id ITEM_ID_FIELD: item_id RATING_FIELD: rating TIME_FIELD: timestamp NEG_PREFIX: neg_ LABEL_FIELD: label load_col: inter: [user_id, item_id, rating, timestamp]
> 
> #data filtering for interactions val_interval: rating: "[3,inf)" unused_col: inter: [rating]
> 
> user_inter_num_interval: "[10,inf)" item_inter_num_interval: "[10,inf)" loss_type: 'BPR'
> 
> #model hidden_dimension: 600 # (int) The hidden dimension of auto-encoder. latent_dimension: 200 # (int) The latent dimension of auto-encoder. dropout_prob: 0.5 # (float) The drop out probability of input. beta: 0.2 # (float) The default hyperparameter of the weight of KL loss. gamma: 0.005 # (float) The hyper-parameter shared across all users. mixture_weights: [0.15, 0.75, 0.1] # (list of float) The mixture weights of three composite priors. n_enc_epochs: 3 # (int) The training times of encoder per epoch. n_dec_epochs: 1 # (int) The training times of decoder per epoch.
> 
> #training and evaluation epochs: 500 train_batch_size: 4096 eval_batch_size: 40960000 metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision'] valid_metric: Hit@10 train_neg_sample_args: {'distribution': 'uniform', 'sample_num': 1} dynamic: False save_dataset: Ture save_dataloaders: Ture dataset_save_path: Ture dataloaders_save_path: Ture
> 
> 原始資料為交互了31個商品，訓練集與驗證集交互過的商品(history_item有18個，剩下的13個在test_data中) 我認為best valid 分數低是代表模型的訓練並不好，也代表交互的學習並不好，推薦的商品都沒有中
> 
> 我的問題為 1.原本我認為的問題是驗證集的TOP31與測試集的TOP31應該要不同(因為資料分割)，但是測試集的TOP31卻都有history_items?照理說應該分割一些交互過的item給驗證集嗎? 2.為甚麼會訓練分數低呢? 3.我扣除history_item，剩下的item卻也與驗證集的Top31排序卻也一樣? 4.還是history有照分數高低排序，TOP31也按照排序但推薦順序但是與history不一樣，所以分數很低? 5.還是應該要將case_study.py中的所有test_data，改為vaild_data或是train_data?
> 
> 我想了解為甚麼訓練分數會低的原因(除了參數調整)
> 
> ![image](https://user-images.githubusercontent.com/74802442/203497747-e7654147-343d-4134-ae2c-dcc37ce874bf.png)

@emilyjeng 您好，下面将逐一回答您的问题
1. 请问您还记得上一个issue中您为了在full_sort中使用train_data将recbole/utils/case_study.py中的部分代码注释了，如果在case_study中使用test_data请将那部分代码的注释取消，那部分保证了将用户的历史物品评分置为-inf，从而不会出现在topk结果中。
2. 训练分数低可能有多样的原因，在不同的数据集上，模型的效果可能也会有不同，所以需要通过自行调参来提高效果。
3. 模型是相同的，full_sort指的是用户和所有物品的评分和排序，结果相同是符合预期的(如果我没有理解错您的问题的话)。
4. data中的history_item并没有按照评分排序，是随机的。评测指标和推荐结果都是按照评分高低排序的，与history的顺序无关。
5. 我觉得您如果想要提升模型效果可能还是需要进行调参。另外我注意到topk_score中评分6，7都有，但是yelp的评分似乎是1~5的，这可能是效果不好的原因之一，需要进一步训练或调参。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好，謝謝您的耐心解答!!

請問第五點，在topk_score中评分6與7，yelp的评分1~5分，兩者應該是不同種類的分數，按照文檔所說TopK是類比點擊率，不算是評價指標，您說这可能是效果不好的原因之一，或許topk_score除了類比點擊率，也有其他意思嗎?

**Comment by Paitesanshi** [comment]
@emilyjeng 抱歉！我的表述有误，RecVAE是进行排序任务，score确实不代表评分，而是类似于点击率的排序依据，请以文档为准。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好!

我設置了
history_item = test_data.uid2history_item[list(uid_series)]
external_history_list = dataset.field2id_token['history_item' ]

print('external_history_list', external_history_list)
但會出錯
KeyError: 'history_item'

或許是我設置錯誤，請問要如何改動?
因為改為dataset.field2id_token['item_id']，會有所有的item_id，但我只想要history的item。

另外我發現test_postive= test_data.uid2positive_item，無法用list方式呈現，我想印出所有item，目前呈現如下
test_postive [None tensor([92]) tensor([2680]) ... tensor([2040]) tensor([35])
 tensor([1828])]

我改為
test_postive= test_data.uid2positive_item[list(uid_series)]，輸出

test_postive [tensor([1289,  804])]
test_data.uid_list tensor([   1,    2,    3,  ..., 4320, 4321, 4322])

請問test_data.uid_list是甚麼?

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，像我上面回复的一样，您在dataset.field2id_token['item_id']中获取了所有的item_id，用history中的id作为下标进行索引自然可以获取history_item的token。
positive表示仅在test_data中交互的物品，输出两项似乎是正常的。

**Comment by emilyjeng** [comment]
@Paitesanshi 您好，請問作為history中的id作为下标的意思是自行搜尋嗎? 舉例為384對應為'[PAD]'，1156對應為'rBdG_23USc7DletfZ11xGA'?

<img width="493" alt="image" src="https://user-images.githubusercontent.com/74802442/203686965-56edecb3-0fd2-4b9b-bccd-76d472a3bdf6.png">

**Comment by Paitesanshi** [comment]
> @Paitesanshi 您好，請問history中的id作为下标的意思是自行搜尋嗎? 舉例為384對應為'[PAD]'，1156對應為'rBdG_23USc7DletfZ11xGA'?
> 
> <img alt="image" width="493" src="https://user-images.githubusercontent.com/74802442/203686965-56edecb3-0fd2-4b9b-bccd-76d472a3bdf6.png">

@emilyjeng 是的,比如dataset.field2id_token['item_id'][384]对应384的item_token

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，如果问题已解决，可以关闭本条issue。感谢对伯乐的支持~

**Comment by emilyjeng** [comment]
@Paitesanshi 您好!!這幾天我嘗試修改訓練集的設置，發現將以下交互設置為15
user_inter_num_interval = [15,inf)
item_inter_num_interval = [15,inf)

因此在yelp2022訓練集的評估指標提升，我不太明白為何刪除了少於15個交互的用戶或商品刪除會提升

**Comment by Paitesanshi** [comment]
@emilyjeng 您好，这是推荐系统中一个比较常见的设置，我的理解是对于交互数据较少的冷启动用户和物品，模型并不能较好的建模，推荐结果较差，所以去除这部分数据后评价指标可能上升

**Comment by emilyjeng** [comment]
@Paitesanshi 了解了，非常感謝
