### ISSUE TITLE
one more user embedding in LightGCN

### ISSUE THREAD

**Issue by cizhouyu** [RUCAIBox/RecBole#1558]
**Describe the bug**
训练LightGCN模型，用user_all_embeddings, item_all_embeddings = model.forward()得到用户和物品的embedding。但是发现用户user_all_embeddings维度是(236,64)，然而原子文件.user中只有235位用户。

**To Reproduce**
代码如下:
`
# load model and get user_embedding 
    config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file='saved/' + 'LightGCN-Nov-17-2022_17-18-36.pth'
        ,
        dataset_file='saved/' + 'ml-1m-cluster0-dataset.pth',
        dataloader_file='saved/' + 'ml-1m-cluster0-for-LightGCN-dataloader.pth',
        device_str=device_str,
    )
    user_all_embeddings, item_all_embeddings = model.forward()
`

**Expected behavior**
user_all_embeddings第一维大小应当和原子文件.user中用户数目保持一致？

**Screenshots**
第一张图可以看出user_all_embeddings维度是(236,64)。原子文件.user中用户信息从第2行开始。
第二张图可以看出原子文件.user中用户信息到第236行结束。所以实际上只有235位用户。
![q1-1](https://user-images.githubusercontent.com/60316519/203527361-ee7ceeac-2f80-41ec-ac3c-cdab516b007c.png)
![q1-2](https://user-images.githubusercontent.com/60316519/203527383-c3872414-9c1c-45bb-9007-df3462c310e1.png)

**question**
我希望可以获得235位用户的embedding，现在user_all_embeddings维度是(236,64)，不知道对应关系是怎样的？为什么user_all_embeddings维度不是(235,64)？
谢谢！

**Comment by leoleojie** [comment]
@cizhouyu 您好，感谢你对伯乐的关注！
伯乐在处理数据时，会额外的加上`<pad>`，因此最终的user embedding会比原子文件中的user数目要多。您可以通过查看`dataset.field2token_id`或`dataset.field2id_token`来查看外部id和伯乐内部id的对应关系。具体可以查看[相关接口说明](https://recbole.io/docs/recbole/recbole.data.dataset.dataset.html?highlight=field2token_id#recbole.data.dataset.dataset.Dataset.field2token_id)

**Comment by cizhouyu** [comment]
理解了，感谢您的回复！
