### ISSUE TITLE
How to test for Cold Start users using recbole? 

### ISSUE THREAD

**Issue by kashyaprajveer** [RUCAIBox/RecBole#1559]
Hi, I want to test KGCN for user cold start. Could you tell me how can I do that? Thank you

**Comment by zhengbw0324** [comment]
Hello @kashyaprajveer !
KGCN solves certain cold start problems through knowledge enhancement, and has no special operation configuration. If you want to test KGCN in a cold start scenario, you can try to train the model on a dataset with fewer user interactions.

**Comment by kashyaprajveer** [comment]
Thanks, @zhengbw0324 ! , May I ask it is possible to split data by users such that I can train some users and test on new users? Basically splitting users instead of their interactions. will that be possible on recbole? Thank you!

**Comment by zhengbw0324** [comment]
@kashyaprajveer 
You can follow the [MetaRec](https://github.com/nuster1128/RecBole-MetaRec) package in [RecBole 2.0](https://github.com/RUCAIBox/RecBole2.0)

**Comment by kashyaprajveer** [comment]
precision@10 : 1.0    recall@10 : 1.0    hit@10 : 1.0    ndcg@10 : 1.0    mrr@10 : 1.0
24 Nov 11:55    INFO  Saving current: saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55    INFO  epoch 49 training [time: 2.22s, train loss: 0.2469]
24 Nov 11:55    INFO  epoch 49 evaluating [time: 0.23s, valid_score: 1.000000]
24 Nov 11:55    INFO  valid result: 
precision@10 : 1.0    recall@10 : 1.0    hit@10 : 1.0    ndcg@10 : 1.0    mrr@10 : 1.0
24 Nov 11:55    INFO  Saving current: saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55    INFO  Loading model structure and parameters from saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55    INFO  best valid result: OrderedDict([('precision@10', 1.0), ('recall@10', 1.0), ('hit@10', 1.0), ('ndcg@10', 1.0), ('mrr@10', 1.0)])
24 Nov 11:55    INFO  test result: OrderedDict([('precision@10', 1.0), ('recall@10', 1.0), ('hit@10', 1.0), ('ndcg@10', 1.0), ('mrr@10', 1.0)])

# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
LABEL_FIELD: rating
load_col:
    inter: [user_id, item_id, rating]
    item: [item_id,movie_title,release_year,class]
    user: [user_id,age,gender,occupation,zip_code]
# user_inter_num_interval: [13,100]

# Training and evaluation config
seed: 1128
epochs: 50
train_batch_size: 32
valid_metric: mrr@10

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode : labeled

# Meta learning config
meta_args:
    support_num: none
    query_num: 10

# MeLU Parameters
embedding_size: 32
mlp_hidden_size: [64,64]
melu_args:
    local_lr: 0.000005
    lr: 0.00005

# Metrics
metrics: ['precision','recall','hit','ndcg','mrr']
metric_decimal_place: 4
topk: 10

user_inter_num_interval: "[20,inf)"
MAX_ITEM_LIST_LENGTH: 100

How come precision@10 for MeLU is coming out as 1 infact all metric is 1? is precision taking any correct in list of 10 as correct?

**Comment by kashyaprajveer** [comment]
Thanks @zhengbw0324,

I was able to run the code but I see an issue  **How come precision@10 for MeLU is coming out as 1 in fact all metric is 1? is precision taking any correct in list of 10 as correct?**

topk: 10

user_inter_num_interval: "[20,inf)"
MAX_ITEM_LIST_LENGTH: 100

precision@10 : 1.0 recall@10 : 1.0 hit@10 : 1.0 ndcg@10 : 1.0 mrr@10 : 1.0
24 Nov 11:55 INFO Saving current: saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55 INFO epoch 49 training [time: 2.22s, train loss: 0.2469]
24 Nov 11:55 INFO epoch 49 evaluating [time: 0.23s, valid_score: 1.000000]
24 Nov 11:55 INFO valid result:
precision@10 : 1.0 recall@10 : 1.0 hit@10 : 1.0 ndcg@10 : 1.0 mrr@10 : 1.0
24 Nov 11:55 INFO Saving current: saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55 INFO Loading model structure and parameters from saved\FOMeLU-Nov-24-2022_11-53-42.pth
24 Nov 11:55 INFO best valid result: OrderedDict([('precision@10', 1.0), ('recall@10', 1.0), ('hit@10', 1.0), ('ndcg@10', 1.0), ('mrr@10', 1.0)])
24 Nov 11:55 INFO test result: OrderedDict([('precision@10', 1.0), ('recall@10', 1.0), ('hit@10', 1.0), ('ndcg@10', 1.0), ('mrr@10', 1.0)])

**Comment by zhengbw0324** [comment]
@kashyaprajveer 
Hello, you can go to the [MetaRec](https://github.com/nuster1128/RecBole-MetaRec) package to ask problem.
