### ISSUE TITLE
请问recbole.model.general_recommender这个模块

### ISSUE THREAD

**Issue by Light-lyy** [RUCAIBox/RecBole#1562]
怎么消失了呢？以前recbole.model下有sequential_recommender、general_recommender等多个模块的，现在怎么只剩sequential_recommender了呢？想参考一下general_recommender里面的模型实现的

**Comment by chenyuwuxin** [comment]
@Light-lyy 您好，感谢您的关注！
目前是有general_recommender的~。请安装最新版本的RecBole。具体运行示例可以参考[General Methods](https://recbole.io/docs/get_started/started/general.html)。

**Comment by Light-lyy** [comment]
> @Light-lyy 您好，感谢您的关注！ 目前是有general_recommender的~。请安装最新版本的RecBole。具体运行示例可以参考[General Methods](https://recbole.io/docs/get_started/started/general.html)。

我的意思是，为什么在[这里](https://github.com/RUCAIBox/RecBole/tree/master/recbole/model)看不到了呢？以前是能在这里看到有个general_recommender模块，里面有许多模型的代码实现的。现在只能看到sequential_recommender模块了

**Comment by chenyuwuxin** [comment]
@Light-lyy 非常抱歉，我们之前存在一些操作失误。目前版本已经回退，十分感谢您的提醒！
