### ISSUE TITLE
Sequential recommendations list

### ISSUE THREAD

**Issue by Giova151297** [RUCAIBox/RecBole#1564]
Hi all,

I'm using the "GRU4Rec" model and the "ml-100k database", and when I use the "full_sort_topk "function to compute the recommendation list and prediction scores for the topk items, for each user, I notice that the recommended items are the same for all users, and only for some change the position of the items. 
I would like to know if this is normal or am I making some mistake. 
Thank you

**Comment by Paitesanshi** [comment]
Hi, @Giova151297 ！
I can't figure out the cause of the problem from your description. There seems to be no problem with recbole's case study. Maybe you can look at the metrics of the model after training to determine whether the model itself is performing well.

**Comment by Giova151297** [comment]
Hi @Paitesanshi!
Thank you for the response! Sorry probably i didn't explain good what i meant, i basically following the quick start section on the documentation: 

1.  "run_recbole" function to execute the model ("Gru4Rec") , the dataset ("ml-100k") and the configuration file (i set properly hyper-parameters for this model);
2.  "load_data_and_model" function to take some attributes i need for the next function; i also create an array with the user_ids;
3. "full_sort_topk" function to compute recommendation list and prediction scores for the topk items;

Now, when i extract item_ids from the recommendation l obtain a result like this:

_**array([['64', '195', '748', ..., '187', '302', '98'],
       ['64', '195', '748', ..., '187', '302', '98'],
       ['64', '195', '748', ..., '284', '302', '393'],
       ...,
       ['64', '195', '748', ..., '284', '302', '393'],
       ['64', '195', '748', ..., '284', '302', '98'],
       ['64', '195', '748', ..., '187', '302', '443']], dtype='<U5')**_

where each list corresponds to a recommendation list for one user; as you can see, and i also checked the entire array, the item_ids are pretty the same, and it sounds me a bit strange; i checked the evaluation metrics and these seem not so good. 

Probably there is something i am doing wrong but i don't understand what.
Hope you can help me, thank you very much!

**Comment by Paitesanshi** [comment]
@Giova151297 
I train GRU4Rec with RecBole's default configuration file and ml-100k dataset. The topk recommendation result is shown in the figure below, which looks normal. According to your description, I think it may be because the model training is not sufficient, resulting in the inability to make personalized recommendations.
![image](https://user-images.githubusercontent.com/45314239/204116207-4b106f37-3ced-4c23-9767-23743c96074e.png)
