### ISSUE TITLE
官網頁面故障

### ISSUE THREAD

**Issue by emilyjeng** [RUCAIBox/RecBole#1566]
您好!我最近在官網查詢資料，發現頁面的評估指標似乎故障了，四種類型的推薦都是loading狀態

<img width="574" alt="image" src="https://user-images.githubusercontent.com/74802442/204137464-2073c124-f6ec-4d64-9fc5-b354d6e7480b.png">
<img width="749" alt="image" src="https://user-images.githubusercontent.com/74802442/204137511-b4b78c66-6ef6-4bcf-8860-027a815c548c.png">

**Comment by zhengbw0324** [comment]
@emilyjeng 您好！
这个页面在我们的官网上已经不对外开放，请问您是如何进入的呢？

**Comment by emilyjeng** [comment]
@zhengbw0324 從瀏覽器打入recbole benchmark，找到的

**Comment by zhengbw0324** [comment]
@emilyjeng 您好！
benchmark页面目前不对外开放，给您带来麻烦非常抱歉。
