### ISSUE TITLE
[💡SUG] new dataset training

### ISSUE THREAD

**Issue by frostmourne78** [RUCAIBox/RecBole#1568]
Hello, when I want to use the recommended model of the knowledge graph to replace the data set for training, there is no default in the data set downloaded from the web disk. inter file, and error "dataset/MovieLens-KG\ movielens-kg. inter not exist" but it seems that this file is required in the code.Do you need to modify some parameters？

**Comment by Sherry-XLL** [comment]
@frostmourne78 Hello, for knowledge-based recommendation, RecBole provides users with three recommendation datasets as well as linked knowledge graph data, including [MovieLens](https://github.com/RUCAIBox/RecDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md), [Amazon-book](https://github.com/RUCAIBox/RecDatasets/blob/master/conversion_tools/usage/Amazon-book-KG.md) and [LFM-1b (tracks)](https://github.com/RUCAIBox/RecDatasets/blob/master/conversion_tools/usage/LFM-1b-KG.md). You can refer to our dataset repository [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) for more details. 

Take MovieLens-KG as an example, [this link](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md) shows how to generate the KG atomic files (*.kg and *.link) for MovieLens dataset.

**Comment by frostmourne78** [comment]
> 50/5000 
I downloaded the processed data set directly from the web disk, but I still could not start the training. There was no file with the suffix.inter in the data set and error was reported File dataset/MovieLens-KG\MovieLens-KG.inter not exist.

**Comment by Sherry-XLL** [comment]
@frostmourne78 Hello, you can directly download the processed interactions of MovieLens datasets from [Google Drive](https://drive.google.com/drive/folders/1OkDVEqetvOrtbuWebxl4y1JlZ_YjjfWj), including `ml-100k`, `ml-1m`, `ml-10m` and `ml-20m`, such as 'ml-100k.inter', 'ml-1m.inter' and so on. 

`MovieLens-KG` is the original dataset to generate the KG atomic files (*.kg and *.link) for MovieLens dataset, and you should follow the instructions in [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md) to get all atomic files. 

Similarly, if you want to get the knowledge graph data for `LFM-1b (tracks)`, you should download the interactions of `LFM-1b (tracks)` in [Google Drive](https://drive.google.com/drive/folders/1Kqu5-AA36pykOoVxBjPSzSmJeTRl4kvZ) and get `lfm1b-tracks.inter`. Then, download the KG file named `LFM-1b-KG.zip` from [Baidu Yun](https://pan.baidu.com/s/1p51sWMgVFbAaHQmL4aD_-g) or [Google Drive](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing) and run the following command in [RecSysDatasets/conversion_tools](https://github.com/RUCAIBox/RecSysDatasets) to get the KG atomic files of LFM-1b dataset.

```
python add_knowledge.py --dataset lfm1b-tracks --inter_file lfm1b-tracks.inter \ 
--kg_data_path LFM-1b-KG --output_path output_data/lfm1b-tracks/ --hop 1
```

After this, we will get 'lfm1b-tracks.kg' and 'lfm1b-tracks.link' in `output_data/lfm1b-tracks/`.

If you still have problems with the atomic files in RecBole, you can refer to the toy dataset in [test_data](https://github.com/RUCAIBox/RecBole/tree/master/tests/test_data/test) and documentation of [Atomic Files](https://recbole.io/docs/user_guide/data/atomic_files.html) for more details.

Thanks for your attention to RecBole!

**Comment by frostmourne78** [comment]
@Sherry-XLL Thanks for your answer！

**Comment by frostmourne78** [comment]
@Sherry-XLL Hello after processing the data of lfm1b according to the regulations, there was a situation that the data set was too large during the training, resulting in insufficient GPU video memory. Could you please set the data set optimization parameters in the recbole training parameters to reduce the GPU burden and accelerate the training？

**Comment by Sherry-XLL** [comment]
Hello @frostmourne78, RecBole has made many optimizations on training performance and memory occupation, and you are welcome to give us your suggestions on specific functions or modules.

The LFM-1b dataset is difficult to train because it is too large. It is recommended to use smaller data sets, or reduce the data size through data filtering methods such as `filter by value`, `remove interation by user or item` and `filter by number of interactions`. For details, please refer to [our documentation](https://recbole.io/docs/user_guide/config/data_settings.html#filtering) on dataset filtering.

Thanks again for your attention to RecBole!

**Comment by frostmourne78** [comment]
@Sherry-XLL Thanks for your answer！
