### ISSUE TITLE
[🐛BUG] MHCN模型每次运行结果不一样

### ISSUE THREAD

**Issue by LDY911** [RUCAIBox/RecBole#1572]
您好，我在运行RecBole_GNN中的社会化推荐中的MHCN时，设置了reproducibility = True，seed = 2020，但是发现每次运行结果不一样，想请教一下原因在哪里，谢谢！

**Comment by AoiDragon** [comment]
@LDY911 您好，RecBole_GNN是RecBole 2.0中的子库，您可以到[相应仓库](https://github.com/RUCAIBox/RecBole-GNN)中进行提问。

**Comment by Sherry-XLL** [comment]
@LDY911 您好，与 RecBole-GNN 子包相关的问题建议您在相关的子库下提 issue，我们开发团队会在 [RecBole-GNN issues 57](https://github.com/RUCAIBox/RecBole-GNN/issues/57) 下继续跟进您的问题，这个 issue 将被关闭，感谢您对 RecBole 系列的关注！
