### ISSUE TITLE
[🐛BUG] RecBole的v1.1.1版设置不同的worker，运行结果差距较大

### ISSUE THREAD

**Issue by LDY911** [RUCAIBox/RecBole#1573]
您好，我发现RecBole的v1.1.1版设置不同大小的worker，同一模型运行结果差距较大，想问一下是什么原因谢谢！

**Comment by zhengbw0324** [comment]
@LDY911 您好！
worker 的大小会一定程度上影响数据加载顺序，有可能影响模型结果。

**Comment by LDY911** [comment]
好的，感谢回复！

**Comment by zyx1017** [comment]
@zhengbw0324 您好！
请问只有v1.1.1版本才能设置这个worker参数嘛？
我使用的是v1.0.1版本，在服务器上训练时，GPU的利用率特别低，我想通过设置dataloaders的num_workers参数解决，但是好像没找到这个参数的设置方法。
如果改版本无法设置这个参数，请问有什么办法可以解决我这种情况嘛

**Comment by zhengbw0324** [comment]
@zyx1017 您好！
在v1.0.1版本中我们是完全自己实现的dataloader，并没有继承pytorch的Dataloader类，因此并没有workers参数。

**Comment by zyx1017** [comment]
> 

那针对在服务器上训练时，GPU的利用率特别低这种情况，有什么解决办法嘛

**Comment by zyx1017** [comment]
@zhengbw0324 那针对在服务器上训练时，GPU的利用率特别低这种情况，有什么解决办法嘛？在服务器上模型的训练时间非常慢

**Comment by zhengbw0324** [comment]
@zyx1017 如果GPU内存够大的话可以尝试调整训练和验证的batch size。

**Comment by zyx1017** [comment]
@zhengbw0324 好的。谢谢
