### ISSUE TITLE
Large CPU memory usage for distributed training

### ISSUE THREAD

**Issue by yogixRush** [RUCAIBox/RecBole#1578]
Hi all, thanks for the framework. I was trying distributed training (one machine multiple GPU) with Bert4Rec model, but the memory usage is a lot higher (about 4X higher) than single-gpu training and the process get killed because of this... Do you have any idea how to optimize CPU memory usage for distributed training?

**Comment by Paitesanshi** [comment]
@yogixRush Hi, thanks for your attention to RecBole!
Reducing the CPU usage in DDP training is a difficult problem, and we will consider optimizing this problem in subsequent development. As for now, I think you can try to reduce the batch_size, which may help reduce cpu usage.
