### ISSUE TITLE
cuda nvision

### ISSUE THREAD

**Issue by Iwillcome** [RUCAIBox/RecBole#1580]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

Dear Author:
   we have some problems with the RecBole framework, we use the 3090 GPU with 10.0 Cuda, but I can't run the code written by RecBole. I had tried other ways, but I find it needs to improve the Cuda version from 10.0 to the version of GPU. This way destroy the environment of the system make other code written by Tensorflow can't running.  I can't do it. However, I run the program in the current environment. The RecBole can adopt any complex condition. I didn't what solution can solve this problem.
  so, we wish the server can run RecBole and I didn't need to change the version of Cuda.

The experiment environment and code is fellow
The code of NCL.
URL: https://github.com/RUCAIBox/NCL
experiment envinorment
-Os System  Linux dell-PowerEdge-R740 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-RecBole 1.0.1
-PyTorch 1.9.0
-Cuda 10.0
![image](https://user-images.githubusercontent.com/51507131/206831004-10aa343a-3150-4892-9a16-8a81fbc66f12.png)
![image](https://user-images.githubusercontent.com/51507131/206831232-db4ccbf5-dbcd-4882-bf8c-dd0e6dbfacdc.png)
![image](https://user-images.githubusercontent.com/51507131/206831231-d0934640-f966-4fb3-ba9f-b2198bc3dee9.png)

**Comment by Iwillcome** [comment]
some file fails up, so the error log is list:
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
10 Dec 13:28    INFO  NCL(
  (user_embedding): Embedding(58145, 64)
  (item_embedding): Embedding(58052, 64)
  (mf_loss): BPRLoss()
  (reg_loss): EmbLoss()
)
Trainable parameters: 7436608
10 Dec 13:28    INFO  Running E-step ! 
WARNING clustering 58145 points to 2000 centroids: please provide at least 78000 training points
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265; details: cublas failed (13): (512, 64) x (2000, 64)' = (512, 2000) gemm params m 2000 n 512 k 64 trA T trB N lda 64 ldb 64 ldc 2000

**Comment by zhengbw0324** [comment]
@Iwillcome Hello！
If you are worried about affecting the environment of other programs, I suggest you use conda to create a new virtual environment, and then install pytorch corresponding to the GPU Cuda version. In addition, if you need to run the NCL model, you may also need to install the faiss library.

**Comment by Iwillcome** [comment]
Dear Author:
    Thanks for you response, this preoblem had solve.
                                                                                  best wish!
