### ISSUE TITLE
求问：序列模型是否可修改用AUC作为评价指标？

### ISSUE THREAD

**Issue by wzbaxx** [RUCAIBox/RecBole#1584]
我在跑序列模型DIN和DIEN时，使用AUC和logloss作为评价指标，当我想跑其他模型时发现报错
`NotImplementedError: Full sort evaluation do not match value-based metrics!`
我查看这些序列模型时发现都有一个full_sort_predict，以GRU4Rec为例
`def full_sort_predict(self, interaction):`
`        item_seq = interaction[self.ITEM_SEQ]`
`        item_seq_len = interaction[self.ITEM_SEQ_LEN]`
`        seq_output = self.forward(item_seq, item_seq_len)`
`        test_items_emb = self.item_embedding.weight`
`        scores = torch.matmul(seq_output, test_items_emb.transpose(0, 1))  # [B, n_items]`
`        return scores`
想知道是否该函数影响使用AUC报错，想问如果想要修改成该评价指标是否可行

**Comment by Wicknight** [comment]
@wzbaxx 您好！感谢您对伯乐的关注！
这是因为您在跑序列模型DIN和DIEN时没有使用full评测模式，而在跑其它序列模型时采用了full评测模式。因此您需要检查一下您的'eval_args'参数中'mode'参数的取值，关于该参数的相关信息您可以查阅[文档](https://recbole.io/docs/user_guide/train_eval_intro.html#evaluation-method)。
