### ISSUE TITLE
是否可以选择不适用验证集

### ISSUE THREAD

**Issue by fightingman1** [RUCAIBox/RecBole#1587]
在配置数据集时是否可以只是用训练集和测试集，而不使用验证集

**Comment by zhengbw0324** [comment]
@fightingman1 您好！
如果您使用按比例划分数据集也就是`RS`模式，不支持仅使用测试集。反之如果您使用留一法划分数据集也就是`LS`模式，可以选择三种模式，支持仅使用验证集或测试集。具体信息请参考我们的[文档](https://recbole.io/docs/user_guide/config/data_settings.html)。
