### ISSUE TITLE
On the implementation of MacridVAE

### ISSUE THREAD

**Issue by trannhuthuat96** [RUCAIBox/RecBole#1590]
Hi Team,

In your implementation of MacridVAE in line 89 https://github.com/RUCAIBox/RecBole/blob/0c7197b01c009d822ed95d17011ab6289c86ac58/recbole/model/general_recommender/macridvae.py#L89, a dropout layer is applied before multiplying with `cates_k` in line 107 https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/macridvae.py#L107. 
This implementation may remove one or more historical interaction(s) due to dropout, which is in contrast with formula (7) in the paper https://proceedings.neurips.cc/paper/2019/file/a2186aa7c086b46ad4e8bf81e2a3a19b-Paper.pdf.

In original implementation by author, 
![image](https://user-images.githubusercontent.com/21955171/208301688-a076afd7-a8e2-4946-acc2-15147032a792.png), 
`rating matrix (input_ph)` is multiplied by `cates_k` first before applying normalization and dropout.
MacridVAE code published by author can be found at https://jianxinma.github.io/

Could you please explain this difference as this may cause a big gap between model performance?

Thank you so much.

**Comment by chenyuwuxin** [comment]
@trannhuthuat96  Hello. Thank you very much for your reminder! We will confirm this problem and fix it in the subsequent version.

**Comment by trannhuthuat96** [comment]
@chenyuwuxin Thank you. Sorry for late response. Issue close!
