### ISSUE TITLE
[💡SUG] Looking for evaluating on a custom at a data split

### ISSUE THREAD

**Issue by cramraj8** [RUCAIBox/RecBole#1592]
I am using my custom datasets in the DIGINITICA format to run GRU4Rec. However, my custom dataset has its own custom data split between train & test. So I wonder can I specify the split to the API or can I separately load train data and once I completed the training, can I separately load test data and evaluate on the saved model ?

Especially I am looking for ways to evaluate a model on a separate dataset given that I loaded the model using the following API,
```
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file="../saved/GRU4Rec-Aug-20-2021_03-32-13.pth",
    )
```

**Comment by Paitesanshi** [comment]
@cramraj8 Hi,thanks for your attention to RecBole!
RecBole supports custom split of datasets, please refer to the [documentation](https://recbole.io/docs/user_guide/config/data_settings.html#benchmark-file) for details
