### ISSUE TITLE
ModuleNotFoundError: No module named 'recbole.config'; 'recbole' is not a package

### ISSUE THREAD

**Issue by Furyboyy** [RUCAIBox/RecBole#1594]
我按照指引安装了之后，在`import recbole`时遇到了`ModuleNotFoundError: No module named 'recbole.config'; 'recbole' is not a package`。

pip和conda都试过，一样的结果。

**Comment by zhengbw0324** [comment]
@Furyboyy 您好！
直接`import recbole`应该会出错，如果您需要使用Config类，应通过`from recbole.config import Config`导入。

**Comment by Furyboyy** [comment]
Hi @zhengbw0324 , 报了一样的bug。完整错误信息
`Traceback (most recent call last):
  File "recbole.py", line 5, in <module>
    from recbole.config import Config
  File "/home/workshop22/recomendation/recbole.py", line 5, in <module>
    from recbole.config import Config
ModuleNotFoundError: No module named 'recbole.config'; 'recbole' is not a package
`

**Comment by zhengbw0324** [comment]
@Furyboyy 
您的当前目录下是否有一个名叫`recbole`的python文件，如果有请更换名称。

**Comment by Furyboyy** [comment]
噢~我知道问题了，感谢
