### ISSUE TITLE
关于用户项目的初始Embedding

### ISSUE THREAD

**Issue by RSnewbie** [RUCAIBox/RecBole#1601]
十分感谢您们的工作！！

在使用您们的平台时，发现使用LightGCN等相关模型时初始Embedding：（用户/物品数量 + 1） * d

因需要进行特征融合(concat)，会出现维度不一致问题

请问如何可以修改初始化Embedding的维度为: （用户/物品实际数量） *  d

期待您的回复

**Comment by zhengbw0324** [comment]
@RSnewbie 您好！
对于user和item，我们在进行数据处理时会将0视为用于padding的index，因此索引为0的user/item没有实际意义，您如果不需要这个embedding，可以通过切片`[1:]`忽略它。

**Comment by RSnewbie** [comment]
> @RSnewbie 您好！ 对于user和item，我们在进行数据处理时会将0视为用于padding的index，因此索引为0的user/item没有实际意义，您如果不需要这个嵌入，可以通过切片忽略它。`[1:]`

十分感谢您的回复!

切片方法之前也使用过，当对初始的embedding.weight切片进行覆盖后，会引起梯度计算错误的问题；

如果想着在源码的基础上进行修改index，可以从哪里修改呢？

**Comment by zhengbw0324** [comment]
@RSnewbie 
您是对初始Embedding的权重进行重新赋值了吗？不需要重新赋值，当你需要使用的时候进行切片，不建议对embedding.weight进行修改或覆盖。

**Comment by RSnewbie** [comment]
> @RSnewbie 您是对初始Embedding的权重进行重新赋值了吗？不需要重新赋值，当你需要使用的时候进行切片，不建议对embedding.weight进行修改或覆盖。

好的好的，十分感谢您的回复
