### ISSUE TITLE
[🐛BUG] 随着TOPK的增大NDCG逐渐减小

### ISSUE THREAD

**Issue by RSnewbie** [RUCAIBox/RecBole#1605]
您好，十分感谢您们的工作！

在运行几个经典模型(NGCF、LightGCN)时，让K=[1,2,3,4,5,6,7,8,9,10]

NDCG的值是随之减小的，当K=1时NDCG数值最大，K=10时数值最小

数据集为自建数据集

其他参数为:
eval_args:                      
  split: {'RS':[0.7,0.1,0.2]}   
  group_by: user                
  order: RO                     
  mode: full                 
repeatable: False               
metrics: ["Recall","NDCG"]  
topk: [1,2,3,4,5,6,7,8,9,10]                      
valid_metric: NDCG@10           
valid_metric_bigger: True      
eval_batch_size: 4096         
metric_decimal_place: 4

**Comment by Wicknight** [comment]
@RSnewbie 您好！感谢您对RecBole的关注！

我认为NDCG的值和K的大小似乎没有必然的联系，这很大程度上取决于您推荐结果中候选物品的顺序，您可以通过打印模型的推荐结果来对这个递减结果进行验证。我们在ml-100k数据集上进行上述实验，会发现NDCG的值先随着K的增加而减小（K∈[1,7]），之后随着K的增加而增加(K∈[8,10])。

**Comment by RSnewbie** [comment]
> @RSnewbie 您好！感谢您对RecBole的关注！
> 
> 我认为NDCG的值和K的大小似乎没有必然的联系，这很大程度上取决于您推荐结果中候选物品的顺序，您可以通过打印模型的推荐结果来对这个递减结果进行验证。我们在ml-100k数据集上进行上述实验，会发现NDCG的值先随着K的增加而减小（K∈[1,7]），之后随着K的增加而增加(K∈[8,10])。

好的好的，十分感谢您的回复！
