### ISSUE TITLE
关于simpleX的实现

### ISSUE THREAD

**Issue by Luo-rex** [RUCAIBox/RecBole#1608]
您好！

这可能是一个数学问题

根据SimpleX的论文，CCL损失函数应该会使用向量的余弦相似度来进行计算，但在recbole对simpleX的实现中，使用的是`torch.matmul()`函数，请问这是为什么呢？是因为这样的做法和`torch.cosine_similarity()`在训练时效果相同吗？那在预测时会不会有不同的影响呢？

![image](https://user-images.githubusercontent.com/83912716/210066511-8e49eccd-219e-4f6e-bc4c-46e04b6aa157.png)
图为recbole中SimpleX模型计算cos的部分

**Comment by zhengbw0324** [comment]
@Luo-rex 您好！
先进行normalize，再使用matmul进行内积操作与计算余弦相似度是等价的，您可以写出公式，很容易理解。

**Comment by Luo-rex** [comment]
啊，我理解了，感谢解答！

顺便，元旦快乐！
