### ISSUE TITLE
请问应该如何在yaml文件中设置"MODEL_INPUT_TYPE"？

### ISSUE THREAD

**Issue by LorenzoSun-V** [RUCAIBox/RecBole#1614]
比如默认是`InputType.POINTWISE`，但是我想强制改成`InputType.PAIRWISE`，我该如何在yaml文件中修改呢？

**Comment by leoleojie** [comment]
@LorenzoSun-V 您好，感谢你对伯乐的关注！
目前伯乐并不支持在yaml文件中修改model_input_type
 如果您想要修改默认的方式，您可以通过在模型文件中定义```input_type = InputType.PAIRWISE```来实现。
具体可参考[我们的文档](https://recbole.io/docs/developer_guide/customize_models.html)

**Comment by LorenzoSun-V** [comment]
好的，谢谢！
