### ISSUE TITLE
[💡SUG] export embeddings

### ISSUE THREAD

**Issue by skunkwerk** [RUCAIBox/RecBole#1620]
**Is your feature request related to a problem? Please describe.**
Is there a way to export the embeddings from supported models, such as lightGCN?

**Describe the solution you'd like**
For example, the recommenders library has [this method](https://microsoft-recommenders.readthedocs.io/en/staging/models.html#recommenders.models.deeprec.models.graphrec.lightgcn.LightGCN.infer_embedding) to export the user & item embeddings

**Additional context**
For online KNN search in production

**Comment by Paitesanshi** [comment]
@skunkwerk Hi,thanks for your attention to RecBole!
Thanks for your suggestion! I'm sorry that this feature is not currently supported. However, we will take it into consideration for future development. In the meantime, you can use the `torch.save` function to export the embeddings after training.

**Comment by skunkwerk** [comment]
ok thanks I'll try it out
