### ISSUE TITLE
Questions about considering the user features in sequential recommender

### ISSUE THREAD

**Issue by freedomSummer1964** [RUCAIBox/RecBole#1629]
Thank you for the excellent work. Now I have a problem in considering the user features in sequential recommender.
For an example, I use sasrecf, and I get the item embedding `item_emb` with the size (2048,50,64), where 2048 is the batch size, 50 is the length of sequence, 64 is the embedding size, then I get the item feature embedding `item_feature_emb` with the size (2048,50,192), 3 is the number of item features.
Then I use your ContextSeqEmbLayer class to get the user feature embedding `user_feature_emb` with the size (2048, 320), 5 is the number of user features.
The basic code is
`input_concat = torch.cat((item_emb, item_feature_emb), -1)  # [B 1+field_num*H]`

 `input_emb = self.concat_layer(input_concat)`
and the size of `input_emb` is (2048,50,256).

Now I want to concat the user embedding `user_feature_emb` into the input_emb, and get the final `input_emb` with size of (2048, 50, 256+320)=(2048,50, 576). But to concat them, tensors must have same number of dimensions, the item_emb and feature_emb is 3 and user embedding is 2. To the purchase sequence, the user feature is not change. So should I need to extend the `user_feature_emb` from (2048, 320) to (2048,50, 320)?
Would you please show me the code to concat them? I noticed that the code of DIN also doesn't show how to use the user embedding in final recommendation. Thank you very much!

**Comment by ChuanSaoSun** [comment]
I tried a method to solve the problem
`tt=feature_emb_user.unsqueeze(1) `
`feature_emb_user_new = tt.repeat(1, 50, 1)`
So the `feature_emb_user_new`size is (2048,50, 320) now
For each user, the user feature is the same for the 50 items, so I repeat them. Is this right? Thank you！

**Comment by zhengbw0324** [comment]
@freedomSummer1964 Hello!
You are right. In addition, you can achieve the same operation through the "expand" function.

**Comment by freedomSummer1964** [comment]
> @freedomSummer1964 Hello! You are right. In addition, you can achieve the same operation through the "expand" function.

Thank you!
