### ISSUE TITLE
[🐛BUG] GCMC dense layer error

### ISSUE THREAD

**Issue by jackmedda** [RUCAIBox/RecBole#1631]
Inside the GcEncoder of GCMC the user and item embeddings are fed into the dense layer as follows:
```
u_hidden = self.dense_layer_u(u_hidden)
v_hidden = self.dense_layer_u(v_hidden)
```
Shouldn't be:
```
u_hidden = self.dense_layer_u(u_hidden)
v_hidden = self.dense_layer_v(v_hidden)
```
It share_user_item_weights = False the user dense layer would be used for both embeddings

**Comment by Sherry-XLL** [comment]
@jackmedda Hello, thanks very much for your suggestion, we have fixed this bug in #1635.
