### ISSUE TITLE
使用AutoInt模型时，报如下错误

### ISSUE THREAD

**Issue by yandong667** [RUCAIBox/RecBole#1633]
![image](https://user-images.githubusercontent.com/43993301/216057401-217b7a58-e835-415e-9f24-2e0cd847b01a.png)

**Comment by Wicknight** [comment]
@yandong667 您好！感谢您对RecBole的关注！
经过检验，AutoInt模型可以正常在ml-100k等数据集上运行。根据您提供的报错信息，该问题应该是您的配置文件缺失信息导致的，请您检查配置文件中`'embedding_size'`, `'attention_size'`等信息是否丢失。

**Comment by Wicknight** [comment]
由于该issue 长时间未回复，我们将关闭该issue，如果您后续遇到相关问题，欢迎您继续和我们讨论！
