### ISSUE TITLE
[🐛BUG] MCCLK

### ISSUE THREAD

**Issue by frostmourne78** [RUCAIBox/RecBole#1638]
![image](https://user-images.githubusercontent.com/93038658/217709416-16294e92-9ae5-4602-8381-1d80cd6f8393.png)
Hello, running the relational MCCKL model in the recbole library has encountered the following problems. I have tried to reproduce the environmental requirements in the paper, but there is no result.

**Comment by Sherry-XLL** [comment]
@frostmourne78 Hello, thanks for your attention to RecBole! If you need to use the KGIN or MCCLK model, you need to install `torch-scatter` for the running environment as follows.

First, you need to check the version of `torch` and `cuda` on your device:
```
python -c "import torch; print(torch.__version__)"
>>> 1.12.1
python -c "import torch; print(torch.version.cuda)"
>>> 11.3
```

Then install `torch-scatter` according to the version of `torch` and `cuda`. The command is as follows:
```
pip install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html
# eg：pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
```

If you have further questions, please feel free to contact us.

**Comment by frostmourne78** [comment]
@Sherry-XLL Thank you for your answer！
