### ISSUE TITLE
[💡SUG] 在evaluation阶段，可否将 `NegSampleEvalDataLoader` 用于 `valid` phase，而将 `FullSortEvalDataLoader` 用于 `test` phase?

### ISSUE THREAD

**Issue by ChenglongMa** [RUCAIBox/RecBole#1640]
**您希望添加的功能是否与某个问题相关？**
这个问题的出发点是在我想得到模型的topN结果，按照文档或 case study 中的例子，我需要用 `FullSortEvalDataLoader`, 但是像 `DIN` 或 `DIEN` 这种默认使用 `NegSampleEvalDataLoader` 的是走不通的（原因在于 `NegSampleEvalDataLoader` 没有 `is_sequential` 这一值，当然我们可以修改原代码将它补充上）；但是我想是否可以对 valid data 和 test data使用不同的dataloader？我认为理论上是可行的，请指正！

**描述您希望的解决方案**
假设在yaml配置文件中将 `eval_args` 分为 `valid_eval_args` 和 `test_eval_args`，
然后在 [recbole.data.utils#get_dataloader](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/utils.py#L247) 处，修改如下：
```diff
+ eval_mode = config[f"{phase}_eval_args"]["mode"]
- eval_mode = config["eval_args"]["mode"]
  if eval_mode == "full":
      return FullSortEvalDataLoader
  else:
      return NegSampleEvalDataLoader
```
这样我们可以分别为valid phase和test phase配置不同的evaluator。

**描述您考虑的替代方案**
如果只是单纯解决我上述提到了 case study 的问题，我建议将 [self.is_sequential = config["MODEL_TYPE"] == ModelType.SEQUENTIAL](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataloader/general_dataloader.py#L195) 放到 [AbstractDataLoader#\_\_init\_\_()](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataloader/abstract_dataloader.py#L47) 中

**其他**
如有需要我愿意创建一个 pull request，谢谢！

**Comment by Wicknight** [comment]
@ChenglongMa 您好！非常感谢您的建议，对 valid data 和 test data使用不同的dataloader确实是潜在的需求，同时也是可行的方案，欢迎您创建pull request来进一步探讨！

**Comment by ChenglongMa** [comment]
@Wicknight 您好，我已经创建了相应的pull request，有问题我们再讨论 :)
