### ISSUE TITLE
[🐛BUG] Data leakage in `data_augmentation`

### ISSUE THREAD

**Issue by ChenglongMa** [RUCAIBox/RecBole#1649]
**描述这个 bug**

在 `SequentialDataset` 中我们需要先进行 `data_augmentation` 操作，然后再进行数据划分；但是对于 `item_id_list` 这一用户历史数据是否存在 Data leakage 问题？

**如何复现**

假如数据集中用户A交互的 item 序列为：`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`，`data_augmentation` 操作会有如下结果：

| user_id | item_id | item_id_list          |       |
|---------|---------|-----------------------|-------|
| A       | 1       | 0                     |       |
| A       | 2       | 1                     |       |
| A       | 3       | 1 2                   |       |
| A       | 4       | 1 2 3                 |       |
| A       | 5       | 1 2 3 4               |       |
| A       | 6       | 1 2 3 4 5             |       |
| A       | 7       | 1 2 3 4 5 6           | train |
| A       | 8       | 1 2 3 4 5 6 7         | valid |
| A       | 9       | 1 2 3 4 5 6 7 **8**   | test  |
| A       | 10      | 1 2 3 4 5 6 7 **8 9** | test  |

如果我们按照 `0.7, 0.1, 0.2` 划分，`item_id` 为 `9` 和 `10` 的数据会划分到 `test` 中，但是 `item_id_list`则
将 `8` 和 `9` 泄漏了。

**预期**

不应将 `valid` 数据甚至 `test` 历史数据包含在 `test`中，上例中的 `test` 应为：

| user_id | item_id | item_id_list  |      |
|---------|---------|---------------|------|
| A       | 9       | 1 2 3 4 5 6 7 | test |
| A       | 10      | 1 2 3 4 5 6 7 | test |

不知道这是不是一个潜在的bug？谢谢！

**Comment by leoleojie** [comment]
@ChenglongMa 感谢您对伯乐的关注。
通常情况下我们在使用序列数据增强时，会使用leave-one-out的评测方式，在您的例子中，我们会将```item_id_list: 1,2,3,4,5,6,7,8->9```作为验证集，而将```item_id_list: 1,2,3,4,5,6,7,8,9->10```作为测试集，其余作为训练集使用，所以并不会造成您说的问题。

**Comment by ChenglongMa** [comment]
@leoleojie 谢谢您的回答，但是 `RS` 的方式在Recbole中也是被允许的吧？而且这也是一个常见的评测方式。

**Comment by hyp1231** [comment]
@ChenglongMa 您好！这确实是个很好的问题。

我们当时开发的时候确实有考虑过，比如对 test 集合的历史交互序列要不要引入 `8 9` 这段在训练集中没出现的序列。最终我们选择了您看到的这种数据划分方式则主要出于两点考虑：
* 更符合真实场景。我们可以认为 train 集合上训练得到的模型就是实际中部署的模型，那在部署后，`1 2 ... 8` 和 `1 2 ... 8 9` 这样的序列是更符合数据真实分布的，比如实际业务中我们也不会在上线后对需要预测的用户行为进行截断。
* 几乎不会有严重的数据泄露的问题。我推断您想说的是，比如模型会不会因为见过 `1 2 ... 8 9` 就知道了 `1 2 ...` 后面要接商品 `8`。我们讨论的结果是，如果按照 ratio 划分的话，如果 valid 集合时间跨度很长，那模型确实可能会有略微过拟合在 valid 集合上。但是这对 test 集合的表现影响不大，因为在 test 集合的任何数据都不会被用于帮助训练模型。此外，我个人推测，这可能也是目前学界比较常用 leave one out 划分方法的原因，因为会规避掉刚才说的问题。

但是这并不是说我们认为 RecBole 已有的实现方式是优于您提到的那种方式的。我个人认为只要所比较的模型都使用同一种划分方式，且不要专门卡这种bug来设计模型，那这两种方式都是合理的。此外，据我们所知，可能也没有论文专门讨论过这个问题。

**Comment by ChenglongMa** [comment]
@hyp1231 非常感谢您的解答，我明白了！
