### ISSUE TITLE
训练完模型之后如何加载模型做推理？

### ISSUE THREAD

**Issue by lironghua318** [RUCAIBox/RecBole#1661]
模型训练完成后如何加载模型文件推理呢？比如dssm，推理的一条数据也要用dataset类吗，看代码好像只能这样？

**Comment by Wicknight** [comment]
@lironghua318 是的，需要对使用的数据做一定处理与封装之后进行推理。您可以参考我们提供的[具体样例](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py)来实现。

**Comment by Wicknight** [comment]
由于该issue 长时间未回复，我们将关闭该issue，如果您后续遇到相关问题，欢迎您继续和我们讨论！
