### ISSUE TITLE
如何加速Evaluate阶段？

### ISSUE THREAD

**Issue by ralgond** [RUCAIBox/RecBole#1664]
hi，您好

我发现训练需要的时间要比Evaluate少很多，比如train需要9分钟，而Evaluate却要30-40分钟，请问有没有什么办法让Evaluate快一点？

谢谢

**Comment by zhengbw0324** [comment]
@ralgond 您好！
您可以在GPU内存允许的情况下适当增大`eval_batch_size`。或者在配置文件中设置`worker`，加快数据加载速度。
