### ISSUE TITLE
[💡SUG] 你好，请问如果我把购买和浏览数据合并在一个文件里面时（添加了一列表示行为类型），drop_duplicates过滤重复数据时，是否会考虑到行为的不同

### ISSUE THREAD

**Issue by XiaoJing-C** [RUCAIBox/RecBole#1665]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by peteryang1031** [comment]
您好，在伯乐中实现的drop_duplicates函数是根据user-item pair来过滤重复数据的。您可以在dataset.py文件中的drop_duplicates函数的subset参数中加入您自定义的行为类型，例如[self.uid_field, self.iid_field, self.behavior_type]，这样可以仅对具有相同行为类型的重复数据进行过滤。
感谢您对伯乐的关注，希望我的回答能够对您有帮助。
