### ISSUE TITLE
[🐛BUG] 用一句话描述您的问题。

### ISSUE THREAD

**Issue by hpli** [RUCAIBox/RecBole#1672]
**描述这个 bug**
对 bug 作一个清晰简明的描述。

**如何复现**
复现这个 bug 的步骤：
1. 您引入的额外 yaml 文件
# Training and evaluation config
epochs: 500
train_batch_size: 12288
eval_batch_size: 4096
train_neg_sample_args:
    distribution: uniform
    sample_num: 1
    alpha: 1.0
    dynamic: False
    candidate_num: 0
eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: MRR@10
metric_decimal_place: 4
2 您的代码
run_recbole(model='SimpleX', dataset='yelp-2018',config_file_list=['test-yelp-2018.yaml'])

问题1：
![image](https://user-images.githubusercontent.com/9545680/222122361-92862771-0ddd-43e7-96a4-08e76b35c1f9.png)
每一步训练后，运行evaluating占用时间特别大，为什么？有什么办法加快训练过程吗？
问题2:
为了加快训练过程，我将 train_batch_size 设置为 12288 是默认值的3倍，但是显存几乎没有变化。
![image](https://user-images.githubusercontent.com/9545680/222123137-1a852709-1f03-4dfc-a224-3479081a6f06.png)

**实验环境（请补全下列信息）：**
 - 操作系统: ubuntu 22.04
- RecBole 1.1.1
 - Python 3.9.3
- PyTorch 1.11.0+cu113
- cudatoolkit 版本 不清楚如何查看，ubuntu上安装gpu版pytorch和显卡驱动，没有单独安装cudatoolkit，有没有影响？

期待您的解答，谢谢！

**Comment by peteryang1031** [comment]
您好，以下是对您上述问题的解答：
