### ISSUE TITLE
When using uni100 mode when evaluating bert4rec, the program gives an error

### ISSUE THREAD

**Issue by chang88710** [RUCAIBox/RecBole#1673]
Hello BoleRec Team:

When I use the uni100 mode when evaluating bert4rec, the program reports an error, and the given error code is shown in the attachment.

Also, when evaluating SASRec in uni100 mode, no error is reported.

I tried many things, including error codes, instructions to set CUDA_LAUNCH_BLOCKING=1, and methods in #1012, #1042.

However, this problem cannot be ruled out. I hope you can help me and look forward to your reply.

ERROR CODE:
"CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1."
![image](https://user-images.githubusercontent.com/47891043/222419673-1abc3e13-1088-408a-bb85-a7313d7b84ea.png)

**Comment by Sherry-XLL** [comment]
Hello @chang88710! Thanks for your attention to RecBole.

The reason for this error is that there is a small problem in the `predict` function of BERT4Rec. We have fixed this bug in #1675. You are welcome to download our latest version of code and conduct the experiment again. 

Thank you again for your feedback on RecBole!

**Comment by chang88710** [comment]
Hello @Sherry-XLL 
Thanks for your help, the program can run successfully and use uni100 mode to evaluate bert4rec.

非常感謝您，祝您有個美好的一天 :)
