### ISSUE TITLE
[🐛BUG] torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by maancham** [RUCAIBox/RecBole#1676]
**Describe the bug**
Hi, I am trying to run large Movielens datasets and do a case study using a few general recommender algorithms, like NAIS, FISM, etc. However, I keep running out of memory from torch!

**To Reproduce**
Just use 'run_recbole' with a relatively large dataset and model = 'NAIS'. I have provided the link to my sample Colab notebook. Please make sure to set runtime type to 'GPU'.

**Expected behavior**
The training failed midway. I thought the issue was with Colab. Thus, I tied to run the code on another server with V100 GPU (32 GB memory) but received the same error: _(GPU 0; 31.75 GiB total capacity; 20.61 GiB already allocated; 10.47 GiB free; 20.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF._  
The same issue happened with NeuMF and FISM. I searched the web but did not find a decent way to set PYTORCH_CUDA_ALLOC_CONF.

**Screenshots**
![image](https://user-images.githubusercontent.com/45919414/222556650-50810c3f-be60-4205-82cd-05525aee3e98.png)

**Colab Links**
https://colab.research.google.com/drive/1_TKe9RlzCdX4oiNKYTkIgzyNv6mZK_F-?usp=sharing

**Desktop (please complete the following information):**
 - OS: [Linux]
- RecBole Version [1.1.1]
 - Python Version [3.8]
- PyTorch Version [1.13]
- cudatoolkit Version [11.8]

**Comment by Paitesanshi** [comment]
@maancham Hi, thanks for your attention to RecBole!
As indicated by the WARNING message in the figure, you can increase `split_to` to avoid OOM errors. For example, you can set `--split_to=5` in the command line or `split_to: 5` in the config file.

**Comment by maancham** [comment]
Thanks :)
