### ISSUE TITLE
[🐛BUG] KeyError: 'class' occurs when running the GRU4RecF model on ml-100k dataset.

### ISSUE THREAD

**Issue by FannieCream** [RUCAIBox/RecBole#1679]
**Describe the bug**
Hi, when i was running the GRU4RecF model on ml-100k dataset, an error occured: KeyError: 'class'. And the traceback is as followed:

> Traceback (most recent call last):
  File "run_recbole.py", line 52, in <module>
    model=args.model, dataset=args.dataset, config_file_list=config_file_list
  File "/data/lyf/PL-LSC/recbole/quick_start/quick_start.py", line 77, in run_recbole
    model = get_model(config["model"])(config, train_data._dataset).to(config["device"])
  File "/data/lyf/PL-LSC/recbole/model/sequential_recommender/gru4recf.py", line 66, in __init__
    self.device,
  File "/data/lyf/PL-LSC/recbole/model/layers.py", line 1264, in __init__
    self.get_fields_name_dim()
  File "/data/lyf/PL-LSC/recbole/model/layers.py", line 900, in get_fields_name_dim
    if self.dataset.field2type[field_name] == FeatureType.TOKEN:
KeyError: 'class'

**To Reproduce**
1. Following the GRU4RecF documentation, I modified the _ml-100k.inter_ by merge _ml-100k.inter_ and _ml-100k.item_  to add the _class:token_seq_ to the _ml-100k.inter_, an example in modified _ml-100k.inter_ is as followed(sep="\t"):

> user_id:token	item_id:token	rating:float	timestamp:float	movie_title:token_seq	release_year:token	class:token_seq
196	242	3	881250949	Kolya	1996	Comedy

2. I also modified the _.yaml_:  

> selected_features: ['class']
load_col:
    inter: [user_id, item_id, timestamp, rating, class]

3. script for running:
`python -u run_recbole.py --model GRU4RecF --dataset ml-100k --config_files configs/ml-100k-gru4recf.yaml`

4. There is no more modification except the above files.

**Expected behavior**
No bugs.

**Desktop**
 - OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-48-generic x86_64)
- RecBole Version: 1.1.1
 - Python Version: 3.7.16
- PyTorch Version: 1.12.0+cu102
- CUDA Version: 11.0

**Looking forward to your reply.**

**Comment by peteryang1031** [comment]
Hi@FannieCream, it is necessary to add `item: [class]` under `load_col` when you wanna embed item features, and parameter `selected_features` is particularly designed for `.item` file. Hope my answer is helpful for you.

**Comment by FannieCream** [comment]
Thanks for your solution! It works when i modified the .yaml like this:

> selected_features: ['class']
load_col:
inter: [user_id, item_id, timestamp, rating]
item: [item_id, class]
