### ISSUE TITLE
[🐛BUG] The performance of SASRec from RecBole is much worse than that from the implementation of authors on ml1m

### ISSUE THREAD

**Issue by BoPeng112** [RUCAIBox/RecBole#1682]
Thanks for the great project. I recently found that on ml1m, the HIT@10 of SASRec from RecBole is around 16%, however if I use the implementation from "https://github.com/pmixer/SASRec.pytorch", it gives me HIT@10 of about 25%. Do you have any idea of why will it happen? I could provide my processed dataset and training scripts if needed.

**Comment by Wicknight** [comment]
Hello @BoPeng112 , thanks for your attention to RecBole!

I think the first thing you need to check is whether the two versions of SASRec model run in exactly the same setting.

For example, you can check whether the evaluation method and negative sampling method is the same for both versions of SASRec.

**Comment by Wicknight** [comment]
Since this issue has not been replied for a long time, we will close this issue. If you have any problems, you are welcome to continue to discuss with us!
