### ISSUE TITLE
a problem with pre-trained embeddins

### ISSUE THREAD

**Issue by bodymostafa123** [RUCAIBox/RecBole#1689]
![git3](https://user-images.githubusercontent.com/63293505/224505354-011b01f1-caf1-4f97-8f7f-4250ef7f0e13.JPG)
![git1](https://user-images.githubusercontent.com/63293505/224505339-b9203158-a704-49ae-aff7-f7822f1322ca.JPG)

I got the following error I don't know why
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [27], in <cell line: 1>()
----> 1 dataset = create_dataset(config )

File ~\anaconda3\lib\site-packages\recbole\data\utils.py:70, in create_dataset(config)
     67         logger.info(set_color("Load filtered dataset from", "pink") + f": [{file}]")
     68         return dataset
---> 70 dataset = dataset_class(config)
     71 if config["save_dataset"]:
     72     dataset.save()

File ~\anaconda3\lib\site-packages\recbole\data\dataset\sequential_dataset.py:36, in SequentialDataset.__init__(self, config)
     34 self.max_item_list_len = config["MAX_ITEM_LIST_LENGTH"]
     35 self.item_list_length_field = config["ITEM_LIST_LENGTH_FIELD"]
---> 36 super().__init__(config)
     37 if config["benchmark_filename"] is not None:
     38     self._benchmark_presets()

File ~\anaconda3\lib\site-packages\recbole\data\dataset\dataset.py:108, in Dataset.__init__(self, config)
    106 self.dataset_name = config["dataset"]
    107 self.logger = getLogger()
--> 108 self._from_scratch()

File ~\anaconda3\lib\site-packages\recbole\data\dataset\dataset.py:118, in Dataset._from_scratch(self)
    116 self._get_preset()
    117 self._get_field_from_config()
--> 118 self._load_data(self.dataset_name, self.dataset_path)
    119 self._init_alias()
    120 self._data_processing()

File ~\anaconda3\lib\site-packages\recbole\data\dataset\dataset.py:275, in Dataset._load_data(self, token, dataset_path)
    269 self.user_feat = self._load_user_or_item_feat(
    270     token, dataset_path, FeatureSource.USER, "uid_field"
    271 )
    272 self.item_feat = self._load_user_or_item_feat(
    273     token, dataset_path, FeatureSource.ITEM, "iid_field"
    274 )
--> 275 self._load_additional_feat(token, dataset_path)

File ~\anaconda3\lib\site-packages\recbole\data\dataset\dataset.py:383, in Dataset._load_additional_feat(self, token, dataset_path)
    381 feat_path = os.path.join(dataset_path, f"{token}.{suf}")
    382 if os.path.isfile(feat_path):
--> 383     feat = self._load_feat(feat_path, suf)
    384 else:
    385     raise ValueError(f"Additional feature file [{feat_path}] not found.")

File ~\anaconda3\lib\site-packages\recbole\data\dataset\dataset.py:462, in Dataset._load_feat(self, filepath, source)
    460     head = f.readline()[:-1]
    461 for field_type in head.split(field_separator):
--> 462     field, ftype = field_type.split(":")
    463     try:
    464         ftype = FeatureType(ftype)

ValueError: too many values to unpack (expected 2)

**Comment by bodymostafa123** [comment]
the problem is with the way of  saving the dataframe

**Comment by tillwf** [comment]
For those who may come here, I solve the problem by saving the csv with `\t` as separator.

When I specified `"field_separator": ","` in the `config` it didn't work.
