### ISSUE TITLE
[🐛BUG] 关于training negative items的问题

### ISSUE THREAD

**Issue by LiuZS10** [RUCAIBox/RecBole#1695]
在issue #1646 中， 当training negative items设置为3时，interactions的形式为.
ITEM_ID | NEG_ITEM_ID
-- | --
1 | 3
1 | 4
1 | 5
2 | 7
2 | 8
2 | 9

（https://github.com/RUCAIBox/RecBole/issues/1646#issuecomment-1430666781）
请问是否可以得到
| ITEM_ID  |      NEG_ITEM_ID      | 
|-----|-------|
| 1 |  3,4,5 | 
| 2 |   7,8,9   | 

形式的interaction呢，（user, pos_item, list of neg items）

**Comment by Wicknight** [comment]
@LiuZS10 您好！感谢您对RecBole的关注！
如果想要实现您的需求，需要对以下代码进行检查或修改：

1. 修改[`AbstractSampler`](https://github.com/RUCAIBox/RecBole/blob/master/recbole/sampler/sampler.py)中的`sample_by_key_ids`函数，在您给出的例子中，该函数会返回shape=(2x3, ) 的包含neg_item的tensor，您可以将其reshape为shape=(2, 3)的tensor；

2. 修改NegSampleDataLoader中的_neg_sample_by_pair_wise_sampling函数以及_neg_sample_by_point_wise_sampling函数，在这两个函数中我们使用了repeat函数来将pos_item的维度进行扩展，您可以根据您的需求进行调整；

3. 检查您使用的模型（如`BPR`模型的`calculate_loss`部分）是否满足您的需求

如果您在修改的过程中遇到问题，也欢迎您随时和我们讨论！

**Comment by LiuZS10** [comment]
@Wicknight 感谢回复，十分感谢您提供的方法，亲测有效

**Comment by Wicknight** [comment]
由于该issue 长时间未回复，我们将关闭该issue，如果您后续遇到相关问题，欢迎您继续和我们讨论！
