### ISSUE TITLE
[💡SUG] 最终的结果可以保留6位小数吗

### ISSUE THREAD

**Issue by BelliumTang** [RUCAIBox/RecBole#1705]
**您希望添加的功能是否与某个问题相关？**
20 Mar 22:56    INFO  test result: OrderedDict([('recall@10', 0.0492), ('recall@20', 0.0686), ('recall@40', 0.0976), ('ndcg@10', 0.0358), ('ndcg@20', 0.0415), ('ndcg@40', 0.0484)])

**描述您希望的解决方案**
目前的结果是保留4位小数 例如：'recall@10', 0.0492
但是出于结对比结果的比较，能否保留6位小数？

感谢RecBole开发组！

**Comment by LiuZS10** [comment]
peoperties里面的overall.yaml文件，line52(如果你没改过的话)，metric_decimal_place：4改成6就行了

**Comment by BelliumTang** [comment]
太感谢啦！
