### ISSUE TITLE
[question] Does timestamp applied in inference time?

### ISSUE THREAD

**Issue by fenneccat** [RUCAIBox/RecBole#1706]
I wanted to give the current timestamp to predict items differently when the prediction time is changed.

I checked the code and it seems the timestamp is treated as one of the features of items.
As I understood, it seems it only uses time info in input items and prediction is not affected by inferencing time.
Did I understand correctly?

Thank you for your reply in advance

**Comment by zhengbw0324** [comment]
@fenneccat Hello!
In the process of constructing sequential recommendation data, interaction sequences are sorted in chronological order. During training, validation, and testing, only the interaction sequence before the target item, that is, the sequence before the interaction time, will be used.
