### ISSUE TITLE
I want to read my dataset with full path in configuration file

### ISSUE THREAD

**Issue by bodymostafa123** [RUCAIBox/RecBole#1707]
recbole require that I must put my data in a folder and name the data as the name of the folder

but I want to read the data with my full path

How can I do it ?

thanks in advance

**Comment by peteryang1031** [comment]
Hi @bodymostafa123, thank you for attention. You can change the `data_path` parameter in `overall.yaml` as well as the `self.final_config_dict["data_path"]` in `configurator.py` line 334, and modiy it with your dataset file path.
Hope the above answer can help you.
