### ISSUE TITLE
如何在recbole里面使用pin_memory与pin_memory的值，以提高模型训练速度？

### ISSUE THREAD

**Issue by lalunex** [RUCAIBox/RecBole#1708]
您好，首先感谢您们提供了一个如此方便的推荐模型库，它给我带来了很多的便利，谢谢。

但是我有一个问题：如何加快模型的训练速度，我在网络上找到了三个解决方案：

①将pin_memory设置true
②将num_workers设置为8或16
③将模型改为半浮点运算

我在官方文档的Environment Settings里面找到了work参数，那么是否可以通过这个参数来实现第一个解决方案呢？而对于另外两个解决方案，如何使用recbole来实现呢？

**Comment by Sherry-XLL** [comment]
@lalunex 您好，感谢您对伯乐的关注！

对于模型的训练加速，现在伯乐支持的多 GPU 训练和混合精度训练都可以在一定程度上实现加速的目的。多 GPU 训练与多设备和多卡有关，有多卡环境的话可以试着参考我们文档中的[使用说明](https://recbole.io/docs/get_started/distributed_training.html)进行并行训练。而混合精度训练（mixed precision training）就是您提到的第三点，将模型改为半浮点运算，这个可以通过伯乐的[参数](https://recbole.io/docs/user_guide/config/training_settings.html) `enable_amp` 和 `enable_scaler` 来调控，设置为 `True` 即可通过半浮点运算加速。

关于您提到的第一点和第二点都是 `torch.utils.data.DataLoader` 内置的用于调节训练速度的参数，而伯乐的 `DataLoader` 继承自 PyTorch 的官方接口，自然也具备 torch 官方库中的训练加速设置。`worker` 就是用于对 `num_workers` 的调节，在 config 中修改 `worker` 参数可以一定程度上提升速度。

> worker (int) : The number of workers processing the data. Defaults to 0.

https://github.com/RUCAIBox/RecBole/blob/27cb949231562582f4e5df8689c74e0e54e31473/recbole/data/dataloader/abstract_dataloader.py#L65-L73

而对于 `pin_memory`，伯乐暂时没有提供直接的对口参数，若您需要的话可以在 `num_workers=config["worker"],` 的后面添加一行 `pin_memory=True` 的设置即可，我们在后续开发时也会考虑将 `pin_memory` 作为伯乐的接口参数。

再次感谢您对伯乐的关注和建议，若仍有问题欢迎继续提问。

**Comment by lalunex** [comment]
非常感谢您的回复，望心想事成
