### ISSUE TITLE
[💡SUG] 对于单节点多GPU来说，GPU的利用率不理想

### ISSUE THREAD

**Issue by lalunex** [RUCAIBox/RecBole#1722]
您好，我有一个问题
我在test.yaml文件里面配置了下面的参数以启动单机多卡训练，但是显卡利用效果不理想
```
gpu_id: '0,1,2,3,4,5,6,7'
nproc: 8
```
下面是前几台机器的占用情况，请问有什么办法可以使每个GPU利用率都达到100%呢？
![image](https://user-images.githubusercontent.com/63094854/230708847-cf83661d-ca5b-4125-b02f-86a0979c583a.png)

**Comment by Sherry-XLL** [comment]
您好，@lalunex，感谢您对伯乐的关注！

目前伯乐实现的多 GPU 训练是依托于 PyTorch 的接口来进行并行处理，对于具体的显卡占用细节，伯乐的框架内暂时没有进行调节的处理的模块。对于显卡利用效果不理想的情况，我们团队会考虑在后续的版本中优化这一点，如果您有比较好的处理方式也欢迎您随时和我们联系。

再次感谢您的反馈和建议！

**Comment by lalunex** [comment]
感谢您的回复，我再想想其他办法
