### ISSUE TITLE
如何在训练是给模型输入一些自定义的其他变量

### ISSUE THREAD

**Issue by FollowingWind117** [RUCAIBox/RecBole#1727]
你好，最近在使用贵课题组的CORE为baseline跑一些改进的思路，CORE是基于recbole的，然后我看recbole对于序列推荐的输入只能是session_id、item_id、item_list和timestamp这几种，那我想加一些自定义的其他输入的话（比如类似于TISASRec中的时间差变量）应该如何加呢，我尝试更改了yaml文件里的输入column，但是好像没反应，后面在dataset引用我的自定义变量会报错。

但是我直接作为timestamp输入确实能够在模型的forward见到，但是好像经过预处理后变得不太对头（我应该获得一个[batchsize，ListNum]的二维列表，但他就分出来一个batch长度的一维列表)，可能是它的处理方式只针对于时间戳？

所以想问一下recbole有相关支持输入自定义变量的功能或用法嘛？

**Comment by zhengbw0324** [comment]
@FollowingWind117 您好！
如果您自定义的变量是类似时间戳的非序列类型变量，可以直接通过配置文件中的`load_col`实现。如果您的需求是将自定义的变量类似item_id一样根据时间顺序组织成一个list，则需要修改datasets源码或提前预处理数据并以`token_seq`或`float_seq`类型读入。

**Comment by FollowingWind117** [comment]
> @FollowingWind117 您好！ 如果您自定义的变量是类似时间戳的非序列类型变量，可以直接通过配置文件中的`load_col`实现。如果您的需求是将自定义的变量类似item_id一样根据时间顺序组织成一个list，则需要修改datasets源码或提前预处理数据并以`token_seq`或`float_seq`类型读入。
感谢您的回复！对于您提到的后者“以token_seq类型读入”有没有什么可参考的代码写法吗，我已经通过预处理处理好了一个time_interval（时间差），类似于TiSASRec，一个seq中每个item对应一个时间差，然后一条数据就会有一个时间差的列表。

**Comment by FollowingWind117** [comment]
> @FollowingWind117 您好！ 如果您自定义的变量是类似时间戳的非序列类型变量，可以直接通过配置文件中的`load_col`实现。如果您的需求是将自定义的变量类似item_id一样根据时间顺序组织成一个list，则需要修改datasets源码或提前预处理数据并以`token_seq`或`float_seq`类型读入。

感谢您的回复！对于您提到的后者方案“以token_seq类型读入”有没有什么可参考的代码写法吗，我已经通过预处理处理好了一个time_interval（时间差），类似于TiSASRec，一个seq中每个item对应一个时间差，然后一条数据就会有一个时间差的列表。

**Comment by zhengbw0324** [comment]
@zhengbw0324 
您可以参考我们的[文档](https://recbole.io/docs/user_guide/data/atomic_files.html)。

**Comment by FollowingWind117** [comment]
> @zhengbw0324 您可以参考我们的[文档](https://recbole.io/docs/user_guide/data/atomic_files.html)。

非常感谢，尝试了相关操作，确实成功了

**Comment by FollowingWind117** [comment]
> @zhengbw0324 您可以参考我们的[文档](https://recbole.io/docs/user_guide/data/atomic_files.html)。

顺带一提，如果推断不错您应该是某软比我高一届的学长吧，再次感谢bw学长（手动狗头）

**Comment by zyx1017** [comment]
@FollowingWind117 你好，我目前遇到一样的问题。能问一下你是怎么解决的吗
