### ISSUE TITLE
ItemKNN, DMF, MultiVAE error: HTTPSConnectionPool

### ISSUE THREAD

**Issue by giuspillo** [RUCAIBox/RecBole#1729]
Dear authors,

thanks again for this huge project.

I'm using RecBole to make some benchmarks, so I'm using several provided models.
I'm experiencing this error with some of them (such as ItemKNN, DMF and MultiVAE):

```
- ERROR: 4_ItemKNN_dbbook. HTTPSConnectionPool(host='get.geojs.io', port=443): Max retries exceeded with url: /v1/ip/geo.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45ec283b50>: Failed to establish a new connection: [Errno 110] Connection timed out'))
- ERROR: 6_DMF_dbbook. HTTPSConnectionPool(host='get.geojs.io', port=443): Max retries exceeded with url: /v1/ip/geo.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45ec9e3160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
- ERROR: 7_MultiVAE_dbbook. HTTPSConnectionPool(host='get.geojs.io', port=443): Max retries exceeded with url: /v1/ip/geo.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45eca0ae80>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

Any idea about the reason?

**Comment by Sherry-XLL** [comment]
@giuspillo Hello, thanks for your attention to RecBole!

Your issue may seem like a network connection issue, but our model does not involve networking operations. `/v1/ip/geo.json` is also not a required file for our library. 

Please provide more error information and the results of other models, so that we can solve your problem.

**Comment by giuspillo** [comment]
I guess I solved it, it seems it was related to another library I was using :)
