### ISSUE TITLE
请教一下recbole中的负例采样

### ISSUE THREAD

**Issue by ithok** [RUCAIBox/RecBole#1730]
RT，请问遵循recbole的采样策略，在valid-phase阶段采样的负例(比如用于计算NDCG和Hitrate)和train-phase中的负例会有重叠吗？

**Comment by chenyuwuxin** [comment]
@ithok  有重叠。在RecBole中，对于每个user，在valid阶段不会采样其在train阶段交互过的正例，但其交互过的负例仍有可能被重新采样。

**Comment by ithok** [comment]
好的，感谢您的回复

Tian Zhen ***@***.***> 于2023年4月22日周六 16:16写道：
