### ISSUE TITLE
Criteo-4m，avazu-2m 数据集疑问

### ISSUE THREAD

**Issue by sunorset** [RUCAIBox/RecBole#1731]
在 Hyper-parameter Search Results 中提到了数据集 Avazu-2m 和 Criteo-4m，我想请教下：怎么得到这两个数据集，是从原始数据集中随机取出的样例数据吗？

**Comment by Wicknight** [comment]
@sunorset 您好！这里是我们处理后的数据集下载链接：[Avazu-2m](https://drive.google.com/file/d/1ZZVKgaNuWTEgLasV0DDOfU0DX0gr-FUT/view?usp=sharing) 和 [Criteo-4m](https://drive.google.com/file/d/1EuWXN0vspbq1bLMIIto8k7wx6YOYRIkX/view?usp=sharing).

**Comment by Wicknight** [comment]
由于该issue 长时间未回复，我们将关闭该issue，如果您后续遇到相关问题，欢迎您继续和我们讨论！
