### ISSUE TITLE
长尾实验

### ISSUE THREAD

**Issue by gylgyl123** [RUCAIBox/RecBole#1750]
请问recbole中有实现长尾实验的功能吗

**Comment by Sherry-XLL** [comment]
@gylgyl123  您好，感谢您对伯乐的关注！目前伯乐及 [2.0 子包](https://github.com/RUCAIBox/RecBole2.0)中尚未对长尾实验进行特定的设计，如果您需要的话可以在现有的代码上进行修改。我们团队会考虑在以后的开发中增加长尾实验的情况，感谢您的建议！
