### ISSUE TITLE
[🐛BUG] ValueError: train_neg_sample_args [None] should be None when the loss_type is CE.

### ISSUE THREAD

**Issue by VladHardAndSoftWare** [RUCAIBox/RecBole#1761]
**Describe the bug**
I get `ValueError: train_neg_sample_args [None] should be None when the loss_type is CE.`
I got this error when try to hypertune my saved BERT4Rec model.

**To Reproduce**
My code:
```
from recbole.quick_start import objective_function
from recbole.trainer import HyperTuning
from recbole.quick_start import load_data_and_model
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    # model_file='saved/BERT4Rec-Mar-16-2023_21-13-51.pth',
    model_file='saved/FullParquet0.pth',
)

parameter_dict = {
    'loss_type': "CE",
    'train_neg_sample_args': None,
    'model': 'BERT4Rec'
}


hp = HyperTuning(objective_function=objective_function, algo='exhaustive', early_stop=10, max_evals=100,
                 params_file='hyper.test', fixed_config_file_list=['config.yaml'], params_dict=parameter_dict)

# run
hp.run()

# export result to the file
hp.export_result(output_file='hyper_example.result')

# print best parameters
print('best params: ', hp.best_params)

# print best result
print('best result: ')
print(hp.params2result[hp.params2str(hp.best_params)])
```

**Expected behavior**
Get standard HyperTuning return
https://recbole.io/docs/user_guide/usage/parameter_tuning.html

**Screenshots**
![image](https://user-images.githubusercontent.com/42782084/236190906-2168bd6f-1462-420a-92c4-d93a6ebd7656.png)
![image](https://user-images.githubusercontent.com/42782084/236190835-b7dce5a6-9009-4126-a8f4-b2d41d155de6.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10Pro 22H2, Running in VS Code]
- RecBole Version [1.1.1]
 - Python Version [3.9.16]
- PyTorch_lightning Version [1.8.4.post0]
- torch.version.cuda Version [11.7]

**Comment by Wicknight** [comment]
Hello, @VladHardAndSoftWare 

In yaml files, we should use "null" or "~" to indicate that the parameter is null, and "None" to indicate that the value is the string "None".

So you can assign this parameter with following lines:

`train_neg_sample_args: ~`
or 
`train_neg_sample_args: null`
or
`train_neg_sample_args: `

**Comment by zyx1017** [comment]
@VladHardAndSoftWare Hello，How did your Bert4Rec run out? I'm running much lower performance than SASRec.
