### ISSUE TITLE
[🐛BUG] RecBole-DA维护

### ISSUE THREAD

**Issue by XiaoJing-C** [RUCAIBox/RecBole#1773]
请问RecBole-DA是不维护了吗，里面并没有文档里说的CauseRec等模型，问题也无人回复

**Comment by fancybian** [comment]
您好，在model/sequential_recommender的目录下有CCL、CL4SRec、CauseRec、CoSeRec等模型，请您再看一下，后续会在RecBole-DA及时回复issuse的问题，也欢迎您在RecBole-DA的issue下提出建议。
