### ISSUE TITLE
[🐛BUG] ValueError: `model_name` [FiGNN] is not the name of an existing model.

### ISSUE THREAD

**Issue by Diuyilu** [RUCAIBox/RecBole#1784]
**描述这个 bug**
我想使用FiGNN这个模型，在运行下面代码后
```python
from recbole.quick_start import run_recbole
run_recbole(model='FiGNN', dataset='ml-100k')
```
报错：‘ValueError: `model_name` [FiGNN] is not the name of an existing model.’

**实验环境**
 - 操作系统: Windows
- RecBole 版本 1.1.1
 - Python 版本 3.9.16

**Comment by Sherry-XLL** [comment]
您好 @Diuyilu!

非常感谢您对 RecBole 的关注。FiGNN 确实是 RecBole 最新版本中已经实现的模型：

https://github.com/RUCAIBox/RecBole/blob/a757b7c31bfa407c82847b4a06c8580fa1a6b45e/recbole/model/context_aware_recommender/__init__.py#L16

你可以在你的仓库 `recbole/model/context_aware_recommender` 文件夹下找到 `fignn.py` 这个文件。根据你调用的方式，可能你导入的 `recbole` 是作为库函数被安装在了 conda 环境中，但并没有更新到最新的版本，可以根据具体报错内容的路径来判断。

您也可以通过 git clone 的方式获取 RecBole 的最新源码，然后在终端通过命令行的方式查看调用是否有问题：`python run_recbole.py --model=FiGNN`。若命令行方式未出现问题，则很有可能是您目前方式的包或路径不匹配。

欢迎您提供更多的信息，以便我们更好地解决您的问题。

**Comment by Diuyilu** [comment]
已经通过git安装最新源码的方式解决了这个问题，感谢回复。
