### ISSUE TITLE
Document description error

### ISSUE THREAD

**Issue by Iwillcome** [RUCAIBox/RecBole#1786]
Dear author:
  In the morning, when I looked up the recbole document, I found some problems. The MultiVAE and MultiDAE models point to the same paper, but there are some gaps between the two models in the recbole code.(Variational Autoencoders for Collaborative Filtering) May I ask whether there are any errors in the document preparation when they indicate the papers respectively?
  Best wish!
![image](https://github.com/RUCAIBox/RecBole/assets/51507131/7410b3ba-8bf2-41d9-9882-9519016a2d1d)

**Comment by Sherry-XLL** [comment]
Hello @Iwillcome! Both MultiVAE and MultiDAE are proposed in the paper [Variational Autoencoders for Collaborative Filtering](https://dl.acm.org/doi/pdf/10.1145/3178876.3186150), so these two models point to the same paper with different implementation.
