### ISSUE TITLE
如何按照自己的方式划分数据集？

### ISSUE THREAD

**Issue by zyx1017** [RUCAIBox/RecBole#1787]
你好，关注到伯乐的框架对序列推荐模型默认开启了一个序列增强，如果要关闭这个增强则需要自己划分训练集、测试集和验证机。请问该如何去划分这个数据集？有提供参考的代码吗？

**Comment by zyx1017** [comment]
@Sherry-XLL @Wicknight

**Comment by ChenglongMa** [comment]
可以参考 https://recbole.io/docs/user_guide/config/data_settings.html#benchmark-file 手动生成不同的数据集
以及 https://github.com/RUCAIBox/RecBole/issues/1624
如果是Sequential的会有点麻烦

**Comment by zyx1017** [comment]
@ChenglongMa 谢谢回复！就是Sequential...
对一个数据集手动生成训练集、验证集和测试集，这部分是否有参考的示例？

**Comment by Wicknight** [comment]
@zyx1017 

您好！您可以参考我们组的其他工作对于数据集的处理过程，如[UniSRec](https://github.com/RUCAIBox/UniSRec/tree/master/dataset/preprocessing). 其中的`process_amazon.py` 展示了对于Amazon数据集的完整处理流程。虽然其中也进行了数据增广过程，但是您可以根据您的需求来自由更改，如删除其中的增广过程（line 344 - line 347）。

**Comment by zyx1017** [comment]
@Wicknight 好的，谢谢！
