### ISSUE TITLE
[Question] KeyError: 'neg_item_id' on calculating loss for new interaction

### ISSUE THREAD

**Issue by Atovange** [RUCAIBox/RecBole#1796]
Hi, I'm trying to calculate the loss function of an interaction outside of the dataset (it is for a project on data poisoning).
I am using the BPR model with the ml-100k dataset and all default configurations.
I create the interaction and use the calculate_loss() method of the trained model
```
from recbole.data.interaction import Interaction

i_data = {
    'user_id': [944],
    'item_id': [1],
    'rating': [5],
    'timestamp': [879959584]
}

i = Interaction(i_data)

model.calculate_loss(i)
```

I get this error:
```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[26], line 1
----> 1 model.calculate_loss(i)

File [c:\Users\Giorgio\TesiLOKI\recbole\lib\site-packages\recbole\model\general_recommender\bpr.py:75](file:///C:/Users/Giorgio/TesiLOKI/recbole/lib/site-packages/recbole/model/general_recommender/bpr.py:75), in BPR.calculate_loss(self, interaction)
     73 user = interaction[self.USER_ID]
     74 pos_item = interaction[self.ITEM_ID]
---> 75 neg_item = interaction[self.NEG_ITEM_ID]
     77 user_e, pos_e = self.forward(user, pos_item)
     78 neg_e = self.get_item_embedding(neg_item)

File [c:\Users\Giorgio\TesiLOKI\recbole\lib\site-packages\recbole\data\interaction.py:135](file:///C:/Users/Giorgio/TesiLOKI/recbole/lib/site-packages/recbole/data/interaction.py:135), in Interaction.__getitem__(self, index)
    133 def __getitem__(self, index):
    134     if isinstance(index, str):
--> 135         return self.interaction[index]
    136     else:
    137         ret = {}

KeyError: 'neg_item_id'
```
I tried adding more interactions and changing the user id but I still get the same error.

**Comment by Sherry-XLL** [comment]
Hello @Atovange, thanks for your attention to RecBole!

As for the model implementation of BPR, we use the pair-wise loss named `BPRLoss` to maximize the difference between positive and negative items for users. 

In the default setting, our data loader will provide positive and negative sample data for each user through negative sampling. If you want to directly calculate the loss of a single user, please include negative examples in the dictionary, such as 'neg_item_id' : [12345].

Feel free to contact us if you have further questions.

**Comment by Atovange** [comment]
Thanks I understand now

**Comment by pp-bb** [comment]
I think it's possible to debug in the kg_dataset.py to check if the number of item_token matches the actual one, because I found that item_id doesn't count in the item_id_list, which can cause KeyError.
