### ISSUE TITLE
[🐛BUG] Item ID remapping problem for sequential models when benchmark_filename is not None

### ISSUE THREAD

**Issue by ouyangxin24** [RUCAIBox/RecBole#1813]
**Describe the bug**

Suppose that I have my own dataset in the following format:

| user_id::token | item_id_list:token_seq | item_id:token |
| -------------- | ---------------------- | -------------- |
| a1  | i1,i2     | i4 |
| a2 | i2,i3,i4 | i5 |
| a3 | i4,i5     | i6 |

It seems that the remapping code below would change the above format into the following one
https://github.com/RUCAIBox/RecBole/blob/a757b7c31bfa407c82847b4a06c8580fa1a6b45e/recbole/data/dataset/dataset.py#L1165-L1173

| user_id::token | item_id_list:token_seq | item_id:token |
| -------------- | ---------------------- | -------------- |
| 1  | 1,2     | 1 |
| 2 | 2,3,4 | 2 |
| 3 | 4,5     | 3 |

The IDs in item_id_list column are not consistent with that in item_id column, for example i4 in table 1 in both columns should refer to same item but in table 2, they are mapped to different IDs, i.e., 4 for item_id_list (line 1171-1173) and 1 for item_id (line 1167-1169).

Please let me know if my understanding is correct or not. Thank you.

**Comment by ouyangxin24** [comment]
following up on this issue

**Comment by hyp1231** [comment]
Hi! Please add `"alias_of_item_id": ["item_id_list"]` to the configurations. This will make `item_id_list` and `item_id` align together during the remapping process.

An example can be found [here](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py#L63C9-L63C46).
