### ISSUE TITLE
[🐛BUG] 将movielens 转成原子档案时报错

### ISSUE THREAD

**Issue by paul0728** [RUCAIBox/RecBole#1822]
![Screenshot from 2023-08-01 01-53-49](https://github.com/RUCAIBox/RecBole/assets/44644609/5a4e08e5-1903-4804-8135-4ec9a514b3f8)

**实验环境：**
 - 操作系统 : Ubuntu 22.04.2 LTS
 - RecBole 版本 : 1.1.1
 - Python 版本 : 3.7.16
- PyTorch 版本 : 1.13.1
- cudatoolkit 版本 : 11.7

**Comment by Sherry-XLL** [comment]
您好 @paul0728，感谢您对 RecBole 的关注！

这个错误是因为您的文件中包含了 utf-8 格式不支持的字符，导致解码失败并抛出 `UnicodeDecodeError`。

您可以尝试在读入文件处通过 `encoding` 参数指定文件编码格式。

**Comment by paul0728** [comment]
謝謝！
