### ISSUE TITLE
[🐛BUG] reverse kg data 錯誤

### ISSUE THREAD

**Issue by paul0728** [RUCAIBox/RecBole#1825]
在kg_dataset.py檔案當中的第393行為self.head_entity_field: original_hids,應改為self.tail_entity_field: original_hids才對。
![Screenshot from 2023-08-10 16-09-29](https://github.com/RUCAIBox/RecBole/assets/44644609/354d6b87-447a-432f-adc5-420e60f4a210)

這樣會造成self.kg_feat 當中無tail_id column在reverse_kg_feat部份皆為NaN

**Comment by Sherry-XLL** [comment]
Hello @paul0728, thanks for your attention to RecBole! 

We have fixed this bug in pull request #1829, thanks again for your feedback and suggestions!

**Comment by paul0728** [comment]
You're welcome!
