### ISSUE TITLE
[💡SUG] How to use recbole if i need to introduce a new dataset and the custom train/val/test split? 

### ISSUE THREAD

**Issue by Escape142** [RUCAIBox/RecBole#1832]
I'm working on comparison of different recsys models from various libraries on several datasets. To do so, I have to use a single train/val/test split. However, Recbole has built in splitter and dataloader. How can I use Recbole without built in blocks?

**Comment by Sherry-XLL** [comment]
Hello @Escape142, thanks for your attention to RecBole!

In general, RecBole will load the entire dataset and perform splitting operations. From the user's point of view, a considerable number of users already have a pre-split dataset, and RecBole also provides the interface `benchmark_filename` a to load the pre-split user-item interactions.

[Data settings — RecBole 1.1.1 documentation](https://recbole.io/docs/user_guide/config/data_settings.html)

For example, let's assume that the dataset is called click, and `benchmark_filename` equals to `['part1', 'part2', 'part3']`.

We will load `click.part1.inter`, `click.part2.inter` and `click.part3.inter`, and treat them as `train`, `valid`, `test` datasets respectively. In this way, we will only apply `normalize`, `remap-id`, which will not delete the interaction in `inter_feat`. And then split the `inter_feat` by `benchmark_filename`.

These are related issues of `benchmark_filename`: [#1056](https://github.com/RUCAIBox/RecBole/issues/1056), [#1092](https://github.com/RUCAIBox/RecBole/issues/1092), [#1110](https://github.com/RUCAIBox/RecBole/issues/1110), [#1114](https://github.com/RUCAIBox/RecBole/issues/1114), [#1120](https://github.com/RUCAIBox/RecBole/discussions/1120), [#1152](https://github.com/RUCAIBox/RecBole/issues/1152), [#1273](https://github.com/RUCAIBox/RecBole/issues/1273), [#1304](https://github.com/RUCAIBox/RecBole/issues/1304), [#1408](https://github.com/RUCAIBox/RecBole/issues/1408), [#1436](https://github.com/RUCAIBox/RecBole/issues/1436), [#1498](https://github.com/RUCAIBox/RecBole/issues/1498), [#1535](https://github.com/RUCAIBox/RecBole/issues/1535), [#1592](https://github.com/RUCAIBox/RecBole/issues/1592), [#1619](https://github.com/RUCAIBox/RecBole/discussions/1619)

**Comment by Escape142** [comment]
Thank you for the clarification!

I intend to utilize my custom metrics that involve rankings and the top-k recommended items. Could you advise on the most effective approach to obtain rankings and the top-k items for each user within the test set?

The usage of the 'full_sort_topk' function results in the following error:
"TypeError: full_like(): argument 'input' (position 1) must be Tensor, not NoneType."

However, running 'run_recbole' with my personalized dataset proceeds without any issues.

**Comment by zhengbw0324** [comment]
Hello @Escape142! 
For the use of case_study and custom metrics, you can refer to the following related issue: [#1659](https://github.com/RUCAIBox/RecBole/issues/1659). 
As for the above error report, it may be because the user you tested did not appear in the training or test set, you can also refer to issues: [#1181](https://github.com/RUCAIBox/RecBole/issues/1181), [#1178](https://github.com/RUCAIBox/RecBole/issues/1178), [#1114](https://github.com/RUCAIBox/RecBole/issues/1114), [#1005](https://github.com/RUCAIBox/RecBole/issues/1005).

**Comment by Escape142** [comment]
Thank you.

I believe the primary problem is that certain users are present only in my training and validation data, while the 'test_items' of these users have no data available.

If I intend to fine-tune hyperparameters using the 'valid_set' with the help of optuna, what would be the process for later including the 'valid_set' into the 'train_set' once the tuning is complete? Additionally, could you guide me on how to merge these separate dataloaders?
