### ISSUE TITLE
為什麼wandb的run summary 與跑出來的結果不一致?

### ISSUE THREAD

**Issue by paul0728** [RUCAIBox/RecBole#1837]
![Screenshot from 2023-08-18 01-30-09](https://github.com/RUCAIBox/RecBole/assets/44644609/f14527fa-76e3-4805-afb7-faebd536c0c5)
如圖所示
best valid: auc=0.7731
wandb: valid/auc=0.7678

**Comment by Sherry-XLL** [comment]
您好 @paul0728，感謝您對 RecBole 的關注！

RecBole 使用了提前停止策略避免過度擬合數據，並存下當前在驗證集上的最好結果以便在測試集上評測。wandb 的 `run_summary` 中，`eval/auc` 顯示的是最好的 `checkpoint` 模型在測試集上的結果，與 RecBole 最後提供的 `test result` 壹致。

但對于 `train/train_loss` 和 `valid/auc`，wandb 中顯示的是第 `valid_step: 172` 時的結果，即模型訓練時的最後壹輪輸出，而 RecBole 提供的是 `best valid`，即最優的驗證集指標，因此結果並不完全壹致。

**Comment by paul0728** [comment]
感謝說明！
