### ISSUE TITLE
[🐛BUG] 用FDSA模型跑Amazon_Electronics数据集时有异常

### ISSUE THREAD

**Issue by WeishanOoi** [RUCAIBox/RecBole#1849]
**描述这个 bug**
各位大佬们好，我昨天尝试用FDSA模型跑Amazon_Electronics数据集时有异常，如图：
![mspaint_B7AZsEw4sQ](https://github.com/RUCAIBox/RecBole/assets/130117362/1012d1d6-68e7-43b4-934c-ddf82269b8fe)

当我尝试用其他模型跑运行的时候也是有类似的问题，然而当我用ml-1m的数据集的时候没这个问题。他的error上面写的[timestamp] is not exist in interaction可我尝试与其他数据集对比研究后我还是百思不得其解，求各位大佬们提点。

**如何复现**
复现这个 bug 的步骤：
1. 引入的额外 yaml 文件
![Code_TDXPdoqmjH](https://github.com/RUCAIBox/RecBole/assets/130117362/ce7b0887-41d9-4de4-98c9-6b925e580c06)

2. 代码
![Code_CO4Cb9mzhO](https://github.com/RUCAIBox/RecBole/assets/130117362/2f07999a-74fa-4b2d-b409-353dae2cf502)

3. 运行脚本
python run.py

**预期**

![Code_SZA6eOhliN](https://github.com/RUCAIBox/RecBole/assets/130117362/e9ea5af7-c251-4c44-9ce0-27089f329aea)
可以成功运行且return回类似这样的result

**实验环境（请补全下列信息）：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [1.1.1]
 - Python 版本 [3.11.1]
- PyTorch 版本 [2.0.1]
- cudatoolkit 版本 [none]

**Comment by chenyuwuxin** [comment]
@WeishanOoi 你好，非常感谢您的关注！
您可以尝试使用以下配置文件进行测试：
```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, rating, timestamp]

# data filtering for interactions
val_interval:
    rating: "[3,inf)"    
unused_col: 
    inter: [rating]

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_batch_size: 40960000
valid_metric: NDCG@10
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO

# disable negative sampling
train_neg_sample_args: ~

# model
embedding_size: 64


```

**Comment by WeishanOoi** [comment]
![mspaint_q0d82gq7xY](https://github.com/RUCAIBox/RecBole/assets/130117362/d60dd8b8-cc5e-4cf2-959e-23ebeea29f8e)
您好，感谢您的回复。我刚刚重新跑了一遍可是还是不能。error message依旧显示ValueError: [timestamp] is not exist in interaction ，请问我是不是漏了些什么？

**Comment by chenyuwuxin** [comment]
@WeishanOoi 您好，我使用`python run_recbole.py --config_files=amazon.yaml --model=FDSA --dataset=amazon-electronics`命令运行并没有出现错误。可能是您使用脚本文件运行没有正确读取命令行参数导致配置文件没有起到作用。

**Comment by WeishanOoi** [comment]
噢噢，能运行了，谢谢你!
