### ISSUE TITLE
[🐛BUG] Error: "Tensors must have same number of dimensions: got 1 and 2", when I am using model.predict().

### ISSUE THREAD

**Issue by VladHardAndSoftWare** [RUCAIBox/RecBole#1852]
**Describe the bug**
I try get sequential recommend layer and use `model.predict()` with BERT4Rec model. To do this I load my model from file and use my model and dataset to evaluate `model.predict()`. But I got error "Tensors must have same number of dimensions: got 1 and 2". And it's strange because I take them from `load_data_and_model`

**To Reproduce**
My code:
```
from recbole.quick_start import load_data_and_model
config, model, dataset, train_data, valid_data, test_data = load_data_and_model
(
    model_file='saved/FullParquet0.pth',
)

for interaction in dataset:
    score = model.predict(interaction)
```

**Expected behavior**
I want to evaluate `model.predict()` in BERT4Rec model.

**Screenshots**
![image](https://github.com/RUCAIBox/RecBole/assets/42782084/8fdbf7c8-fcbb-4045-83eb-a22136ab77a7)

**Desktop (please complete the following information):**
 - OS: [Windows 10Pro 22H2, Running in VS Code]
- RecBole Version [1.1.1]
 - Python Version [3.9.16]
- PyTorch_lightning Version [1.8.4.post0]
- torch.version.cuda Version [11.7]

**Comment by chenyuwuxin** [comment]
@VladHardAndSoftWare  You should use the dataloader type for iteration.
Such as:
```
for interaction in train_data:
    score = model.predict(interaction)
```
