### ISSUE TITLE
请问如何查询某个batch的某个特殊位置user id？

### ISSUE THREAD

**Issue by freedomSummer1964** [RUCAIBox/RecBole#1853]
例如，该batch size为1024，我想要查询该batch中第1个user id是什么。
期待您的帮助，感谢！

**Comment by chenyuwuxin** [comment]
@freedomSummer1964 非常感谢您的关注！
可以尝试用`interaction.user_id[0]` 变量进行查询。

**Comment by freedomSummer1964** [comment]
> @freedomSummer1964 非常感谢您的关注！ 可以尝试用`interaction.user_id[0]` 变量进行查询。

感谢您的回答！
