### ISSUE TITLE
[🐛BUG] Tensors Found on Different Devices, cuda:x and cpu!

### ISSUE THREAD

**Issue by ChenglongMa** [RUCAIBox/RecBole#1869]
**Describe the bug**

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:x and cpu!` can be raised at L259 of `trainer.py`
https://github.com/RUCAIBox/RecBole/blob/2c6f066eb1e87814bb5101eb727b1308661e030c/recbole/trainer/trainer.py#L259

This is because the `loss` returned by the `calculate_loss` function of some models is placed on the CPU. Then **when running RecBole in DDP mode on a multi-GPU server**, the devices of `loss` and `sync_loss` would be different.

For example, the `calculate_loss` function of `Pop` model will return a `CPU` tensor:
https://github.com/RUCAIBox/RecBole/blob/2c6f066eb1e87814bb5101eb727b1308661e030c/recbole/model/general_recommender/pop.py#L40-L46

**To Reproduce**
```bash
python run_recbole.py --model Pop --nproc n (n>1)
```

**2 Ways To Fix This**

1. Check all models to ensure the `calculate_loss` function returns correctly placed tensors.
    For example, in `pop.py`:
    
    ```python
    def calculate_loss(self, interaction):
        item = interaction[self.ITEM_ID]
        self.item_cnt[item, :] = self.item_cnt[item, :] + 1

        self.max_cnt = torch.max(self.item_cnt, dim=0)[0]

        return torch.nn.Parameter(torch.zeros(1)).to(self.device)  # <-- fix here
    ```
2. Update the device of `loss` in `trainer.py`
    Before L259 and L1470, we can check and fix the device of `loss` when necessary:
    
    ```python
    if isinstance(loss, torch.Tensor):
        loss = loss.to(self.device)
    ```
Hope this can help! I will be happy to create a pull request if necessary.
Thanks!

**Comment by TayTroye** [comment]
@ChenglongMa  Hello！ 
Thanks for your method, we have fixed this issue by add  ` .to(self.device) ` in model Pop . You can check it  in #1873

**Comment by ChenglongMa** [comment]
Thanks @TayTroye for your update! I will close this issue then :)
