### ISSUE TITLE
[🐛BUG] RippleNet与KGIN模型复现错误，在初始化步骤中错误使用了整个数据集的数据

### ISSUE THREAD

**Issue by HotBento** [RUCAIBox/RecBole#1893]
**描述这个 bug**
RippleNet与KGIN模型的初始化步骤中错误地使用了整个数据集的数据（即使用了训练集、验证集与**测试集**的全部数据）。在KGIN.py的第273列与RippleNet的47列，代码直接使用了dataset中的全部interaction数据进行初始化，这很可能导致模型的准确率高于预期，并使模型表现出一些错误的特性。

**如何复现**
代码复现错误，无需复现。

**预期**
我认为出现这个错误和RecBole的整体架构有一定关系，RecBole在模型初始化时将完整的dataset作为参数传入，这很可能导致数据的越界使用。最佳方法是将初始化时传入的dataset更改为训练数据集，但这可能需要对架构进行一定更改。折中的方案是在Dataset类的build()过程中保留训练集、验证集和测试集的划分，并更改相关模型的代码（包括但很可能不限于RippleNet和KGIN）。

**实验环境（请补全下列信息）：**
- RecBole 1.1.1

**Comment by Yilu114** [comment]
您好，我们在quick_start部分(https://github.com/RUCAIBox/RecBole/blob/1a9dfeca2c6af7833c7e01de7ae73315ab6029e3/recbole/quick_start/quick_start.py)的137行代码中，在model部分仅传入了训练数据。
`    model = get_model(config["model"])(config, train_data._dataset).to(config["device"])`
因此并不存在您所提到的初始化步骤中错误地使用了整个数据集的数据的情况。

**Comment by HotBento** [comment]
感谢解答，确实是我没有注意到quick_start部分的这段代码。我在自己使用时根据init的传入参数名称直接传入了dataset。十分感谢你花费时间解答我的问题！
