### ISSUE TITLE
Customizing Sampler

### ISSUE THREAD

**Issue by tripledoubleE** [RUCAIBox/RecBole#1913]
Hi Teams, thank you for your great RecBole library!

I'm now working on the negative sampling on RecSys and using RecBole. I have some questions and I appreciate it if you give me any comments, links, and suggestions.

Recbole uses uniform distribution as a negative sampling strategy. I'm curious how the models will yield results with different distributions. Therefore, I made some changes to the sampler.py file on my local. I have some questions:

1. In the sample_by_key_ids(...) function creates (key_num * num) negative items. In the documentation, it says that key_id is candidate objective id list. When we say "candidate objective id" here, do we mean items that users do not interact with?
2. If (key_num*num) negative items are selected, aren't we selecting num negative items for each item? (Actually I can not understand what the key_num variable means)
3. Is sampler.py run for each user? If sampler.py runs specifically for each user, when we say dist=uniform, is it working on the entire data or only on the items that that user interacts with?
4. I want to investigate the effect of different distributions in my own project. While doing this, I want to do negative sampling more specifically for the user, taking into account the item distributions of the users separately. In other words, for each user, I want to narrow down my data set to only the items that those users interact with. Is it possible to do this using sampler.py?

I'm looking forward to hearing from you if you have time. 
Thank you in advance!

**Comment by Fotiligner** [comment]
@tripledoubleE  Thanks for your attention to RecBole!
- For question 1, key_id does not refer to items that users do not interact. In different conditions
- For question 2, the key_num is the number of total ids in key_ids, we sample num negative items for each key_id in key_ids list, so the total length of the output is key_num * num.
- For question 3, sampler.py will sample negative items for each user in the batch. In [uniform](https://github.com/RUCAIBox/RecBole/blob/61848c0cc03d25645ebeffbfe9b58c48aaafaa76/recbole/sampler/sampler.py#L222-L223), you could see that we generate sampled items from the whole item pool and then remove used items(positive items) in the list as the final negative samples. 
- For question 4, you could try to change or add code in [sample_by_key_ids](https://github.com/RUCAIBox/RecBole/blob/61848c0cc03d25645ebeffbfe9b58c48aaafaa76/recbole/sampler/sampler.py#L143-L144).

Hope these would answer your questions.

**Comment by tripledoubleE** [comment]
Hello,
First of all, thank you very much for your answer. However, there is one thing I cannot understand:
In your answer to the second question, you said that the key_num is the number of total ids in key_ids.
I couldn't understand exactly what the 'key_ids' variable means. According to my logic, key_ids should be all of the user_ids in the data set. Because the documentation says that negative sampling is done for each userID.
However, when I look at the length of the key_ids list in the code, I understand that it does not include all users.
I don't fully understand whether negative items are sampled for each user at the end of all operations.

Thank you very much in advance for your answer.

**Comment by Fotiligner** [comment]
@tripledoubleE 
Actually when used in `sample_by_user_ids` function, key_ids refers to user_ids, and the data processing focus on a single batch, so negative sampling in this way is done for each user in a batch，not for all of the user_ids in the dataset. 

Hope these would answer your questions.
