### ISSUE TITLE
关于yelp数据集

### ISSUE THREAD

**Issue by njt123123** [RUCAIBox/RecBole#1917]
https://drive.google.com/drive/folders/1n_wODEhexezzI1yJyQP_PEBDrKNV0mEG
请问该链接中的yelp.zip和yelp2022.zip有什么不同

**Comment by Sherry-XLL** [comment]
@njt123123 您好，`yelp.zip` 和 `yelp2022.zip` 这两者是一样的，只是为了兼容之前版本中 `dataset=yelp` 的场景才保留了命名为 `yelp` 的数据集。感谢您对 RecBole 的关注！
