### ISSUE TITLE
使用recbole1.0.0时，训练过程显示的训练数据进度和验证数据是指什么？

### ISSUE THREAD

**Issue by kmr666** [RUCAIBox/RecBole#1918]
**Is your feature request related to a problem? Please describe.**
为什么训练集比验证集数据少，训练用时也更短？
![image](https://github.com/RUCAIBox/RecBole/assets/84135862/6f6cf70e-90ec-4b5c-bf3e-0533eb501357)
请问这图中的train后面的749/749和evaluate后面的319142分别是指代什么？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BishopLiu** [comment]
@kmr666 您好！因为训练集的`batch_size`和测试集的`batch_size`大小设置不一样，749和319142分别指的是训练集和测试集的`data_number/batch_size`，您可以通过yaml配置文件中的参数`train_batch_size`和`eval_batch_size`进行自定义设置，如果您采用full-sort evaluation, 并且不是sequential类型的推荐时，`batch_size=max(config["eval_batch_size"] // self.dataset.item_num, 1)`也就是您设置的eval_batch_size表示一个step中包含的item的总数量。您可以适当增大测试集的batch_size来缩短测试时间。
