### ISSUE TITLE
yelp2018数据集统计信息与NGCF论文不一致

### ISSUE THREAD

**Issue by HangxiaoX** [RUCAIBox/RecBole#1924]
我使用Bole里面的yelp-2018，设置

![10-core](https://github.com/RUCAIBox/RecBole/assets/57467667/bbf0c17f-06f8-4fd6-9cce-b0122aaf92a7)

数据集统计信息如下

![image](https://github.com/RUCAIBox/RecBole/assets/57467667/71bace9b-67cc-4a8b-ba93-be340035ce02)

而NGCF原文写的是10-core ，其yelp2018数据统计信息如下

![image](https://github.com/RUCAIBox/RecBole/assets/57467667/06b3c440-c0e5-45de-9979-44d714400417)

两部分不一致，请问是我哪里搞错了吗

**Comment by BishopLiu** [comment]
我们的yelp2018数据集是从kaggle上下载处理得到的，由于处理方式可能存在不同，数据集可能存在差异，如果想使用与原文一致的数据，可以下载原文提供的数据

**Comment by HangxiaoX** [comment]
好的 谢谢
