### ISSUE TITLE
[🐛BUG] When training FEARec ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by Xueqi-Li** [RUCAIBox/RecBole#1926]
![Uploading 截屏2023-11-29 09.56.16.png…]()

**Comment by Xueqi-Li** [comment]
> @Xueqi-Li Hello, I can't see the picture you uploaded.

upload the picture, and I use ml-1m dataset.
![fearec](https://github.com/RUCAIBox/RecBole/assets/64135308/0594df47-d9d7-46ed-a132-87b6ed33fb3f)

**Comment by Xueqi-Li** [comment]
> @Xueqi-Li Hello,I did not encounter this error when using ml-1m dataset. Could you provide the complete configuration so that I can reproduce your problem.

The preprocessed ml-1m dataset is downloaded from Google drive and the configure file is as follows.

# general
gpu_id: 0
seed: 2023
save_dataset: True
dataset_save_path: ~
save_dataloaders: True
dataloaders_save_path: ~
worker: 8

# dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id


# training and evaluation
learning_rate: 0.001
ft_ratio: 0.5
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
eval_step: 5
stopping_step: 50
valid_metric: Recall@10
topk: [10, 20]
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO
train_neg_sample_args: ~

field_separator: "\t"
seq_separator: " "
load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: [item_id, genre]
unused_col: 
    inter: [rating]
item_attribute: genre

user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"

# model
n_layers: 2                      # (int) The number of transformer layers in transformer encoder.
n_heads: 2                       # (int) The number of attention heads for multi-head attention layer.
hidden_size: 64                  # (int) The number of features in the hidden state
inner_size: 256                  # (int) The inner hidden size in feed-forward layer.
hidden_dropout_prob: 0.5         # (float) The probability of an element to be zeroed.
attn_dropout_prob: 0.5           # (float) The probability of an attention score to be zeroed.
hidden_act: 'gelu'               # (str) The activation function in feed-forward layer.
layer_norm_eps: 1e-12            # (float) A value added to the denominator for numerical stability.
initializer_range: 0.02          # (float) The standard deviation for normal initialization.
loss_type: 'CE'                  # (str) The type of loss function.
lmd: 0.1                         # (float) The weight of unsupervised normalized CE loss.
lmd_sem: 0.1                     # (float) The weight of supervised normalized CE loss.

global_ratio: 1                  # (float) The ratio of frequency components
dual_domain: False               # (bool) Frequency domain processing or not
std: False                       # (bool) Use the specific time index or not
spatial_ratio: 0                 # (float) The ratio of the spatial domain and frequency domain
fredom: False                    # (bool)  Regularization in the frequency domain or not
fredom_type: None                # (str)  The type of loss in different scenarios
topk_factor: 1                   # (int)  To aggregate time delayed sequences with high autocorrelation

**Comment by Xueqi-Li** [comment]
> @Xueqi-Li Hello,I did not encounter this error when using ml-1m dataset. Could you provide the complete configuration so that I can reproduce your problem.

also encountered the same error when using yelp2018, and the Recbole version is 1.2.0.

**Comment by TayTroye** [comment]
@Xueqi-Li 
Hello,I use the configuration you offered,there somthing wrong in `'SequentialDataset' object has no attribute 'item_attribute_feat'`,I moved this ,then it can be trained normally.

**Comment by Xueqi-Li** [comment]
> @Xueqi-Li Hello,I use the configuration you offered,there somthing wrong in `'SequentialDataset' object has no attribute 'item_attribute_feat'`,I moved this ,then it can be trained normally.

Thank you. I also remove this but encounter the same error.

**Comment by Xueqi-Li** [comment]
@TayTroye 
Even running the sample as follows, still encounter the same error. Can help to check it again? Thank you.

from recbole.quick_start import run_recbole
parameter_dict = {"train_neg_sample_args": None, "gpu_id": "3"}
run_recbole(model="FEARec", dataset="ml-100k", config_dict=parameter_dict)

"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
