### ISSUE TITLE
如何把数据集变成.pkl格式的数据

### ISSUE THREAD

**Issue by njt123123** [RUCAIBox/RecBole#1929]

**Comment by Yilu114** [comment]
在RecBole中，数据集的处理流程主要包括以下几个步骤：
**原始数据集**：未经处理的原始数据集。
 **原子文件**：RecBole约定的一类通用的输入数据文件。
 **Dataset类**：根据原子文件生成的数据集对象，主要依托于pandas.DataFrame。从原子文件到Dataset类的转换中，RecBole提供了一系列的数据预处理操作，如ID重映射、数据筛选、缺失值填充等。
**DataLoader类**：将Dataset类中的数据转为对模型友好的格式，主要依托于RecBole定义的Interaction类。Interaction是送入推荐系统算法的，基于python.dict类设计的中间数据结构。

一般来说，.pkl文件是使用Python的pickle模块生成的二进制文件，用于将对象序列化到磁盘上。因此，你可以使用pickle模块将RecBole的Dataset类或DataLoader类对象保存为.pkl文件。这样，你就可以在需要的时候加载这些.pkl文件，而不必每次都从原始数据开始处理。

以下展示了如何使用pickle模块将对象保存为.pkl文件：

```python
import pickle

# 假设 `dataset` 是一个 RecBole 的 Dataset 类对象
with open('dataset.pkl', 'wb') as f:
    pickle.dump(dataset, f)
```

然后，可以使用以下代码来加载.pkl文件：

```python
with open('dataset.pkl', 'rb') as f:
    dataset = pickle.load(f)
```

你可能需要根据你的具体需求和使用情况进行调整。上述只是提供一个实现思路，如果仍无法顺利转换，建议查阅[RecBole的API文档](https://recbole.io/docs/)，尤其是其中的数据流处理部分 [数据流文档](https://recbole.io/cn/dataset_list.html) 来了解如何处理数据集。
