### ISSUE TITLE
【数据集】关于MIND数据集的一点问题

### ISSUE THREAD

**Issue by clown-maker** [RUCAIBox/RecBole#1935]
您好，您所提供的处理好的MIND数据集包括：`user_id`, `item_id`，`label`，`timestamp`四列，请问这个是只用了原始数据集中的`Impressions`数据，而未使用`History`数据吗？因为我现在需要用MIND数据集来完成序列推荐任务，而您所提供的处理好的数据集似乎是用来完成类似于CTR的任务的，我需要弄清楚这一点，期待您的回复。

**Comment by Yilu114** [comment]
根据你的描述，你正在使用 RecBole 提供的处理好的 MIND 数据集，这个数据集包括了 `user_id`、`item_id`、`label` 和 `timestamp` 四列。你想知道这个数据集是否只使用了原始数据集中的 Impressions 数据，而未使用 History 数据。

MIND 数据集包含了大约 16 万篇英语新闻文章和超过 1500 万篇由 100 万用户产生的印象日志。原始的 MIND 数据集中的 Impressions 数据包含了用户在某一时间点看到的新闻列表以及他们的点击行为³，而 History 数据包含了用户过去点击过的新闻列表³。

RecBole 在处理数据集时，会根据不同的推荐任务需求来选择使用哪些数据。对于类似于点击率预测（CTR）的任务，通常只需要使用 Impressions 数据，因为这个任务的目标是预测用户是否会点击某个新闻。而对于序列推荐任务，通常需要使用 History 数据，因为这个任务的目标是预测用户下一次会点击哪个新闻。

因此，如果 RecBole 提供的处理好的 MIND 数据集只包括了 `user_id`、`item_id`、`label` 和 `timestamp` 四列，那么这个数据集可能只使用了 Impressions 数据，而未使用 History 数据。这个数据集可能是用来完成类似于 CTR 的任务的。

如果你需要用 MIND 数据集来完成序列推荐任务，你可能需要自己处理原始的 MIND 数据集，以包含 History 数据。这里您可以参考 RecBole 的 [数据流文档](https://recbole.io/cn/dataset_list.html) 和 [API 文档](https://recbole.io/docs/)  来了解如何处理数据集。

希望这个信息对你有所帮助！如果你还有其他问题，欢迎随时向我提问。
