### ISSUE TITLE
[🐛BUG] AttributeError when training BERT4Rec on yelp2022

### ISSUE THREAD

**Issue by Xueqi-Li** [RUCAIBox/RecBole#1936]
raise AttributeError(f"'Interaction' object has no attribute '{item}'")
AttributeError: 'Interaction' object has no attribute 'size'
![bert4rec](https://github.com/RUCAIBox/RecBole/assets/64135308/0dde6075-6884-4408-8e97-f6e6309489bc)

**Comment by Xueqi-Li** [comment]
no problem when training BERT4Rec on ml-1m
The configuration file is as follows.
# general
gpu_id: 0
seed: 2023
save_dataset: True
dataset_save_path: ~
save_dataloaders: True
dataloaders_save_path: ~
worker: 8

# dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id


# training and evaluation
learning_rate: 0.001
ft_ratio: 0.5
epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
eval_step: 5
stopping_step: 50
valid_metric: Recall@10
topk: [10, 20]
eval_args:
    split: {'LS': 'valid_and_test'}
    mode: full
    order: TO
train_neg_sample_args: ~

field_separator: "\t"
seq_separator: " "
load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: [item_id, categories]
unused_col: 
    inter: [rating]
item_attribute: categories

user_inter_num_interval: "[50,inf)"
item_inter_num_interval: "[10,inf)"

# model
embedding_size: 64 
n_layers: 2                     # (int) The number of transformer layers in transformer encoder.
n_heads: 2                      # (int) The number of attention heads for multi-head attention layer.
hidden_size: 64                 # (int) The number of features in the hidden state.
inner_size: 256                 # (int) The inner hidden size in feed-forward layer.
hidden_dropout_prob: 0.2        # (float) The probability of an element to be zeroed.
attn_dropout_prob: 0.2          # (float) The probability of an attention score to be zeroed.
hidden_act: 'gelu'              # (str) The activation function in feed-forward layer.
layer_norm_eps: 1e-12           # (float) A value added to the denominator for numerical stability.
initializer_range: 0.02         # (float) The standard deviation for normal initialization.
mask_ratio: 0.2                 # (float) The probability for a item replaced by MASK token.
loss_type: 'CE'                 # (str) The type of loss function.
transform: mask_itemseq         # (str) The transform operation for batch data process.
ft_ratio: 0.5                   # (float) The probability of generating fine-tuning samples
learning_rate: 0.003

**Comment by Xueqi-Li** [comment]
> @Xueqi-Li Hello! There are some problems when use the saved dataloader with BERT4Rec where several attributes are missing. It works well with new dataloader. Thus, you can delete the saved dataloader and set `save_dataloader` to `False` and rerun the command. We'll fix the bugs in the next develop plan.

It works! Thank you.

**Comment by Lyz103** [comment]
how to delete the saved dataloader？plz

**Comment by Xueqi-Li** [comment]
> how to delete the saved dataloader？plz

find the file [data_name]-for-[model_name]-dataloader.pth, and del. maybe in the path "./saved/".
