### ISSUE TITLE
.link file for Knowledge-Based Recommendation

### ISSUE THREAD

**Issue by tripledoubleE** [RUCAIBox/RecBole#1952]
Hello team,

Thank you for your great library. 

I am trying to use RecBole library for knowledge graph methods. But I can not understand exactly the usage of entity_id and item_id columns in .link file. 

I search for previous issues and found that in #1724 you have already answered a similar question. Unfortunately, because of the bad translation, I can not find an answer to my question. 

I also wrote my problem as a comment. But I want to write here also.

From your answer in #1724, when I translated you said "The 'entity_id' in the .link file corresponds to the 'id' in the .kg file. ". But there is no "id" field in .kg file. I think the reason for my confusion is because of the translation.

I think that "item_id" is basically the items that we want to recommend (movie, book, ..etc), but I could not solve the entity_id.

I have 4 relationships in my project:
->User-hotel
->User-transaction
->User-date
->Hotel-RoomType

In the case that "item_id" is HotelId (because I want to recommend hotels); I will miss some relationships, and I will solely use hotel-user and hotel-room_type. In that case, entity IDs are user IDs and room_types. If I do so, is there any problem with the algorithms implemented in the scope of the RecBole? I am new in this area, so it is very possible that I misunderstood.

Thank you for your answer in advance.

**Comment by BoXiaohe** [comment]
Thanks for your attention to RecBole! As for your problem, 
1. The format of the kg file is like (head_entity_id, relationship, tail_entity_id), so "the 'id' in the .kg file" mans the content in the first and the third columns, like 'm.01jfclc', 'm.037xlx' in the first picture of #1724 .
2. .link file, which represents the mapping from item_id in recommendation tasks to the entity_id in knowledge graphs, is expected to provide additional item information from the knowledge graph. For example, in line 2 of the second picture in #1724 , '914' is the item id for recommendation prediction, 'm.0cq7kw' is the corresponding id of '914' in knowledge graph, so during the recommendation, you can find the information of '914' in knowledge graphs.
3. As for your case, the item_id and entity_id are different id representations of the hotels and some relationships in the knowledge graphs will not be used. There is user_id field for users, which you can refer to https://recbole.io/docs/user_guide/model/sequential/gru4reckg.html?highlight=item_id
Hope this could help you!

**Comment by tripledoubleE** [comment]
I got it, thank you for your answer :)

**Comment by 1728435673** [comment]
你好，我想咨询一下关于自定义数据集的link文件的内容，是否只满足item_id与entity_id一 一对应即可，而不需要在link文件中考虑user_id与entity_id的对应关系。如果是这样生成，导致最终识别的item和entity内容和数量完全一致，会对结果造成什么影响？
