### ISSUE TITLE
请问怎么训练数据集中的一部分数据（纯小白）

### ISSUE THREAD

**Issue by StDuJdHy** [RUCAIBox/RecBole#1953]
请问怎么训练数据集中的一部分数据呀？

**Comment by Yilu114** [comment]
如果你想使用数据集中的一部分用于模型训练，你可以参考以下的步骤：

- 首先，你需要导入 Recbole 的相关模块，如 `config`、`data`、`model` 和 `trainer`。
- 然后，你需要创建一个 `config` 对象，用于配置你的实验参数。你可以使用 `config = Config(model='BPR', dataset='ml-100k')` 来指定你要使用的模型和数据集。你也可以通过 `config['xxx'] = yyy` 来修改或添加其他的参数，如 `config['train_ratio'] = 0.8` 来设置训练集占比为 80%。
- 接下来，你需要创建一个 `data` 对象，用于加载和处理数据集。你可以使用 `data = create_dataset(config)` 来根据你的配置生成一个 `Dataset` 类的实例。这个类会自动完成数据的预处理、划分和负采样等操作。
- 然后，你需要创建一个 `model` 对象，用于定义和初始化你的模型。你可以使用 `model = create_model(config, data)` 来根据你的配置和数据生成一个 `Model` 类的实例。这个类会自动根据你选择的模型和数据集的特征来构建模型的网络结构和参数。
- 最后，你需要创建一个 `trainer` 对象，用于训练和评估你的模型。你可以使用 `trainer = Trainer(config, model)` 来根据你的配置和模型生成一个 `Trainer` 类的实例。这个类会自动根据你设置的优化器、损失函数、评估指标和早停策略来进行模型的训练和评估。

你可以参考以下的示例代码，它使用了 `BPR` 模型和 `ml-100k` 数据集，并设置了训练集占比为 80%：

```python
# 导入 Recbole 的相关模块
from recbole.config import Config
from recbole.data import create_dataset
from recbole.model import create_model
from recbole.trainer import Trainer

# 创建 config 对象
config = Config(model='BPR', dataset='ml-100k')
# 设置训练集占比为 80%
config['train_ratio'] = 0.8

# 创建 data 对象
data = create_dataset(config)

# 创建 model 对象
model = create_model(config, data)

# 创建 trainer 对象
trainer = Trainer(config, model)

# 开始训练和评估
trainer.fit()
```

在 RecBole 中，假如你只想使用ml-1m数据集中10%的数据条目用来训练、验证和测试。你可以通过设置 `config['dataset']` 和 `config['ratio_split']` 来实现你的需求。`config['dataset']` 用于指定你要使用的数据集，`config['ratio_split']` 用于指定你要使用的数据条目的比例。

以下是一个使用 `ml-1m` 数据集中 10% 的数据条目用来训练、验证和测试的示例代码：

```python
# 导入 Recbole 的相关模块
from recbole.config import Config
from recbole.data import create_dataset
from recbole.model import create_model
from recbole.trainer import Trainer

# 创建 config 对象
config = Config(model='BPR', dataset='ml-1m')
# 设置训练集、验证集和测试集的比例为 8:1:1
config['ratio_split'] = [0.08, 0.01, 0.01]

# 创建 data 对象
data = create_dataset(config)

# 创建 model 对象
model = create_model(config, data)

# 创建 trainer 对象
trainer = Trainer(config, model)

# 开始训练和评估
trainer.fit()
```

在这个示例代码中，`config['ratio_split'] = [0.08, 0.01, 0.01]` 表示将数据集中的 10% 的数据条目划分为训练集、验证集和测试集，其中训练集占 80%，验证集和测试集各占 10%。

请注意，由于 RecBole 的数据处理机制，你可能无法精确地控制使用的数据条目的数量。因此，实际使用的数据条目的数量可能会略有不同。

更多关于 Recbole 的使用，请参考 [[API 文档](https://recbole.io/docs/)]((https://recbole.io/docs/))。

**Comment by StDuJdHy** [comment]
好的，谢谢
