### ISSUE TITLE
固定使用0号GPU问题

### ISSUE THREAD

**Issue by hdd1009** [RUCAIBox/RecBole#1955]
**描述这个 bug**
对 bug 作一个清晰简明的描述。
我用以下三种方法设置GPU
1 在PyCharm的Configurations中添加CUDA_VISIBLE_DEVICES=8
2 在程序中os.environ['CUDA_VISIBLE_DEVICES'] = '8'
3 在命令行中添加CUDA_VISIBLE_DEVICES=8
但程序依然在0号GPU上运行。

**实验环境（请补全下列信息）：**
 - 操作系统:  Linux
- RecBole 版本 1.0.1
 - Python 版本 3.9.13
- PyTorch 版本 1.13.1
- cudatoolkit 版本 12.2

**Comment by HoupingY** [comment]
我的是在运行RecBole-GNN时，有同样的问题。
操作系统: Linux
RecBole 版本 1.1.1
Python 版本 3.7
PyTorch 版本 1.12.0
cudatoolkit 版本 10.2
请问你的这个问题解决了吗

**Comment by hdd1009** [comment]
没有阿，不知道怎么解决。

**Comment by hdd1009** [comment]
> 我的是在运行RecBole-GNN时，有同样的问题。 操作系统: Linux RecBole 版本 1.1.1 Python 版本 3.7 PyTorch 版本 1.12.0 cudatoolkit 版本 10.2 请问你的这个问题解决了吗



> 我的是在运行RecBole-GNN时，有同样的问题。 操作系统: Linux RecBole 版本 1.1.1 Python 版本 3.7 PyTorch 版本 1.12.0 cudatoolkit 版本 10.2 请问你的这个问题解决了吗

没有阿，不知道咋解决。

**Comment by Fotiligner** [comment]
@hdd1009 您好，RecBole可以通过设定gpu_id来指定训练的GPU号。您可以在命令行中设置，或进入[overall.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/overall.yaml)进行设置。

**Comment by hdd1009** [comment]
> @hdd1009 您好，RecBole可以通过设定gpu_id来指定训练的GPU号。您可以在命令行中设置，或进入[overall.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/overall.yaml)进行设置。

非常非常感谢！通过您的设置overall.yaml的方式解决了！

**Comment by qinxingkun** [comment]
> [@hdd1009](https://github.com/hdd1009) 您好，RecBole可以通过设定gpu_id来指定训练的GPU号。您可以在命令行中设置，或进入[overall.yaml](https://github.com/RUCAIBox/RecBole/blob/master/recbole/properties/overall.yaml)进行设置。

您好，为什么设置了gpu_id: '1', 运行的还是0号显卡呢
