### ISSUE TITLE
[💡SUG] 一句话描述您希望新增的功能或特性

### ISSUE THREAD

**Issue by 1371149** [RUCAIBox/RecBole#1959]
在对用户做TopRank推荐时，耗时过长，有没有什么办法，只对部分user做TopRank推荐，比如说，我只对其中200个user做full推荐，然后计算mrr？

**Comment by Yilu114** [comment]
对于TopRank推荐，RecBole使用了一种加速策略，即在给定用户-项目评分后，只选择和生成Top-k项目，而不是对所有项目进行排序。这种策略可以显著提高评估效率，但仍然需要对每个用户-项目对进行评分预测，这可能是耗时的。

如果你想只对部分用户做TopRank推荐，可以有以下几个思路：

- 你可以使用RecBole提供的数据划分方法，如随机排序+比例划分（RO_RS），时间排序+留一法划分（TO_LS），随机排序+留一法划分（RO_LS）或时间排序+比例划分（TO_RS），来划分训练集、验证集和测试集。然后，只对测试集中的用户做TopRank推荐，而不是对整个数据集中的用户做推荐。这样可以减少评估的用户数量，从而节省时间。
- 你可以使用RecBole提供的采样机制，如full或uniN，来选择正负样本。full表示对所有项目进行评估，uniN表示对每个正样本配对N个负样本进行评估。你可以选择一个较小的N值，如1或5，来减少评估的项目数量，从而节省时间。
- 你可以使用RecBole提供的配置文件，如config文件或yaml文件，来设置评估的参数，如topk，metric，valid_metric等。你可以选择一个较小的topk值，如5或10，来减少评估的项目数量，从而节省时间。你也可以选择一个较少的metric值，如HR或NDCG，来减少评估的指标数量，从而节省时间。

希望对你有所帮助。
