### ISSUE TITLE
LR/FM/DeepFM这几个模型运用ml-100k跑Recall, MRR,NDCG,Hit,Precision评价指标报错了

### ISSUE THREAD

**Issue by catmint999** [RUCAIBox/RecBole#1977]
问题如题，我讲述一下我的运营流程：
1. 在终端中运行：python run_recbole.py --model=WideDeep --dateset = ml-100k --config_files=test_ml.yaml
<img width="1119" alt="截屏2024-01-22 23 13 07" src="https://github.com/RUCAIBox/RecBole/assets/152595877/387f48c8-e658-4266-a005-cc26647ae61a">
batch_user_num = positive_u[-1] + 1
TypeError: 'NoneType' object is not subscriptable

2. 其中test_ml.yaml文件的内容如下：
# 新手入门：https://blog.csdn.net/Turinger_2000/article/details/111493291
# evalution settings
eval_setting: TO_LS,full #对数据按时间排序，设置留一法划分数据集，并使用全排序
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准
valid_metric: MRR@10 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size

我猜测是否是因为ContextRecommender基础类与Recall, MRR,NDCG,Hit,Precision这几个评价指标不兼容。我运行din、dien上没有遇到这个问题

**Comment by teal024** [comment]
同样遇到了这个错误

**Comment by Yilu114** [comment]
您好，
您在运行RecBole时遇到的错误似乎与`batch_user_num`的计算有关，具体是`batch_user_num = positive_u[-1] + 1`这一行。错误消息表明'NoneType'对象不可订阅。

以下是一些诊断和可能解决问题的步骤：

1. **检查数据加载**：
    - 确保您的数据集（`ml-100k`）正确加载并包含有效的用户-项目互动。
    - 验证您的`test_ml.yaml`配置文件中指定的数据路径指向正确的位置。

2. **检查`positive_u`**：
    - 错误发生在尝试访问`positive_u`的索引时，`positive_u`似乎是一个列表或数组。
    - 检查`positive_u`是否正确初始化并包含有效数据。它应该是正用户索引的列表。

3. **调试计算**：
    - 检查定义`positive_u`的上下文以及它如何用于计算`batch_user_num`。
    - 确保`positive_u`不是`None`且具有有效值。


4. **查看`run_recbole.py`脚本**：
    - 仔细检查您用来运行RecBole的命令：`python run_recbole.py --model=WideDeep --dateset=ml-100k --config_files=test_ml.yaml`。
    - 确保没有拼写错误或遗漏的参数。


如果您继续面临问题，考虑提供更多上下文或分享额外的代码片段以便进一步调查。此外，检查RecBole文档或社区资源，了解与此错误相关的任何特定故障排除步骤，以下的文档链接可以进行参考。

- [评估 | RecBole](https://recbole.io/evaluation.html)
- [培训与评估介绍 — RecBole 1.2.0 文档](https://recbole.io/docs/user_guide/train_eval_intro.html)
- [[问题] 使用大型评估批量大小加速评估 #1556 - GitHub](https://github.com/RUCAIBox/RecBole/issues/1556)
- [https://github.com/github/codeql/issues/8712](https://github.com/github/codeql/issues/8712)
- [https://blog.csdn.net/qq_41595149/article/details/119249132](https://blog.csdn.net/qq_41595149/article/details/119249132)
- [https://stackoverflow.com/questions/65606514/i-have-an-error-with-my-jsconfig-json-in](https://stackoverflow.com/questions/65606514/i-have-an-error-with-my-jsconfig-json-in-react-js-says-throw-err-unexpected-toke)
- [https://ithelp.ithome.com.tw/articles/10227493](https://ithelp.ithome.com.tw/articles/10227493)
- [https://github.com/libp2p/js-libp2p/issues/1273](https://github.com/libp2p/js-libp2p/issues/1273)

**Comment by houWenK** [comment]
> 问题如题，我讲述一下我的运营流程：
> 
> 1. 在终端中运行：python run_recbole.py --model=WideDeep --dateset = ml-100k --config_files=test_ml.yaml
> 
> <img alt="截屏2024-01-22 23 13 07" width="1119" src="https://private-user-images.githubusercontent.com/152595877/298631210-387f48c8-e658-4266-a005-cc26647ae61a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzM3MzksIm5iZiI6MTcyNzg3MzQzOSwicGF0aCI6Ii8xNTI1OTU4NzcvMjk4NjMxMjEwLTM4N2Y0OGM4LWU2NTgtNDI2Ni1hMDA1LWNjMjY2NDdhZTYxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMjUwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWU4MzM2OTRiMGU5ZDc4MTNiMjAyMjJlNDcwZTg3OGY2MDIwY2IzZjNmYjU1YmVlODUwMThiYzExZjQ4YzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p-pfwuzr0DXSdk1wA0NAX-gt0NJIoZqFnJyJTpwfYDQ"> batch_user_num = positive_u[-1] + 1 TypeError: 'NoneType' object is not subscriptable
> 2. 其中test_ml.yaml文件的内容如下：
> 
> # 新手入门：https://blog.csdn.net/Turinger_2000/article/details/111493291
> # evalution settings
> eval_setting: TO_LS,full #对数据按时间排序，设置留一法划分数据集，并使用全排序 metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准 valid_metric: MRR@10 #选取哪个评测标准作为作为提前停止训练的标准 eval_batch_size: 4096 #评测的batch_size
> 
> 我猜测是否是因为ContextRecommender基础类与Recall, MRR,NDCG,Hit,Precision这几个评价指标不兼容。我运行din、dien上没有遇到这个问题

同学，你解决了吗，咋解决的

**Comment by staphylinid** [comment]
才发现昨天是这个问题的周年纪念，，，但是还是没有解决
