### ISSUE TITLE
如何使用gpu进行数据评测

### ISSUE THREAD

**Issue by Frw14qve** [RUCAIBox/RecBole#1995]
**您希望添加的功能是否与某个问题相关？**
在进行precision，recall，ndcg进行数据评测时。由于评测在cpu上进行导致耗时巨大且gpu利用效率低

**描述您希望的解决方案**
希望能提供评测在gpu上运行的方法或者显著提高评测速度的替代方案

**其他**
![image](https://github.com/RUCAIBox/RecBole/assets/121424221/9c0b7dff-388b-4da0-bfe9-16aed5896f82)
最后感谢各位项目开发者的辛勤付出！

**Comment by Yilu114** [comment]
以下是在gpu上运行的方法或者显著提高评测速度的替代方案：

1. **在GPU上加速评测**：
    - RecBole为`top-k`评测指标提供了加速策略，因为这些指标通常需要为每个用户-物品对估计分数，因此耗时较长。
    - 关键步骤是基于排名分数选择和生成`top-k`物品。
    - 为此，RecBole使用了PyTorch提供的GPU版本的`topk()`函数。该函数针对CUDA进行了高度优化，因此在查找用户得分最高的`top-k`物品时非常高效。
    - 这里是如何使用这种GPU加速方法的示例代码：

    ```python
    import torch

    # 假设您已经计算了用户和物品的排名分数
    scores = torch.tensor(...)  # 请替换为实际的分数
    k = 10  # 指定所需的top-k值

    # 使用GPU加速的topk()函数找到top-k物品
    _, topk_indices = scores.topk(k, dim=1)

    # 现在topk_indices包含每个用户的top-k物品的索引
    ```

2. **替代策略**：
    - 如果GPU加速不足或不可行，考虑以下替代方案：
        - **批处理处理**：不要逐个处理用户-物品对，而是处理数据批次。这可以显著减少开销。
        - **采样**：对于大型数据集，考虑对一部分用户或物品进行采样评测。虽然这可能不会提供精确的指标，但可以给出合理的估计。
        - **近似指标**：使用评测指标的近似值（例如，使用Recall@5代替Recall@k）。这些近似值计算速度更快。
        - **并行化**：在多个CPU核心或机器上并行化评测过程。
        - **缓存**：缓存中间结果，避免在评测过程中进行冗余计算。

请注意，选择的策略取决于您的具体用例、数据集大小和可用资源。尝试不同的方法，找到准确性和速度之间的最佳平衡。

有关更多详细信息，请参阅RecBole官方文档中关于评测方法和指标的部分 。请根据您的具体情况自行调整提供的代码片段！ 🚀 [[RecBole documentation](https://recbole.io/evaluation.html)]
