### ISSUE TITLE
facing issues with fearec

### ISSUE THREAD

**Issue by thigazholi** [RUCAIBox/RecBole#2001]
1. how to choose seq_len in config for fearec?
2. The training job doesn't end on custom interaction data. How to train FEARec sequential model on custom data?

**Comment by Yilu114** [comment]
**FEARec** is a model designed for **sequential recommendation**, with strong modeling capabilities in both the time and frequency domains. If you want to train the FEARec model on custom data, here are some steps and recommendations:

1. **Choosing `seq_len`**:
    - `seq_len` refers to the maximum length of user behavior sequences. In your configuration file, you can set the value of `seq_len` to fit your dataset. Typically, you can choose an appropriate value based on the average behavior sequence length in your dataset. If your dataset has varying sequence lengths, consider selecting a slightly larger value to avoid truncating longer sequences. However, keep in mind that excessively large `seq_len` values may lead to high memory consumption, so it's essential to strike a balance.

2. **Training the FEARec Model**:
    - First, ensure that you have installed RecBole and downloaded the source code.
    - Next, you can use the `run_hyper.py` script to tune the model's hyperparameters. Here's an example command (modify it according to your dataset and requirements):
        ```bash
        python run_hyper.py --model=FEARec --dataset=your_dataset_name --config_files=your_config_files_path --params_file=hyper.test
        ```
        Replace `your_dataset_name` with your dataset's name and `your_config_files_path` with the path to your configuration files. You can set the hyperparameter search space in the `hyper.test` file.

3. **Custom Dataset**:
    - If your dataset is custom, you'll need to convert it to a format supported by RecBole. Refer to the dataset section in the official RecBole documentation for specific steps.

I hope this information helps!
