### ISSUE TITLE
AttributeError: 'SequentialDataset' object has no attribute 'item_id_list_field'

### ISSUE THREAD

**Issue by wbcat132** [RUCAIBox/RecBole#2016]
this is my data,this photo is the first one
![part of data](https://github.com/RUCAIBox/RecBole/assets/90330731/23bd6aae-80b3-4e7e-9af7-0aacbc354e71)
and this is my config
![config](https://github.com/RUCAIBox/RecBole/assets/90330731/f894a58c-7056-430e-9676-0881bdb17519)
the final picture is my run_recbole.py ,i just set the "model" and "dataset" and the "config_files"
![run_recbole](https://github.com/RUCAIBox/RecBole/assets/90330731/22e558f1-cbee-4b76-b202-a8e97225b39d)
How do I modify these files?，please help me,tk

**Comment by wbcat132** [comment]
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: venue_id
LABEL_FIELD: label
NEG_PREFIX: neg_
benchmark_filename: [train, val, test]
alias_of_item_id: [item_id_list]
load_col:
    inter: [user_id, venue_id,item_id_list,label]
epochs: 500
train_batch_size: 1024
eval_batch_size: 1024
eval_args:
  split:  {'LS': 'valid_and_test'}
  group_by: ~
  mode: labeled
  order: TO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
loss_type: 'BPR'

**Comment by zhengbw0324** [comment]
@wbcat132 Hello!
The sequential recommendation model does not support AUC and logloss metrics. You can refer to the experimental setup [here](https://github.com/RUCAIBox/UniSRec/tree/master/props).

**Comment by wbcat132** [comment]
@zhengbw0324 why i use this config can run the  sequential recommendation
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: venue_id
TIME_FIELD: timestamp
NEG_PREFIX: neg_
load_col:
    inter: [user_id, venue_id,timestamp]

epochs: 500
train_batch_size: 1024
eval_batch_size: 1024
training_neg_sample_num:uniform: 1

eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}
  group_by: ~
  mode: uni1
  order: TO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
loss_type: 'BPR'

**Comment by wbcat132** [comment]
i have settle the problem, thank you.
this is my config:
field_separator: "\t"
seq_separator: " "
LABEL_FIELD: label
benchmark_filename: [train, val, test]

load_col:
    inter: [user_id,item_id_list,item_id,label]
alias_of_item_id: [item_id_list]
train_neg_sample_args: ~
unisrec_transform: ~
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 2696
epochs: 500
train_batch_size: 1024
eval_batch_size: 1024
eval_args:
  split:  ~
  group_by: user
  mode: labeled
  order: TO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']
loss_type: 'BPR'
