### ISSUE TITLE
recbole能否进行交叉验证？[💡SUG] Description of what you want to happen in one sentence

### ISSUE THREAD

**Issue by kmr666** [RUCAIBox/RecBole#2025]
我想对模型进行交叉验证实验请问该如何实现？
例如将训练集和验证集合并，再将合并后的数据分为十份，任选九份作为训练集，一份为验证集，然后跑多次实验得到交叉验证的实验结果，请问利用recbole库该如何实现呀？

**Comment by NEUYuYang** [comment]
请问您有解决方法了吗

**Comment by Yilu114** [comment]
在RecBole中，要实现交叉验证实验，你可以使用其内置的数据分割功能，并自定义数据加载和模型训练逻辑。

实现步骤如下：

1. 数据集准备和合并：
   - 将训练集和验证集合并为一个数据集。
   - 使用RecBole的`Dataset`类加载数据，并指定合并后的数据文件路径。

2. 自定义数据分割：
   - 自定义数据分割策略，通过配置`split`参数（如`split_ratio`）来定义数据分割方式。你可以手动分割数据集为10份，或者使用`KFold`等交叉验证方法。

3. 模型训练和评估：
   - 利用RecBole的`Trainer`类来定义和执行多次实验。每次选择九份作为训练集，一份作为验证集。
   - 使用`train()`方法进行训练，并用`evaluate()`方法进行模型评估。


通过这种方式，你可以利用RecBole框架进行交叉验证实验，并获得模型在不同数据分割下的性能表现。

有关更多详细信息和API参考，请查看[RecBole文档](https://recbole.io/docs/)。
