### ISSUE TITLE
[🐛BUG] Quick start 中的GRU4REC实现，epoch是500，但是只运行了50次就自动停了

### ISSUE THREAD

**Issue by 97z** [RUCAIBox/RecBole#2029]
**描述这个 bug**
按照Quick start中的步骤，运行了GRU4REC，epoch是500，但是只运行了50次就自动停了。当我把epoch调为50以下，都是正常实现，但是调为50以上到50个epoch训练就停止了，想请问是哪里有问题吗

**Comment by Tensionteng** [comment]
训练的yaml文件里有一个`stopping_step`参数，在这个步骤内如果测量指标没变化，就会提前结束训练

**Comment by 97z** [comment]
谢谢您，得到解决了
