### ISSUE TITLE
[🐛BUG] Context-aware recommenders not properly embedding float sequences.

### ISSUE THREAD

**Issue by mmosc** [RUCAIBox/RecBole#2043]
Hello!
Thank you for this library.

**Describe the bug**
I am running several context-aware models using several float-sequence item features. However, the results that I get are for each model always the same, irrespective of the feature loaded.

While inspecting the code of Context Aware recommenders, I noticed that float sequences are always [embedded with a number of embeddings of `float_seq_field_dim`](https://github.com/RUCAIBox/RecBole/blob/2b6e209372a1a666fe7207e6c2a96c7c3d49b427/recbole/model/abstract_recommender.py#L327). However, `float_seq_field_dim` is always 1 for float sequences, as can be seen [here](https://github.com/RUCAIBox/RecBole/blob/2b6e209372a1a666fe7207e6c2a96c7c3d49b427/recbole/model/abstract_recommender.py#L302) and [here](https://github.com/RUCAIBox/RecBole/blob/2b6e209372a1a666fe7207e6c2a96c7c3d49b427/recbole/data/dataset/dataset.py#L1226). This means that every item is assigned the same embedding. This would explain why I get the same result, no matter which item feature I am loading.
 
**Expected behavior**
The model performance should vary depending on the float seq feature used.

**My guess on the origin of the problem**
float sequences are always embedded with a number of embeddings of 1, which means that every item is assigned the same embedding. This would explain why I get the same result, no matter which item feature I am loading. 

Are my hypotheses correct? If so, I think I found a bug :)

Best, 
Marta

**Comment by mmosc** [comment]
Hello! 

Are there any updates on this?

Best, 
Marta

**Comment by Yilu114** [comment]
Based on the RecBole documentation, the issue described might stem from a misunderstanding of how float sequence features are embedded. The float_seq_field_dim is not necessarily fixed at 1 for all models or features. The embedding dimension can be adjusted according to the model and the configuration file settings. It is recommended to check the configuration files and model parameters to ensure they are correctly set up. For more details, you can consult the [RecBole documentation](https://recbole.io/docs/).

Thank you for reaching out with your concerns. If you need further clarification, feel free to ask.

Best regards,
