### ISSUE TITLE
关于Recbole1.2.0版本安装问题

### ISSUE THREAD

**Issue by DX12321** [RUCAIBox/RecBole#2055]
您好，我想问一下Recbole1.2.0版本，对应的Numpy和Pandas版本是多少呢？（或者可以提供一下Recbole 1.2.0对应的其他核心Python库的版本吗）

我之前安装的是1.0的recbole，使用`pip`升级后版本不兼容了
目前的版本配置：
recbole    1.2.0
numpy    1.24.4
pandas    2.0.3
ray          2.0.0
scipy     1.10.1
torch    1.10.0+cu111
python 3.8

非常感谢！

**Comment by Yilu114** [comment]
RecBole 1.2.0版本对Python及其核心库的依赖版本有特定要求。推荐的版本如下：

- **Python**: 3.7 或 3.8
- **NumPy**: 1.17.2 或更高版本
- **Pandas**: 1.0.0 或更高版本
- **SciPy**: 1.5.4 或更高版本
- **PyTorch**: 1.6.0 或更高版本

你当前的配置看起来大部分符合要求，但需要确保所有依赖库版本与RecBole 1.2.0的兼容性。如果仍然出现问题，建议在虚拟环境中重新安装这些依赖库的推荐版本。

更多详细信息可以参考RecBole的[官方文档](https://recbole.io/docs/)
