### ISSUE TITLE
[🐛BUG] 运行SRGNN和LESSR时报了同样的错误

### ISSUE THREAD

**Issue by konglongbaka** [RUCAIBox/RecBole#2057]
**最近尝试复现一些基于会话的图神经推荐时，遇到了一个问题不知道如何解决**

Trainable parameters: 169920
Train     0: 100%|█████████████████████████| 48/48 [00:06<00:00,  7.67it/s, GPU RAM: 0.71 G/15.78 G]
08 Jun 17:18    INFO  epoch 0 training [time: 6.26s, train loss: 337.9507]
Evaluate   :   0%|                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/workspace/RecBole-GNN/run_recbole_gnn.py", line 15, in <module>
    run_recbole_gnn(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/mnt/workspace/RecBole-GNN/recbole_gnn/quick_start.py", line 48, in run_recbole_gnn
    best_valid_score, best_valid_result = trainer.fit(
  File "/usr/local/lib/python3.10/dist-packages/recbole/trainer/trainer.py", line 464, in fit
    valid_score, valid_result = self._valid_epoch(
  File "/usr/local/lib/python3.10/dist-packages/recbole/trainer/trainer.py", line 283, in _valid_epoch
    valid_result = self.evaluate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/recbole/trainer/trainer.py", line 616, in evaluate
    interaction, scores, positive_u, positive_i = eval_func(batched_data)
  File "/usr/local/lib/python3.10/dist-packages/recbole/trainer/trainer.py", line 554, in _neg_sample_batch_eval
    batch_user_num = positive_u[-1] + 1
TypeError: 'NoneType' object is not subscriptable

**所用代码**
只把run_recbole_gnn.py文件中添加了模型名和其对应的yaml文件

    parser.add_argument('--model', '-m', type=str, default='SRGNN', help='name of models')
    parser.add_argument('--dataset', '-d', type=str, default='ml-100k', help='name of datasets')
    parser.add_argument('--config_files', type=str, default='/mnt/workspace/RecBole- 
    GNN/recbole_gnn/properties/model/SRGNN.yaml', help='config files')

**参数都是默认**
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /usr/local/lib/python3.10/dist-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'none', 'sample_num': 'none', 'alpha': 'none', 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = True
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 
seq_separator =  
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters: 
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
step = 1
loss_type = CE
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.SEQUENTIAL
gnn_transform = sess_graph
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}

**问题**
由于刚刚接触图神经的推荐，可能是某些参数没有配置好，希望可以得到答复，感谢感谢

**实验环境：**
 - 操作系统:  Linux
- RecBole 版本 1.2.0
 - Python 版本 3.10
- PyTorch 版本 1.18

**Comment by Fotiligner** [comment]
你好！
run_recbole.py可以根据设定的模型和数据集自动调用对应的yaml配置文件。我更改了model，dataset以及对应配置文件，其他保持不变的情况下SRGNN和LESSR均可以正常训练。请问可以更详细的描述你的配置过程吗？

**Comment by konglongbaka** [comment]
你好，在遇到这个问题以后，我花了一段时间认真阅读了recbole的官方文档，现在问题已经得到了解决，感谢你们开发了recbole，这对我的科研工作有着很大的帮助

**Comment by houWenK** [comment]
你好请问怎么解决的我也出现了这个问题

**Comment by qinxingkun** [comment]
> 你好，在遇到这个问题以后，我花了一段时间认真阅读了recbole的官方文档，现在问题已经得到了解决，感谢你们开发了recbole，这对我的科研工作有着很大的帮助

您好，可以分享一下解决方案吗
