### ISSUE TITLE
打印输出预测正确的item_id

### ISSUE THREAD

**Issue by Echo-yajie** [RUCAIBox/RecBole#2067]
您好，想问一下，我想知道预测正确的item_id，这个要怎么实现呢？
感谢感谢~

**Comment by Yilu114** [comment]
您好！要在RecBole中打印预测正确的`item_id`，您需要先获取模型的预测结果，然后将预测的`item_id`与实际的`item_id`进行比较。您可以使用模型的`predict`方法获取预测分数，并通过自定义评估函数来找到正确预测的条目。

这样做的目的是在每个用户的预测结果中查找实际的`item_id`，并记录那些被正确预测的条目。完成比较后，就可以打印或存储所有预测正确的`item_id`。

您可以参考RecBole文档中的[模型评估部分](https://recbole.io/docs/user_guide/quick_start/evaluation.html)来获取更多详细的实现方法和示例代码。希望这些建议对您有帮助！如果有其他问题，欢迎继续提问。
