### ISSUE TITLE
[🐛BUG]  大神们，你们好，我想知道应该如何得到一个知识图谱推荐新的数据集

### ISSUE THREAD

**Issue by KAI-XIA** [RUCAIBox/RecBole#2073]
以MovieLens-KG这个数据集为例，里面的kg文件我应该怎么做才能得到。
我了解到通过https://github.com/RUCAIBox/RecSysDatasets这个地址使用转换工具中的add_knowledge.py可以生成kg文件，但是运行add_knowledge报错说需要link.kg文件，link.kg文件我应该怎么生成
![image](https://github.com/user-attachments/assets/10600f17-cff2-4c57-9cd6-5586b0066ec4)

**Comment by Yilu114** [comment]
你好，关于如何为知识图谱推荐生成新的数据集，以下是解决方法的详细步骤。

首先，`add_knowledge.py`脚本需要一个`link.kg`文件，该文件用于映射数据集中的物品ID（如MovieLens中的电影ID）与知识图谱（如Freebase）中的实体ID。你需要手动创建这个文件，其中每一行记录一个物品ID和对应的实体ID。

一旦`link.kg`文件准备好，你可以运行`add_knowledge.py`脚本，它会使用该映射文件从知识图谱中提取相关的实体和关系，生成最终的`kg`文件。

你可以在[RecSysDatasets GitHub页面](https://github.com/RUCAIBox/RecSysDatasets)上找到更多详细的操作步骤和示例。希望这些信息对你有帮助！如有更多问题，请继续提问。
