### ISSUE TITLE
复现bert4rec时train_neg_sample_args不为None

### ISSUE THREAD

**Issue by saccharin723** [RUCAIBox/RecBole#2097]
在跑SASRec或BERT4Rec时总是出现ValueError: train_neg_sample_args [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}] should be None when the loss_type is CE.
这个错误

想问一下在配置文件那个地方改

**Comment by saccharin723** [comment]
get answer

**Comment by duiyady** [comment]
大佬问下是怎么改的呢？遇到了同样的问题
