### ISSUE TITLE
训练时的疑问

### ISSUE THREAD

**Issue by saccharin723** [RUCAIBox/RecBole#2099]
我在进行recbole-master的训练的时候，不管跑什么模型，我在debug的时候，他的item_seq都是[1, 50]的tensor，item_seq_len为1的tensor，而我在recbole-DA-master训练的时候debug的item_seq是[256, 50]的tensor，我觉得item_seq应该是[256, 50]的tensor，为什么recbole-master的item_seq是[1, 50]的tensor呢
recbole-master的debug结果：
![1](https://github.com/user-attachments/assets/d4c58af5-e79b-4b28-a555-899443778969)
recbole-DA-master的debug结果：
![2](https://github.com/user-attachments/assets/952b05ed-4186-4fce-af01-f682fa8b1e15)
我想问一下这是因为配置文件的不同还是因为训练框架的不同

**Comment by rookie2568** [comment]
我也发现了这个问题，换用老版本的recbole则batch_size正常，我估计是新版本的bug?

**Comment by BishopLiu** [comment]
@saccharin723 你好，我们检查了一下发现训练的时候batch_size是正常的，你看到的batch_size为1的情况是在计算flops。
![截屏2024-10-18 17 38 31](https://github.com/user-attachments/assets/7245df88-e0d3-4b06-a37b-4b9e27fd437d)
![截屏2024-10-18 17 35 55](https://github.com/user-attachments/assets/378bdd91-c8ba-4143-8e76-0389edd2aec9)

**Comment by BlackTea-c** [comment]
solved, thanks a lot!
