### ISSUE TITLE
[🐛CRITICAL] The SSL certificate of the official documentation site has expired

### ISSUE THREAD

**Issue by 9re-pe** [RUCAIBox/RecBole#2111]
**Describe the bug**

The SSL certificate of the RecBole official documentation site (https://recbole.io/) appears to have expired, making it inaccessible via browsers that enforce strict HTTPS policies. This issue prevents users from accessing the documentation securely.

**Comment by 9re-pe** [comment]
This problem has been fixed! Than you!

**Comment by perfectclear** [comment]
It's happened again. May want to reopen issue.
