### ISSUE TITLE
[💡SUG] Distributed train and evaluation

### ISSUE THREAD

**Issue by suhmily** [RUCAIBox/RecBole#486]
I wonder if RecBole will support distributed pytorch architecture such as horovod?

**Comment by ShanleiMu** [comment]
Thanks for your insightful commment. In the future versions, we will consider adding this feature.

**Comment by Sherry-XLL** [comment]
Hello @suhmily, we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the distributed training and evaluation is supported in our framework. You can refer to our [documentation](https://recbole.io/docs/get_started/distributed_training.html) for more details and running examples.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We very much welcome you to use our library again and give your valuable comments.
