### ISSUE TITLE
Will you support MIND dataset? 

### ISSUE THREAD

**Issue by ConnollyLeon** [RUCAIBox/RecBole#498]
**Is your feature request related to a problem? Please describe.**
MIND (MIcrosoft News Dataset) is published by Microsoft, which is a recommendation dataset comprised of user behaviors and news. 

Will there be any chances that RecBole can support this dataset in the future?

Looking forward to your replies.

**Comment by linzihan-backforward** [comment]
Thanks for your suggestion.  In the future versions, we will consider taking in this dataset and related models. By the way, this kind of  dataset which contains textual information is naturally support in this framework. You can handle your own dataset and run it with Recbole. :)

**Comment by batmanfly** [comment]
@ConnollyLeon This suggestion sounds interesting. Our team is currently making code improvement on the first release of RecBole. We are not available to implement your idea right now. However, we are always looking for participants who would like to join in the development.  Would you like to join us for contributing to this idea?

**Comment by ConnollyLeon** [comment]
@linzihan-backforward @batmanfly Thanks for your reply. I would love to join you for contributing this idea after I understand how your code works😄.  As long as I encounter any questions, I will post them here.

**Comment by ConnollyLeon** [comment]
Hey, sorry for replying late for many other business. I have made a pull request in the RecDatasets github. Expecting for any suggestions and cooperations.

**Comment by ShanleiMu** [comment]
> Hey, sorry for replying late for many other business. I have made a pull request in the RecDatasets github. Expecting for any suggestions and cooperations.

**Comment by ShanleiMu** [comment]
> Hey, sorry for replying late for many other business. I have made a pull request in the RecDatasets github. Expecting for any suggestions and cooperations.

It has been merged into RecDatasets ([RUCAIBox/RecDatasets#84](https://github.com/RUCAIBox/RecDatasets/pull/84)). =)
