### ISSUE TITLE
[💡SUG] Do you support the ability to extract recommendations after training and evaluation?

### ISSUE THREAD

**Issue by tszumowski** [RUCAIBox/RecBole#506]
**Is your feature request related to a problem? Please describe.**
After I train and evaluation, I am struggling to figure out how to run the models on data after-the-fast. For example, 
* suppose I have a series of user IDs for which I'd like to get the top-10 rankings for. or
* suppose I have  a user ID and an item ID, and would like to know what is the item's positional ranking for that user

Because the `DataLoader`'s class has several other elements built in (e.g. negative sampling config, used IDs information), I am unsure how to create a "fresh" DataLoader with IDs that I'd like to generate rankings for.

**Describe the solution you'd like**
An exposed interface/function to evaluate:
* scores and/or rankings of items, given a user ID
* score and position of an item, given an item ID and a user ID

**Describe alternatives you've considered**
I've tried to "override" the `test_data` `DataLoader` object in the quickstart with my own data, but ran into indexing issues and figured I'd  ask first.

**Additional context**
N/A -- Thank you for open-sourcing this! Really cool!

**Comment by chenyushuo** [comment]
Thanks for your insightful commment. Because we are refactoring related functions, these features will be added in the future versions. If you want to implement these features in the current version temporally,  please refer to the following code:

```Python3
import numpy as np
import torch
from recbole.model.general_recommender.bpr import BPR
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.data.interaction import Interaction


@torch.no_grad()
def get_scores(uid_series, model, test_data):
    """Calculate the scores of all items for each user in uid_series.
    
    Note:
        The score of [pad] and history items will be set into -inf.
    
    Args:
        uid_series (np.ndarray): User id series
        model (AbstractRecommender): Model to predict
        test_data (AbstractDataLoader): The test_data of model
    
    Returns:
        torch.Tensor: the scores of all items for each user in uid_series.
    """
    uid_field = test_data.dataset.uid_field
    iid_field = test_data.dataset.iid_field
    
    # Get scores of all items
    input_interaction = Interaction({uid_field: torch.tensor(uid_series.repeat(dataset.item_num))})
    input_interaction.update(test_data.get_item_feature().repeat(len(uid_series)))
    score = model.predict(input_interaction).view(len(uid_series), dataset.item_num)

    score[:, 0] = -np.inf  # set scores of [pad] to -inf

    # Get history items
    test_inter = test_data.dataset.inter_feat
    history_item_ids = []
    for uid in uid_series:
        pos_item_id = test_inter[iid_field][test_inter[uid_field] == uid].values
        used_item_id = test_data.sampler.used_ids[uid]
        history_item_ids.append(list(used_item_id - set(pos_item_id)))

    # set scores of history items to -inf
    for i, hist_iid in enumerate(history_item_ids):
        score[i, hist_iid] = -np.inf

    return score

def get_topk(uid_series, model, test_data, k):
    """Calculate the top-k items' scores and ids for each user in uid_series.
    
    Args:
        uid_series (np.ndarray): User id series
        model (AbstractRecommender): Model to predict
        test_data (AbstractDataLoader): The test_data of model
        k (int): The top-k items.
    
    Returns:
        tuple:
            - topk_scores (torch.Tensor): The scores of topk items.
            - topk_index (torch.Tensor): The index of topk items, which is also the internal ids of items.
    """
    score = get_scores(uid_series, model, test_data)
    return torch.topk(score, k)


if __name__ == '__main__':
    # Load config, dataset and model (if you have load these things, you can skip these codes)
    config = Config(model='BPR', dataset='ml-100k')
    dataset = create_dataset(config)
    train_data, valid_data, test_data = data_preparation(config, dataset)
    model = BPR(config, train_data)
    checkpoint = torch.load('RecBole/saved/BPR-Nov-16-2020_10-38-53.pth')
    model.load_state_dict(checkpoint['state_dict'])
    model.eval()

    # uid_series = np.array([1, 2])  # internal user id series
    # or you can use dataset.token2id to transfer external user token to internal user id
    uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])

    topk_score, topk_iid_list = get_topk(uid_series, model, test_data, 10)
    print(topk_score)  # scores of top 10 items
    print(topk_iid_list)  # internal id of top 10 items
    external_item_list = dataset.id2token(dataset.iid_field, topk_iid_list)
    print(external_item_list)  # external tokens of top 10 items
    print()

    score = get_scores(uid_series, model, test_data)
    print(score)  # score of all items
    print(score[0, dataset.token2id(dataset.iid_field, ['242', '302'])])  # score of item ['242', '302'] for user '196'.
```

Note: method ``dataset.token2id`` & ``dataset.id2token`` are added in #511 .

Output:
![2020-11-18 21-18-05 的屏幕截图](https://user-images.githubusercontent.com/31039063/99535461-e3bc1000-29e3-11eb-94b1-3d71a2bb24f5.png)

**Comment by tszumowski** [comment]
@chenyushuo Thank you for the fast and comprehensive reply. This is perfect for what I was interested in! And very clean and understandable interface!

**Comment by tszumowski** [comment]
Just a quick update on the code for `get_scores()`.
There is a reference to `dataset` variable in a few places, but it isn't assigned. For example:
```python
input_interaction = Interaction({uid_field: torch.tensor(uid_series.repeat(dataset.item_num))})
```

A quick workaround is to add
```python
dataset = test_data.dataset
```
at the top.

**Comment by chenyushuo** [comment]
Thank you for your correction. I have updated the code in ``get_scores()``.

**Comment by fotol1** [comment]
@chenyushuo  Thanks for the example! Unfortunately, this does not work for sequential models. Could you provide some sample code that retrieves the top k recommendations for sequential models?

**Comment by chenyushuo** [comment]
@fotol1, thanks for your reminding, you can refer to this example to retrieve the top k items for sequential models:
```python3
@torch.no_grad()
def get_scores_in_seq_model(uid_series, model, test_data):
    """Calculate the scores of all items for each user in uid_series.
    
    Note:
        The score of [pad] item will be set into -inf.
    
    Args:
        uid_series (np.ndarray): User id series
        model (SequentialRecommender): Model to predict
        test_data (SequentialDataLoader): The test_data of model
    
    Returns:
        torch.Tensor: the scores of all items for each user in uid_series.
    """
    uid_field = test_data.dataset.uid_field
    iid_field = test_data.dataset.iid_field
    dataset = test_data.dataset
    
    index = np.isin(test_data.uid_list, uid_series)
    input_interaction = test_data.augmentation(test_data.uid_list[index], test_data.item_list_index[index],
                                               test_data.target_index[index], test_data.item_list_length[index])
    input_interaction = test_data._dict_to_interaction(input_interaction)

    try:
        score = model.full_sort_predict(input_interaction)
    except NotImplementedError:
        input_interaction = input_interaction.repeat(dataset.item_num)
        input_interaction.update(test_data.get_item_feature().repeat(len(uid_series)))
        score = model.predict(input_interaction).view(len(uid_series), dataset.item_num)

    score[:, 0] = -np.inf
    return score

def get_topk_in_seq_model(uid_series, model, test_data, k):
    """Calculate the top-k items' scores and ids for each user in uid_series.
    
    Args:
        uid_series (np.ndarray): User id series
        model (SequentialRecommender): Model to predict
        test_data (SequentialDataLoader): The test_data of model
        k (int): The top-k items.
    
    Returns:
        tuple:
            - topk_scores (torch.Tensor): The scores of topk items.
            - topk_index (torch.Tensor): The index of topk items, which is also the internal ids of items.
    """
    score = get_scores_in_seq_model(uid_series, model, test_data)
    return torch.topk(score, k)
```

**Comment by mayaKaplansky** [comment]
Was this code added to the solution or I should add it manually?

**Comment by chenyushuo** [comment]
@mayaKaplansky These code are temporary solution, you can use them manually.

**Comment by mayaKaplansky** [comment]
Hi,
I'm not sure how to send the arguments expected in the code above. If I run the model in command line, in the end a *.pth file is created. Is it one of the arguments in the function? If not, what should be sent?

**Comment by mayaKaplansky** [comment]
Hi
I copied-pasted the code in the beginning of the thread and got an error on this line:
`score = model.predict(input_interaction).view(len(uid_series), dataset.item_num)`

this is the error:
`RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)`

What should I fix?
Many thanks!

**Comment by mayaKaplansky** [comment]
Hi
I'm trying to use the code above, and I see the arguments that are sent to "get_topk_in_seq_model" is a user Id which in sequential model is actaully he session ID. Is there a way to send to the function a series of itemID, to get the top K next predictions?
So in sequential, it mean I would like to send a list of clicks, and get a prediction of the next one, like using "predict" function in other libraries. 
Thanks

**Comment by dxjjhm** [comment]
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

**Comment by chenyushuo** [comment]
@dxjjhm Which model do you run to cause this RuntimeError? Can you give more information to help us? We will check it.

**Comment by mayaKaplansky** [comment]
Thank you both, I managed to solve the issue.
I'm trying to use the code above for sequential models, and I see the arguments that are sent to "get_topk_in_seq_model" is a user Id which in sequential model is actaully he session ID. Is there a way to send to the function a series of itemID, to get the top K next predictions?
So in sequential, it mean I would like to send a list of clicks, and get a prediction of the next one, like using "predict" function in other libraries.
Thanks

**Comment by chenyushuo** [comment]
@mayaKaplansky  The code above is used for get topk items in valid dataset or test dataset. You can use `Interaction` to load given userID and a series of itemID, and then pass it to `full_sort_predict` function in model. Almost every sequential model have this function which is used for calculate the score of all items by input `Interaction`.

The doc for `Interaction` is here: https://recbole.io/docs/recbole/recbole.data.interaction.html

By the way, we suggust you to read more comments and [doc](https://recbole.io/docs/index.html), which will solve many of your problems.

**Comment by mayaKaplansky** [comment]
Hi
Thank you for helping, I'm doing my best...
I couldn't find in https://recbole.io/docs/recbole/recbole.data.interaction.html an argument that allows me to send a list of items.
Also, for sequential models, the user id is the session id, which each session happens only once in a dataset. So I find it hard to understand how this must be an input for prediction. A specific session happens only once and its fully known, the purpose of the model is to predict a new session item order I would say. For sequential models the input should be only a list of items IDs, and predict the next items.
also in function

>  full_sort_predict(interaction): full sort prediction function. Given users, calculate the scores between users and all candidate items.

 Fro sequential model, shouldn't it be "Given sequence of items, calculate the scores between the given sequence and all candidate items."
What am I missing? Many thanks in advance

**Comment by dxjjhm** [comment]
#

> 
> 
> @dxjjhm Which model do you run to cause this RuntimeError? Can you give more information to help us? We will check it.

BPR model, and I am already fixed it by given dtype=torch.long, but I find another problem , the prediction result is different every time. Why?

**Comment by mayaKaplansky** [comment]
Hi is there a way to re-open this thread? there are 2 unanswered questions here.
many thanks
