### ISSUE TITLE
使用豆瓣数据集，卡死在DataLoader的遍历上

### ISSUE THREAD

**Issue by silsuer** [RUCAIBox/RecBole#510]
下载了豆瓣的数据集，大概长下面这样:
```
user_id:token	item_id:token	rating:float	timestamp:float	likes_num:float
0	0	3	1431446400	2404
1	0	2	1429804800	1231
2	0	2	1429977600	1052
3	0	4	1429718400	1045
4	0	2	1429632000	723
```
然后用文档中的代码:
```
config_dict = {
    "load_col": {
        "inter": ["user_id", "item_id", "rating", "timestamp", "likes_num"],
    }
}
run_recbole(model='LightGCN', dataset='douban', config_dict=config_dict)
```

通过断点调试发现在 `trainer.py`的`_train_epoch`方法中：
```
for batch_idx, interaction in enumerate(train_data):
    print(batch_idx)
```
始终无法打印出 `batch_idx`

而使用 `ml-100k` 数据集是可以正常遍历的，请问是我使用方法不对还是如何？

刚开始接触这个，不太懂，求指教~

**Comment by chenyushuo** [comment]
暂时建议不要使用豆瓣数据集。这个数据集里面只有27个item，存在 user 把所有的 item 都交互过，导致无法负采样。日后我们对这种情况进行处理。

**Comment by silsuer** [comment]
明白了，谢谢

**Comment by SmileTM** [comment]
issue中唯一的红点，进来问问 有vx / qq交流群吗？

**Comment by batmanfly** [comment]
> issue中唯一的红点，进来问问 有vx / qq交流群吗？

我们现在还在着手进行代码的优化（接口尽量都不会动，大家可以放心使用）。因此短期内没有人力来维护相关的交流群。

但是我们将保证绝大部分问题将在1-3天内给出来回复或者修复（部分无法完成的问题将明确告知），视困难程度而定。

也欢迎大家提需求（例如，你期望添加的模型等），我们可能成批次地、按需地完成这些更新。

也欢迎亲自参与开发你所希望的功能。

感谢你的关注！

~赵鑫

**Comment by chenyushuo** [comment]
我们在#613 修复了这个问题。

现在如果有user 把所有的 item 都交互过，我们在Sampler里会报错，提示需要在配置文件中添加`max_user_inter_num`参数。

这个参数是用来删除过多交互的用户，具体文档参考[这里](https://recbole.io/docs/user_guide/data/data_args.html?highlight=max_user_inter_num#filter-by-number-of-interactions)。
