### ISSUE TITLE
[💡SUG] Add progress bar to training an epoch

### ISSUE THREAD

**Issue by tszumowski** [RUCAIBox/RecBole#516]
**Is your feature request related to a problem? Please describe.**
When training on large datasets, it's difficult to know how far along training is and whether or not I should stop training to tweak parameters to speed up the training process.

**Describe the solution you'd like**
Add tqdm progress bar to training progress. See context section. I have a suggested patch to `trainer.py` that adds this. Happy to PR it in, or feel free to take as you see appropriate.

**Describe alternatives you've considered**
One alternative is a manual print. But tqdm is the standard for this typically. 

**Additional context**

[trainer.py.patch.txt](https://github.com/RUCAIBox/RecBole/files/5573977/trainer.py.patch.txt)

I attached a patch file that adds an optional `show_progress` argument in a similar manner to what's used in DataLoader already. Note: This patch only shows it for the `Trainer` class, not the child classes. That is because this is for an example only. 

The main change is this:

```diff
-        for batch_idx, interaction in enumerate(train_data):
+        iter_data = (
+            tqdm(
+                enumerate(train_data),
+                total=len(train_data),
+                desc=f"Train {epoch_idx:>5}",
+            )
+            if show_progress
+            else enumerate(train_data)
+        )
+        for batch_idx, interaction in iter_data:
```

Here is an example output while training a larger dataset. Scroll right to see full output.

```
Trainable parameters: 735267
Train     0:  20%|███████████████████████████▌                                                                                                           | 6480/31756 [10:47<42:09,  9.99it/s]
```

**Comment by chenyushuo** [comment]
Thanks for your insightful commment. Using tqdm is a good way to add this feature. We'd appreciate it if you would like to PR it in branch 0.1.x. By the way, any PRs are welcome.
Note: ``trainer.py`` has been refactor in #521 , be careful to add this feature.

**Comment by adebiasio-estilos** [comment]
when running the code via jupyter notebook, tqdm print all the time new lines
