### ISSUE TITLE
[🐛BUG] Minor Typo on Atomic Files Page

### ISSUE THREAD

**Issue by tszumowski** [RUCAIBox/RecBole#538]
**Describe the bug**
I wasn't sure where or what repository this HTML is generated in. But there is a minor typo in https://recbole.io/atomic_files.html. Under `ml-1m.item`, it says `user_id:token`. I believe that should say `item_id:token`

**To Reproduce**
Go to https://recbole.io/atomic_files.html

**Expected behavior**
See description

**Screenshots**
![image](https://user-images.githubusercontent.com/10282962/99967161-743c7c80-2d65-11eb-8823-0dc83831e512.png)

**Colab Links**
If applicable, add links to Colab or other Jupyter laboratory platforms that can reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS or Windows]
- RecBole Version [e.g. 0.1.0]
 - Python Version [e.g. 3.79]
- PyTorch Version [e.g. 1.60]
- cudatoolkit Version [e.g. 9.2, none]

**Comment by chenyushuo** [comment]
Thanks for your corrections. We have fix this problem in our website pages.
