### ISSUE TITLE
Model cannot get access to interaction features other than item and time. 

### ISSUE THREAD

**Issue by rowedenny** [RUCAIBox/RecBole#546]
**Describe the bug**
I am developing a sequential model that needs the interaction features, such as rating and comment, but I find the tensor that the model gets from the corresponding field is not correct.  

So I dive into the sequential dataloader, and find a issue
1. In the function next_batch, either real_time or not, it both relies on the function augmentation
2. In the function augmentation, based on my understanding, for a feature from a field out of item and time, the current implementation only record the features of the *target* item, referring to https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataloader/sequential_dataloader.py#L138
and then it records item index and time index, but ignores the other feature field of the history items, referring to
https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataloader/sequential_dataloader.py#L144

So that explains my case that when my model tries to get access to the rating of history items, the length of the corresponding tensor is 1, rather than being equal to the length of the tensor of max_seq_length

I think it could be a bug because basically, we will not care about the interaction features for the item to be predicted. Please be free to correct me if I am wrong. 

**Expected behavior**
The sequential model can get access to other interaction features.

**Comment by rowedenny** [comment]
Update:
I just figure out that the model like SASRecF can get access to rich features out of the Interaction object, and following this example I can make it on my own.  So please be free to unlabeled my issue and close it.

**Comment by rowedenny** [comment]
I have noticed that Recbole has implemented the FeatureSeqEmbLayer, yet it only works for item and user features, not including the interaction features

**Comment by hyp1231** [comment]
Thanks for your kind suggestion! :D

We didn't implement this feature in the first version for insufficient development time issue. In the next version, which will be released within one week, we will enhance RecBole's sequential datadoader with arbitrary historical interaction features. Then historical interaction features can be accessed by ``field_name + config['LIST_SUFFIX']`` from ``Interaction`` objects.

**Comment by rowedenny** [comment]
Hi @hyp1231, thank you for your quick response. I understand that for all developer the time is limited, so I'm happy to PR it in, or feel free to take as you see appropriate. 
I think I can make it today thus when you wake up, you can start the code review. ;)

**Comment by hyp1231** [comment]
Thanks for your contribution! It looks good and has been merged. It will also be released in the next version.
