### ISSUE TITLE
[🐛BUG] Cuda usage when use_gpu is False

### ISSUE THREAD

**Issue by fotol1** [RUCAIBox/RecBole#555]
I set `use_gpu = False` but noticed that BERT4Rec is trying to use cuda (but I don't have cuda on my laptop). [Here](https://github.com/RUCAIBox/RecBole/blob/cedd7eac5cd2455727532b031beedf224d92be2f/recbole/model/sequential_recommender/bert4rec.py#L196) is an example.

**Comment by aHuiWang** [comment]
Thanks! It has been fixed, referring to #556
