### ISSUE TITLE
[Question] Custom Dataset

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#567]
Is there an example of generating a custom dataset?
I need to transform raw data into atomic ones then dataframe?  Or can I simply transform raw files (let's assume it's txt) into dataframe and put it into custom dataloader?

**Comment by EliverQ** [comment]
Thanks for your question! We suggest you to transform raw data into atomic ones instead of using customized dataloader.
We have demonstrated the structure of atomic files and given some examples on our home page: https://recbole.io/atomic_files.html and you can transform your raw data files to atomic files in the specified format.

**Comment by johnny12150** [comment]
Thanks for the great package.
So how do I load the dataset after I transform the original input data into atomic format?
Is there an example or tutorial for this?

**Comment by EliverQ** [comment]
Assuming that the name of the dataset is `test_data` and you've got `test_data.inter`, `test_data.user` and `test_data.item`, then you may put these three atomic files into the directory `RecBole/dataset/test_data` and run:
```
python run_recbole.py --model=xxx --dataset=test_data
```

**Comment by EliverQ** [comment]
> Assuming that the name of the dataset is `test_data` and you've got `test_data.inter`, `test_data.user` and `test_data.item`, then you may put these three atomic files into the directory `RecBole/dataset/test_data` and run:
> 
> ```
> python run_recbole.py --model=xxx --dataset=test_data
> ```

For more detail, you can click here: [https://recbole.io/docs/user_guide/usage/running_new_dataset.html](https://recbole.io/docs/user_guide/usage/running_new_dataset.html)

**Comment by johnny12150** [comment]
Thanks! 
It sounds simple, and I will try it now.
When will I need to use the parts of `Convert to Dataset` and `Convert to Dataloader` within the below link?
https://recbole.io/docs/user_guide/usage/running_new_dataset.html

**Comment by hyp1231** [comment]
> Thanks!
> It sounds simple, and I will try it now.
> When will I need to use the parts of `Convert to Dataset` and `Convert to Dataloader` within the below link?
> https://recbole.io/docs/user_guide/usage/running_new_dataset.html

Generally, if you just want to run the existing models on your custom dataset, there is no need to use these parts.

If you want to run RecBole in a more customized way, e.g. k-fold evaluation, then maybe you need to rewrite ``recbole.quick_start.run_recbole``, and in this way, you need to learn about ``Convert to Dataset`` and ``Convert to Dataloader``.

**Comment by johnny12150** [comment]
Got it. 
Thanks!

**Comment by mayaKaplansky** [comment]
Hi,
lets say I have my own dataset, and convert it to the tables as described. When I want to actually save them as atomic files, do I just change the file type manually?

**Comment by hyp1231** [comment]
> Hi,
> lets say I have my own dataset, and convert it to the tables as described. When I want to actually save them as atomic files, do I just change the file type manually?

Please refer to [https://github.com/RUCAIBox/RecBole/discussions/607#discussioncomment-236083](https://github.com/RUCAIBox/RecBole/discussions/607#discussioncomment-236083).
