### ISSUE TITLE
How to make click dataset to .inter?

### ISSUE THREAD

**Issue by hfzarslan** [RUCAIBox/RecBole#593]
I have the following columns in my dataset what columns can be useful for making .inter data for sequential recommender system

Columns List:
`event_time ,event_type ,product_id,  category_id, category_code, brand, price, user_id  ,user_session_id

`
thanks

**Comment by hyp1231** [comment]
For running customized datasets with the existing models in RecBole, please refer to [Running New Dataset](https://recbole.io/docs/user_guide/usage/running_new_dataset.html).

What's more, discussions in #567 may be also helpful.

**Comment by mayaKaplansky** [comment]
Hi
If adding 'user_session_id' as a feature, how does the model use it just as a diffrenatiator between sessions, and not as a feature that impacts the model calculations? 
I want to use GRU4Rec and I'm not sure how to mark a session.
