### ISSUE TITLE
[💡SUG] Suggested hyperparameter ranges

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#598]
Since most papers come with suggested hyperparameter options I think it would be useful to have those ranges listed somewhere so people don't need to dig into the paper for them. One possibility would be to have premade `model.hyper` Hyperopt files with the typical ranges. This would make it easier to try out different baselines, etc

**Comment by 2017pxy** [comment]
Sorry for late reply, we added the hyper parameter ranges of our models in our [API Docs](https://recbole.io/docs/user_guide/model_intro.html) last week, and now you can check the hyper parameter ranges in model introduction pages(e.g: [ItemKNN](https://recbole.io/docs/user_guide/model/general/itemknn.html) ). Note that we just provide these hyper parameter ranges for reference only, and we can not guarantee that they are the optimal range of this model.

**Comment by deklanw** [comment]
@2017pxy Thanks! But, I have to ask, why are all the parameters `choice`? Why not more `quniform` or `qloguniform`? With `choice` for everything Hyperopt has no notion of "nearness" of parameters

**Comment by 2017pxy** [comment]
@deklanw We refer to the practice of general research papers and use grid search to traverse the range of candidate parameters, so it is enough to use `choice` in Hyperopt. Of course, if you want more precise tuning, you can set the corresponding settings supported by Hyperopt for continuous variables or discrete variables, such as `uniform` and `quniform`, to better play the role of Hyperopt.

**Comment by deklanw** [comment]
@2017pxy I see. But, the quantized stochastic symbols `quniform`,  `qloguniform`, etc can still be used with exhaustive search (and enable use of other non-exhaustive search strategies like TPE).

See, this example implementation https://github.com/hyperopt/hyperopt/issues/200#issuecomment-507287308

> The exhaustive search is based on random sampling of the space and avoiding any duplicated sample evaluation. It supports the usage of 'randint', 'quniform', 'qloguniform', 'qnormal', 'qlognormal' and 'categorical' within complex, conditional spaces.
