### ISSUE TITLE
[Question] Split train and test data by timestep

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#604]
Is there a way in the data loader to split train and test data by certain timestamp?
For example, SR-GNN and GC-SAN use the newest data to test/ validate.

**Comment by hyp1231** [comment]
This function can be abstracted as splitting the original interaction records according to values of the certain feature (``split_by_value``), which should be another choice besides ``split_by_ratio``. This part has been considered but not been implemented yet. PR about this function is highly welcomed. Please see [https://github.com/RUCAIBox/RecBole/blob/948d9d6f30325cb506f61db362d15a2320eb2556/recbole/data/dataset/dataset.py#L1356-L1364](https://github.com/RUCAIBox/RecBole/blob/948d9d6f30325cb506f61db362d15a2320eb2556/recbole/data/dataset/dataset.py#L1356-L1364) for details.

Besides the above discussion, there is indeed another way to split train and test data by certain timestamps. You can pre-split the ``.inter`` into several new atomic files by timestamp, and use the config ``benchmark_filename`` to load the pre-split datasets. Please refer to [https://github.com/RUCAIBox/RecBole/issues/586#issuecomment-748043623](https://github.com/RUCAIBox/RecBole/issues/586#issuecomment-748043623) for details.

**Comment by johnny12150** [comment]
Ok, I will take a look at it.
```YAML
benchmark_filename: ['part1', 'part2', 'part3']
```
Is it correct that `part1` will be automatically loaded as training data?
Also, is there a way to do data augmentation in config?
Or I should finish this part in `.inter` file?
