### ISSUE TITLE
Control decimal places for metric and loss

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#605]
Is there a field I can set in the config file to set the decimal places for loss and metric?

**Comment by 2017pxy** [comment]
@johnny12150 Sorry for late reply and thanks for your suggestion, we have added this new feature into RecBole (#625)  and it has been merged into 0.2.x branch. You can set `loss_decimal_place`  and `metric_decimal_place` in the config file to control the decimal place of train loss and metric result separately. By the way, we will release new version next month and this new feature will be added.

**Comment by johnny12150** [comment]
Thanks for the great work!
Is there a timeline for adding pre-split dataset support to sequential models?
