### ISSUE TITLE
[Question] How do I set data augmentation in config?

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#614]
Is there a way to do data augmentation in config?
Or I should finish this part in `.inter` file? 
The reason why I ask is related to how GRU4Rec, SRGNN, GCSAN handle the preprocessing part.

**Comment by ShanleiMu** [comment]
The data augmentation has been done by default in SequentialDataloader for Sequential recommendations.

For example, if a session interaction record is c1, c2, c3, c4, c5, after processing, the training data will be like this:

c1 -> c2
c1, c2 -> c3
c1, c2, c3 -> c4
c1, c2, c3, c4 -> c5

**Comment by chenyushuo** [comment]
We always do data augmentation in the sequential model. You can see the following code for details:

https://github.com/RUCAIBox/RecBole/blob/90d5c3f18ca0e10d6cad5c74ff0723125ef9aa25/recbole/data/dataset/sequential_dataset.py#L40-L94

**Comment by johnny12150** [comment]
Thanks!
