### ISSUE TITLE
[Question] What is predicted in sequential recommendation? 

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#616]
Hi
Just to make sure, when using sequential model, the prediction is done on the next "item id" for the user session, correct?
How can I get a log of top 5 predictions per input on the test data?

**Comment by ShanleiMu** [comment]
Q1:
You are right. In the current version, the sequential models only support predicting the next "item id". In the future, we will consider supporting the next basket recommendations.

Q2:
Please refer to #506.
