### ISSUE TITLE
SequentialDataset inter_feat has label leakage

### ISSUE THREAD

**Issue by rowedenny** [RUCAIBox/RecBole#620]
I am recently developing a sequential dataset, but similar to LightGCN. So I follow the current implementation of LighGCN to fetch the historical interactions from `train_data.inter_feat`, but the performance is way higher than my expectation. 

Then I cautiously check if there is any possibility that the test label may leak. unfortunately, it is indeed.

During `leave_one_out` of sequential_dataset, [a direct copy of the whole dataset](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataset/sequential_dataset.py#L106) is implemented, and then to select the index according to the item indices. In general, it should be fine, but the key problem is the inter_feat of the dataset, no matter for train_set, test_set, valid_set are identical. So when I directly fetch the inter_feat within the trainset, the test label has leaked.

In comparison with the implementation in general dataset, [it select the corresponding indices](https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataset/sequential_dataset.py#L106) and save the partitioned inter_feat. So LightGCN does not suffer from this issue.

I am not sure whether it is a bug, but it indeed shows some risk. If some other user is not aware of the tiny issue on the sequential dataset, it makes a false improvement on the performance.

**Comment by rowedenny** [comment]
I have found a simple way to work around it, yet I am not sure how to prohibit this risk in general cases. Please let me know if you have a clear idea to fix and I would like to PR for it.

**Comment by chenyushuo** [comment]
Can you describe your way to fix this bug? We can check if there are any other problems.

**Comment by rowedenny** [comment]
In my case, I need to fetch the `self.inter_feat` of a sequential dataset object. Take the leave_one_out into consideration, the last two interactions of each user should not be included, thus what I did is to reconstruct the function `_create_spare_matrix` by the following code
```
new_inter_feat = self.inter_feat.groupby(self.uid_field, as_index=False).apply(lambda x: x.iloc[:-2])
```
and then work with the `new_inter_feat` instead of `self.inter_feat`

**Comment by chenyushuo** [comment]
OK, there's no problem with your idea on the whole.

However, we are going to release v0.2.0 (on the 0.2.x branch) recently. On this branch, `dataset.inter_feat` will be converted to `Interaction` after the initial data processing,
https://github.com/RUCAIBox/RecBole/blob/0772227c2e5f5899f394073c6a3c27b804b555d8/recbole/data/dataset/dataset.py#L113
https://github.com/RUCAIBox/RecBole/blob/0772227c2e5f5899f394073c6a3c27b804b555d8/recbole/data/dataset/dataset.py#L924-L929
So we will rewrite the code you provide to be equivalent.

Finally, thank you for discovering this problem.

**Comment by rowedenny** [comment]
A pleasure to make a contribution to Recbole.

**Comment by chenyushuo** [comment]
That's fine, we suggest you to make contributions to branch 0.2.x, because we will release v0.2.0 next month.

Thanks for your contributions again.
