### ISSUE TITLE
[🐛BUG] module 'recbole.data.dataset' has no attribute 'GRU4RecDataset' , KeyError: 'session_id'

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#624]
Hi, 
I tried to run GRU4Rec, this is the full error:

```

Traceback (most recent call last):
  File "C:\Users\Administrator\RecBole\recbole\data\utils.py", line 35, in create_dataset
    return getattr(importlib.import_module('recbole.data.dataset'), config['model'] + 'Dataset')(config)
AttributeError: module 'recbole.data.dataset' has no attribute 'GRU4RecDataset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'session_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\Users\Administrator\RecBole\recbole\quick_start\quick_start.py", line 38, in run_recbole
    dataset = create_dataset(config)
  File "C:\Users\Administrator\RecBole\recbole\data\utils.py", line 40, in create_dataset
    return SequentialDataset(config)
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\sequential_dataset.py", line 38, in __init__
    super().__init__(config, saved_dataset=saved_dataset)
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\dataset.py", line 100, in __init__
    self._from_scratch()
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\dataset.py", line 113, in _from_scratch
    self._data_processing()
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\dataset.py", line 152, in _data_processing
    self._data_filtering()
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\dataset.py", line 172, in _data_filtering
    self._filter_nan_user_or_item()
  File "C:\Users\Administrator\RecBole\recbole\data\dataset\dataset.py", line 607, in _filter_nan_user_or_item
    dropped_inter = self.inter_feat.index[self.inter_feat[field].isnull()]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'session_id'
```

This is my config file:
```
# Atomic File Format
field_separator: "\t"
seq_separator: " "

# Common Features
USER_ID_FIELD: session_id 
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
seq_len: ~

# Label for Point-wise DataLoader
LABEL_FIELD: label
threshold: ~

# NegSample Prefix for Pair-wise DataLoader
NEG_PREFIX: neg_

# Selectively Loading
load_col:
    inter: [session_id, item_id, timestamp, PatientLocationID,GenderID,AgeGroup, JobGroup]
    # the others
unload_col: ~
additional_feat_suffix: ~

# Filtering
rm_dup_inter: ~
max_user_inter_num: ~
min_user_inter_num: 0
max_item_inter_num: ~
min_item_inter_num: 0
lowest_val: ~
highest_val: ~
equal_val: ~
not_equal_val: ~
drop_filter_field : True

# Preprocessing
fields_in_same_space: ~
fill_nan: True
preload_weight: ~
drop_preload_weight: True
normalize_field: ~
normalize_all: True

# Sequential Model Needed
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id


# Benchmark .inter
benchmark_filename: ~

# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/Ofek'
checkpoint_dir: 'saved'

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
training_neg_sample_num: 1
eval_step: 1
stopping_step: 10

# evaluation settings
eval_setting: RO_RS,full
group_by_user: True
split_ratio: [0.8,0.1,0.1]
leave_one_num: 2
real_time_process: True
metrics: ["Recall", "MRR","NDCG","Hit","Precision"]
topk: [5]
valid_metric: MRR@5
eval_batch_size: 4096

```

and this is the header of my inter file:

`JobGroup:token 	 item_id:token 	 PatientLocationID:token 	 GenderID:token 	 AgeGroup:token 	 timestamp:float 	 session_id:token 
`
Where is my mistake?
Thanks!!

**Comment by hyp1231** [comment]
I run the latest code of branch 0.2.x, using a toy ``.inter`` generated according to your description and the config file provided by you. 

```
RecBole/
├── dataset/
│   └── Ofek/
│       └── test/
│           └── test.inter
├── test.yaml
├── run_recbole.py
├── recbole/
└── ...
```

```bash
python run_recbole.py --model=GRU4Rec --dataset=test --config_file=test.yaml
```

But I didn't meet the bug you pasted, and the ``Dataset`` is generated successfully. (BTW, sequential models don't support ratio-based splitting strategy currently, which may cause other errors later.)

Could you please check out if my ``.inter`` has a different format or other misunderstandings?

Attachments: [test.zip](https://github.com/RUCAIBox/RecBole/files/5745675/test.zip)

**Comment by mayaKaplansky** [comment]
Thanks I will check. What is the separator in the first row of the inter file? is it \t?
When you say " sequential models don't support ratio-based splitting strategy currently" - then should I remove this configuration from the yaml file? And how should I load train\test data to there?

**Comment by hyp1231** [comment]
> Thanks I will check. What is the separator in the first row of the inter file? is it \t?
> When you say " sequential models don't support ratio-based splitting strategy currently" - then should I remove this configuration from the yaml file? And how should I load train\test data to there?

**Q1**: Yes, it's ``\t`` (as in your config file's second line writes ``field_separator: "\t"``).

**Q2**: Generally, sequential models are evaluated using *leave-one-out* strategy. E.g. the last two items of one user are used for validation and test separately. Try changing ``eval_setting: RO_RS,full`` to ``eval_setting: TO_LS,full``.

For more details, please refer to [Evaluation Settings](https://recbole.io/docs/user_guide/evaluation_support.html#evaluation-settings).

**Comment by mayaKaplansky** [comment]
Hi
Thank you.
for Q2 - If in each session lets say I have 5 clicks, then the validation will happen on predicting click 4 and test on predicting click 5. That creates a bias toward those specific clicks, as maybe the model can be very good at predicting other clicks. Also this means that that the model is 'learning' on clicks 1-3, and then tested on click 5 which lowers the probability to succeed. Is there any way to randomly use for Test all types of clicks as a percentage of the data, or alternatively can I feed separate files for test and train?

**Comment by mayaKaplansky** [comment]
That helped a lot!!
I passed that error, and got this (your also got this error on my PC):
`ValueError: Sequential models require "loo" split strategy.`

**Comment by hyp1231** [comment]
Maybe I have not got the point yet.

If you'd like to select clicks randomly for testing, but not follow the temporal order, you can change ``eval_setting: TO_LS,full`` to ``eval_setting: RO_LS,full``.

For the last question, I think it has been discussed in https://github.com/RUCAIBox/RecBole/issues/586#issuecomment-751155144.

**Comment by mayaKaplansky** [comment]
Hi
I certainty do want to follow temporal order, I will try to ask again, referring to this comment:

> Generally, sequential models are evaluated using leave-one-out strategy. E.g. the last two items of one user are used for validation and test separately. Try changing eval_setting: RO_RS,full to eval_setting: TO_LS,full.

Lets say I have multiple sessions, each session has 5 clicks.
According to the comment, click 4 of each session is left out for validation, and click 5 is for testing.
Can I understand from this that the training is done on learning how to predict click 2 and click 3 of each session?
But then, for testing we try to predict click 5 of each session although no training was done on it?

**Comment by 2017pxy** [comment]
Please refer to #632.
