### ISSUE TITLE
[🐛BUG] Waiting time for 1st epoch

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#627]
Hi
My inter file has almost 8M lines.
How much time is it reasonable to wait at this stage:
![image](https://user-images.githubusercontent.com/57919041/103240336-f7925480-4947-11eb-9e21-e33ac9b8d09f.png)

I did check on a smaller file and it worked.
How can I configure to use more than one GPU?
Should I increase the log level in some way?

thanks!

**Comment by mayaKaplansky** [comment]
Hi,
after more than 40 minutes I got the first epoch:
![image](https://user-images.githubusercontent.com/57919041/103241968-a46ed080-494c-11eb-80ea-7529d5593435.png)

I checked and my server has 2 GPUs of NVIDIA Tesla M60. Should I run this on Tesla K80?
How can I configure REcBole to use 2 GPUs?
Thanks!

**Comment by hyp1231** [comment]
Hi,
* We have added progress bar when training an epoch to branch 0.2.x (which will be released soon), please refer to #516.
* Currently, RecBole has not developed or tested to adapt to distributed training and evaluation. We may add this feature in the future. Track #486 to keep an eye on this.
* We have provided comprehensive reference on training speed & memory usage of different models on various datasets, please refer to [Time and Memory Costs](https://github.com/RUCAIBox/RecBole#time-and-memory-costs) and #518 to find a similar case.

**Comment by mayaKaplansky** [comment]
Thank you very much, I replaced my machine to NVIDIA Tesla T4, and eventually it finished running :)
