### ISSUE TITLE
[🐛BUG] Error loading a config file in PyCharm

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#635]
Hi
I manage to run the model through command line, but when trying to get topK from here: https://github.com/RUCAIBox/RecBole/issues/506 
I must use Pycharm, then I altered the config code to be like this:

```
if __name__ == '__main__':
    # Load config, dataset and model (if you have load these things, you can skip these codes)
    config = Config(model='GRU4Rec', dataset='Ofek',config_file_list='OfekConfig.yaml')
```

I located the yaml file in the directory of the project, and yet I get `No such file or directory: 'O'`
When I look into the Config code, I see that for:
`for file in file_list:`
in configurator.py the iterator creates `file=0` instead of the name I sent.

Please advice, Maya. Thanks!

**Comment by dxjjhm** [comment]
config file list need absolute path, already tested.

**Comment by mayaKaplansky** [comment]
Thanks a lot!
