### ISSUE TITLE
Dataset.save Throw an error. TypeError: Object of type FeatureType is not JSON serializable

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#636]
**Describe the bug**

**To Reproduce**
model = 'BPR'
dataset = 'ml-100k'
config_file_list = []
saved = True
param_dict = {
    "use_gpu": False,
    "topk": "[10]",
    "valid_metric": "MRR@10"
}
# configurations initialization
config = Config(model=model, dataset=dataset, config_file_list=config_file_list, config_dict=param_dict)
init_seed(config['seed'], config['reproducibility'])

dataset = Dataset(config)
dataset.save("D:/data/test/save_test")

3. script for running

Traceback (most recent call last):
  File "D:/source/recbole-0.1.2/recbole/example/dataset_eg.py", line 22, in <module>
    dataset.save("D:/data/test/save_test")
  File "D:\source\recbole-0.1.2\recbole\data\dataset\dataset.py", line 1366, in save
    json.dump(basic_info, file)
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\whdu\.conda\envs\pytorch\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type FeatureType is not JSON serializable

**Screenshots**

**Colab Links**
If applicable, add links to Colab or other Jupyter laboratory platforms that can reproduce the bug.

**Desktop (please complete the following information):**
 - OS: Windows
- RecBole Version 0.1.2
 - Python Version  3.7
- PyTorch Version 1.7.1
- cudatoolkit Version none

**Comment by 2017pxy** [comment]
@dxjjhm Firstly, thanks for your close attention to RecBole. About `Dataset.save`, this feature is still under development, so calling this feature does cause a bug. We will continue to develop this feature in the future. Once it is available, we will inform you here.

**Comment by dxjjhm** [comment]
> @dxjjhm Firstly, thanks for your close attention to RecBole. About `Dataset.save`, this feature is still under development, so calling this feature does cause a bug. We will continue to develop this feature in the future. Once it is available, we will inform you here.

Does this bug will be fixed in next version? 
And, when will be published?

**Comment by 2017pxy** [comment]
@dxjjhm I am sorry to tell you that we won't fix this problem in next version, but we have already addad it into our development plan and we will fix it as soon as possible.

**Comment by rowedenny** [comment]
Yeap, I am also highly looking forward to this function. 
We usually need to apply various data preprocessing, and it could be time costly to prune a large dataset to fit a specific task. If a benchmark could be saved, it means we do not need to re-run the preprocessing again.

**Comment by chenyushuo** [comment]
@dxjjhm @rowedenny 
Hi, we have already refactored `dataset.save` in #760. The usage of this function can be found in [https://github.com/RUCAIBox/RecBole/blob/master/run_example/save_and_load_example.py](https://github.com/RUCAIBox/RecBole/blob/master/run_example/save_and_load_example.py).
Thanks for your suggestions.
