### ISSUE TITLE
Dataset remap the origin user_id to a new user_index, where to get the relationship?

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#638]
Dataset remap the origin user_id to a new user_index, where to get the relationship?
Dataset remap the origin item_id to a new item_index, where to get the relationship?

**Comment by hyp1231** [comment]
Inside the framework, we store the mapping relationships in ``Dataset.field2id_token``, please refer to the [API Doc](https://recbole.io/docs/recbole/recbole.data.dataset.dataset.html#recbole.data.dataset.dataset.Dataset.field2id_token).

If you are working on case study, you can also see #506 and [case_study.py](https://github.com/RUCAIBox/RecBole/blob/0.2.x/recbole/utils/case_study.py) for details.
