### ISSUE TITLE
[💡SUG] gpu_id only support 1 gpu, how to config support 2 or more gpus?

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#640]
gpu_id only support 1 gpu, how to config support 2 or more gpus?

**Comment by chenyushuo** [comment]
Currently, RecBole has not developed or tested to adapt to distributed training and evaluation. We may add this feature in the future. Track #486 to keep an eye on this.

**Comment by johnny12150** [comment]
Can I pick the GPU that I want to run on?

**Comment by linzihan-backforward** [comment]
> Can I pick the GPU that I want to run on?

Certainly, you can sellect GPU by 
`python run_recbole.py --gpu_id=1 `

**Comment by Sherry-XLL** [comment]
Hello @dxjjhm , we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the distributed training and evaluation is supported in our framework now. You can refer to our [documentation](https://recbole.io/docs/get_started/distributed_training.html) for more details and running examples.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
