### ISSUE TITLE
Config defaults lead to error with MultiVAE

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#649]
@guoyihonggyh The RecBole default value of `training_neg_sample_num = 1` causes an error in MultiVAE. Maybe better to give a warning?

**Comment by 2017pxy** [comment]
@deklanw We have already set a `ValueError` in the function: `dataloader_construct` to warn users.  If you run the non-sampling model (including CDAE, MultiVAE, MultiDAE and MacridVAE) by `python run_recbole --model=[model_type]` without setting `training_neg_sample_num = 0`, you will receive the error info like `ValueError: training_neg_sample_num should be 0` from the function `dataloader_construct`. I think it's enough for users to know what's going wrong.

**Comment by 2017pxy** [comment]
@deklanw Plus, we will also make a special note in our docs in a few days to warn users that if users want to run these non-sampling models, they have to set `training_neg_sample_num=0 `. By the way, I am so surprised that someone can pose a issue about MultiVAE which was added into RecBole just 2 days ago and we even didn't update its docs in our website ! Thanks for your close attention to RecBole !
