### ISSUE TITLE
[🐛BUG] Small mistake in docs of AutoInt

### ISSUE THREAD

**Issue by huangbiubiu** [RUCAIBox/RecBole#650]
**Describe the bug**
In the quick start of [AutoInt](https://recbole.io/docs/user_guide/model/context/autoint.html), the running code 
```python
from recbole.quick_start import run_recbole

run_recbole(model='AUTOINT', dataset='ml-100k')
```

should be
```python3
from recbole.quick_start import run_recbole

run_recbole(model='AutoInt', dataset='ml-100k')
```

**Comment by 2017pxy** [comment]
@huangbiubiu Thx for your scrutiny and we have fixed this typo.
