### ISSUE TITLE
GPU is not being used in training despite GPU memory allocated

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#669]
Hi,
I am training the BPR model for a general recommendation on custom data. It is set to use GPU and it is using almost 5 GB of GPU memory but the usage of GPU is quite low; it's around 3 to 4%.

![image](https://user-images.githubusercontent.com/16714612/104230604-cbacbe00-5473-11eb-9bd3-700414b69203.png)

Are there any specific settings I need to do for high usage?

**Comment by 2017pxy** [comment]
@laxmimerit You can increase the `train_batch_size` (default to 2048) and `eval_batch_size` (default to 4096) to improve the usage of GPU. You can set these two settings in command line as follow: 
```
python run_recbole.py --model=BPR --train_batch_size=[int] --eval_batch_size=[int] 
```
Click [here](https://recbole.io/docs/user_guide/config_settings.html) for more infomation about these two settings.

**Comment by laxmimerit** [comment]
I have set `batch_size=16384` but still don't see any usage increment in GPU. Half of the time, it is utilized just `0%`. Memory allocation is almost 5GB of GPU. I have also tried to set a higher and lower batch size. Nothing is changing in GPU utilization.
Any idea?

**Comment by laxmimerit** [comment]
**Update 1:**
It is not using GPU for computation for sure! I tried to run two separate codes simultaneously and my GPU usage did not change (0% -1%) but CPU usage just got double and with three instances running simultaneously CPU usage increased thrice.

**Comment by laxmimerit** [comment]
**Update 2:**
Installed it from the source of branch @0.2.x. It's training fine. One thing I would like to also highlight for other windows users.
Windows Task Manager doesn't include CUDA usage in overall GPU utilization. Select CUDA in the top-right graph to see actual GPU usage.

![image](https://user-images.githubusercontent.com/16714612/104365261-ccaa2200-553d-11eb-8239-0e7210d94941.png)
