### ISSUE TITLE
[🐛BUG] 主页上的模型没有同步

### ISSUE THREAD

**Issue by zhuhh666** [RUCAIBox/RecBole#675]
使用conda安装了最新的recbole，但是主页上的模型并没有被更新（General recommendation），想问一下是怎么回事呢
![](https://nextlab.oss-cn-shanghai.aliyuncs.com/img/20210113170354.png)
![](https://nextlab.oss-cn-shanghai.aliyuncs.com/img/20210113170557.png)

**Comment by 2017pxy** [comment]
@zhuhh666 你好，我们将于1月15号发布新的版本（RecBole v0.2.0）并更新我们在conda和Pypi平台上的软件包，为了保证新版本能够顺利发布，我们提前在主页上更新了模型列表。在新版本中我们添加了5个General recommendation类模型（CDAE(#642),  MacridVAE(#637),  MultiVAE(#626),  MultiDAE(#626), LINE(#591)），除这些模型外，其他的General recommendation类模型应该都是可以正常调用的。
这些模型目前已经并入我们master分支的代码，你可以通过拉取代码来提前使用这些模型，也可以等待1月15号正式发布代码包后重新更新代码包。最后，感谢你对伯乐项目的关注！

**Comment by zhuhh666** [comment]
明白了，谢谢解答
