### ISSUE TITLE
Batch Size is not strictly following params value

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#678]
Hi,
I am sorry to ask too many questions. Seems like I am the only one who is having lots of issues while developing on custom data.

I am using `GCMC` in General Recommendation. I have set `    "train_batch_size": 4096,
    "eval_batch_size": 4096` but these settings are being changed dynamically. I have also tried with a few more models. Each model setting Batch_size dynamically and issuing this warming. The higher batch size is causing GPU OOM (`CUDA out of memory`). The warning is as follows

```
14 Jan 02:22    INFO batch_size = [[4096, 4096]], shuffle = [False]

14 Jan 02:22    WARNING Batch size is changed to 155944
14 Jan 02:22    WARNING Batch size is changed to 155944
```

Is there any way to fix it?

**Comment by dxjjhm** [comment]
I also find this problem, by testing the general recommender. It is always changing the batch size,  bad codes.

**Comment by EliverQ** [comment]
Hi, Thanks for your question. We've demonstrated the accurate definition of batch_size and why we define it in the Q3 of this link:
https://recbole.io/docs/user_guide/usage/qa.html
You may be able to figure it out after you've read it.

**Comment by laxmimerit** [comment]
Thanks. Understood! This makes sense.
