### ISSUE TITLE
[🐛BUG] Extreme memory usage with contextual features?

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#686]
I'm testing with a reasonably sized dataset (350k~ interactions) with a handful of token or token_seq features:

```yaml
  item:
    [
      "item_id",
      "year",
      "artist",
      "category",
      "designer",
      "family",
      "game_type",
      "mechanic",
      "publisher",
    ]
```
When I try running e.g. SASRecF or FDSA I get:

```
RuntimeError: CUDA out of memory. Tried to allocate 53.25 GiB (GPU 0; 15.90 GiB total capacity; 264.21 MiB already allocated; 14.79 GiB free; 306.00 MiB reserved in total by PyTorch)
```

Some of these categories are high cardinality, but they should be represented as sparse, right? What would cause memory usage this high?

for context, the size of the dataset:

![image](https://user-images.githubusercontent.com/11601778/104849199-87c41980-58b6-11eb-85d2-bf1f62a08a22.png)

**Comment by chenyushuo** [comment]
Thanks for reporting this bug, we have fixed it in #926.
