### ISSUE TITLE
[💡SUG]metrics.py 中 pos_index 的数据格式是什么，在doc文档中能否添加描述

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#695]
metrics.py 中 pos_index 的数据格式是什么，在doc文档中能否添加描述?
python中查看源码对于数据类型没有明确说明，对源码的理解特别不方便。

**Comment by chenyushuo** [comment]
@dxjjhm metrics.py 中 pos_index 是一个numpy的bool数组，他表示的是每个用户打分前k高的物品中，哪些是正例。
因为现有evalutor的设计不太好理解，我们正在准备对它重新进行设计，文档可能需要一些时间之后才会添加。

**Comment by tsotfsk** [comment]
Hi！@dxjjhm 你可以在[evaluation](https://recbole.io/evaluation.html)网页里了解到我们评测阶段所使用到的一些小技巧，实际上`pos_index` 就是上述页面中图[topk](https://recbole.io/images/eval_img1.png)中的矩阵**C**。而`pos_len`则是图中的矩阵**B**。很抱歉未能在代码中给出注释，对您的理解造成困扰。
