### ISSUE TITLE
[💡SUG] Sequential Model to reset hidden states?

### ISSUE THREAD

**Issue by jianshen92** [RUCAIBox/RecBole#697]
The sequential model are supposed to be stateless (short sequence), so we should be resetting the hidden state every batch. However I don't see any code that reset the hidden state in the training loop. May I know if this is intentional?

**Comment by aHuiWang** [comment]
In our implementation of the sequential data format, we need not this operation.
For example, given the interaction sequences from two users:
```
seq_1: 1 2 3 4
seq_2: 5 6 7 8
```
We split the sequences into several subsequences:
```
sub_seq: input: 1 output: 2
sub_seq: input: 1 2 output: 3
...
sub_seq: input: 5 output: 6
sub_seq: input: 5 6 output: 7
…
```
In this way, some complex models can be used. For GRU4Rec, we directly use GRU to encode sequence and don't need the reset operation.

However, in the official theano implementation of GRU4Rec, the authors concatenated all the sequences to a long sequence, 
```
seq: 1 2 3 4 5 6 7 8
```
so it should mark the [end index](https://github.com/hidasib/GRU4Rec/blob/master/gru4rec.py#L630) of one user interaction sequence and reset the hidden state for next sequence.

**Comment by jianshen92** [comment]
Hi @aHuiWang , thanks for replying. I understand that your implementation split into several subsequence, so we don't need to reset hidden states within the same batch.

However, BETWEEN batches, we should still reset the hidden states? Unless pytorch does it by default, which is something that I am not too familiar with.

**Comment by aHuiWang** [comment]
Yes. The GRU in the PyTorch needs input_tensor and hidden_state_tensor. The initial hidden state for each element in the batch defaults to zero if not provided. This can found in the comments for GRU in PyTorch.

**Comment by jianshen92** [comment]
Thanks @aHuiWang for your explanation!
