### ISSUE TITLE
[Question] Pre-split Dataset for Sequential Recommendation

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#700]
Is the pre-split dataset config now support sequential recommendation models?

As mentioned in 
#586

**Comment by 2017pxy** [comment]
@johnny12150 I am sorry to tell you that now we don't support pre-split dataset for sequential recommendation models, and we will consider adding this feature in the future.

**Comment by 2017pxy** [comment]
@johnny12150 Hi, we have released a new version (v1.0.0) and now we support the pre-split dataset loading for sequential models. You can pull our latest code and have a try!

**Comment by johnny12150** [comment]
Thank you for the great news!
