### ISSUE TITLE
How to create .kg and .link files?

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#708]
Hi,
I was hoping to get some suggestions on how to create the `.kg` and `.link` files?

**Comment by 2017pxy** [comment]
@laxmimerit Hi, you can find our dataset example in `recbole/dataset_example/ml-100k/`, where you can see the format of `.kg` and `.link` file.

**Comment by laxmimerit** [comment]
Hi,
I have seen these files but did not understand how to create these two files.

**Comment by laxmimerit** [comment]
Hi,
I understand that I need to prepare a knowledge graph first. Would you please suggest any article which can give me an idea on how to prepare .kg and .link files?

**Comment by 2017pxy** [comment]
@laxmimerit  Hi, I think [《KB4Rec: A Dataset for Linking Knowledge Bases with Recommender Systems》](https://arxiv.org/abs/1807.11141) may be helpful. By the way, you can see our [RecSysDatasets repo](https://github.com/RUCAIBox/RecSysDatasets) to get more information about dataset.

**Comment by laxmimerit** [comment]
Thanks a lot for a reference. Will let you know if I get stuck anywhere.
