### ISSUE TITLE
[💡SUG] 关于NDCG的解释不清

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#726]
![1](https://user-images.githubusercontent.com/6416625/108586415-5e048380-7389-11eb-8097-f96d88c2da66.png)

是否应该这样理解，
推荐结果在测试集中 rel_i = 1 反之为0。

**Comment by dxjjhm** [comment]
rel_i = 1, 2的rel_i次幂应该是2.

**Comment by 2017pxy** [comment]
@dxjjhm 是的，这里属于我们文档编写的小错误，应该是 rel_i 而不是 2^rel_i。 我们会尽快修正这个错误并更新网站，感谢你的纠正！
