### ISSUE TITLE
How to use customized dataloader

### ISSUE THREAD

**Issue by rowedenny** [RUCAIBox/RecBole#733]
The `model_type` is loaded from the config file associated the key word `MODEL_TYPE`, and then it is compared with enum variable, e.g `self.config['MODEL_TYPE'] == ModelType.GENERAL`.

However, when we assign MODEL_TYPE as an int in the yaml, the comparison above will be false; I also try to assign  MODEL_TYPE as ModelType.GENERAL, but then it would be converted to str type, thus the comparison will be false as well.

Though having googled it, unfortunately, I found no solution.  Would you please clarify how to set enum variable in the config file?

**Comment by 2017pxy** [comment]
@rowedenny I am sorry to tell you that now RecBole doesn't support to set `MODEL_TYPE` by user. If you read our code in `RecBole/recbole/config/configuartor.py`, you can see that we set the `MODEL_TYPE` in `_load_internal_config_dict()` automatically.

In  `_load_internal_config_dict()`, we will set the `MODEL_TYPE` base on which parent class your model inherits from. 
For example, if your model class is like:
``` python
from recbole.model.abstract_recommender import GeneralRecommender
class NewModel(GeneralRecommender):
    ```Your Code```
```
Then, `_load_internal_config_dict()` will set the `MODEL_TYPE` as ModelType.GENERAL(not a str).

Now RecBole supports four kinds of model type, namely General Recommendation, Sequential Recommendation, Context-aware Recommendation and Knowledge-based Recommendation. If you want to create a new model in RecBole, your model class must inherit one of them.  You can read `RecBole/recbole/model/abstract_recommender.py` to get more information about these four class.

Also, our [API DOCS](https://recbole.io/docs/developer_guide/customize_models.html) have some guides about how to create a new model by yourself, hope it can be helpful to you.

**Comment by rowedenny** [comment]
I see. The motivation to I wanna set `MODEL_TYPE` to train a new model in which the requirements on dataset, dataloader, and sampler are different from what we have now, so I would like to how to work around.

Currently what I may try is to when checking the `model_type` in the if-else, firstly assign a new value out of four kinds to `model_type`, then activate the customized dataset, dataloader, and sampler correspondingly. 

So for this case, would you mind provide more suggestions?

**Comment by 2017pxy** [comment]
@rowedenny Well, you can read the `get_data_loader()` in `RecBole/recbole/data/utils.py`.  
Part of the code is as follows:
```python
def get_data_loader(name, config, eval_setting):
    """Return a dataloader class according to :attr:`config` and :attr:`eval_setting`.

    Args:
        name (str): The stage of dataloader. It can only take two values: 'train' or 'evaluation'.
        config (Config): An instance object of Config, used to record parameter information.
        eval_setting (EvalSetting): An instance object of EvalSetting, used to record evaluation settings.

    Returns:
        type: The dataloader class that meets the requirements in :attr:`config` and :attr:`eval_setting`.
    """
    register_table = {
        'DIN': _get_DIN_data_loader,
        "MultiDAE": _get_AE_data_loader,
        "MultiVAE": _get_AE_data_loader,
        'MacridVAE': _get_AE_data_loader,
        'CDAE': _get_AE_data_loader,
        'ENMF': _get_AE_data_loader
    }

    if config['model'] in register_table:
        return register_table[config['model']](name, config, eval_setting)
        ......
```
In fact, in RecBole, some models are special and we need to return special dataloader for them. So you can see that like DIN and MultiDAE, we create special function ( `_get_DIN_data_loader()` and `_get_AE_data_loader()` ) for them. I think if your model also has some special needs, you can create a `_get_XXX_data_loader()` in  `RecBole/recbole/data/utils.py` for it. And then, you can add your model into the `register_table ` like DIN and MultiDAE.

As for the details about  `_get_DIN_data_loader()` and `_get_AE_data_loader()` , you can find their code in `RecBole/recbole/data/utils.py`.

**Comment by rowedenny** [comment]
Great! I guess this is function is fresh for version 0.2 since to my best knowledge I did not see this function previously, I will definitely read the new code.
