### ISSUE TITLE
How to get id's mapping

### ISSUE THREAD

**Issue by alankras** [RUCAIBox/RecBole#734]
After training, I want to get item embeds, but when data preprocessed, all my ids shuffling.
May I get mapping from old ids (before preprocessing) to new ids?

**Comment by chenyushuo** [comment]
We already have this function, [token2id](https://recbole.io/docs/recbole/recbole.data.dataset.dataset.html?highlight=token2id#recbole.data.dataset.dataset.Dataset.token2id) can mapping old ids to new ids.

**Comment by alankras** [comment]
Great job! 
Thank you
