### ISSUE TITLE
Case study removes what 'historical' items?

### ISSUE THREAD

**Issue by deklanw** [RUCAIBox/RecBole#740]
Intuitively it seems like the `full_sort_scores` should exclude *all* historical items from the full dataset: positive items from train/valid/test. From experimenting with it it does not seem to do that.

https://github.com/RUCAIBox/RecBole/blob/master/recbole/utils/case_study.py#L44

There doesn't appear to be documentation for `uid2history_item` so I can't tell what this is doing exactly. I'm guessing it's calling the train+valid positive items "historical" but not the test positive items? If this is the intention, it would be convenient to have an option to count all positive items as historical.

Thanks

**Comment by chenyushuo** [comment]
In training process, our design is that the positive items in train and valid are not involved in the evaluation in test. When we implement `full_sort_scores`, we hope that the scoring matrix is consistent with that in the training process. So we set score of 'historical' item (the positive items in train and valid) to -inf, and we remove these 'historical' item in `full_sort_scores`.
