### ISSUE TITLE
CFKG模型问题

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#745]
您好，想问几个问题
1、CFKG模型是不是就是直接把user-item交互数据构建为KG然后进行KGE吗？还是也加上了外部知识图谱？
2、您的代码中注释到“In this version, we sample recommender data and knowledge data separately, and put them together for training.“我不太理解这个版本是做了怎样的改动，能麻烦您简单解释下吗？

**Comment by ShanleiMu** [comment]
你好
1、联合了user-item交互数据（U-I）和外部知识图谱（KG）。
2、和作者源代码的训练数据组织方式略有差别。作者源代码将U-I数据和KG数据混合在一起shuffle然后训练，这版将U-I数据和KG数据分开shuffle，然后分别从这两部分取数据合在一起作为训练数据。

**Comment by vencexu** [comment]
请问知识图谱的推荐仅能运用top-K指标吗，如KGAT、RIppleNet等论文中有提到AUC的评估，在RecBole中如何实现呢？

**Comment by ShanleiMu** [comment]
> 请问知识图谱的推荐仅能运用top-K指标吗，如KGAT、RIppleNet等论文中有提到AUC的评估，在RecBole中如何实现呢？

目前是只能用top-K指标来做ranking的评价，对于AUC等指标还不支持，后续会进行完善。

**Comment by HUE96yhz** [comment]
还想问一下，您实现的CKE模型跟原论文有什么不同？因为CKE那篇论文比较早，作者代码也没找到，看您注释里是说只用到知识图谱结构知识信息，没有使用文本和图片信息是吗？除了这个还有与原论文不一样的地方吗？

**Comment by ShanleiMu** [comment]
> 还想问一下，您实现的CKE模型跟原论文有什么不同？因为CKE那篇论文比较早，作者代码也没找到，看您注释里是说只用到知识图谱结构知识信息，没有使用文本和图片信息是吗？除了这个还有与原论文不一样的地方吗？

还有正则项略有不同，不过基本不影响效果，其他都一样

**Comment by HUE96yhz** [comment]
@ShanleiMu 用dataset_example/ml-100k数据集跑了CKE，有个疑问就是ml-100k.inter里是评分的形式，CKE的paper用的是隐式反馈数据，那RecBole框架里是有把打分先转成了隐式反馈数据的吗？非常抱歉一直打扰您。。。

**Comment by ShanleiMu** [comment]
> @ShanleiMu 用dataset_example/ml-100k数据集跑了CKE，有个疑问就是ml-100k.inter里是评分的形式，CKE的paper用的是隐式反馈数据，那RecBole框架里是有把打分先转成了隐式反馈数据的吗？非常抱歉一直打扰您。。。

是的，把评过分的item看作与用户交互过的item（一般也会筛掉一些评分低的item），从而转化成隐式反馈数据。把评分这种显式反馈数据应用到针对隐式反馈的模型上，主流的做法都是这样。

**Comment by HUE96yhz** [comment]
> 你好
> 1、联合了user-item交互数据（U-I）和外部知识图谱（KG）。
> 2、和作者源代码的训练数据组织方式略有差别。作者源代码将U-I数据和KG数据混合在一起shuffle然后训练，这版将U-I数据和KG数据分开shuffle，然后分别从这两部分取数据合在一起作为训练数据。

CFKG模型原论文使用的电商数据集，有5种类型实体和6种类型关系；我用您复现的模型跑了movielens数据集，那这个实体和关系是该怎么理解呢？
