### ISSUE TITLE
[🐛BUG] rm_dup_inter works with False argument

### ISSUE THREAD

**Issue by fotol1** [RUCAIBox/RecBole#748]
**Describe the bug**
Hello!

I wanted to explicitly indicate that I don't want to remove duplicates in my dataset. So i put rm_dup_inter = False (if I was attentive, I would put None). I think that "false" is also appropriate if i don't want to remove duplicates. After a long time, I realized that if the value is not None, then it is transferred to the drop_duplicates(... keep=keep). So rm_dup_inter=False means that **all** interactions with duplicates will be deleted. I don't think that this scenario is needed in recommender models. But it's really counterintuitively and hard to debug

https://github.com/RUCAIBox/RecBole/blob/master/recbole/data/dataset/dataset.py#L620

**Comment by hyp1231** [comment]
Thanks for your advice!

Currently, maybe acceptable values of our args are not robust enough. Our development team will talk about it and add more intuitive candidate values.

Before that, please check your arg settings carefully by referring to [Config Settings](https://recbole.io/docs/user_guide/config_settings.html) and [Args for Data](https://recbole.io/docs/user_guide/data/data_args.html).
