### ISSUE TITLE
[💡SUG] 如何使用本框架进行回归预测，希望增加运行样例

### ISSUE THREAD

**Issue by zzzAshui** [RUCAIBox/RecBole#749]
请问如何使用本框架进行回归预测，在文档中似乎没有找到相应的实例，可否添加一个运行样例，谢谢！

**Comment by 2017pxy** [comment]
@zzzAshui 你好，请问你可以提供一个例子具体描述一下你要做的任务吗？

**Comment by zzzAshui** [comment]
> @zzzAshui 你好，请问你可以提供一个例子具体描述一下你要做的任务吗？

比如进行评分预测推荐，已经找到相应的方法了，谢谢回复
