### ISSUE TITLE
[Question] How to prepare data as Session-Based Recommendation settings?

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#766]
I am aware that for the moment sequential models don’t support split ratio and benchmark files.
Therefore, my question is that what’s the workaround for me to achieve the same as general session based or next-item recommendations do.

- Spilt train and test in certain amount or prepared files
- Set whether to use data augmentation in training

For the second setting, is it possible to just comment out the augmentation parts used in data_prepared?

**Comment by 2017pxy** [comment]
@johnny12150 I am sorry to tell you that these two requirements are not supported for our session-based recommendation models either, since our architecture of session-based recommendation models is as same as the sequential models'. In fact, in RecBole we all recognize them as sequential recommendation models.

**Comment by johnny12150** [comment]
Oh! That's unfortunate to hear that. 
Is there any plan to supported the next-item-based recommendation settings?

**Comment by 2017pxy** [comment]
@johnny12150 We will carefully consider about this in near future, thx.

**Comment by johnny12150** [comment]
Is `Set whether to use data augmentation in training` still not available yet?

**Comment by hyp1231** [comment]
> Is `Set whether to use data augmentation in training` still not available yet?

Sorry for the delayed reply.
FYI, an example can be found in [session-based benchmarking](https://github.com/RUCAIBox/RecBole/blob/master/run_example/session_based_rec_example.py), where no data augmentation is performed in RecBole and interactions with preprocessed item sequences are loaded.
