### ISSUE TITLE
Error occurs in custom prediction

### ISSUE THREAD

**Issue by johnny12150** [RUCAIBox/RecBole#767]
> For the first question, we suggest that you can use `pickle` to dump these split data, just like this:
> ```python3
> import pickle
> with open('split_data.pth', 'wb') as f:
>     pickle.dump((train_data, test_data), f)
> ```
> And we added save funtion for split data in #760 recently. You can use `save_split_dataloaders` and `load_split_dataloaders` to save and load split data in the later version.
> 
> For the second question, you can see these code (mainly based on #506):
> ```python3
> import numpy as np
> import torch
> 
> from recbole.data.dataloader.general_dataloader import GeneralFullDataLoader
> from recbole.data.dataloader.sequential_dataloader import SequentialFullDataLoader
> 
> 
> uid_series = np.array([1, 2])
> 
> # We assume you have load test_data and model
> uid_field = test_data.dataset.uid_field
> dataset = test_data.dataset
> model.eval()
> 
> if isinstance(test_data, GeneralFullDataLoader):
>     index = np.isin(test_data.user_df[uid_field].numpy(), uid_series)
>     input_interaction = test_data.user_df[index]
> elif isinstance(test_data, SequentialFullDataLoader):
>     index = np.isin(test_data.uid_list, uid_series)
>     input_interaction = test_data.augmentation(
>         test_data.item_list_index[index], test_data.target_index[index], test_data.item_list_length[index]
>     )
> else:
>     raise NotImplementedError
> 
> # Get scores of all items
> try:
>     scores = model.full_sort_predict(input_interaction)
> except NotImplementedError:
>     input_interaction = input_interaction.repeat(dataset.item_num)
>     input_interaction.update(test_data.get_item_feature().repeat(len(uid_series)))
>     scores = model.predict(input_interaction)
> 
> scores = scores.view(-1, dataset.item_num)  # scores of all item, shape: len(uid_series) * 
> 
> # Get Groud truth interaction
> index = np.isin(test_data.dataset.inter_feat[uid_field].numpy(), uid_series)
> real_inter = test_data.dataset.inter_feat[index]  # the ground truth interaction
> ```
> 
> _Originally posted by @chenyushuo in https://github.com/RUCAIBox/RecBole/discussions/762#discussioncomment-452818_

The snippet above seems to have some bugs and I have mentioned it in the discussion.

**Comment by chenyushuo** [comment]
The argument of `test_data.augmentation` has been updated in #559. We suggest you to use the lastest version of RecBole.
Beside, in RecBole, data augmentation is necessary in the testing phase to generate `input_interaction` for sequential model. And the `interaction` should be a dictionary of `torch.tensors`, you can see this [page](https://recbole.io/docs/user_guide/data/interaction.html) for more infomation about `Interaction`.

**Comment by johnny12150** [comment]
Tks!
Both errors seem to happen on the latest released version on pip.

- interaction should be a dictionary of torch.tensors
- The argument of test_data.augmentation has been updated
