### ISSUE TITLE
[🐛Question] 数据集转换为原子文件的脚本

### ISSUE THREAD

**Issue by N-Kingsley** [RUCAIBox/RecBole#769]
你好，请问数据集转换为原子文件的脚本在哪开源呢

**Comment by hyp1231** [comment]
请参考 [conversion_tools](https://github.com/RUCAIBox/RecSysDatasets/tree/master/conversion_tools)。

**Comment by N-Kingsley** [comment]
下载MIND原子文件后运行如下代码：
python run_recbole.py --model=DIN --dataset=MIND --config_files=test.yaml

test.yaml文件内容如下：
# dataset config
field_separator: "\t"  #指定数据集field的分隔符
seq_separator: " "   #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: item_id #指定物品id域
RATING_FIELD: label   #指定打分rating域
TIME_FIELD: timestamp  #指定时间域

报如下错误：
Traceback (most recent call last):
  File "D:/EvePytorchWins/RecBole/run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "D:\EvePytorchWins\RecBole\recbole\quick_start\quick_start.py", line 43, in run_recbole
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "D:\EvePytorchWins\RecBole\recbole\data\utils.py", line 78, in data_preparation
    built_datasets = dataset.build(es)
  File "D:\EvePytorchWins\RecBole\recbole\data\dataset\sequential_dataset.py", line 145, in build
    return self.leave_one_out(group_by=group_field, leave_one_num=split_args['leave_one_num'])
  File "D:\EvePytorchWins\RecBole\recbole\data\dataset\sequential_dataset.py", line 96, in leave_one_out
    self.prepare_data_augmentation()
  File "D:\EvePytorchWins\RecBole\recbole\data\dataset\sequential_dataset.py", line 68, in prepare_data_augmentation
    self.sort(by=[self.uid_field, self.time_field], ascending=True)
  File "D:\EvePytorchWins\RecBole\recbole\data\dataset\dataset.py", line 1369, in sort
    self.inter_feat.sort(by=by, ascending=ascending)
  File "D:\EvePytorchWins\RecBole\recbole\data\interaction.py", line 293, in sort
    raise ValueError(f'[{b}] is not exist in interaction [{self}].')
ValueError: [timestamp] is not exist in interaction [The batch_size of interaction: 5843444
    user_id, torch.Size([5843444]), cpu, torch.int64
    item_id, torch.Size([5843444]), cpu, torch.int64

].

**Comment by hyp1231** [comment]
推测是没有加载 `timestamp` 这列，请设置参数：
```yaml
load_col:
    inter: [user_id, item_id, label, timestamp]
```

另外，请在运行前仔细对照 [config_settings](https://recbole.io/docs/user_guide/config_settings.html) 和 [data_args](https://recbole.io/docs/user_guide/data/data_args.html) 已确认您希望的运行参数。

**Comment by N-Kingsley** [comment]
感谢您的回答，上述问题均解决。

还想问下模型训练完之后，模型预测部分的数据处理是否有demo呢？

**Comment by 2017pxy** [comment]
@N-Kingsley 你好，我们的数据处理都是统一处理的，处理完毕之后会划分训练，验证，测试三个集合。我不太清楚你说demo是指什么？

**Comment by N-Kingsley** [comment]
模型导出后的使用这一部分，假如要使用该模型预测新的数据集，那么对该数据集如何处理呢。

**Comment by hyp1231** [comment]
> 模型导出后的使用这一部分，假如要使用该模型预测新的数据集，那么对该数据集如何处理呢。

如果是完全崭新的数据集，恐怕是做不到的，因为 user / item 的“数量”以及“ID 映射关系”都会发生改变，需要重新训练模型。

如果是同源的数据集，您也需要确保 User ID 和 Item ID 都在之前的数据集中出现过。

在满足以上条件后，请您参考 API 文档中的 [Benchmark file](https://recbole.io/docs/user_guide/data/data_args.html?highlight=benchmark#benchmark-file)，以及相关讨论 #604 和 #586 。
