### ISSUE TITLE
不从文件中加载数据

### ISSUE THREAD

**Issue by LongBean12138** [RUCAIBox/RecBole#782]
模型使用的数据能不能从网络获取的字节流构建成需要的格式，而不是从文件中读取。

**Comment by 2017pxy** [comment]
@LongBean12138 你好，我们的原子文件对具体的数据来源没有要求，只要最终生成的原子文件符合我们规定的原子文件的数据格式即可，你可以阅读[我们的文档](https://recbole.io/docs/user_guide/data/atomic_files.html)来了解更多关于原子文件的信息。

**Comment by LongBean12138** [comment]
那就是要先保存为原子文件到磁盘上，才能用？

**Comment by 2017pxy** [comment]
@LongBean12138 是的，目前数据导入方式只支持文件读取

**Comment by LongBean12138** [comment]
好的，谢谢！
