### ISSUE TITLE
Config Settings中drop_filter_field参数的含义

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#793]
**drop_filter_field**在[官网文档](https://recbole.io/docs/search.html?q=drop_filter_field&check_keywords=yes&area=default#)中找不到更具体的说明，只在DMF模型中找到下面这段话：
If you set inter_matrix_type='rating', the ‘rating’ field from *.inter atomic files must be remained when loading dataset. It means that ‘rating’ must be appeared in load_col. `Besides, if you use ‘rating’ field to filter the dataset, please set drop_filter_field=False.`

上面说要是要用rating字段对数据集进行过滤，就把它设置为False，但是在[官方博客](https://blog.csdn.net/Turinger_2000/article/details/111878432)的**设置数据集参数**中给出了如下：
```
lowest_val:
    rating: 3
drop_filter_field: True
```
在过滤评分小于3的时候又把drop_filter_field设置为True，所以对改参数的使用有点迷惑，希望您能简单说一下该参数的含义和用法

**Comment by hyp1231** [comment]
您好，抱歉对您造成困惑。

`drop_filter_field` 是一个旧版本[参数](https://recbole.io/docs/v0.1.2/user_guide/data/data_args.html?highlight=drop_filter_field#filter-by-value)，现已被**遗弃**，其功能已经被并入一个新的配置参数 `unused_col`。强烈建议您使用新版本的 `unused_col` 参数，来控制数据处理后、训练前应保留哪些 feature。新参数的文档请参考 [API 文档](https://recbole.io/docs/user_guide/data/data_args.html?highlight=unused_col#selectively-loading)。

另外感谢您指出这个问题，我们会尽快更新过时内容。

**Comment by tsotfsk** [comment]
事实上，在旧版本中，当这一参数设置为true时，表明rating数据只作为过滤域来筛选正样本，过滤结束后，这一列将被drop来避免冗余。而当设置为false时，我们不仅利用其来筛选正样本，还需要其作为context特征输入到模型中，比如在DMF模型中，我们需要使用用户和商品的评分矩阵，那么rating在预处理之后，也应当被保留。

**Comment by 2017pxy** [comment]
@HUE96yhz 你好，我们已经对博客，文档的相关部分进行了修改并更新了；感谢你指出这个问题！
