### ISSUE TITLE
关于RecBole软件包使用RMSE作为evaluate标准的咨询

### ISSUE THREAD

**Issue by BYHu-2** [RUCAIBox/RecBole#796]
RecBole开发团队您好, 我发现对于evaluate matric里面设置有rmse函数, 但是实际修改yaml中的evaluate matric=RMSE会造成报错, 网上也没看到对于类似的部分有对应的解释, 不知道这里的应该怎么设置呢?

**Comment by 2017pxy** [comment]
@BYHu-2 你好，请提供一下你完整的yaml文件，命令行命令（或者run.py文件）以及报错信息，我这边帮你看看。

**Comment by BYHu-2** [comment]
[test.yaml.txt](https://github.com/RUCAIBox/RecBole/files/6268379/test.yaml.txt)

[test.py.txt](https://github.com/RUCAIBox/RecBole/files/6268382/test.py.txt)
![image](https://user-images.githubusercontent.com/78837091/113797183-58b99780-9783-11eb-8dfe-fedfeb7ea071.png)
yaml文件，run.py以及报错信息如上, 不知道是我设置不正确吗?

**Comment by 2017pxy** [comment]
@BYHu-2 我这边测试了一下，没有问题，请问你是用的是哪个版本的RecBole呢？

**Comment by BYHu-2** [comment]
我当时就是pip安装的, pip list里面看起来是recbole=0.2.1这样

**Comment by 2017pxy** [comment]
@BYHu-2 你好，请问你上传的这个test.py.txt是对应你命令行里的那个run_recbole.py吗？

**Comment by tsotfsk** [comment]
目前我们的库还不支持使用RMSE，MAE，LogLoss，AUC等指标使用于全商品评测的场景。因为RMSE常用于评分预测，一般评测样例直接由数据集提供，不依赖于后续采样。如果您要将其用于二分类任务，我们推荐您使用如下设置：
```yaml
metrics: RMSE
valid_metric: RMSE
valid_metric_bigger: False
eval_setting: RO_RS
lowest_val:
  rating: 3
```

**Comment by 2017pxy** [comment]
@BYHu-2 而且我仔细看了一下你的yaml文件，你的`training_neg_sample_num` 是0， 那这样的话模型训练的时候是没有负例的。如果按照你提供的run.py来运行，那么跑的模型是NAIS, 数据集是ml-100k，那是无法进行模型训练的。我这边复现你结果的时候，运行的报错也和你提出的不太一样。请你再明确一下你的运行情况吧

**Comment by BYHu-2** [comment]
好的, 我再试一下能不能正常运行或者复现之前额结果, 麻烦二位了

**Comment by BYHu-2** [comment]
> 目前我们的库还不支持使用RMSE，MAE，LogLoss，AUC等指标使用于全商品评测的场景。因为RMSE常用于评分预测，一般评测样例直接由数据集提供，不依赖于后续采样。如果您要将其用于二分类任务，我们推荐您使用如下设置：
> 
> ```yaml
> metrics: RMSE
> valid_metric: RMSE
> valid_metric_bigger: False
> eval_setting: RO_RS
> lowest_val:
>   rating: 3
> ```
> 
> 此外，希望您暂时使用git clone的方式来使用我们的库，因为我们刚刚修复了一些bug，具体体现在 #797 中。

我现在想评估一下预测的评分和实际评分直接的RMSE, 现在是还暂时不支持吗?

**Comment by BYHu-2** [comment]
> @BYHu-2 而且我仔细看了一下你的yaml文件，你的`training_neg_sample_num` 是0， 那这样的话模型训练的时候是没有负例的。如果按照你提供的run.py来运行，那么跑的模型是NAIS, 数据集是ml-100k，那是无法进行模型训练的。我这边复现你结果的时候，运行的报错也和你提出的不太一样。请你再明确一下你的运行情况吧

[run_recbole.py.txt](https://github.com/RUCAIBox/RecBole/files/6269110/run_recbole.py.txt)
[test.yaml.txt](https://github.com/RUCAIBox/RecBole/files/6269111/test.yaml.txt)
![image](https://user-images.githubusercontent.com/78837091/113813453-82ce8200-97a2-11eb-8838-4c863da38eb7.png)
我重新从服务器上修改了一下, 虽然我之前用的数据集不是ml-100k, 不过现在这样应该可以正常复现了. 不知道您方便再看一下吗?

**Comment by 2017pxy** [comment]
@BYHu-2 你好，这次成功复现了。关于RMSE的计算，其实之前是支持的，但我们发现了一个bug，并在#797中修复了，但目前还没有发布代码包进行更新，所以即便你设置了正确的参数，在v0.2.1上还是无法正常运行的。如果你想计算RMSE，建议拉取我们0.2.x分支上的代码，进行使用。

关于具体的参数设置，如果对于未提供label的数据集（例如ml-100k），基于你提供的yaml文件，首先我们需要将`eval_setting` 中的`full`改成`uniXXX` 或 `popXXX`来进行采样（具体可以参考[文档](https://recbole.io/docs/user_guide/config_settings.html)中对eval_setting的描述），我们目前不支持全部商品的评测。此外，还需要设置`valid_metric_bigger` 为`False`。

希望我的回复对你有帮助，如果有任何问题请在本issue下告知我们，谢谢！

**Comment by BYHu-2** [comment]
好的, 麻烦您了, 我试试看

**Comment by BYHu-2** [comment]
> t
不知道最新的0.2.x分支的代码可以在那里找到呢?

**Comment by BYHu-2** [comment]
您好, 现在rmse已经可以使用了, 不过我发现 Train 和 evaluate 的大小似乎都与我想要的不太一样, 不知道这个可以人为的修改吗?

**Comment by tsotfsk** [comment]
> 您好, 现在rmse已经可以使用了, 不过我发现 Train 和 evaluate 的大小似乎都与我想要的不太一样, 不知道这个可以人为的修改吗?

您指的是 `train_batch_size` 和`eval_batch_size`嘛，这个可以在配置文件里添加的，比如
```yaml
eval_batch_size: 4096
train_batch_size: 2048
```

**Comment by BYHu-2** [comment]
另外可能还想再了解一下, 不知道咱们的代码支持增量训练吗?

**Comment by BYHu-2** [comment]
> > 您好, 现在rmse已经可以使用了, 不过我发现 Train 和 evaluate 的大小似乎都与我想要的不太一样, 不知道这个可以人为的修改吗?
> 
> 您指的是 `train_batch_size` 和`eval_batch_size`嘛，这个可以在配置文件里添加的，比如
> 
> ```yaml
> eval_batch_size: 4096
> train_batch_size: 2048
> ```

train_batch_size 和eval_batch_size我都设置了, 但是看他跑起来的时候似乎并不是按照这个的?
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/78837091/113854303-50884900-97d1-11eb-9d28-1e2a2a6bcc24.png)

**Comment by tsotfsk** [comment]
你的图片似乎并没有显示这一特征，`5196/5196` 表示的 batch_num，并不是batch_size. batch_num * batch_size = data_size

**Comment by BYHu-2** [comment]
哦哦哦, 好的, 那我大概明白了, 感谢您的帮助

**Comment by 2017pxy** [comment]
@BYHu-2 
>另外可能还想再了解一下, 不知道咱们的代码支持增量训练吗?

你好，我们目前不支持增量训练。主要是因为我们会对数据（例如uid，iid）进行remap，新增的数据的remap无法和旧数据的remap保持在同一个映射空间中。关于这个需求，我们之后会考虑。
