### ISSUE TITLE
运行LINE模型报错

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#802]
用ml-1m跑LINE模型出错
![111](https://user-images.githubusercontent.com/53745234/114258661-bad00200-99fa-11eb-9f7c-6e9416799457.png)
但是用ml-100k可以跑，是数据集的问题吗？

**Comment by 2017pxy** [comment]
@HUE96yhz 你好，我们最近注意到了LINE代码的bug并做了修复(#790)，但目前我们还没有更新版本，所以这个bug在v0.2.1的代码包中依然存在，我建议你拉取我们0.2.x分支的代码来运行LINE。
抱歉，为你的工作带来了不便，感谢你的指出。
