### ISSUE TITLE
group_by_user的设置问题

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#804]
在RO_RS这种评估设置下，group_by_user可以是True或False，实验发现其对一些指标比如NDCG会有一些影响，看了下官网，general模型通常需要按用户对数据进行分组并执行否定采样，一般按如下设置：
```
group_by_user: True
training_neg_sample_num: 1
```
那Knowledge-based模型一般怎么设置group_by_user，希望您能简单说明一下。

**Comment by 2017pxy** [comment]
@HUE96yhz 你好，我不太理解你的问题，`group_by_user` 是一个划分的参数设置，和模型具体是什么类型的没有关系。

**Comment by HUE96yhz** [comment]
模型评估阶段对用户进行分组的目的是什么呢

**Comment by tsotfsk** [comment]
> 模型评估阶段对用户进行分组的目的是什么呢

一些topk指标，如NDCG@10，是指为user/session推荐10个商品，观察正样本在其中排名(没有则为0）来衡量模型性能的，对user进行group是必要的操作。

**Comment by 2017pxy** [comment]
@HUE96yhz 你好，你可能不太理解`group_by_user` 这个参数。
`group_by_user`是针对划分的一个参数选项，决定是以用户交互进行划分还是整体数据集进行划分。
举个例子，假设数据集有2个用户，每个用户有5个交互，数据集格式如下：
```
-------
uid iid
-------
1  1
1  2
1  3
1  4
1  5 
2  1
2  2
2  3
2  4
2  5
```
如果设置了按照3:1:1进行数据集划分，那么：
如果`group_by_user` 是 `True`，数据会从用户维度进行划分：
```
--------
uid  iid
--------
train:
1 1
1 2
1 3
2 1
2 2
2 3
valid:
1 4
2 4
test:
1 5
2 5
```
如果`group_by_user` 是 `False`，数据会从整体直接划分：
```
--------
uid  iid
--------
train:
1 1
1 2
1 3
1 4
1 5
2 1
valid:
2 2
2 3
test:
2 4
2 5
```
