### ISSUE TITLE
[💡SUG] topk的选择里面并不支持Context-aware recommendation类型的模型

### ISSUE THREAD

**Issue by stopium** [RUCAIBox/RecBole#807]
我看到/recbole/utils/case_study.py内的full_sort_scores中的代码中，对于读取的General和Sequential的数据具有topk类型的筛选，对于Context-aware类型并不支持。请问是我理解的错误，并不需要；还是确实还未开发。谢谢您。

**Comment by 2017pxy** [comment]
@stopium 你好，其实是支持的。因为我们的sequential dataloader是继承了general dataloader的，所以在执行if语句时会走第一个general dataloader分支。所以我们的case study原则上是四类模型都支持的

**Comment by stopium** [comment]
> @stopium 你好，其实是支持的。因为我们的context-aware dataloader是继承了general dataloader的，所以在执行if语句时会走第一个general dataloader的分支。所以我们的case study原则上是四类模型都支持的

好的，谢谢您。我运行的时候起来了NotImplementedError，可能是我代码的问题我继续细查一下，谢谢您。
