### ISSUE TITLE
[💡SUG] It seems that RecBole can't run on multi-gpu in parallel

### ISSUE THREAD

**Issue by KinvenW** [RUCAIBox/RecBole#815]
I find that RecBole can't run on multi-gpu in parallel, will parallel training be implemented in the future?

**Comment by hyp1231** [comment]
Thanks for your attention. Currently, RecBole has not developed or tested to adapt to distributed training and evaluation. We may add this feature in the future. Track #486 to keep an eye on this.

**Comment by Sherry-XLL** [comment]
Hello @KinvenW, we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the distributed training and evaluation is supported in our framework now. You can refer to our [documentation](https://recbole.io/docs/get_started/distributed_training.html) for more details and running examples.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
