### ISSUE TITLE
Is there a way to use multi behavior interaction data in Context aware/Sequential models?

### ISSUE THREAD

**Issue by khajaphysist** [RUCAIBox/RecBole#817]
Hi,

Thanks for the awesome library. I am working on a model where user has `multiple types of interaction` with items (jobs), for example view, save and apply. And all of these interactions can occur multiple times. Is there any way to use RecBole with such kind of problems? [This](http://staff.ustc.edu.cn/~hexn/papers/icde19-multi-behavior-rec.pdf) is the example paper I am looking at.

**Comment by hyp1231** [comment]
Hi,

It's an interesting question, and I think RecBole can handle this in a context-aware scenario. You can view multi behavior as one hot interaction features, e.g.
```
user_id:token item_id:token view:float save:float apply:save
1             1             1          0          0
1             2             1          1          1
...
```
Then you can implement `calculate_loss` and `predict` interfaces of your own model according to the multi behavior freely.

While for the sequential scenario, it will be more complex. We need to define the multi behavior historical interacted-item sequences and the accordingly data augmentation strategies.

If you are interested in the multi behavior models, you can give a try in a context-aware scenario firstly.

**Comment by khajaphysist** [comment]
@hyp1231 

Thanks for the prompt reply. I am doing something similar, because there are multiple view/save/apply events, I am not sure which of the following strategies works well with Recbole

1. Use one hot encoding and have multiple entries for same user-item pair but with different timestamps

```tsv
user_id:token item_id:token view:float save:float apply:save timestamp:float
1             1             1          0          0          1583049600
1             1             0          1          0          1583059600
1             1             0          0          1          1583069600
1             1             1          0          0          1583079600
...
```

Is it allowed to have multiple entries in `.inter` file with same `user_id` and `item_id` but with different timestamps? if so how is it handled?

2. Group by `user_id` and `item_id` and get counts of each event and latest timestamp of such events

```tsv
user_id:token item_id:token view_count:float save_count:float apply_count:save last_view_timestamp:float ...
1             1             4          2          1          1583049600
1             2             2          1          0          1583059600
2             1             3          2          2          1583069600
2             2             2          0          0          1583079600
...
```

So my questions are
1. Can you please suggest which of the above two ways is more suitable with Recbole?
2. What should be used as label if I want to maximize `apply` for the top k recommendations?

Thanks

**Comment by hyp1231** [comment]
Hi @khajaphysist ,

For the first question, I think the first way is more suitable. We also have some benchmarks in [[RecSysDatasets]](https://github.com/RUCAIBox/RecSysDatasets) having multiple interaction for the same user-item pair.

For the second question, if you just use a regular model, then just set `apply` as label. Otherwise, if you are implementing a new model (where negative sampling is essential), then the column of lablel depends on tome other consideration,

**Comment by khajaphysist** [comment]
Thanks.
