### ISSUE TITLE
Model Types of DIN and DIEN

### ISSUE THREAD

**Issue by KinvenW** [RUCAIBox/RecBole#818]
Firstly, thank you for your efforts to develop such a excellent recommendation library. 
I have some confusions about model taxonomy.  In [API doc](https://recbole.io/docs/user_guide/model_intro.html) of RecBole, both DIN and DIEN are classified into context-aware model, while in source codes both they are placed in sequential model. I think the reasonable taxonomy is: DIN belongs to context-aware model, and DIEN belongs to sequential model.

**Comment by guijiql** [comment]
Hello, Kinven. Both DIN and DIEN are special context-aware models. They utilize users' and items' features. So they are classified into context-aware model in the API doc.  In my opinion, we can regard users' interaction seuquence as a kind of context. However, they must use the data input format of sequential models to get users' interaction sequence, so they inherit the ``SequentialRecommender``. In consequence, they are placed in sequential model in source code.

**Comment by KinvenW** [comment]
@guijiql Thanks, I've figured out that. In addition to inheriting the SequentialRecommender, DIN also uses SequentialDataLoader and SequentialDataset to facilitate sequential data processing.
