### ISSUE TITLE
[🐛BUG] InterestExtractorNetwork of DIEN lacks a dense layer

### ISSUE THREAD

**Issue by KinvenW** [RUCAIBox/RecBole#821]
**InterestExtractorNetwork** contains a **auxiliary_net** to calculate **_click_prop_** and **_noclick_prop_** so as to calculae auxiliary loss, however, auxiliary_net is a MLPLayers which output dim != 1, I thought we should add a output layer after auxiliary_net to  transform dimension **[output_dim of auxiliary_net → 1]**

**Comment by guijiql** [comment]
Oh, sorry. It's my negligence. I' ll fix it soon. Thank for your reminding!

**Comment by 2017pxy** [comment]
@KinvenW Hi, the bug has been fixed in #824, thanks for your correction.
