### ISSUE TITLE
[🐛BUG] The values of dataset.field2id_token and dataset.field2token_id are not the same in Knowledge based models. 

### ISSUE THREAD

**Issue by russellkim** [RUCAIBox/RecBole#823]
**Describe the bug:**

The values of dataset.field2id_token and dataset.field2token_id are not the same in Knowledge-based models. 

**To Reproduce:**

I inserted the following debug message code in the run_recbole to check the reason of the bug. 
https://github.com/RUCAIBox/RecBole/blob/152358e570c05826c63e3308bd627c08f2d5f80f/recbole/quick_start/quick_start.py#L39
```
    # dataset filtering
    dataset = create_dataset(config)
    logger.info(dataset)

    #! insert debug message
    print('tr dataset.field2id_token=', len(dataset.field2id_token['item_id']))
    print('tr dataset.field2token_id=', len(dataset.field2token_id['item_id']))
```
I trained KGCN model ( other KG-based model also has the same errors )
`python run_recbole.py --model=KGCN`

**Expected behavior:**

I expected dataset.field2id_token and dataset.field2id_token are the same. 
However, it shows two dictionary length is not the same. 
**It makes errors when we call dataset.id2token().** 

```
tr dataset.field2id_token= 1683
tr dataset.field2token_id= 34713

```

When I train/test sequential models, the values of dataset.field2id_token and dataset.field2token_id are the same.

**Comment by chenyushuo** [comment]
Thanks for your bug report. We have fix this bug in #825.

**Comment by russellkim** [comment]
@chenyushuo Thank you for quick path!

However, the relevant problem has not resolved. 

We can copyy ml-100k.inter to ml-100k.test to make query(ml-100k.test) for testing model.full_sort_predict(). 

We have several problems to do that as follows ( line number may be not the same because of my code):

**(problem 1)**

```
  File "~/RecBole/recbole/data/dataset/dataset.py", line 1072, in id2token     
    return self.field2id_token[field][ids]
TypeError: only integer tensors of a single element can be converted to an index

```

When config['MODEL_TYPE'] is ModelType.SEQUENTIAL, we can use list of tensor.  
However, it requires single element. 

**(problem 2)** 

So, I query an id from the model prdedicdion result for id2token one by one, but I got "IndexError: list index out of range". 

```
    j = dataset.id2token(dataset.iid_field, int(i))
  File "~/RecBole/recbole/data/dataset/dataset.py", line 1077, in id2token
    raise ValueError(f'[{ids}] is not a valid ids.')
ValueError: [2591] is not a valid ids.
```

Thanks.

**Comment by chenyushuo** [comment]
@russellkim 
About problem 1, for `dataset.id2token`, we didn't require that the `ids` must be a single element, it can be a list, `numpy.array` or `torch.tensor`. In fact, the type of `dataset.field2id_token[field]` is `numpy.ndarray`.
![image](https://user-images.githubusercontent.com/31039063/117563274-4ced2800-b0d7-11eb-9c54-dc70981cf471.png)

About problem 2, there are only 1683 items in ml-100k dataset, so it is clear that 2591 is not a valid ids.
![image](https://user-images.githubusercontent.com/31039063/117563424-5925b500-b0d8-11eb-9c3b-918c7e4ad709.png)

**Comment by russellkim** [comment]
@chenyushuo Thank you for your reply despite it's Sunday. 

About problem 1, the list that I used is from the KGCN algorithm. 
If I just replace the model name with BERT4Rec, it doesn't generate any errors. 

About problem 2, the id(2591) was generated from the KGCN algorithm. 
So, it's strange.  I suspect the cause is dataset.field2id_token() or the algorithm.

**Comment by chenyushuo** [comment]
@russellkim 
It seems that the id(2591) is an entity id but not an item id. Could you please provide your code so that we can check if there is any bug?

**Comment by russellkim** [comment]
@chenyushuo Thank you for your attention.

I uploaded my test script and test data. 

After unziping the file, copy theses files as follows:
~/RecBole/dataset/ml-100k/ml-100k.test
~/RecBole/test_predict.py

You can test each model
```
#  non-KG based model
python test_predict.py --model=KGCN

```
```
# KG based model
python test_predict.py --model=KGCN
```

I got the following errors while executing the script with KGCN.

```
Traceback (most recent call last):
  File "~/RecBole/recbole/data/dataset/dataset.py", line 1072, in id2token
    return self.field2id_token[field][ids]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_predict.py", line 258, in <module>
    train_test(args, config_dict)
  File "test_predict.py", line 231, in train_test
    nCorrect, nTotal = predict_test(model, dataset, config, GT, topk=10)
  File "test_predict.py", line 184, in predict_test
    j = dataset.id2token(dataset.iid_field, int(i))
  File "~/RecBole/recbole/data/dataset/dataset.py", line 1077, in id2token
    raise ValueError(f'[{ids}] is not a valid ids.')
ValueError: [2485] is not a valid ids.
```
[test_predict.zip](https://github.com/RUCAIBox/RecBole/files/6453363/test_predict.zip)

**Comment by chenyushuo** [comment]
@russellkim 
Thanks for your code. 
We fixed a type error in `KnowledgeBasedDataset` (#831), which will fix problem 1.
For problem 2, you need to change the shape of `scores` in line 169 like this
![2021-05-12 17-38-47 的屏幕截图](https://user-images.githubusercontent.com/31039063/117954149-4fef4f00-b349-11eb-88b6-0f9d81e99e68.png)
Now you can run your code in KGCN algorithm. We also uploaded the fixed code.
[fixed_test_predict.zip](https://github.com/RUCAIBox/RecBole/files/6465207/fixed_test_predict.zip)

**Comment by russellkim** [comment]
@chenyushuo Thanks for your kind and hard work! I appreciate it.
