### ISSUE TITLE
[🐛BUG] FPMC-使用Amozon-books时RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by BelliumTang** [RUCAIBox/RecBole#829]
**描述这个 bug**
RuntimeError: CUDA out of memory. Tried to allocate 980.00 MiB (GPU 0; 10.91 GiB total capacity; 9.35 GiB already allocated; 168.19 MiB free; 10.05 GiB reserved in total by PyTorch)

**如何复现**
复现这个 bug 的步骤：
**yaml 文件**
gpu_id : 1
use_gpu : True

**model config**
embedding_size: 32

**dataset config**
field_separator: "\t"  #指定数据集field的分隔符
seq_separator: " "   #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: item_id #指定物品id域
RATING_FIELD: rating   #指定打分rating域
TIME_FIELD: timestamp  #指定时间域
NEG_PREFIX: neg_   #指定负采样前缀
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列
load_col:
  inter: [user_id, item_id, rating, timestamp]

**training settings**
epochs: 20  #训练的最大轮数
train_batch_size: 16 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 1 #负采样数目
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

**evalution settings**
eval_setting: TO_LS,full #对数据随机重排，设置按比例划分数据集，且使用全排序
group_by_user: True #是否将一个user的记录划到一个组里，当eval_setting使用RO_RS的时候该项必须是True
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准
topk: [20] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: MRR@20 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 16 #评测的batch_size

**预期**
数据集使用的是官方提供的
想问下是因为数据集过大导致的吗？
batchsize已经设置为32，按道理GPU显存不应该爆炸
GPU是nvidia 2080

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）
![image](https://user-images.githubusercontent.com/37737197/117635161-22bc6880-b1b2-11eb-83e5-b6262912f61e.png)

**链接**
添加能够复现 bug 的代码链接，如 Colab 或者其他在线 Jupyter 平台。（可选）

**实验环境（请补全下列信息）：**
 - 操作系统:  Linux
- RecBole 版本 0.2.1
 - Python 版本 3.6
- PyTorch 版本 1.8.1
- cudatoolkit 版本 9.2

**Comment by ShanleiMu** [comment]
请问运行的哪一个模型？应该是数据集过大，用户或物品数太大导致模型参数占满了显存。推荐进行一下K-core等过滤数据集的操作。

**Comment by BelliumTang** [comment]
运行的是FPMS，使用的是官方提供的数据集
非常感谢！

**Comment by ShanleiMu** [comment]
不客气，请问是FPMC吗

**Comment by BelliumTang** [comment]
sorry,心急把名字打错了 
对，是FPMC
