### ISSUE TITLE
LightGCN model,使用 GPU训练， GPU模式下加载预测报错， CPU模式下加载预测正常

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#834]
**Describe the bug**

**To Reproduce**
1. extra yaml file
2. your code
3. script for running

**Expected behavior**

**Screenshots**

**Colab Links**
If applicable, add links to Colab or other Jupyter laboratory platforms that can reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS or Windows]
- RecBole Version [e.g. 0.1.0]
 - Python Version [e.g. 3.79]
- PyTorch Version [e.g. 1.60]
- cudatoolkit Version [e.g. 9.2, none]

**Comment by chenyushuo** [comment]
能否提供一下报错信息，以及yaml文件

**Comment by dxjjhm** [comment]
Traceback (most recent call last):
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/home/cbgrdd/anaconda3/envs/pytorch/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "lightgcnSDYD.py", line 60, in predict
    topk_score, topk_iid_list = full_sort_topk(uid_series, lightgcn_model, test_data, 10)
  File "/data/home/cbgrdd/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/utils/case_study.py", line 87, in full_sort_topk
    scores = full_sort_scores(uid_series, model, test_data)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/utils/case_study.py", line 45, in full_sort_scores
    history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
CUDA: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/build/aten/src/ATen/CUDAType.cpp:2983 [kernel]
QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/autograd/generated/TraceType_2.cpp:9654 [kernel]
Autocast: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/ATen/autocast_mode.cpp:258 [kernel]
Batched: registered at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

**Comment by dxjjhm** [comment]
使用GPU训练，然后GPU加载预测，就会爆出如上错误，改成CPU加载并预测没有错误。

**Comment by chenyushuo** [comment]
> File "/data/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/recbole-0.2.1-py3.7.egg/recbole/utils/case_study.py", line 45, in full_sort_scores
> history_row = torch.cat([torch.full_like(hist_iid, i) for i, hist_iid in enumerate(history_item)])

你这个报错看上去是因为`history_item`是一个空数组导致的，能否检查一下`full_sort_scores`函数中的`uid_series`和`test_data.uid2history_item`的情况，或者提供更多的输入信息以便我们检查？

**Comment by dxjjhm** [comment]
但是问题是，切换到cpu模式就没有问题

**Comment by 2017pxy** [comment]
@dxjjhm 你好，你提供的信息非常有限，我们无法进行bug复现，请你提供完整代码和必要的复现信息

**Comment by zrg1993** [comment]
I got the same error.  I only add "_repeatable: True_" to the `knowledge_base.yaml` file in `./recbole/properties/quick_start_config/`, and run KGAT model.

**Comment by Sherry-XLL** [comment]
@zrg1993 Hello, I modify the `knowledge_base.yaml` file and run KGAT model on the GPU with the command `python run_recbole.py --model=KGAT`, but there is no error. Could you please provide complete error reporting information?

**Comment by zrg1993** [comment]
I found that this error happened when one item only have one interation with one user in the dataset. So I think this case results into a error in train/test splitting. Please have a try on adding one new item to the `ml-100k.item` and one <user, the new item>  row into `ml-100k.inter`. And run the` case_study.py` on the new item with any user, you will find the error.
