### ISSUE TITLE
请问用recbole里的算法无法达到论文里的效果，一般是什么情况？

### ISSUE THREAD

**Issue by ZhangShuwenV** [RUCAIBox/RecBole#839]
![image](https://user-images.githubusercontent.com/58580563/120320060-52bfdd00-c314-11eb-8444-4a68fff6bad9.png)
论文里的效果如图片所示，但是我用recbole跑论文的数据集，比论文里的效果低了20%左右，请问一般是什么情况呢

**Comment by 2017pxy** [comment]
@ZhangShuwenV 你好，在推荐系统领域，实验结果往往受到很多因素的影响，要想完全复现论文实验结果其实是需要考虑很多因素的。

首先，数据集预处理方式和划分方式就会影响实验结果；其次，不同的评测方式也会导致结果的差异，例如使用全排序评测(full)和采样评测（uni100, pop100），结果就会不同；同时，还要考虑运行环境的问题，比如深度学习框架的种类和版本，服务器硬件情况等。

此外，最关键的是，你是否进行了调参，或完全按照原论文的模型参数进行了复现。例如学习率，embedding size，训练时的batch size等参数，对于某些对参数较为敏感的模型和数据集，不同的参数也会对结果造成较大影响。

BTW，我们的在实现论文模型时，首先会比对论文源码（如果源码公开），并在发布前进行多个数据集上的内部测试，以保证我们的模型结果和原论文中的实验结果不会有太大差异。在经过一系列检查和测试后，我们才会上线模型，所以我们的代码质量是有一定保证的。如果你在实验时，在保证了大部分因素和原论文一致的情况下，依然发现实验结果差异很大，或者直接发现了我们模型代码中的bug，欢迎你通过issue或pr向我们进行反馈，谢谢！

**Comment by ZhangShuwenV** [comment]
感谢您的解答，我再去细看下论文。
