### ISSUE TITLE
模型使用疑问

### ISSUE THREAD

**Issue by 118988577** [RUCAIBox/RecBole#841]
你好我在使用widedeep模型跑adult数据集，总是出现user_id key Error,由于adult数据集没有user_id,和item_id的字段，那我如何解决这个问题呢？望解答，谢谢

**Comment by hyp1231** [comment]
您好，请问可以提供一下运行的 `.yaml` 参数设定文件吗？

**Comment by 118988577** [comment]
> 您好，请问可以提供一下运行的 `.yaml` 参数设定文件吗？
因为我看的您给的例子是用ml-100k这个数据集，它有use_id，但我想跑的数据集没有这个字段，所以我想了解对于数据集只有单个.inter文件，并且也没有use_id和item_id的数据集例如adult 和criteo，是否可以在Context-aware 类的模型上跑，如果可以跑，这类数据集的参数改如何设置呢？谢谢

**Comment by 118988577** [comment]
> 您好，请问可以提供一下运行的 `.yaml` 参数设定文件吗？
您好，请问可以提供一下运行的 .yaml 参数设定文件吗？
因为我看的您给的例子是用ml-100k这个数据集，它有use_id，但我想跑的数据集没有这个字段，所以我想了解对于数据集只有单个.inter文件，并且也没有use_id和item_id的数据集例如adult 和criteo，是否可以在Context-aware 类的模型上跑，如果可以跑，这类数据集的参数改如何设置呢？谢谢

**Comment by hyp1231** [comment]
您好，对于没有 user id 和 item id 的数据集，依然是可以运行 Context-aware 类的模型的。
由于参数默认设置了 `USER_ID_FIELD` 和 `ITEM_ID_FIELD` 的值，当我们需要跑 adult 和 criteo 这种数据集时，需要手动把相关参数设置为空。

您可以在您提供的参数设定文件中加入下述几行：
```yaml
USER_ID_FIELD: ~
ITEM_ID_FIELD: ~
min_user_inter_num: ~
min_item_inter_num: ~
```

顺便说一下，对于这种有很多需要加载的列的数据集，可以通过如下写法，加载全部 .inter 特征：
```yaml
load_col:
    inter: '*'
```

经测试可以运行成功，您可以在此基础上继续进行特征筛选 / 处理，调整超参数，以测试效果。希望上述回复可以帮到您。
