### ISSUE TITLE
[💡SUG] 测试集能移除用户已经消费过（已经点击过的）的物品吗

### ISSUE THREAD

**Issue by zhangyichi1Z** [RUCAIBox/RecBole#842]
感谢你们的工作。
但是我遇到以下问题：
     （1）测试集能移除用户已经消费过（已经点击过的）的物品吗
              我没有在文档中找到相关说明

**Comment by linzihan-backforward** [comment]
您好。目前在我们的实现中，测试集默认会移除用户在训练集和验证集点击过的商品，即进行不重复推荐的任务

**Comment by zhangyichi1Z** [comment]
> 您好。目前在我们的实现中，测试集默认会移除用户在训练集和验证集点击过的商品，即进行不重复推荐的任务

感谢您的回答。
