### ISSUE TITLE
验证集的指标低于测试集跑了几种模型都是这样，符合预期吗？

### ISSUE THREAD

**Issue by lhz-97** [RUCAIBox/RecBole#843]
如题，正常不应该验证集socre高于测试集吗，在ml-100k和ml-1m上分别跑了BPR、LightGCN模型发现 测试集 score更高？这是为什么呀？
感谢开源，orz

**Comment by hyp1231** [comment]
您好，简要地说是因为测试集上不会评测已经在训练/验证集中出现过的 user-item 交互，具体的讨论可以参考 #623。

**Comment by lhz-97** [comment]
thx
