### ISSUE TITLE
[🐛BUG] split 改成[0.7,0.1,0.2]之后NDCG 和hit、mrr，recall都涨了。

### ISSUE THREAD

**Issue by lhz-97** [RUCAIBox/RecBole#845]
就默认数据集默认模型就可以get到。

**Comment by 2017pxy** [comment]
@lhz-97 你好，请问指标涨的明显吗？一般来说，更改数据集划分方式后，指标是会发生变化的

**Comment by lhz-97** [comment]
ml-100k上 看起来涨了60%   改成[0.5,0.1,0.4]之后又涨，这个split比例是对于每一个用户的所有action分类的吗？不是用总体数据集做的split

**Comment by 2017pxy** [comment]
@lhz-97 是的，我们的数据划分是针对每个用户的交互进行划分的，不是总体数据划分。关于你反映的问题，我们再检查一下，感谢反馈！

**Comment by hyp1231** [comment]
不同数据划分之间，指标具体数值的比较可能不太具备实际含义。评测的 user-item 不同，相当于不同的测试集。
