### ISSUE TITLE
OOV issues

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#846]
Have the OOV issues of items and entities been considered during the construction of the knowledge graph data set

**Comment by HUE96yhz** [comment]
By the way, there is also the quantification of the weight of the edge when constructing the knowledge subgraph between the recommender system data set and the Freebase knowledge graph

**Comment by ShanleiMu** [comment]
@HUE96yhz How to understand the OOV issue you mentioned? Can you provide an example? Do you mean that there is an item in recsys data but are no corresponding KG entities in KG data?

**Comment by HUE96yhz** [comment]
Yes, that's what you said！

**Comment by HUE96yhz** [comment]
@ShanleiMu I'm sorry I didn't make it clear what the problem is？
The question I want to ask is exactly what you said at the end . 
“there is an item in recsys data but are no corresponding KG entities in KG data”

**Comment by ShanleiMu** [comment]
In this case, you can still run these knowledge-aware recommendation models successfully in RecBole, because our implementations only utilize the KG information that exists in the data.
But this may damage the model performance, due to the lack of corresponding KG information.

**Comment by HUE96yhz** [comment]
@ShanleiMu Sorry to bother you again！
I have seen that in the paper of KGAT: “To ensure the KG quality, we then preprocess the three KG parts by filtering out infrequent entities (i.e., lowever than 10 in both datasets) and retaining the relations appearing in at least 50 triplets.”
Whether the knowledge graph dataset in the RecsysDataSets also has related processing operations？
Is there any additional processing for the knowledge graph dataset (.kg file) built using conversion_tools in the RecsysDataset project?Or just follow the KB4Rec project

**Comment by ShanleiMu** [comment]
@HUE96yhz Hi, plz refer to https://github.com/RUCAIBox/RecSysDatasets/issues/93.

**Comment by Sherry-XLL** [comment]
Hello @HUE96yhz , we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the data filtering of knowledge graph is supported in our framework now. You can refer to our [documentation](https://recbole.io/docs/user_guide/config/data_settings.html) and #1342 for more details.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
