### ISSUE TITLE
关于跑自己搭建的模型的问题

### ISSUE THREAD

**Issue by WenrouM** [RUCAIBox/RecBole#858]
您好!
我想请教一下您，如果是需要在自己搭建的模型里使用recbole里的自动调参工具，应该怎么改动呢，有没有什么具体的文档呢？
非常感谢您的帮助!

**Comment by hyp1231** [comment]
您好，如果您是在 RecBole 框架内开发了模型，则可以参考 [文档](https://recbole.io/docs/user_guide/usage/parameter_tuning.html) 进行自动调参。
