### ISSUE TITLE
[💡Question] 只有物品的特征数据没有用户的特征数据，是否可以运行ContextAware的算法

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#866]
在真实场景中，我们只有用户的id信息，没有用户的年龄，性别，等其他额外的信息。
对于物品我们有类别，小标签等属性数据。
这种情况下是否可以运行ContextAware的算法，效果是否可行？

**Comment by hyp1231** [comment]
您好，可以的，可以参考 https://github.com/RUCAIBox/RecBole/issues/841#issuecomment-858550865。
