### ISSUE TITLE
预训练的原子文件怎么获得

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecBole#880]
代码小白一个，在此想问下各位大佬如何获得RecBole文档中提到的`.ent`原子文件。例如文档中举例的`pretrained entity embeddings`。我能否在RecBole提供的代码中得到预训练的嵌入向量，还是说我得自己使用一种knowledge graph embedding来先得到实体的嵌入向量，但是这样又要怎么转换成.ent这样的原子文件。这个问题主要是我注意到RecBole提供了GRU4RecKG代码，想加上KGE跑跑试试，但是不太清楚怎么弄预训练好的向量。
最后顺便吐槽下博客“一直丑颜狗”大佬的小白入门系列断更了，难受的呀批呀。

**Comment by 2017pxy** [comment]
@HUE96yhz 你好，`.ent`文件是需要用户自己提供的；目前在我们的提供的数据集中，MovieLens，Amazon-book和LFM-1b是提供了处理好的`.ent`文件的，如果你想试用，可以在我们的百度网盘中进行下载。关于如何自己构造`.ent`，你可以参考[KB4Rec](https://github.com/RUCDM/KB4Rec) 这个项目。

关于中文博客，因为我们前一段时间比较忙，所以博客后续没有进行更新，对此非常抱歉。最近一段时间我们的团队正在进行一次的较大的代码重构工作，等新版本发布后，我们会将新特性加入到现有的“小白入门系列”中，同时也会考虑出更多的系列来帮助用户了解和使用伯乐。

最后，感谢你对我们项目的关注和支持！

**Comment by HUE96yhz** [comment]
非常感谢您的回答，但是我在`RecSysDatasets`项目提供的网盘里并没有找到`.ent`文件。网盘里`RecBole`文件夹下的`KGDatasets`和`ProcessedDatasets`这两个子文件夹内都没有找到。

**Comment by 2017pxy** [comment]
@HUE96yhz 不好意思，我没说清楚，你需要先下载KGDatasets/下面的数据集，然后使用我们的转换工具进行转换，详细的操作流程请见[MovieLens_KG](https://github.com/RUCAIBox/RecSysDatasets/blob/master/conversion_tools/usage/MovieLens-KG.md)。

**Comment by 2017pxy** [comment]
@HUE96yhz 此外，不好意思，我误解了你的问题，我以为你需要的是`.kg`文件, 我之前的回答都是针对`.kg`文件的。

对于`.ent`文件，是需要用户自己提供的，我们没有给出相对应的例子。至于如何转换成原子文件，其实原子文件的格式类似`.tsv`文件，你可以参考其他类型的原子文件，我认为还是比较容易手动处理的。

希望我的补充对你有帮助！

**Comment by HUE96yhz** [comment]
非常感谢
