### ISSUE TITLE
[💡SUG] Record hyperparameters by tensorboard

### ISSUE THREAD

**Issue by tsotfsk** [RUCAIBox/RecBole#884]
Add a set of hyperparameters to be compared in TensorBoard which will help users better tune the hyperparameters.
```python
from torch.utils.tensorboard import SummaryWriter
with SummaryWriter() as w:
    w.add_hparams({'lr': 0.01, 'bsize': 1024},
                  {'hparam/accuracy': 10, 'hparam/loss': 10})
```

For more details please refer to [tensorboard](https://pytorch.org/docs/stable/tensorboard.html).

**Comment by ChangxinTian** [comment]
Thanks for your suggestion, we will add it as soon as possible

**Comment by 2017pxy** [comment]
Hi, thx for your suggestion and this feature has been added in #887 .
