### ISSUE TITLE
[🐛BUG] evaluators torch.cat((topk_idx, shape_matrix), dim=1) GPU环境报错

### ISSUE THREAD

**Issue by transposition** [RUCAIBox/RecBole#889]
**描述这个 bug**

CPU 可以正常跑，但GPU 环境会报错
recbole/evaluator/evaluators.py", line 77, in collect
    result = torch.cat((topk_idx, shape_matrix), dim=1)
RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'

**预期**

原始代码：
ape_matrix = torch.full((len(user_len_list), 1), scores_matrix.shape[1], device=scores_matrix.device)
可以改成：
shape_matrix = torch.full((len(user_len_list), 1), scores_matrix.shape[1], device=scores_matrix.device,
                                  dtype=torch.long)

**实验环境（请补全下列信息）：**
 - 操作系统: Linux
- RecBole latest
 - Python 3.6
- PyTorch 1.2.0
- cudatoolkit 10.0

**Comment by 2017pxy** [comment]
@transposition 你好，请提供完整的代码，yaml文件以及命令行指令，我这边帮你看一下

**Comment by transposition** [comment]
> @transposition 你好，请提供完整的代码，yaml文件以及命令行指令，我这边帮你看一下

不好意思哈，数据有点敏感，暂时不方便提供哈，我加上dtype=torch.long，就可以正常跑起来了

这是 yaml
`
# model config
embedding_size: 32
# dataset config
field_separator: "\t"  #指定数据集field的分隔符
seq_separator: "-"   #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: poi_id #指定物品id域
RATING_FIELD: ~   #指定打分rating域
TIME_FIELD: order_timestamp  #指定时间域
NEG_PREFIX: neg_   #指定负采样前缀
LABEL_FIELD: buy

rm_dup_inter: ~ #

unused_col:
  inter: [order_timestamp]
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列
load_col:
  inter: '*'
  item: '*'
  user: '*'

# training settings
epochs: 50  #训练的最大轮数
train_batch_size: 2048 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
training_neg_sample_num: 3 #每一个正样本，采样的负样本数目
eval_step: 1 #每训练x次后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了

# evalution settings
#eval_setting: RO_RS,full #对数据随机重排，设置按比例划分数据集，且使用全排序
eval_setting: TO_RS,full #对数据根据TIME_FIELD重排，设置按比例划分数据集，且使用全排序，TO_LO 留N out,N 为 leave_one_num


group_by_user: True #是否将一个user的记录划到一个组里，当eval_setting使用RO_RS的时候该项必须是True
split_ratio: [0.8,0.1,0.1] #切分比例
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] #评测标准
topk: [5] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: Hit@5 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size`

**Comment by 2017pxy** [comment]
@transposition 我大概猜到是哪里的问题了，我怀疑是torch版本的问题，请检查一下你的torch版本是否>=1.7.0; 

此外，下次反馈请提供一下你的命令行信息，我现在都没法知道你运行的是哪个模型，无法进行bug的复现

**Comment by transposition** [comment]
> @transposition 我大概猜到是哪里的问题了，我怀疑是torch版本的问题，请检查一下你的torch版本是否>=1.7.0;
> 
> 此外，下次反馈请提供一下你的命令行信息，我现在都没法知道你运行的是哪个模型，无法进行bug的复现

嗯嗯，这次仓促了，感谢解答，PyTorch 确实还是 1.2.0的老版本。期待你们说的重构，可以早点用上预测功能
