### ISSUE TITLE
How to prepare new batch data?

### ISSUE THREAD

**Issue by abstrcode** [RUCAIBox/RecBole#893]
Currently, training/validation/test data are prepared in advance. I wonder how to prepare streaming data? For example, we have a new batch raw data, how to process this?

**Comment by 2017pxy** [comment]
@abstrcode Hi, in fact, RecBole will firstly load the raw data from [Atomic Files](https://recbole.io/docs/user_guide/data/atomic_files.html), and then the data will be splitted into training/validation/test part automatically. So I think you can firstlly convert your data into atomic files and then you can load your own data and run models in RecBole.

**Comment by abstrcode** [comment]
@2017pxy Is it possible to do this for online streaming data?

**Comment by 2017pxy** [comment]
@abstrcode No. Since RecBole is designed only for scientific research or algorithm competitons, currently it does not support online scenes.
