### ISSUE TITLE
[💡question]  两个数据集，D1和D2 我用D1训好之后AUC大概0.7，在D2上测试，AUC只有0.5，感觉是idx没有对齐

### ISSUE THREAD

**Issue by lhz-97** [RUCAIBox/RecBole#899]
D2数据集和D1的不完全一样。会有一些新的item/user。
两个数据集是对齐的。
我猜数据集load到model里，dataset 会重新把user_id和item_id编码？然后导致两个数据集id 有gap？
感谢🙏

**Comment by 2017pxy** [comment]
@lhz-97 你好，是的，我们会对数据进行remap，id会重新映射，如果数据没有完全对齐，那么一定会有gap；而且你这种使用方法也是我们不提倡的，因为不同数据集之间可能会有很大差异，特别是不同domain的；如果你想在D1上训练然后在D2上测试，可以尝试使用`benchmark_filename`的方式来导入数据，将D1全部设置为训练集，D2设置为测试集，详见[文档](https://recbole.io/docs/user_guide/data/data_args.html)

**Comment by lhz-97** [comment]
了然了，谢谢
