### ISSUE TITLE
[🐛BUG] 使用 RecBole 的 API 运行程序，终端上输出的日志没有颜色

### ISSUE THREAD

**Issue by DuckDuckBug** [RUCAIBox/RecBole#905]
我参照着 https://blog.csdn.net/Turinger_2000/article/details/110414642 上面的教程，从 api 上手 recbole，但是发现这样使用的话，终端上的日志信息是没有颜色的（而使用源码跑程序，终端上的日志是有颜色的），请问有什么解决的方法吗？

![image](https://user-images.githubusercontent.com/33098939/126939105-aba13e15-b112-4523-a771-52be9ac5ac72.png)
![image](https://user-images.githubusercontent.com/33098939/126939242-63cb5fa8-236d-4a7d-8a97-e6f102e2208a.png)

**Comment by hyp1231** [comment]
您好，我通过 pip 安装了 `recbole==0.2.1` 版本，然后运行了样例程序，没能复现出 log 无颜色的问题。

您可以通过 `conda list` 命令，检查一下当前环境下 recbole 的版本。

<img width="758" alt="WX20210726-181402@2x" src="https://user-images.githubusercontent.com/29252610/126973147-49eb5bab-0db3-41b2-a089-f6793cefd6aa.png">

**Comment by DuckDuckBug** [comment]
谢谢，目前问题已经解决。我当时用`conda install -c aibox recbole`命令安装的，版本是 0.2.0，现在我改成了 0.2.1，就没有出现这个问题了。
