### ISSUE TITLE
Session Based Recommendation 

### ISSUE THREAD

**Issue by laxmikant-igp** [RUCAIBox/RecBole#921]
Hi,
I have only three features `session_id, clicked_item, timestamp` and based on these I want to train my model, thereafter, I want to predict next items for new session_id on given list of clicked items. The new session id is not seen by the model yet.

Can anyone suggest me which algorithm I should use? A headstart would be really very helpful.

**Comment by hyp1231** [comment]
Hi, you can try GRU4Rec, NARM, SASRec firstly, which are broadly used session-based recommendation models.
Moreover, you can also test STAMP, SR-GNN, GCSAN on your dataset, which may be a bit time consuming but may also have good performance.

Details about these models can be found in [Model List](https://recbole.io/model_list.html). Good luck!
