### ISSUE TITLE
config gpu_id not works.

### ISSUE THREAD

**Issue by rowedenny** [RUCAIBox/RecBole#925]
It seems that even if I specify gpu_id with the command line, the model is always trained with GPU-0. 
Am I the only one who has this issue?

**Comment by hyp1231** [comment]
Hi, could you please provide your running command line, as well as the first dozens of RecBole's logs?

**Comment by rowedenny** [comment]
Sure. So what I did shows as following,
1) I train a model with default gpu_id,
```
python run_model.py --dataset=taobao --model=HHyperRec
```

and gpu utility is 
![image](https://user-images.githubusercontent.com/29630980/129136909-22109af0-7385-4e04-b143-60dea757ec12.png)

2) Then I train another model specifying the gpu_id as 1
```
python run_model.py --model=HHyperRec --dataset=taobao --gpu_id=1
```

and then the gpu utility is 
![image](https://user-images.githubusercontent.com/29630980/129137101-d29abf0c-dd2a-4f56-94e8-08cda22ff709.png)

I am not sure if this could be related to training a customized model.

**Comment by rowedenny** [comment]
Sorry for the late response. 
I have tried the suggestion one and it seems the gpu_id assigned is correct, but it still does not work.
I also tried to use `CUDA_VISIBLE_DEVICES` to specify the device and it works. 

So it is unclear to hard to figure out what causes this issue right now, I would suggest closing this issue and see if other users also witness this and collect more evidence.

**Comment by rowedenny** [comment]
I think I somehow figure out the reason, and here it is:
For the sequential models, we have no direct way to specify the gpu device. Following [current implementation ](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/sequential_recommender/fdsa.py#L46), we can do as `self.device = config['device']`. However as far as I have observed, it will always assign gpu_id=0 as `self.device`, and even if we use `--gpu_id=1` in the command line, it will not help.

Please let me know if you also witness this issue.
Thanks.

**Comment by ThomasEKolb** [comment]
Hello @rowedenny! I had the same problem with Bert4Rec. I fixed it by applying the code of this post (https://stackoverflow.com/a/60158779) in the beginning of the script. Setting it by using the config as suggested by the recbole docs did also not worked for me.

```
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
```

**Comment by Sherry-XLL** [comment]
Hello, Thomas @ThomasEKolb ! 

First of all, thanks very much for your attention to RecBole.

This is the issue of last year. In order to better solve your problem, we welcome you to create a new issue and describe your configuration in detail, so that we can answer your question or fix the bug in time.

Best Wishes.
