### ISSUE TITLE
[💡SUG] 对于测试部分GPU提速的实现

### ISSUE THREAD

**Issue by Wjk666** [RUCAIBox/RecBole#931]
您好，首先很感谢贵组开源该有效率的推荐系统框架，但针对其中GPU实现top-K预测部分的优化，本人有问题期待您的帮助！

- 请问在实现过程中， re-organize操作是否必要呢？假如已经对训练集样本置为负无穷，那么直接进行排序argsort得到的就是TopK预测结果的下标了，再与ground truth进行对比（这里可以用numpy的与或操作即可）则比较直接得到最终的recall，ndcg等指标的效果。
- 请问贵组在实现预测优化过程对应的代码如何查找呢？在文档中没找到对应源码，同时翻找实现的模型框架由于跳转太多，始终没找到filling，re-organize，topk-finding等操作。请问能否提示下核心实现代码？

感谢！

ndcg,recall  实现案例：
```
def ndcg(X_pred, heldout_batch, k=100):
    ## normalized discounted cumulative gain@k for binary relevance
    ## ASSUMPTIONS: all the 0's in heldout_data indicate 0 relevance
    batch_users = X_pred.shape[0]
    idx_topk_part = bn.argpartition(-X_pred, k, axis=1)
    topk_part = X_pred[np.arange(batch_users)[:, np.newaxis],
                       idx_topk_part[:, :k]]
    idx_part = np.argsort(-topk_part, axis=1)
    # X_pred[np.arange(batch_users)[:, np.newaxis], idx_topk] is the sorted
    # topk predicted score
    idx_topk = idx_topk_part[np.arange(batch_users)[:, np.newaxis], idx_part]
    # build the discount template
    tp = 1. / np.log2(np.arange(2, k + 2))
    DCG = (heldout_batch[np.arange(batch_users)[:, np.newaxis],
                         idx_topk].toarray() * tp).sum(axis=1)
    IDCG = np.array([(tp[:min(n, k)]).sum()
                     for n in heldout_batch.getnnz(axis=1)])
    return DCG / IDCG


def recall(X_pred, heldout_batch, k=100):
    batch_users = X_pred.shape[0]
    idx = bn.argpartition(-X_pred, k, axis=1)
    X_pred_binary = np.zeros_like(X_pred, dtype=bool)
    X_pred_binary[np.arange(batch_users)[:, np.newaxis], idx[:, :k]] = True
    X_true_binary = (heldout_batch > 0).toarray()
    tmp = (np.logical_and(X_true_binary, X_pred_binary).sum(axis=1)).astype(
        np.float32)
    recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))
    return recall
```

**Comment by guijiql** [comment]
@Wjk666 你好！
首先回答你的第一个问题：
在我们[网站](https://www.recbole.io/evaluation.html)的这张[图片](https://www.recbole.io/images/eval_img1.png)中，我们的最终目的是得到0-1矩阵***C***。根据这个矩阵，我们可以一次性计算出所需要的top-k指标（计算指标的时间远远小于得到矩阵**C**的时间），而无需重复取top-k。而通过re-organizing，我们可以直接通过比较图片中的***A***矩阵和***b***向量来快速得到***C***。在新的版本中，我们更改了这个计算的流程，参考https://github.com/RUCAIBox/RecBole/pull/894. 我们会在9月上线新的版本并更新论文和网站内容，到时候会有新的文档说明。

关于你的第二个问题：
filling的部分在https://github.com/RUCAIBox/RecBole/blob/939eb88889f91d1f32d03b8270422bb0fbe3d519/recbole/trainer/trainer.py#L346-L349 

re-organizing的部分在https://github.com/RUCAIBox/RecBole/blob/939eb88889f91d1f32d03b8270422bb0fbe3d519/recbole/trainer/trainer.py#L351-L354

topk-finding在
https://github.com/RUCAIBox/RecBole/blob/939eb88889f91d1f32d03b8270422bb0fbe3d519/recbole/evaluator/evaluators.py#L71-L72

**Comment by Wjk666** [comment]
感谢！期待新版本！
