### ISSUE TITLE
参数‘ training_neg_sample_num’的疑问？

### ISSUE THREAD

**Issue by Lyons-T** [RUCAIBox/RecBole#932]
请问，这个训练集负采样参数有什么作用，我看了很久代码，不太明白内部是怎么实现这个负采样的？我使用的是一个电影数据集，比如在BPR算法中，定义完这个负采样参数，请问你们是怎么进行负采样的？目前我看到的是每条数据好像增加了一个叫neg_item_Id的特征列。所以，**意思输入的原数据都被判定为正样本？**负样本是RecBole来采集的吗？这个新增的的neg_item_id是不是从未与用户交互过？如果training_neg_sample_num=10，意思是每个原始样本会拓展为10条带正负item_id数据对吗？

**Comment by 2017pxy** [comment]
@Lyons-T 你好，training_neg_sample_num设置的是我们的训练时负采样比。比如training_neg_sample_num=10代表我们会对每一条正例采样10条负例，采样池是用户未交互的商品。这个采样的过程是RecBole来自动做的。

>**意思输入的原数据都被判定为正样本？**负样本是RecBole来采集的吗？这个新增的的neg_item_id是不是从未与用户交互过？如果training_neg_sample_num=10，意思是每个原始样本会拓展为10条带正负item_id数据对吗？

你的这些理解都是正确的，我们会将.inter文件中出现的交互当做用户的正例，其他未出现的当做负例进行采样，所以neg_item_id是未与用户交互的商品；
