### ISSUE TITLE
运行context类模型报错

### ISSUE THREAD

**Issue by pangpang97** [RUCAIBox/RecBole#949]
大佬好，我是按照https://blog.csdn.net/Turinger_2000/article/details/111189783 的例子运行的代码，会报下面的错误：
![image](https://user-images.githubusercontent.com/24262596/131476715-daea5efa-cd08-4487-b838-562939cb97f0.png)
我的.yaml文件完全是复制的例子中的.yaml文件(只改了epochs)。
![image](https://user-images.githubusercontent.com/24262596/131476392-b83e15bb-50b9-4061-b18f-c7e739421dbc.png)
 请问出现这个bug的原因是什么呢？另外我发现我自己的配置文件并没有执行，这是不是引起错误的原因呢？如果是的话，我应该怎么改呢？我发现我的配置文件没有执行的原因是：运行打印出来的配置参数和我的配置文件不一致。
![image](https://user-images.githubusercontent.com/24262596/131476092-b5585ee2-0fd0-44c0-a2cd-a621823395c6.png)
运行的命令是 python run_recbole.py --model=LR --dataset=ml-1m --config_files=test.yaml
我的环境是：python   3.6.9；torch   1.9.0；recbole   0.2.1；macos catalina  10.15.6

**Comment by Sherry-XLL** [comment]
@pangpang97 你好，感谢你对伯乐项目的关注。我试着拉取了 RecBole 的最新版代码，根据[链接](https://blog.csdn.net/Turinger_2000/article/details/111189783)里的 test.yaml 运行 `python run_recbole.py --model=LR --dataset=ml-1m --config_files=test.yaml`，得到的结果为：

```python
31 Aug 10:11    INFO  best valid : {'auc': 0.793, 'logloss': 0.5394}
31 Aug 10:11    INFO  test result: {'auc': 0.7917, 'logloss': 0.5405}
```

你的问题不是项目的 bug，而是程序未能执行 test.yaml 中的配置。test.yaml 中的 `threshold: rating: 4` 通过阈值为数据集添加 01 标签，配置文件没有执行，所以会出现 `KeyError：'label'` 的报错。

从 PyCharm 的截图来看，你的 RecBole 文件夹内并未包含伯乐的所有文件，无法读取配置文件可能与这个有关。请拉取 RecBole 的最新代码，检查命令行空格和 `test.yaml` 的文件地址再试试看。

**Comment by pangpang97** [comment]
@Sherry-XLL  您好，我找到了问题所在是我的run_recbole.py 没有接收参数，多谢您的解答。
