### ISSUE TITLE
如何使用pre-trained embedding

### ISSUE THREAD

**Issue by pangpang97** [RUCAIBox/RecBole#951]
大佬你好，我想把用embedding特征加入到context模型中，我看到格式要求是这样的
![image](https://user-images.githubusercontent.com/24262596/131799341-8f7cc94f-3deb-4954-96b4-42367f8d557d.png) 。 请问user_emb:float_seq的内容的数据类型是什么呢？ 可以什么生成呢？

**Comment by pangpang97** [comment]
@Sherry-XLL 大佬好，原子文件的格式我看懂了，但是我不知道如何去生成这样的格式。 我使用的w2v生成的embedding 是一个m*n的array，然后如何变换成user_emb这种格式，这是我不知道的。

**Comment by Sherry-XLL** [comment]
@pangpang97 原子文件本质上就是 `.tsv` 格式的文件，通过不同的后缀进行区分，既然已经有了 array，只需通过 Python 的文件处理将其按格式保存即可，详情可以参考 [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) 中原子文件存储的相关代码。

**Comment by pangpang97** [comment]
我明白了，多谢大佬

**Comment by pangpang97** [comment]
大佬您好，我已经把数据处理成对应的格式，然后在recbole去跑的时候还是会有问题。 报错如下：
![image](https://user-images.githubusercontent.com/24262596/131816034-d2c8b2de-1e5f-40f1-aff4-bdd1eedfc66e.png)
.yaml文件是：
![image](https://user-images.githubusercontent.com/24262596/131816204-30ece70a-e82f-4241-8677-898dd8d6c0ca.png)
文件结构是
![image](https://user-images.githubusercontent.com/24262596/131816384-00988cd9-ef25-4b54-b894-31e1cf187eaf.png)
useremb的数据格式是：
![image](https://user-images.githubusercontent.com/24262596/131816491-4d552219-e718-424a-97a4-36df26dbb177.png)
生成useremb的代码是
![image](https://user-images.githubusercontent.com/24262596/131816706-10ffbf8c-7369-48ed-844f-2cdc3f58ce23.png)
 麻烦大佬看下问题出在了哪里，谢谢

**Comment by pangpang97** [comment]
大佬您好，我已经生成了useremb文件，模型跑的时候会报错，报错内容如下：
![image](https://user-images.githubusercontent.com/24262596/131817066-27987fbf-fe68-435a-acd3-0a5215f1a93d.png)
.yaml的内容是：
![image](https://user-images.githubusercontent.com/24262596/131817199-be768049-d427-4b77-ad4d-259d5800dc32.png)
文件路径是：
![image](https://user-images.githubusercontent.com/24262596/131817320-82d67829-891c-4f86-a31d-b4e53e062909.png)
useremb的数据是这样的：
![image](https://user-images.githubusercontent.com/24262596/131817389-1419c476-de61-4d85-86f1-ef5fd5f244f8.png)
生成useremb的代码是：
![image](https://user-images.githubusercontent.com/24262596/131817448-d25dbdd7-4f47-45b2-848a-f363c35e8712.png)
麻烦大佬帮忙看下问题所在，多谢多谢。

**Comment by pangpang97** [comment]
@chenyushuo  您好 请问这样设置的说法是在模型中就不会用到user_emb 这个特征么？

**Comment by chenyushuo** [comment]
@pangpang97 `unused_col`这个参数的实际作用是模型不能从交互记录中拿到对应的特征。
由于你已经设置了`preload_weight`这个参数，所以`user_emb`这个域你可以通过`dataset.get_preload_weight('user_emb')`获得。

**Comment by pangpang97** [comment]
@chenyushuo  您的意思是即使我设置了unused_col参数，模型依然会用到user_emb特征对吧？
