### ISSUE TITLE
如何利用训练好的context模型对新数据做预测

### ISSUE THREAD

**Issue by pangpang97** [RUCAIBox/RecBole#952]
大佬好，请问一下如何利用我训练好的模型，对新数据做预测呢？ 我在官网上没有看到相关的例子。但是我看到了这个
![image](https://user-images.githubusercontent.com/24262596/131804003-306db101-9af4-43a0-a5f7-5fbc9aff470c.png) 。 我是不是可以利用这个对新数据做预测呢？ 如果是的话，我的新数据处理的过程是怎样的呢？。多谢大佬。

**Comment by Sherry-XLL** [comment]
@pangpang97 推荐系统的训练和预测一般都是基于同一个数据集。在 RecBole 中，由于数据集的划分和 `Remap ID` 等各种预处理操作，模型都是在 `train_data` 上训练，用 `valid_data` 验证，再在 `test_data` 上测试，embedding 权重和 ID 之间具有对应关系，在训练集上的训练的模型通常只能在测试集上测试模型结果。

官网示例想表达的意思是，可以基于之前已经训练好的参数在之前的数据集划分的基础上测试模型。然而，如果用已经训练好的模型直接对另外一种新数据进行预测，即数据集不一样的情况，此时用户并没有对齐，往往会得到错误的结果。

如果你的新数据和原数据来自同一个数据集，理论上是可以对新数据进行预测的，数据处理方式与原来的 `data_preparation` 类似，但是要将用户进行对齐，这种情况下需要谨慎使用 `Remap ID`。

如果你想进行案例分析，对一些特定用户的行为比较感兴趣，想对某几个用户进行预测，可以参考 [case_study](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py) 的相关代码。

**Comment by pangpang97** [comment]
大佬您好，我们的场景是想把context的模型当成一个排序的模型来用。 会用到和训练数据同源的新数据来预测，而且新数据中会包含新的用户和商品，这样的情况下，是否仍然可以用recbole训练的模型对新数据预测呢？

**Comment by pangpang97** [comment]
@Sherry-XLL ，大佬您好，我们的场景是想把context的模型当成一个排序的模型来用。 会用到和训练数据同源的新数据来预测，而且新数据中会包含新的用户和商品（这些新的商品和用户都是训练数据里没有的），这样的情况下，是否仍然可以用recbole训练的模型对新数据预测呢？

**Comment by Sherry-XLL** [comment]
@pangpang97 你好，RecBole 在进行数据划分时是将同一个用户的不同交互分到了训练、验证和测试集中。也就是说，测试集中的用户和物品都是在训练集中出现过的，用户和物品的数量，即 embedding 表的大小在模型训练时已经确定了。如果新数据中包含新的用户和商品，那么新的商品和用户都不在已经训练的 embedding 中，因此无法直接对新数据进行预测。

**Comment by pangpang97** [comment]
@Sherry-XLL  是因为新用户或者新商品没办法从训练好的embedding表中得到对应的embedding，所有就没有办法用训练好的模型对其进行预测，大佬 我这样理解是对的吧？

所以，recbole的模型是基于一整份数据（记做A数据集）提前做好embedding，然后划分数据集，再做训练的。无论是训练和测试的数据都是出自于A数据集。如果要对新数据集（跟A数据集出自同一个场景下，但是会有不包含在A数据集内的新商品或者新用户）进行预测目前做不到的。是这样的吧？

**Comment by hyp1231** [comment]
您好，如果您的模型不涉及 item ID 和 user ID，而只利用了 user / item feature，那是可以加载训练好的模型对新商品 / 用户预测的。

此部分的文档目前还不是很完善，但是我们提供了使用样例：
* 0.2.1 版本的样例：[save_and_load_example.py](https://github.com/RUCAIBox/RecBole/blob/master/run_example/save_and_load_example.py)
* 即将发布的新版本的样例（API 与 0.2.1 存在一些不一致）：[save_and_load_example.py](https://github.com/RUCAIBox/RecBole/blob/data/run_example/save_and_load_example.py)

**Comment by pangpang97** [comment]
@hyp1231  您好，我的模型目前是不涉及到itemID和userID作为特征进行训练的，那么这样的情况就可以对新的商品/用户预测了，对吧？ 另外如果不涉及到itemID和userID的训练和对新数据预测（包括数据处理和预测两部分）两块是否有样例代码可以参考呢？

**Comment by hyp1231** [comment]
可以的。

目前没有这么细节的样例代码。

* 如果您的新数据比较少，重点在于想分析模型预测的具体结果，希望做一些 case study，可以参考 [case_study_example.py](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py)
* 如果您是相当于希望在另一份 test 集上进行测试，重点希望得到新数据上的指标，您可以使用 benchmark 加载功能 [API Doc](https://recbole.io/docs/user_guide/data/data_args.html#benchmark-file)

**Comment by pangpang97** [comment]
@hyp1231  您好，我的做法应该是您提到第二点（希望在另一份 test 集上进行测试）。

我看到您的benchmark功能是要把训练集，验证集和测试集分成三个独立的文件，给模型去处理。这种情况下，我要提前准备好这三份数据集。
 但是，我的需求是想训练好模型后，如果我再有新的数据集，想再模型上测试得到预测结果和指标，我应该怎么做呢？可以理解为我再训练的时候，我是没办法得到我新的测试数据的。

**Comment by hyp1231** [comment]
刚才想了一下，基于现有 API 好像确实没有很方便的做法。

我们再考虑一下，如果后续有功能跟进，会在此 issue 下回复，感谢建议。

**Comment by pangpang97** [comment]
@hyp1231  谢谢您。

**Comment by sxhysj** [comment]
> 大佬好，请问一下如何利用我训练好的模型，对新数据做预测呢？ 我在官网上没有看到相关的例子。但是我看到了这个
> ![image](https://user-images.githubusercontent.com/24262596/131804003-306db101-9af4-43a0-a5f7-5fbc9aff470c.png) 。 我是不是可以利用这个对新数据做预测呢？ 如果是的话，我的新数据处理的过程是怎样的呢？。多谢大佬。

我理解你是想对新用户及新物品进行冷启动。这时，已有的模型可以被使用，具体有以下三种方法：
1、将已有物品的特征与新物品特征进行embedding，然后通过向量距离测算相似度，找出最相近的，推送最近似的那个物品。
2、将已有人的特征与新人的特征进行embedding，然后通过向量距离测算相似度，找出最接近的，推送最近新的那个人的喜好。
3、将新的特征进行整体编码，通过模型测算距离，也就是直接测算Concatenate之后的特征距离，然后进行特征修改，将新人的ID与新物品的ID近似替换为最接近的向量的ID，然后过模型。

以上三种方法其实也是协同过滤的思想+冷启动的思想，希望对你有帮助。
