### ISSUE TITLE
How to save model with custom name?

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#954]
Hi, how can I override `saved_model_file`? I want to give it a custom name.

**Comment by Sherry-XLL** [comment]
@laxmimerit In RecBole, the general form of `saved_model_file` is `config['checkpoint_dir']/config['model']-get_local_time().pth`. If you want to change the directory where the model is saved, just modify `checkpoint_dir`. If you want to override the file name, you can rewrite the following code in `trainer.py`:
https://github.com/RUCAIBox/RecBole/blob/939eb88889f91d1f32d03b8270422bb0fbe3d519/recbole/trainer/trainer.py#L92

**Comment by laxmimerit** [comment]
wanted to give a custom name to the model file itself. It would be great if you make this as parameter input. As of now, I will make changes in the file so that I can pass it with config param.
