### ISSUE TITLE
python run_recbole.py  --model=BERT4Rec.  Problem appear

### ISSUE THREAD

**Issue by Anna1015** [RUCAIBox/RecBole#955]
**描述这个 bug**
With the source code, I use the script:  python run_recbole.py  --model=BERT4Rec, but a problem arises as follows.

ValueError: training_neg_sample_num should be 0 when the loss_type is CE

Would you mind telling me how to fix it?

**Comment by Sherry-XLL** [comment]
@Anna1015 BERT4Rec in RecBole provides two ways to calculate loss, and you can set `loss_type` to change the type of loss function. If `loss_type='CE'`, the training task is regarded as a multi-classification task and the target item is the ground truth. In this way, you should set `training_neg_sample_num=0`. If `loss_type='BPR'`, the training task will be optimized in the pair-wise way, which maximizes the difference between positive items and negative ones. In this way, negative sampling is necessary, such as setting `training_neg_sample_num=1`. 

As for this problem, you can set `training_neg_sample_num=0` or `loss_type='BPR'` to fix the ValueError. 

For more details, please refer to the [documentation of BERT4Rec](https://recbole.io/docs/user_guide/model/sequential/bert4rec.html).

**Comment by Anna1015** [comment]
It works, thank you ☺️
