### ISSUE TITLE
[💡SUG] Will multi-GPU be supported in the next version?

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#959]
Will multi-GPU be supported in the next version?

**Comment by Sherry-XLL** [comment]
@sxhysj Sorry, considering the complexity of implementation, RecBole's next version still does not support multi-GPU training. We have taken multi-GPU training into consideration. If you have some ideas or relevant papers, comments and suggestions are very welcome as always.

**Comment by dxjjhm** [comment]
I suggest you to learn the method of DJL (DeepJavaLibrary  https://djl.ai/ ), it could use all the gpus of single machine.

**Comment by sxhysj** [comment]
Any updates on this?

**Comment by 2017pxy** [comment]
@sxhysj Sorry, the implementation of this feature is a bit complex in our framework and it still takes some time to add it.  

BTW, @juyongjiang has given his implementation in #961, which works well for sequential recommendation models. You can refer it and try to modify our code by yourself.

**Comment by Sherry-XLL** [comment]
Hello @sxhysj, we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the distributed training and evaluation is supported in our framework now. You can refer to our [documentation](https://recbole.io/docs/get_started/distributed_training.html) for more details and running examples.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
