### ISSUE TITLE
[💡SUG] Any plans to implement DCN-V2?

### ISSUE THREAD

**Issue by sxhysj** [RUCAIBox/RecBole#960]
Are you planning to implement the model DCN-V2?

BTW, the DCN model looks like it has some bugs in the loss calculation function. When I use the DCN model, it shows:
RuntimeError: all elements of input should be between 0 and 1
the error is from functional.py line 2893, in binary_cross_entropy function.

The other content-aware recommendation models look fine under the same dataset.

Any ideas for this?

**Comment by guijiql** [comment]
Can you provide the dataset and configuration file when the error was reported?

**Comment by sxhysj** [comment]
> Can you provide the dataset and configuration file when the error was reported?

I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?

**Comment by guijiql** [comment]
> > Can you provide the dataset and configuration file when the error was reported?
> 
> 
> 
> I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?

Could you tell me:
1.What's the recbole version?
2.What device are you runnning on？(cpu/gpu)

**Comment by guijiql** [comment]
I guess your recbole's version is v0.1.2 and your device is cpu. Because only in v0.1.2 is the code   ``output = self.sigmoid(self.predict_layer(stack))``  in line 118. And this bug has been fixed in v0.2.0(#633). If this is the case, please update to the latest version.

**Comment by sxhysj** [comment]
> > > Can you provide the dataset and configuration file when the error was reported?
> > 
> > 
> > I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?
> 
> Could you tell me:
> 1.What's the recbole and torch version?
1.9.0/1.7.0
> 2.What device are you runnning on？(cpu/gpu)
gpu gtx 1080ti on cuda 11.1
/cpu
> 3.Whether this bug appears in every dataset?
No. Smaller dataset has no problem. Large one (100m lines) appears. I try to see if there is some nan in the target(label column) but not found.

**Comment by guijiql** [comment]
> > > > Can you provide the dataset and configuration file when the error was reported?
> 
> > > 
> 
> > > 
> 
> > > I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?
> 
> > 
> 
> > Could you tell me:
> 
> > 1.What's the recbole and torch version?
> 
> 1.9.0/1.7.0
> 
> > 2.What device are you runnning on？(cpu/gpu)
> 
> gpu gtx 1080ti on cuda 11.1
> 
> /cpu
> 
> > 3.Whether this bug appears in every dataset?
> 
> No. Smaller dataset has no problem. Large one (100m lines) appears. I try to see if there is some nan in the target(label column) but not found.
> 
> 
> 
> 

And what's the rebole's version?

**Comment by sxhysj** [comment]
> I guess your recbole's version is v0.1.1 or 0.1.2 and your device is cpu. Because only in v0.1.1 and v0.1.2 is the code `output = self.sigmoid(self.predict_layer(stack))` in line 118. This bug has been fixed in v0.2.0(#633). If this is the case, please update to the latest version. If not, please tell me above mentioned information.

I used the master branch.

**Comment by sxhysj** [comment]
> > I guess your recbole's version is v0.1.1 or 0.1.2 and your device is cpu. Because only in v0.1.1 and v0.1.2 is the code `output = self.sigmoid(self.predict_layer(stack))` in line 118. This bug has been fixed in v0.2.0(#633). If this is the case, please update to the latest version. If not, please tell me above mentioned information.
> 
> I used the master branch.

In the line 118 of master branch, indeed there is no sigmoid. What i wanted to say is that the 'output' contains nan values which may come from sigmoid functions.

**Comment by sxhysj** [comment]
> > > > > Can you provide the dataset and configuration file when the error was reported?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?
> > 
> > 
> > > 
> > 
> > 
> > > Could you tell me:
> > 
> > 
> > > 1.What's the recbole and torch version?
> > 
> > 
> > 1.9.0/1.7.0
> > > 2.What device are you runnning on？(cpu/gpu)
> > 
> > 
> > gpu gtx 1080ti on cuda 11.1
> > /cpu
> > > 3.Whether this bug appears in every dataset?
> > 
> > 
> > No. Smaller dataset has no problem. Large one (100m lines) appears. I try to see if there is some nan in the target(label column) but not found.
> 
> And what's the rebole's version?

I checked out the latest version from master branch. May be it is 0.2.1?

**Comment by guijiql** [comment]
> > > > > > Can you provide the dataset and configuration file when the error was reported?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I found line 118 of dcn.py might have a bug. The 'output' of sigmoid has 'nan' values. I tried to add a line 'output = torch.where(torch.isnan(output), torch.full_like(output, torch.tensor(1)), output)' to temporarily remove the bug but failed. Could you please take a look at it?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Could you tell me:
> 
> > > 
> 
> > > 
> 
> > > > 1.What's the recbole and torch version?
> 
> > > 
> 
> > > 
> 
> > > 1.9.0/1.7.0
> 
> > > > 2.What device are you runnning on？(cpu/gpu)
> 
> > > 
> 
> > > 
> 
> > > gpu gtx 1080ti on cuda 11.1
> 
> > > /cpu
> 
> > > > 3.Whether this bug appears in every dataset?
> 
> > > 
> 
> > > 
> 
> > > No. Smaller dataset has no problem. Large one (100m lines) appears. I try to see if there is some nan in the target(label column) but not found.
> 
> > 
> 
> > And what's the rebole's version?
> 
> 
> 
> I checked out the latest version from master branch. May be it is 0.2.1?
Thank for your information. We will check the code carefully.

**Comment by Sherry-XLL** [comment]
Hello @sxhysj, we have released the [1.1.1 version of RecBole](https://github.com/RUCAIBox/RecBole/releases/tag/v1.1.1) on Oct 5 2022, and the DCN-V2 model is supported in our framework now. You can refer to our [documentation](https://recbole.io/docs/user_guide/model/context/dcnv2.html) and #1418 for more details and running examples.

Thank you very much for your attention and kindly advice! The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.
