### ISSUE TITLE
how to load from pth file which created earlier and get prediction in recbole

### ISSUE THREAD

**Issue by iamharikrishnank** [RUCAIBox/RecBole#964]

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Hello, RecBole supports reloading the parameters from previously trained models. You can refer to the official documentation [Resume Model From Break Point](https://recbole.io/docs/user_guide/usage/use_modules.html?highlight=pth#resume-model-from-break-point).

**Comment by iamharikrishnank** [comment]
how to define config??
NameError: name 'config' is not defined

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Ellipsis in [this part](https://recbole.io/docs/user_guide/usage/use_modules.html?highlight=pth#resume-model-from-break-point) omits the code that appears above. You can refer to the code in [Use Modules](https://recbole.io/docs/user_guide/usage/use_modules.html?#use-modules) to view the complete process. Config module is used to set parameters and experiment setup. Please refer to [Config Settings](https://recbole.io/docs/user_guide/config_settings.html) for more details.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL  config = Config(model='BPR', dataset='ml-100k') should i define like this..ior jst define like config = Config()

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Is your `.pth` model file trained in RecBole? If so, initialize the configuration with the model and dataset you set during training. If not, there will be problems when testing in RecBole.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL I am using ItemKNN algorithm for model creation and I have created a model ItemKNN-Sep-13-2021_20-12-33.pth and saved in save directory my requirement is to use this model to get recommendation via python file and also how to pass input to recommendation

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Recommendation tasks are closely related to datasets.  If you do not specify a dataset during training, RecBole will use the built-in `ml-100k` for training, and the trained model is only applicable to `ml-100k` dataset.

RecBole is a recommender system for researchers, which is more used for the comparison of academic research. During the running process of RecBole, we will divide the original dataset into training set, validation set and test set. We optimize model parameters on the training set, do parameter selection according to the results on the validation set, and finally report the results on the test set. Usually, the saved model can only be used for recommendations on the original dataset. 

If you are interested in the behavior of some specific users, and want to do case analysising to predict some users, you can refer to [Case Study](https://github.com/RUCAIBox/RecBole/blob/master/run_example/case_study_example.py). Case study is an in-depth study of the performance of a specific recommendation algorithm, which will analysis the recommendation result of some users. If you want to use the trained model for specific recommended tasks, please modify the code according to your requirements.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL I am using a custom dataset for creating model in recbole

**Comment by iamharikrishnank** [comment]
@Sherry-XLL 
can u provide usage instructions for top-k items and I am facing some import library issues

**Comment by Sherry-XLL** [comment]
@iamharikrishnank What's the version of your RecBole? We have realeased [v1.0.0](https://github.com/RUCAIBox/RecBole/releases/tag/v1.0.0) on September 17, 2021, you can update RecBole to the latest version and try again. If the problem still exists, we will fix it in time.

**Comment by miloooooz** [comment]
> @iamharikrishnank What's the version of your RecBole? We have realeased [v1.0.0](https://github.com/RUCAIBox/RecBole/releases/tag/v1.0.0) on September 17, 2021, you can update RecBole to the latest version and try again. If the problem still exists, we will fix it in time.

@Sherry-XLL I try to use load_data_and_model for the .pth file, but it shows
`UnpicklingError: could not find MARK`
My codes are like that
```
from recbole.quick_start import load_data_and_model
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
model_file = "./saved/lightgbm-Sep-16-2021_23-50-12.pth")
```
I checked everywhere but could not find a reason for that, how can I do with it? Thanks in advance.

**Comment by iamharikrishnank** [comment]
> @iamharikrishnank What's the version of your RecBole? We have realeased [v1.0.0](https://github.com/RUCAIBox/RecBole/releases/tag/v1.0.0) on September 17, 2021, you can update RecBole to the latest version and try again. If the problem still exists, we will fix it in time.

@Sherry-XLL when updated the issue is solved.. instead new issue when 
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
        model_file="ItemKNN-Sep-13-2021_14-19-49.pth",
    )
it showed Neither [dataset/datasetname] exists in the devicenor [datasetname] a known dataset name

**Comment by Sherry-XLL** [comment]
@iamharikrishnank You need to put your dataset in the dataset folder and use the dataset with the same name when running the code. I don't know what your settings are, so I can't give an accurate solution for the time being.

**Comment by iamharikrishnank** [comment]
> @iamharikrishnank You need to put your dataset in the dataset folder and use the dataset with the same name when running the code. I don't know what your settings are, so I can't give an accurate solution for the time being.
@Sherry-XLL  now i am getting this error
![image](https://user-images.githubusercontent.com/20636478/133737445-d861f943-1600-45aa-8613-0299133b3f96.png)

**Comment by Sherry-XLL** [comment]
@iamharikrishnank What's your command line to get the model file `ItemKNN-Sep-13-2021_14-19-49.pth`? Maybe `config` loaded in the model file has some problem. You can try to output config before error to see configuration information and missing parameters.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL can i know  uid_series = dataset.token2id(dataset.uid_field, ['196', '186'])
is 196 and 186 are userids,,

**Comment by iamharikrishnank** [comment]
@Sherry-XLL Can u explain what is topk score
![image](https://user-images.githubusercontent.com/20636478/133986376-5d3b435f-f09a-4ee0-ad80-16f14f45da7a.png)

**Comment by Sherry-XLL** [comment]
@iamharikrishnank `recbole.utils.case_study.full_sort_topk` calculates the top-k items' scores and ids for each user in uid_series. The score of `[pad]` and history items will be set into `-inf`. 

Args:
- `uid_series` (numpy.ndarray): User id series.
- `model` (AbstractRecommender): Model to predict.
- `test_data` (FullSortEvalDataLoader): The test_data of model.
- `k` (int): The top-k items.
- `device` (torch.device, optional): The device which model will run on. Defaults to ``None``.

Returns:
- `topk_scores` (torch.Tensor): The scores of topk items.
- `topk_index` (torch.Tensor): The index of topk items, which is also the internal ids of items.

`topk_scores` are the scores of topk items for each user in uid_series, more details can be found in [source code](https://github.com/RUCAIBox/RecBole/blob/master/recbole/utils/case_study.py) and [documentation](https://recbole.io/docs/recbole/recbole.utils.case_study.html#recbole.utils.case_study.full_sort_topk).

**Comment by iamharikrishnank** [comment]
@Sherry-XLL Is the output that we get from topk scores the probablity of recommending that item to user

**Comment by Sherry-XLL** [comment]
@iamharikrishnank The output from `topk_scores` is not probability, but the user's scores of the `k` most recommended items. After the training process, every user and every item can calculate a score, which can be used as an index for sorting. Select the first `k` scores in reverse order, and the first `k` scores of items are `topk_scores`.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL  Hi I am facing issue in creating a contextbased recommendation model in recbole.my input dataset consists of
1.inter file ->item_id,user_id
2.item file -> item_id,topics
3. user file -> user_id,subject,description
and following error is occuring

Traceback (most recent call last):
  File "run_recbole.py", line 25, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/home/harikrishnan/Downloads/RecBole/recbole/quick_start/quick_start.py", line 60, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "/home/harikrishnan/Downloads/RecBole/recbole/trainer/trainer.py", line 315, in fit
    train_loss = self._train_epoch(train_data, epoch_idx, show_progress=show_progress)
  File "/home/harikrishnan/Downloads/RecBole/recbole/trainer/trainer.py", line 168, in _train_epoch
    losses = loss_func(interaction)
  File "/home/harikrishnan/Downloads/RecBole/recbole/model/context_aware_recommender/afm.py", line 108, in calculate_loss
    label = interaction[self.LABEL]
  File "/home/harikrishnan/Downloads/RecBole/recbole/data/interaction.py", line 131, in __getitem__
    return self.interaction[index]
KeyError: 'label'

**Comment by iamharikrishnank** [comment]
@Sherry-XLL Another issue I am facing now is 
![image](https://user-images.githubusercontent.com/20636478/134365092-28b58db1-5b71-4e91-a5c7-e6c63e9122b7.png)

**Comment by Sherry-XLL** [comment]
@iamharikrishnank As for the first question, context-aware recommendation can be seen as an extension of click-through rate prediction. All the model in this class can be used for CTR prediction. Usually, the dataset is explicit and contains `label` field. 

- If your data has already been labeled, you only need to set `LABEL_FIELD` to tell the model which column represents the label of data, and then set `neg_sampling` as None.
- If your data doesn’t have `labels` but has users' feedback information (like rating for items) to show their preferences, a general way to label them is to set `threshold`.
- If your only have implicit feedback data, without `label` or users' feedback information. A general way to label these kinds of data is `negative sampling`.

You can refer to [Label of data](https://recbole.io/docs/user_guide/data/label_of_data.html) and [Context-aware Recommendation](https://recbole.io/docs/user_guide/model_intro.html#context-aware-recommendation) for more details.

As for the second question, the shape of `scores` will be `[len(input_interaction), dataset.item_num]` when used properly. You can check the number of items in the dataset and the results returned by the score function to see what went wrong.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL when I tried to install recbole=1.0.0 in ubuntu 18.04 LTS using pip install following error occured
ERROR: Could not find a version that satisfies the requirement scipy==1.6.0 (from recbole) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
ERROR: No matching distribution found for scipy==1.6.0

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Hello, what's the version of your Python and PyTorch?

**Comment by iamharikrishnank** [comment]
@Sherry-XLL Hi..I want to get topk recommendation based on title and description along with userid.inter file consists of title,description and topics .Instead of item id I want to get recommendation as topics.what changes should be made inorder to get recommendations like this

**Comment by Sherry-XLL** [comment]
@iamharikrishnank RecBole implements models covering general recommendation, sequential recommendation, context-aware recommendation and knowledge-based recommendation. As for general, sequential and knowledge-based models, we usually need to set `USER_ID_FIELD` and `ITEM_ID_FIELD`. Your description applies to context-aware recommendation or click-through rate prediction, `USER_ID_FIELD` and `ITEM_ID_FIELD` can be `~` in this case.

Take advertising datasets in our [public data sources](https://github.com/RUCAIBox/RecSysDatasets#advertising) as an example, [criteo](https://www.kaggle.com/c/criteo-display-ad-challenge/data) was collected from Criteo, which consists of a portion of Criteo's traffic over a period of several days. Each record/line in the file has the following fields: `label`, `I1-I13`, `C1-C26`, without user or item ids.  If we want to use context-aware models on such datasets, just set the configuration file  as follows:

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: ~
ITEM_ID_FIELD: ~
LABEL_FIELD: label

load_col: 
    inter: '*'

fill_nan: True
normalize_all: True

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_args:
  mode: labeled
  group_by: ~
valid_metric: AUC
metrics: ['AUC', 'LogLoss']

# model
embedding_size: 10
```

According to your needs, you can load the `userid.inter` file similarly without setting `ITEM_ID_FIELD`, and run the context-aware model. It is worth noting that such models need labels to indicate if a record was clicked (1) or not (0). For the label setting of RecBole, you can refer to [label of data](https://recbole.io/docs/user_guide/data/label_of_data.html) for more details.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL In my dataset there is no click rate

**Comment by iamharikrishnank** [comment]
@Sherry-XLL If  I have item id and userid also in my dataset along with description,title and topics how can I use title,description along with userid to get prediction of item id in topk recommendation

**Comment by Sherry-XLL** [comment]
@iamharikrishnank On the one hand, `description`, `title` and `topics` are context information of recommendation. If you want to utilize them to recommend items, context-aware models are needed. On the other hand, if you only have implicit feedback data, without label or users' feedback information, a general way to label these kinds of data is negative sampling. Therefore, you can still use context-aware recommendation models in your dataset. What's more, if you have item id and user id, just set `USER_ID_FIELD` and `ITEM_ID_FIELD` as usual, context-aware models can handle situations with and without ids. In this case, the configuration file may be as follows:

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: ~
NEG_PREFIX: neg_
LABEL_FIELD: label
threshold: ~
load_col:
    inter: [user_id, item_id, description, title, topics]

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_args:
  split: {'RS':[0.8, 0.1, 0.1]}
  group_by: ~
  mode: uni5  # unixxx and popxxx are designed for the evaluation on implicit feedback (data without label), here the xxx must be an integer.
  order: RO
valid_metric: AUC
metrics: ['AUC', 'LogLoss']

neg_sampling:
    uniform: 1

# model
embedding_size: 10
```

**Comment by iamharikrishnank** [comment]
@Sherry-XLL  how to get recommendations 
uid_series = dataset.token2id(dataset.uid_field, ['0001'])
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])
along with uid field title field and description field should be added in the input section.how to do this to get recommendation

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Current `case study` in RecBole can only calculate the top-k items' scores and ids for each user in `uid_series`, and the dataloader type of `test_data` should be `FullSortEvalDataLoader`. 

If you want to utilize other context fields to get recommendations, you need to train a context-aware model first. What's more, you need to normalize data including `user_id`, `title` and `description` into an interaction that can be calculated by `forward` in context-aware models. To be specific, `input_interaction` in `case_study.py` only contains `uid_field`, you should add  `title field` and `description field` as needed. 

In addition, the model details of general recommendation models and context-aware models are not exactly the same, so the details of context-aware models should be considered when modifying `case_study.py`. If you have implemented this function, a pull request is welcome.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL I encountered with following error
AttributeError: 'NegSampleEvalDataLoader' object has no attribute 'is_sequential'
when executing following code 
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])

**Comment by Sherry-XLL** [comment]
@iamharikrishnank The dataloader type of `test_data` should be `FullSortEvalDataLoader` in  `full_sort_topk`, in other words, you should set `mode:full` in configuration file when pretraining your model. Your pretrained model does not meet the requirements of using existing functions in `case_study.py`, so an error will be reported.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL can u show an example config file inorder to solve this issue

**Comment by Sherry-XLL** [comment]
@iamharikrishnank I don't know the details of the model and dataset you want to use, but `case_study.py` is only applicable to pre-trained models with **full sort evaluation**. That is, evaluation settings in the configuration file should be as follows.

```
# evaluation settings
eval_args: 
  split: {'RS':[0.8, 0.1, 0.1]}
  group_by: user
  order: RO
  mode: full
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: [10]
valid_metric: MRR@10
```

However, if you want to add context information such as `title` and `description` to the model, you need to use **context-aware models**. Context-aware recommendation can be seen as an extension of click-through rate prediction. Usually, the dataset is explicit and contains label field, and evaluation is always conducted in the way of binary classification. Note that RecBole also supports to evaluate the context-aware recommendation models by full-ranking like general recommendation models, but you need to make sure that your `.inter` file **can not load any other context information column**.

In other words, if you want to use `case_study.py` in RecBole, your pre-trained model should be evaluated with full-ranking. However, when context information is needed, `.inter` cannot load any other context information column. In this case, you need to **preprocess the context information** such as `title`, `topics` and `description` in `.inter` into the `.item` file, and then use `.item` to load the context column.

```
# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: ~
NEG_PREFIX: neg_
LABEL_FIELD: label
threshold: ~
load_col:
    inter: [user_id, item_id]
    item: [item_id, description, title, topics]

# training and evaluation
epochs: 500
train_batch_size: 4096
eval_args: 
  split: {'RS':[0.8, 0.1, 0.1]}
  group_by: user
  order: RO
  mode: full
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: [10]
valid_metric: MRR@10

neg_sampling:
    uniform: 1

# model
embedding_size: 10
```

It is worth mentioning that the context model pre-trained from the configuration above **can not be directly used for prediction**. You need to **modify the source code** in `RecBole/recbole/utils/case_study.py` according to context-aware models, and you should add `title` field and `description` field in `input_interaction` as needed. 

Last but not least, case study is an in-depth study of the performance of a specific recommendation algorithm, which will analysis the recommendation result of some users. **It can't directly solve your problem**, and you need to implement the specific functions according to your needs.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL can u show how to add description and title to case_study.py

**Comment by Sherry-XLL** [comment]
@iamharikrishnank You can get the interaction containing `description` and `title` from the code of this branch, and the premise is that you need to add the context information during pre-training.
https://github.com/RUCAIBox/RecBole/blob/434e3f02ecc19968698f03078cc80f35ed638e33/recbole/utils/case_study.py#L50-L53

**Comment by Sherry-XLL** [comment]
@iamharikrishnank The original codes in `RecBole/recbole/utils/case_study.py` to get `input_interaction` are as follows.

https://github.com/RUCAIBox/RecBole/blob/434e3f02ecc19968698f03078cc80f35ed638e33/recbole/utils/case_study.py#L45

You can add `description` and `title` like this:
```python
input_interaction = dataset.join(Interaction({uid_field: uid_series}))
context_feat = Interaction({'description': description, 'title': title})
input_interaction.update(context_feat)
```

**Comment by Sherry-XLL** [comment]
@iamharikrishnank `dataset.token2id` is used to transfer external user token to internal user id, and `uid_series` are internal user id series we want to predict. What you need to change is not `uid_series`, but the function `full_sort_scores`. You should add two variables `title` and `description`, and then change function in `case_study.py`. Then, you can add context information like this:
```python
topk_score, topk_iid_list = full_sort_topk(uid_series, title, description, model, test_data, k=10, device=config['device'])
```

**Comment by iamharikrishnank** [comment]
@Sherry-XLL how to display recommended topics as output instead of item_ids in topk_iid_list or any other solutions to print recommended topic list

**Comment by Sherry-XLL** [comment]
@iamharikrishnank If the purpose of your recommendation is not items but topics, you can set `ITEM_ID_FIELD: topic` instead of `item_id` during pre-training, and the recommended list is the topic list.

**Comment by iamharikrishnank** [comment]
@Sherry-XLL can u show an example.Even if I changed in config 
![image](https://user-images.githubusercontent.com/20636478/136178941-42f0c4b3-178a-4a35-b0d8-9e0993d04854.png)
topk_iid_list shows like this
tensor([[179, 159,   2,  45, 361, 362,   4,   5,   6,   7]])

**Comment by iamharikrishnank** [comment]
@Sherry-XLL when creating AFM model this error occurs
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 4004 and 16247 in dimension 0 (The offending index is 1)

**Comment by Sherry-XLL** [comment]
> @iamharikrishnank If the purpose of your recommendation is not items but topics, you can set `ITEM_ID_FIELD: topic` instead of `item_id` during pre-training, and the recommended list is the topic list.

@iamharikrishnank As I said before, just replace the `item_id` with `topics`.

**Comment by Sherry-XLL** [comment]
@iamharikrishnank Please find out the relationship between datasets and column fields first. Is the topic, title and description the characteristics of users or items? You need to read the source code and documentation carefully and think about how to achieve your goal.

**Comment by iamharikrishnank** [comment]
uid_series = dataset.token2id(dataset.uid_field, ['1234'])
topk_score, topk_iid_list = full_sort_topk(uid_series, model, test_data, k=10, device=config['device'])

how should I alter this to get right prediction

**Comment by iamharikrishnank** [comment]
@Sherry-XLL following error occured
IndexError                                Traceback (most recent call last)
<ipython-input-11-3cd12fe211a2> in <module>
----> 1 topk_score, topk_iid_list = full_sort_topk(uid_series, title, description, model, test_data, k=10, device=config['device'])

~\Downloads\RecBole\RecBole-master\recbole\utils\case_study.py in full_sort_topk(uid_series, description, title, model, test_data, k, device)
     91             - topk_index (torch.Tensor): The index of topk items, which is also the internal ids of items.
     92     """
---> 93     scores = full_sort_scores(uid_series, description, title, model, test_data, device)
     94     return torch.topk(scores, k)

~\anaconda3\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~\Downloads\RecBole\RecBole-master\recbole\utils\case_study.py in full_sort_scores(uid_series, description, title, model, test_data, device)
     43 
     44     if not test_data.is_sequential:
---> 45         input_interaction = dataset.join(Interaction({uid_field: uid_series}))
     46         context_feat = Interaction({'description': description, 'title': title})
     47         input_interaction.update(context_feat)

~\Downloads\RecBole\RecBole-master\recbole\data\dataset\dataset.py in join(self, df)
   1255         """
   1256         if self.user_feat is not None and self.uid_field in df:
-> 1257             df.update(self.user_feat[df[self.uid_field]])
   1258         if self.item_feat is not None and self.iid_field in df:
   1259             df.update(self.item_feat[df[self.iid_field]])

~\Downloads\RecBole\RecBole-master\recbole\data\interaction.py in __getitem__(self, index)
    133             ret = {}
    134             for k in self.interaction:
--> 135                 ret[k] = self.interaction[k][index]
    136             return Interaction(ret)
    137 

IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by Sherry-XLL** [comment]
@iamharikrishnank In RecBole, we will transfer set of fields in the same remapping space into remap list, this is the reason why we should use `dataset.token2id` to transfer external user token to internal user id in the following codes. 

https://github.com/RUCAIBox/RecBole/blob/f56bcd001074b0a0f1dec5dd4ece90643d60ec8c/run_example/case_study_example.py#L23-L25

Similarly, both `description` and `title` are data in the type of `str`, and we need to map them into the ID space like the `uid_series`. Likewise, you can use `dataset.token2id` to transfer `[<class 'numpy.str_'>]` to internal feature id as follows.

```python
description_series = train_data.dataset.token2id('description', description)
title_series = train_data.dataset.token2id('title', title)
context_feat = Interaction({'description': description_series, 'title': title_series})
input_interaction.update(context_feat)
```

**Comment by iamharikrishnank** [comment]
@Sherry-XLL I changed accordingly following error occured
----> 1 topk_score, topk_iid_list = full_sort_topk(uid_series, title, model, test_data, k=10, device=config['device'])

~\Downloads\RecBole\RecBole-master\recbole\utils\case_study.py in full_sort_topk(uid_series, title, model, test_data, k, device)
     91             - topk_index (torch.Tensor): The index of topk items, which is also the internal ids of items.
     92     """
---> 93     scores = full_sort_scores(uid_series,  title, model, test_data, device)
     94     return torch.topk(scores, k)

~\anaconda3\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~\Downloads\RecBole\RecBole-master\recbole\utils\case_study.py in full_sort_scores(uid_series, title, model, test_data, device)
     44     if not test_data.is_sequential:
     45         input_interaction = dataset.join(Interaction({uid_field: uid_series}))
---> 46         context_feat = Interaction({'title': title})
     47         input_interaction.update(context_feat)
     48         history_item = test_data.uid2history_item[list(uid_series)]

~\Downloads\RecBole\RecBole-master\recbole\data\interaction.py in __init__(self, interaction)
    102             for key, value in interaction.items():
    103                 if isinstance(value, (list, np.ndarray)):
--> 104                     self.interaction[key] = _convert_to_tensor(value)
    105                 elif isinstance(value, torch.Tensor):
    106                     self.interaction[key] = value

~\Downloads\RecBole\RecBole-master\recbole\data\interaction.py in _convert_to_tensor(data)
     35         new_data = rnn_utils.pad_sequence(seq_data, batch_first=True)
     36     else:
---> 37         raise ValueError(f'[{type(elem)}] is not supported!')
     38     if new_data.dtype == torch.float64:
     39         new_data = new_data.float()

ValueError: [<class 'numpy.int32'>] is not supported!

**Comment by iamharikrishnank** [comment]
@Sherry-XLL  I am getting this error 
AttributeError: 'torch.device' object has no attribute 'dataset'
