### ISSUE TITLE
[🐛BUG] 带中文的文件无法兼容

### ISSUE THREAD

**Issue by miloooooz** [RUCAIBox/RecBole#965]
您好，我在用我自己的数据集时发现如果文件中有中文，会报UnicodeDecodeError错误，找到对应位置是recbole\data\dataset\dataset.py的 _load_feat(self, filepath, source)报错
```
with open(filepath, 'r') as f:
    head = f.readline()[:-1]
for field_type in head.split(field_separator):
    field, ftype = field_type.split(':')
    try:
        ftype = FeatureType(ftype)
    except ValueError:
        raise ValueError(f'Type {ftype} from field {field} is not supported.')
    if load_col is not None and field not in load_col:
        continue
    if unload_col is not None and field in unload_col:
        continue
    if isinstance(source, FeatureSource) or source != 'link':
        self.field2source[field] = source
        self.field2type[field] = ftype
        if not ftype.value.endswith('seq'):
            self.field2seqlen[field] = 1
    columns.append(field)
    usecols.append(field_type)
    dtype[field_type] = np.float64 if ftype == FeatureType.FLOAT else str

if len(columns) == 0:
    self.logger.warning(f'No columns has been loaded from [{source}]')
    return None

df = pd.read_csv(filepath, delimiter=self.config['field_separator'], usecols=usecols, dtype=dtype)
```

考虑是因为open()读取文件用gbk，pandas读文件用utf8导致的，这里能否更新一下更兼容一些呢？非常感谢

**Comment by Sherry-XLL** [comment]
@miloooooz 您好，我试着在 Linux 服务器上，将 UTF-8 格式的 `ml-100k` 数据集中的英文改为中文，代码仍能正常运行。您的代码之所以会出现 `UnicodeDecodeError` 的错误，可能是文件编码格式的原因。您可以试着用编译器打开数据集文件，查看中文是否正常显示，并查看您数据集的文件编码格式。如果您的数据集文件编码格式与 `ml-100k` 数据集一致，请告知您所用的操作系统和 RecBole 版本，我们会针对具体问题进行更新。

**Comment by miloooooz** [comment]
> @miloooooz 您好，我试着在 Linux 服务器上，将 UTF-8 格式的 `ml-100k` 数据集中的英文改为中文，代码仍能正常运行。您的代码之所以会出现 `UnicodeDecodeError` 的错误，可能是文件编码格式的原因。您可以试着用编译器打开数据集文件，查看中文是否正常显示，并查看您数据集的文件编码格式。如果您的数据集文件编码格式与 `ml-100k` 数据集一致，请告知您所用的操作系统和 RecBole 版本，我们会针对具体问题进行更新。

您好 @Sherry-XLL ，我的数据集编码格式也是UTF-8，我前面尝试了一下把`ml-100k.item`的`Toy Story`字段改成`玩具总动员`，在`recbole\data\dataset\dataset.py` 的
```
with open(filepath, 'r') as f:
    head = f.readline()[:-1]
```
位置还是会报错
`UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 1576: illegal multibyte sequence`

我的操作系统是Windows10，RecBole版本为 0.2.1，非常感谢！

**Comment by Sherry-XLL** [comment]
@miloooooz 您好，在 Windows 系统中，文件虽然是 UTF-8 编码，但是在计算机存储的还是 Unicode 编码数据，即计算机是将文件的内容按照 UTF-8 编码成 Unicode 后存到了硬盘上。由于代码这个地方没有指定编码，`open` 发现文件中有中文，所以试图用 `gbk` 将 Unicode 解码，这与文件本身的 UTF-8 格式不匹配，所以解码失败。

您可以在 `open` 函数打开文件时，指定文件的编码方式为 UTF-8，即改为
```Python
with open(filepath, 'r', encoding='utf-8') as f:
```
另一种改法是不编码解码 Unicode，而是直接读取 Unicode 编码，即在 open 函数中，指定读取方式为 'rb'，b 代表读取二进制编码文件。

感谢您的问题反馈，我们会在下一版本更新时对可能会出现的 `UnicodeDecodeError` 错误进行判断处理。

**Comment by miloooooz** [comment]
> @miloooooz 您好，在 Windows 系统中，文件虽然是 UTF-8 编码，但是计算机中存储的还是 Unicode 编码数据，即计算机是将文件的内容按照 UTF-8 编码成 Unicode 后存到了硬盘上。由于代码这个地方没有指定编码，`open` 发现文件中有中文，所以试图用 `gbk` 将 Unicode 解码，这与文件本身的 UTF-8 格式不匹配，所以解码失败。
> 
> 您可以在 `open` 函数打开文件时，指定文件的编码方式为 UTF-8，即改为
> 
> ```python
> with open(filepath, 'r', encoding='utf-8') as f:
> ```
> 
> 另一种改法是不编码解码 Unicode，而是直接读取 Unicode 编码，即在 open 函数中，指定读取方式为 'rb'，b 代表读取二进制编码文件。
> 
> 感谢您的问题反馈，我们将在下一版本更新时对可能出现的 `UnicodeDecodeError` 错误进行判断处理。

嗯嗯，我了解了，非常感谢！
