### ISSUE TITLE
Questions about the vm, GPU and training speed

### ISSUE THREAD

**Issue by Joyce920hope** [RUCAIBox/RecBole#969]
Hello, thank you for bringing this wonderful package!

I'm testing LightGCN model using ml-1m data. I use Tesla V100 (16gb) GPU. The vm has 8 CPUs, each has 4 cores, and total ram is 32gb. However, the speed for one epoch is 25s, which is almost 7 times slower than your test results on LightGCN.

And I noticed that the GPU you were using is TITAN V (12gb) GPU, which is not as powerful as the GPU I'm using. So I'm very confused about this testing result. And I also noticed that your machine is 14 CPU machine, 256GB RAM, which is much larger than mine. I think maybe this is the reason that my training speed is much slower than yours? Will the vm CPU and RAM affect GPU performance that much? When we run model on very large data, how does CPU and GPU devide their work? 

Thank you so much for your patience! Looking forward to your reply.

**Comment by Sherry-XLL** [comment]
@Joyce920hope Hello, thanks for your attention to RecBole!

The speed for one epoch is determined by several factors. The results in [RecBole/asset/time_test_result](https://github.com/RUCAIBox/RecBole/blob/master/asset/time_test_result/General_recommendation.md) are for your reference only. Before discussing the contribution of CPU and GPU, please check the following two points.

- What's the config file of your model? When testing time and memory cost on ml-1m dataset, we will filter data by dataset setting. More importantly, we set `eval_batch_size=102400` to accelerate evaluation. LightGCN belongs to general recommendation models. If GPU supports, increasing `eval_batch_size` can speed up an epoch without affecting the model results.
- What's the version of your RecBole? We have finished the refactor of RecBole and released a new version: RecBole [v1.0.0](https://github.com/RUCAIBox/RecBole/releases/tag/v1.0.0) yesterday. The new version restructures the framework and partially improves the speed.

**Comment by Joyce920hope** [comment]
@Sherry-XLL Thank you for your timely reply!

I changed my eval_batch_size to 102400, and train_batch_size to 4096, now the evaluation time is 0.70s, very similar to your result. And training time speeds up a lot, which is 6.12s,  but still not close to your result. Do you think it's because of our CPU difference? Thank you so much!

**Comment by Joyce920hope** [comment]
And another question is when I test my own dataset (1 million inter), the training time can be controlled to around 8s, but the evaluation time will be about 12s no matter how large eval_batch_size is set after setting to 10240000. I think it's very strange that the eval time is longer than training time. Do you have any ideas on that? Thank you!

Here's the data info that might be useful:
The number of users: 232602
Average actions of users: 4.299207656028994
The number of items: 54852
Average actions of items: 18.23120818216623
The number of inters: 1000000
The sparsity of the dataset: 99.99216220160993%

**Comment by Sherry-XLL** [comment]
@Joyce920hope The training time of LightGCN may also be related to the model version. You can update the code to our latest version and try again.

As for your own dataset, LightGCN is a general recommendation model. Its evaluation method is full sorting by default, that is, scoring each user and item. Therefore, the evaluation quantity is 10% * number of users * number of items. You can see the quantity through the number behind the progress bar. For general models, it is normal that the evaluation time is longer than the training time. You can refer to our [paper](https://arxiv.org/pdf/2011.01731.pdf) for more details about training and evaluation.

**Comment by Joyce920hope** [comment]
@Sherry-XLL Hello Sherry, I use the new version RecBole, and the training time and evaluation time becomes longer.
data: ml-1m
Previous RecBole: Train: 6s, Eval: 0.7s
Current RecBole: Train: 8.28s, Eval: 4.66s

**Comment by Sherry-XLL** [comment]
@Joyce920hope Hello, the training and testing time of the model is largely related to the software and hardware. We have not systematically studied the impact of GPU and CPU on the speed for the time being, so our training can only provide a reference.

I run LightGCN with ml-1m dataset on the latest version of RecBole, `ml-1m_general.yaml` is the same as `Config file of ml-1m dataset` in [RecBole/asset/time_test_result](https://github.com/RUCAIBox/RecBole/blob/master/asset/time_test_result/General_recommendation.md). My command line input is `python run_recbole.py --model=LightGCN --dataset=ml-1m --config_files=ml-1m_general.yaml --epochs=1`, and the training time of epoch 0 is 4.78s, while the evaluating time of epoch 0 is 0.73s. When I try several times, I find that the time will float within a certain range.

In RecBole, if `use_gpu=True`, we will accelerate parallelization through GPU. In principle, the better the GPU performance, the faster the speed will be. Nevertheless, performance is also related to CPU and ram performance. Your question is very good, but we haven't made a rigorous analysis, so it's hard for me to explain the speed difference on your device. I hope my answer can help you. Thank you again for your attention to RecBole.
