### ISSUE TITLE
[🐛BUG] test时无法加载模型

### ISSUE THREAD

**Issue by miloooooz** [RUCAIBox/RecBole#971]
您好，我想将训练完的模型加载进行测试，调用一下方法返回UnpicklingError
```
from recbole.quick_start import load_data_and_model
config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
    model_file = "./saved/lightgbm-Sep-17-2021_13-55-05-temp.pth")
```
Error message如下：
```
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17976/6809800.py in <module>
      1 import torch, pickle
      2 from recbole.quick_start import load_data_and_model
----> 3 config, model, dataset, train_data, valid_data, test_data = load_data_and_model(
      4     model_file = "./saved/lightgbm-Sep-17-2021_13-55-05-temp.pth")
      5 # checkpoint = torch.load("./saved/lightgbm-Sep-16-2021_23-50-12.pth")

~\AppData\Roaming\Python\Python39\site-packages\recbole\quick_start\quick_start.py in load_data_and_model(model_file, dataset_file, dataloader_file)
    131             - test_data (AbstractDataLoader): The dataloader for testing.
    132     """
--> 133     checkpoint = torch.load(model_file)
    134     config = checkpoint['config']
    135     init_logger(config)

c:\users\milozhou\appdata\local\programs\python\python39\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    606                     return torch.jit.load(opened_file)
    607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 
    610 

c:\users\milozhou\appdata\local\programs\python\python39\lib\site-packages\torch\serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: could not find MARK
```
请问这是什么问题呢，我已经更新到RecBole最新版本
PS：似乎automatically download有点问题，直接调用模型训练Yelp文件显示没有yaml文件，后来我选择自己下载了

**Comment by Sherry-XLL** [comment]
@miloooooz 您好，`torch.load` 读取 `pth` 的实质也是在调用 `pickle`，`pickle` 只能加载由 `pickle.dump` 或 `dumps` 编写的文件，使用时应确保写出的二进制文件仍然是二进制文件，并且不会意外地被替换。

您可以试着将 `checkpoint = torch.load(model_file)` 替换为下面的代码查看是否报错

```python
with open(model_file, 'rb') as f:
    f.seek(0)
    checkpoint = pickle.load(f, encoding='bytes')
```

或者是先将 `model_file` 文件用 `with open(model_file, "rb") as f:` 读入，用 `pickle` 转储它，然后再用 `pickle` 加载试试看。如果仍有问题，请与我们反馈。

另外，RecBole 提供的 Automatically Download 功能只下载数据集文件，`yaml` 文件是需要自己设置的。

**Comment by miloooooz** [comment]
@Sherry-XLL 
您好，我是直接跑run_recbole获得的checkpoint文件，我尝试了不同的pickle读取方法都不适用，我有点不明白为什么我直接用quickstart跑的模型不能load呢。

**Comment by miloooooz** [comment]
@Sherry-XLL 您好，我发现这个好像是用lightgbm会有的问题，我用LR或者ItemKNN什么的就没问题，是否我用lgb的话需要自己额外保存模型参数？非常感谢

**Comment by Sherry-XLL** [comment]
@miloooooz `xgboost` 和 `lightgbm` 是 RecBole 中两个比较特别的模型，它们不属于划分的四类，而是被归入了 `recbole.model.exlib_recommender`。`lightgbm` 的关键步骤在于 `RecBole/recbole/trainer/trainer.py` 中的训练过程，`xgboost` 和 `lightgbm` 都有自己的 `trainer`，即 `xgboostTrainer` 和 `lightgbmTrainer`，它们都继承自 `DecisionTreeTrainer`。

```python
temp_file = '{}-{}-temp.pth'.format(self.config['model'], get_local_time())
self.temp_file = os.path.join(self.checkpoint_dir, temp_file)

saved_model_file = '{}-{}.pth'.format(self.config['model'], get_local_time())
self.saved_model_file = os.path.join(self.checkpoint_dir, saved_model_file)
```

在保存模型的时候，`DecisionTreeTrainer` 有两个保存模型文件的参数，一个是 `self.temp_file`，以 `temp.pth` 结尾，另一个是 `self.saved_model_file`，与一般模型一致。`DecisionTreeTrainer` 在保存模型时，和其他模型一样将参数存入了 `self.saved_model_file`，所以在调用的时候不要选择 `temp.pth` 结尾的模型文件，你可以选择不带 `temp` 的 `pth` 文件再试一下。

**Comment by miloooooz** [comment]
@Sherry-XLL 您好，我尝试用不带temp的pth文件也是这个`UnpicklingError: could not find MARK`问题，请问您那边测试是没问题的是吗？

**Comment by Sherry-XLL** [comment]
@miloooooz 您好，感谢您的问题反馈，这确实是我们代码的一个小 bug，你可以试着按照这个 [commit](https://github.com/Sherry-XLL/RecBole/commit/3dd718488aa2ff7dc721159e9a1618fe5b23ff5a) 里的代码修改一下 `trainer.py`。

**Comment by Sherry-XLL** [comment]
@miloooooz 您好，这确实是我们代码的一个小 bug，已经提交了 #973  Pull Request，感谢您的问题反馈。
