### ISSUE TITLE
[🐛BUG] input_interaction.userId is not consistent with input_interaction

### ISSUE THREAD

**Issue by h12345jack** [RUCAIBox/RecBole#976]
Hello, I am working on RecBole for the ```case_study.py```.
It seems that the ```index``` https://github.com/RUCAIBox/RecBole/blob/952b96c08d4f9d309e793326d003a3e84d8425a0/recbole/utils/case_study.py#L43
 is used incorrectly.

```
index = np.isin(test_data.user_df[uid_field].numpy(), uid_series)
input_interaction = test_data.user_df[index]
```
the ```index``` is [```[True, False] list```](https://numpy.org/doc/stable/reference/generated/numpy.isin.html), but after using, the order of the input_interaction is not consistent with the original order.

For example, we insert ```print('input_interaction', input_interaction.userId)``` in [L55](https://github.com/RUCAIBox/RecBole/blob/952b96c08d4f9d309e793326d003a3e84d8425a0/recbole/utils/case_study.py#L55) to rename as ```full_sort_scores_tmp``` 

```
ipdb> uid_s1
array([27210, 34077, 34415])
ipdb> uid_s2
array([27210, 34077, 34415, 15363])
ipdb> xx= full_sort_scores_tmp(uid_s1, model, test_data, device=config['device'])
input_interaction tensor([27210, 34077, 34415], device='cuda:0')
ipdb> xx= full_sort_scores_tmp(uid_s2, model, test_data, device=config['device'])
input_interaction tensor([15363, 27210, 34077, 34415], device='cuda:0')
```
I don't know the purpose of calling ```np.isin``` here. 
It can be fixed by 
```
test_user_df_numpy = test_data.user_df[uid_field].numpy()
index_test_user_df_numpy = np.argsort(test_user_df_numpy)
sorted_test_user_df_numpy = test_user_df_numpy[index]
index = index_test_user_df_numpy[np.searchsorted(sorted_test_user_df_numpy, uid_series)]
input_interaction = test_data.user_df[index]
```

**Comment by Sherry-XLL** [comment]
@h12345jack Thanks very much for your attention and kindly advice! We have fixed `case_study.py` in #977.
