### ISSUE TITLE
What is the difference between the  external user id and internal user id? Please define these two concepts in the documents.

### ISSUE THREAD

**Issue by zrg1993** [RUCAIBox/RecBole#979]
https://github.com/RUCAIBox/RecBole/blob/b7b29954fbc963a406ddbe2f917b4ba56bd7a22b/run_example/case_study_example.py#L24

**Comment by Sherry-XLL** [comment]
@zrg1993 Hello, take `ml-100k` for example, the first five lines of `ml-100k.inter` is as follows:

| user_id:token | item_id:token | rating:float | timestamp:float |
|:-------------:|:-------------:|:------------:|:---------------:|
|      196      |      242      |       3      |    881250949    |
|      186      |      302      |       3      |    891717742    |
|       22      |      377      |       1      |    878887116    |
|      244      |       51      |       2      |    880606923    |
|      166      |      346      |       1      |    886397596    |

`196` and `186` are external user ids, and they are the identification of users in the dataset. In RecBole, the user ids will be remapped to continuous sequence in `recbole.data.dataset`. Therefore, `196` is remapped to `1`, `186` is remapped to `2`. We add `[PAD]` for all the token like fields. Thus after remapping ID, `0` will be reserved for `[PAD]`, which makes the result of `Dataset.item_num` more than the actual number. In this example, `1` and `2` are internal user ids.

Thanks for your attention to RecBole, I hope I have adequately answered all of your questions.

**Comment by zrg1993** [comment]
Many thanks! The explanation is very clear.
