### ISSUE TITLE
Add implementation of Deep Knowledge-Aware Network Recommendation Model - DKN

### ISSUE THREAD

**Issue by rituk** [RUCAIBox/RecBole#984]
**Is your feature request related to a problem? Please describe.**
It's an enhancement. 

**Describe the solution you'd like**
Add one more model to the list. https://github.com/hwwang55/DKN/ 

**Describe alternatives you've considered**
Have tried various other models KGAT, RecVAE, MultiVAE, LightGCN.

**Comment by chenyuwuxin** [comment]
@rituk Hi, thanks for your attention and suggestion. We will consider implementing this model in the future.

**Comment by rituk** [comment]
thanks, sounds good.
