### ISSUE TITLE
会话推荐session_based_rec_example.py数据集报错

### ISSUE THREAD

**Issue by zyc20thu** [RUCAIBox/RecBole#985]
ubuntu20.04系统上跑session_based_rec_example.py程序

`
def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', '-m', type=str, default='GRU4Rec', help='Model for session-based rec.')
    parser.add_argument('--dataset', '-d', type=str, default='diginetica-session', help='Benchmarks for session-based rec.')
    parser.add_argument('--validation', action='store_true', help='Whether evaluating on validation set (split from train set), otherwise on test set.')
    parser.add_argument('--valid_portion', type=float, default=0.1, help='ratio of validation set.')
    return parser.parse_known_args()[0]

if __name__ == '__main__':
    args = get_args()

    # configurations initialization
    config_dict = {
        'USER_ID_FIELD': 'session_id',
        'load_col': None,
        'neg_sampling': None,
        'benchmark_filename': ['train', 'test'],
        'alias_of_item_id': ['item_id_list'],
        'topk': [20],
        'metrics': ['Recall', 'MRR'],
        'valid_metric': 'MRR@20'
    }

    config = Config(model=args.model, dataset=f'{args.dataset}', config_dict=config_dict)
    init_seed(config['seed'], config['reproducibility'])

    # logger initialization
    init_logger(config)
    logger = getLogger()

    logger.info(args)
    logger.info(config)

    # dataset filtering
    dataset = create_dataset(config)
    logger.info(dataset)

    # dataset splitting
    train_dataset, test_dataset = dataset.build()
    if args.validation:
        train_dataset.shuffle()
        new_train_dataset, new_test_dataset = train_dataset.split_by_ratio([1 - args.valid_portion, args.valid_portion])
        train_data = get_dataloader(config, 'train')(config, new_train_dataset, None, shuffle=True)
        test_data = get_dataloader(config, 'test')(config, new_test_dataset, None, shuffle=False)
    else:
        train_data = get_dataloader(config, 'train')(config, train_dataset, None, shuffle=True)
        test_data = get_dataloader(config, 'test')(config, test_dataset, None, shuffle=False)

    # model loading and initialization
    model = get_model(config['model'])(config, train_data.dataset).to(config['device'])
    logger.info(model)

    # trainer loading and initialization
    trainer = get_trainer(config['MODEL_TYPE'], config['model'])(config, model)

    # model training and evaluation
    test_score, test_result = trainer.fit(
        train_data, test_data, saved=True, show_progress=config['show_progress']
    )

    logger.info(set_color('test result', 'yellow') + f': {test_result}')

`

程序默认从以下下载数据集

05 Oct 11:10    INFO  Prepare to download dataset [diginetica-session] from [https://recbole.s3-accelerate.amazonaws.com/ProcessedDatasets/DIGINETICA/session/diginetica_session.zip].

会报错urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

但我用win10下载好zip文件，解压到/home/zhaoyc/RecBole/run_example/dataset后，程序还会从这个地址下载和报错......请问我应该解压到哪个路径以及改程序里的什么位置呢？

**Comment by zyc20thu** [comment]
求解答，感激不尽~（鞠躬）

**Comment by chenyuwuxin** [comment]
@zyc20thu 您好，您可以试着解压到/home/zhaoyc/RecBole/dataset 

数据集文件组织结构形式如下：
```
~/RecBole/dataset/[Yourdataset]/
├── [Yourdataset].inter
├── [Yourdataset].item
├── [Yourdataset].kg
├── [Yourdataset].link
└── [Yourdataset].user
```

其它细节可以参考[new dataset](https://recbole.io/docs/user_guide/usage/running_new_dataset.html)
希望我的回答能够解决你的问题，谢谢！
