### ISSUE TITLE
使用conda install -c aibox recbole安装时Pytorch版本是1.4

### ISSUE THREAD

**Issue by RLKP** [RUCAIBox/RecBole#995]
使用`conda install -c aibox recbole`安装时Pytorch版本是1.4？是否还要自己将Pytorch升级为1.7

**Comment by chenyuwuxin** [comment]
@RLKP 非常感谢您对RecBole的关注。我们目前conda配置的pytorch版本是1.7以上。我们测试使用`conda install -c aibox recbole`命令安装的pytorch版本应该是1.8.1。如果您安装时pytorch版本是1.4，需要将pytorch版本升级到1.7以上，否则会产生错误。

**Comment by RLKP** [comment]
我使用`conda install -c aibox recbole`命令安装时recbole默认版本是`aibox/osx-64::recbole-0.2.0-py36_0`，怎么安装1.0版本呢

**Comment by 2017pxy** [comment]
@RLKP 你好，我们已经在 #1030 中修复了文档的问题，感谢你的反馈！
